import { useEffect, useState } from 'react';
import { ClipboardList, RotateCcw, Save, Trash2 } from 'lucide-react';
import Modal from '../../components/Modal';
import { apiGet, apiSend } from '../../lib/api';
import Shell from '../Shell';
import { Btn, Panel, Toast } from '../parts';

const initial:any={id:null,locCode:'UWH',binCode:'',binType:'2',binFlag:'2',status:true,invBucket:'-1',zone:'-1',aisle:'',seqNo:'',binLocationType:'-1',allowedUoms:[],xcord:'0.000',ycord:'0.000',zcord:'0.000',orderTags:[],siteLocations:[],commingleItem:true,commingleLot:true,defInbBin:false,inboundTypes:[],clients:[],defRetBin:false,defRTOBin:false,defCrossDockBin:false,defUSNBin:false,looseId:false,lpnCapacity:'',fnvCrossDock:false,carryForward:false,nonCarryForward:false,lotAttributes:[],cubeCapacity:'0',weightCapacity:'0',length:'0',width:'0',height:'0',approximateUnits:'0',thresholdQty:'0',udf1:'',udf2:'',udf3:'',udf4:'',udf5:'',cameraId:''};
const binTypes=[['-1','--- Select ---'],['9','Cycle Count'],['12','Drop Zone'],['8','LetDown'],['13','Pack Station'],['4','GPD'],['7','Kit To'],['2','Normal'],['11','Outbound Lane'],['5','Peigon Hole'],['1','PickTo'],['3','QC'],['6','Receiving']];
const buckets=[['-1','--- Select ---'],['40','Hold'],['20','Bad'],['10','Good'],['30','In Process']];
const locations=[['-1','--- Select ---'],['2','Case'],['5','CASEPACK10'],['6','PALETTE'],['3','Piece'],['1','Regular'],['4','RISHABHCASE']];
export default function BinEditor(){
 const [form,setForm]=useState<any>(initial),[meta,setMeta]=useState<any>({zones:[]}),[toast,setToast]=useState<any>(null),[audit,setAudit]=useState(false),[tab,setTab]=useState('Bin Details');
 useEffect(()=>{apiGet('/api/bin-editor').then(setMeta).catch((e)=>setToast({msg:e.message,type:'err'}));},[]);
 const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value})),reset=()=>{setForm({...initial});setTab('Bin Details')};
 const save=async()=>{const required=!form.binCode?'Please enter bin code':form.binFlag==='-1'?'Please select BIN Flag':form.binType==='-1'?'Please select BIN Type':form.zone==='-1'?'Please select Zone':form.invBucket==='-1'?'Please select BIN Bucket':form.binLocationType==='-1'?'Please select Bin Location Type':'';if(required){setToast({msg:required,type:'err'});return}if(['12','13'].includes(form.binType)&&form.invBucket!=='30'){setToast({msg:'Bin bucket should be InProcess for bin type Drop Zone/Pack Station',type:'err'});return}if(Number(form.thresholdQty||0)>Number(form.approximateUnits||0)){setToast({msg:'ThresHold Qty must be less than or equal to Approx. No Of Units',type:'err'});return}try{const result:any=await apiSend('/api/bin-editor',form.id?'PUT':'POST',form);setForm((f:any)=>({...f,...result.row,id:result.row.id}));setToast({msg:result.jsonMessage,type:'ok'});setMeta(await apiGet('/api/bin-editor'));}catch(e:any){setToast({msg:e.message,type:'err'});}};
 const del=async()=>{if(!form.binCode){setToast({msg:'Please enter bin code',type:'err'});return}if(!form.id){setToast({msg:'Bin was not found.',type:'err'});return}if(!confirm('Do you really want to Delete this Bin?'))return;try{const result:any=await apiSend('/api/bin-editor','DELETE',{id:form.id});setToast({msg:result.jsonMessage,type:'ok'});reset()}catch(e:any){setToast({msg:e.message,type:'err'})}};
 const values=[['cubeCapacity','Cube Capacity'],['weightCapacity','Weight Capacity'],['length','Length'],['width','Width'],['height','Height'],['approximateUnits','Approx. No Of Units'],['thresholdQty','Threshold Qty']];
 return <Shell active="wms" breadcrumb="WMS > Setup > Bin Create/Edit" openScreens={[{label:'Bin Create/Edit',to:'#'}]}><div className="mb-3 flex items-center justify-between"><h1 className="text-lg font-semibold text-slate-700">Bin Create/Edit</h1><div className="flex gap-2"><Btn variant="ghost" onClick={()=>setAudit(true)}><ClipboardList size={15}/>Audit</Btn><Btn variant="warn" onClick={save}><Save size={15}/>Save</Btn><Btn variant="ghost" onClick={reset}><RotateCcw size={15}/>Reset</Btn><Btn variant="danger" onClick={del}><Trash2 size={15}/>Delete</Btn></div></div>
 <div className="mb-3 flex border-b bg-white">{['Bin Details','UDF','Video Capture Configuration'].map((name)=><button key={name} onClick={()=>setTab(name)} className={`px-5 py-3 text-sm ${tab===name?'border-b-2 border-rose-500 font-semibold text-slate-800':'text-slate-500'}`}>{name}</button>)}</div>
 {tab==='Bin Details'&&<>
 <Panel title="Bin Create/Edit"><div className="grid gap-4 md:grid-cols-4"><Sel label="Site Location*" value={form.locCode} options={[['UWH','JX Karawaci']]} disabled set={(v:string)=>set('locCode',v)}/><Inp label="BIN Code*" value={form.binCode} max={50} disabled={!!form.id} set={(v:string)=>set('binCode',v)}/><Sel label="BIN Type*" value={form.binType} options={binTypes} set={(v:string)=>set('binType',v)}/><Sel label="BIN Flag*" value={form.binFlag} options={[['-1','--- Select ---'],['1','Hold'],['2','None']]} set={(v:string)=>set('binFlag',v)}/><Sel label="Is Active" value={form.status?'1':'0'} options={[['1','Yes'],['0','No']]} set={(v:string)=>set('status',v==='1')}/><Sel label="BIN Bucket*" value={form.invBucket} options={buckets} set={(v:string)=>set('invBucket',v)}/><Sel label="Zone*" value={form.zone} options={[['-1','--- Select ---'],...(meta.zones||[]).map((z:string)=>[z,z])]} set={(v:string)=>set('zone',v)}/><Inp label="Aisle" value={form.aisle} max={10} set={(v:string)=>set('aisle',v)}/><Inp label="Sequence No" value={form.seqNo} max={10} set={(v:string)=>set('seqNo',v)}/><Sel label="Bin Location Type*" value={form.binLocationType} options={locations} set={(v:string)=>set('binLocationType',v)}/><Multi label="Allowed UOMs" value={form.allowedUoms} options={['Case','RishabhCase','INNER PACK','CASEPACK10','palette','KGS','Kg']} set={(v:string[])=>set('allowedUoms',v)}/></div></Panel>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Bin Coordinates"><div className="grid grid-cols-3 gap-3">{[['xcord','X Coordinate'],['ycord','Y Coordinate'],['zcord','Z Coordinate']].map(([k,l])=><Inp key={k} label={l} value={form[k]} max={11} set={(v:string)=>set(k,v)}/>)}</div></Panel><Panel title="Pack Station Configuration"><Multi label="Order Tags" value={form.orderTags} options={[]} set={(v:string[])=>set('orderTags',v)}/><Multi label="Site Location" value={form.siteLocations} options={[]} set={(v:string[])=>set('siteLocations',v)}/></Panel></div>
 <div className="mt-4"><Panel title="Other Details"><div className="grid gap-3 md:grid-cols-3">{[['commingleItem','Commingle Item'],['commingleLot','Commingle Lot'],['defInbBin','Default Bin For Inbound'],['defRetBin','Default Bin For Delivered Return'],['defRTOBin','Default Bin For RTO Return'],['defCrossDockBin','Default Bin For CrossDock'],['defUSNBin','Default Bin for USN in CycleCount'],['looseId','Loose LPN'],['fnvCrossDock','Default Bin for FNV CrossDock'],['carryForward','Default Bin for CF'],['nonCarryForward','Default Bin for NCF']].map(([k,l])=><Check key={k} label={l} value={form[k]} set={(v:boolean)=>set(k,v)}/>)}<Multi label="Inbound Type" value={form.inboundTypes} options={['With ASN','Direct Inbound','With PO','With STO']} set={(v:string[])=>set('inboundTypes',v)}/><Multi label="Client" value={form.clients} options={['0-DummyClient']} set={(v:string[])=>set('clients',v)}/><Inp label="LPN capacity" value={form.lpnCapacity} max={9} set={(v:string)=>set('lpnCapacity',v)}/><Multi label="Commingle LotAttrib" value={form.lotAttributes} options={['Barcode','Expiry Date','Inward Date','MRP','Unit Price']} set={(v:string[])=>set('lotAttributes',v)}/>{values.map(([k,l])=><Inp key={k} label={l} value={form[k]} max={11} set={(v:string)=>set(k,v)}/>)}</div></Panel></div></>}
 {tab==='UDF'&&<Panel title="UDF"><div className="grid gap-4 md:grid-cols-3">{[['udf1','UDF1'],['udf2','UDF2'],['udf3','UDF3'],['udf4','UDF4'],['udf5','UDF5']].map(([k,l])=><Inp key={k} label={l} value={form[k]} max={50} set={(v:string)=>set(k,v)}/>)}</div></Panel>}
 {tab==='Video Capture Configuration'&&<Panel title="Video Capture Configuration"><Inp label="Camera Id" value={form.cameraId} max={50} disabled set={(v:string)=>set('cameraId',v)}/></Panel>}
 <Modal title="Audit Details" open={audit} onClose={()=>setAudit(false)}><div className="grid grid-cols-2 gap-3 text-sm"><span>Created By</span><b>{form.created_by||''}</b><span>Created Date</span><b>{form.created_date||''}</b><span>Modified By</span><b>{form.modified_by||''}</b><span>Modified Date</span><b>{form.modified_date||''}</b></div></Modal>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</Shell>
}
function Inp({label,value,set,max,disabled}:any){return <label className="text-xs text-slate-600">{label}<input aria-label={label} className="inp mt-1" value={value??''} maxLength={max} disabled={disabled} onChange={e=>set(e.target.value)}/></label>}
function Sel({label,value,set,options,disabled}:any){return <label className="text-xs text-slate-600">{label}<select aria-label={label} className="inp mt-1" value={value} disabled={disabled} onChange={e=>set(e.target.value)}>{options.map(([v,l]:string[])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Multi({label,value,set,options}:any){return <label className="text-xs text-slate-600">{label}<select aria-label={label} multiple className="inp mt-1 min-h-20" value={value||[]} onChange={e=>set([...e.target.selectedOptions].map(o=>o.value))}>{options.map((o:string)=><option key={o}>{o}</option>)}</select></label>}
function Check({label,value,set}:any){return <label className="flex items-center gap-2 text-xs text-slate-600"><input aria-label={label} type="checkbox" checked={!!value} onChange={e=>set(e.target.checked)}/>{label}</label>}
