import { useEffect, useState } from 'react';
import { Download, Plus, Printer, SlidersHorizontal } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Modal from '../../components/Modal';
import { apiSend } from '../../lib/api';
import EnquiryScreen, { StatusPill } from '../EnquiryScreen';
import Shell from '../Shell';
import { Btn, Toast } from '../parts';

const binTypes = ['--- Select ---', 'Cycle Count', 'Drop Zone', 'LetDown', 'Pack Station', 'GPD', 'Kit To', 'Normal', 'Outbound Lane', 'Peigon Hole', 'PickTo', 'QC', 'Receiving'];

export default function BinEnquiry() {
  const navigate = useNavigate();
  const [rows, setRows] = useState<any[]>([]), [pager, setPager] = useState({ page: 0, total: 0, records: 0, pageSize: 20 }), [loading, setLoading] = useState(false), [last, setLast] = useState<any>({}), [advanced, setAdvanced] = useState(false), [adv, setAdv] = useState<any>({ locCode: 'UWH', binType: '-1', status: '1' }), [toast, setToast] = useState<any>(null);
  const search = async (filters: any = {}, page = 1, size = pager.pageSize) => { setLast(filters); setLoading(true); try { const result: any = await apiSend('/api/bin-enquiry', 'POST', { action: 'search', _search: true, rows: size, page, sidx: 'binCode', sord: 'desc', locCode: adv.locCode || 'UWH', binCode: filters.bin_code || '', binType: adv.binType || '-1', zone: filters.zone || adv.zone || '', invBucket: filters.inv_bucket || '', status: filters.status || adv.status || '1', fromEmptyBins: adv.fromEmptyBins || '', toEmptyBins: adv.toEmptyBins || '', defRetBin: !!adv.defRetBin, defRTOBin: !!adv.defRTOBin, defInbBin: !!adv.defInbBin, defCrossDockBin: !!adv.defCrossDockBin, defUSNExcessBin: !!adv.defUSNExcessBin, aisle: adv.aisle || '', binloactionType: filters.bin_location_type || adv.binloactionType || '-1', REQ_SEARCH_FLAG: true, doFetchCount: true }); setRows(result.rows); setPager({ page: result.page, total: result.total, records: result.records, pageSize: size }); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } finally { setLoading(false); } };
  useEffect(() => { void search({}, 1, 20); }, []);
  const reset = () => { setAdv({ locCode: 'UWH', binType: '-1', status: '1' }); void search({}, 1, 20); };
  const download = () => { const csv = ['Location,Bin Code,Zone,Bin Bucket,Bin Location Type,Approx. No Of Units,Bin Qty,Status,Commingle Lot,Commingle Item', ...rows.map((r) => [r.location,r.bin_code,r.zone,r.inv_bucket,r.bin_location_type,r.approximate_units,r.bin_qty,r.status,r.commingle_lot,r.commingle_item].map((v) => `"${String(v ?? '').replaceAll('"','""')}"`).join(','))].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'bin-enquiry.csv'; a.click(); URL.revokeObjectURL(a.href); };
  const cols: any[] = [
    { key: 'location', label: 'Location' }, { key: 'bin_code', label: 'Bin Code' }, { key: 'zone', label: 'Zone' }, { key: 'inv_bucket', label: 'Bin Bucket', filter: 'select', options: ['Hold','Bad','Good','In Process'] }, { key: 'bin_location_type', label: 'Bin Location Type', filter: 'select', options: ['Case','CASEPACK10','PALETTE','Piece','Regular','RISHABHCASE'] }, { key: 'approximate_units', label: 'Approx. No Of Units' }, { key: 'bin_qty', label: 'Bin Qty' }, { key: 'status', label: 'Status', filter: 'select', options: ['Active','InActive'], render: (r: any) => <StatusPill active={r.status === 'Active'}/> }, { key: 'commingle_lot', label: 'Commingle Lot' }, { key: 'commingle_item', label: 'Commingle Item' },
  ];
  return <Shell active="wms" breadcrumb="WMS > Setup > Bin Enquiry" openScreens={[{ label: 'Bin Enquiry', to: '#' }]}><EnquiryScreen breadcrumb={[{ label: 'WMS' }, { label: 'Setup' }, { label: 'Bin Enquiry' }]} sectionTitle="Bin Details" cols={cols} rows={rows} loading={loading} remote={pager} onSearch={search} onReset={reset} actions={[{ label: 'Advance Search', icon: SlidersHorizontal, onClick: () => setAdvanced(true) }, { label: 'Download', icon: Download, onClick: download }, { label: 'Print', icon: Printer, onClick: () => window.print() }, { label: 'Add new', icon: Plus, onClick: () => navigate('/app/wms/bin-editor') }]}/><Modal title="Advance Search" open={advanced} onClose={() => setAdvanced(false)}><div className="grid grid-cols-2 gap-3"><Select label="Site Location" value={adv.locCode} options={['UWH']} set={(v: string) => setAdv({ ...adv, locCode: v })}/><Select label="Bin Type" value={adv.binType} options={binTypes} set={(v: string) => setAdv({ ...adv, binType: v })}/><Select label="Status" value={adv.status} options={['Active','InActive']} set={(v: string) => setAdv({ ...adv, status: v === 'InActive' ? '0' : '1' })}/><Input label="Aisle" value={adv.aisle} set={(v: string) => setAdv({ ...adv, aisle: v })}/><Input label="Empty Bins From" value={adv.fromEmptyBins} set={(v: string) => setAdv({ ...adv, fromEmptyBins: v })}/><Input label="Empty Bins To" value={adv.toEmptyBins} set={(v: string) => setAdv({ ...adv, toEmptyBins: v })}/>{[['defInbBin','Default Inbound Bin'],['defRetBin','Default Return Bin'],['defRTOBin','Default RTO Bin'],['defCrossDockBin','Default Cross Dock Bin'],['defUSNExcessBin','Default USN Excess Bin']].map(([key,label]) => <label key={key} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={!!adv[key]} onChange={(e) => setAdv({ ...adv, [key]: e.target.checked })}/>{label}</label>)}</div><div className="mt-4 flex justify-end gap-2"><Btn onClick={() => { setAdvanced(false); void search(last, 1, pager.pageSize); }}>Search</Btn><Btn variant="ghost" onClick={() => setAdvanced(false)}>Close</Btn></div></Modal>{toast && <Toast {...toast} onClose={() => setToast(null)}/>}</Shell>;
}
function Input({ label, value, set }: any) { return <label className="text-xs text-slate-600">{label}<input aria-label={label} className="inp mt-1" value={value || ''} onChange={(e) => set(e.target.value)}/></label>; }
function Select({ label, value, options, set }: any) { return <label className="text-xs text-slate-600">{label}<select aria-label={label} className="inp mt-1" value={value || ''} onChange={(e) => set(e.target.value)}>{options.map((o: string) => <option key={o} value={o === '--- Select ---' ? '-1' : o}>{o}</option>)}</select></label>; }
