import { useEffect,useState } from 'react';
import { Plus } from 'lucide-react';
import { apiSend } from '../../lib/api';
import EnquiryScreen from '../EnquiryScreen';
import Shell from '../Shell';
import { Btn,Panel,Toast } from '../parts';
const labels=['Unique Batch Nos','Lottable2','Mfg Date','Lottable 04','Batch No','Recv Date','Lottable 07'];
const fresh=()=>({id:null,lotValCode:'',description:'',isDefault:false,lottables:labels.map((label,i)=>({label,mandatory:false,outward:false,mask:'',length:[0,4,5,6].includes(i)?'50':''}))});
export default function LottableValidation(){
 const [rows,setRows]=useState<any[]>([]),[pager,setPager]=useState({page:0,total:0,records:0,pageSize:20}),[loading,setLoading]=useState(false),[editor,setEditor]=useState(false),[form,setForm]=useState<any>(fresh()),[toast,setToast]=useState<any>(null),[last,setLast]=useState<any>({});
 const search=async(filters:any={},page=1,size=pager.pageSize)=>{setLast(filters);setLoading(true);try{const result:any=await apiSend('/api/lottable-validations','POST',{action:'search',_search:true,rows:size,page,sidx:'id.inboundCode',sord:'desc',receivingValidationCode:filters.lotValCode||'',description:filters.description||'',isDefault:filters.isDefault||'-1',REQ_SEARCH_FLAG:true});setRows(result.rows);setPager({page:result.page,total:result.total,records:result.records,pageSize:size})}catch(e:any){setToast({msg:e.message,type:'err'})}finally{setLoading(false)}};
 useEffect(()=>{void search({},1,20)},[]);
 const open=(row?:any)=>{setForm(row?{...row,lottables:row.lottables.map((x:any)=>({...x}))}:fresh());setEditor(true)};
 const save=async()=>{const error=!form.lotValCode?'Please Enter Lottable Validation Code':!form.description?'Please Enter Description':!/^[a-zA-Z0-9]+$/.test(form.lotValCode)?'Please Enter Only AlphaNumerics':'';if(error){setToast({msg:error,type:'err'});return}try{const result:any=await apiSend('/api/lottable-validations',form.id?'PUT':'POST',form);setToast({msg:result.jsonMessage,type:'ok'});setEditor(false);await search(last)}catch(e:any){setToast({msg:e.message,type:'err'})}};
 const setLot=(i:number,key:string,value:any)=>setForm((f:any)=>({...f,lottables:f.lottables.map((x:any,n:number)=>n===i?{...x,[key]:value}:x)}));
 const cols:any[]=[{key:'lotValCode',label:'Lottable Val. Code',render:(r:any)=><button className="text-sky-700 underline" onClick={()=>open(r)}>{r.lotValCode}</button>},{key:'isDefault',label:'isDefault',filter:'select',options:['Yes','No'],render:(r:any)=>r.isDefault?'Yes':'No'},{key:'description',label:'Description'},...labels.map((label,i)=>({key:`lot${i}`,label,filter:'none',render:(r:any)=>r.lottables[i]?.mandatory?'Yes':'No'}))];
 return <Shell active="wms" breadcrumb="WMS > Setup > Lottable Validation" openScreens={[{label:'Lottable Validation',to:'#'}]}>{!editor?<EnquiryScreen breadcrumb={[{label:'WMS'},{label:'Setup'},{label:'Lottable Validation'}]} sectionTitle="Lottable Validation" cols={cols} rows={rows} loading={loading} remote={pager} onSearch={search} onReset={()=>void search({},1,20)} actions={[{label:'Add New',icon:Plus,onClick:()=>open()}]}/>:<><div className="mb-3 flex items-center justify-between"><h1 className="text-lg font-semibold text-slate-700">Lottable create/Edit</h1><div className="flex gap-2"><Btn variant="warn" onClick={save}>Save</Btn><Btn variant="ghost" onClick={()=>setEditor(false)}>Cancel</Btn></div></div><Panel title="Lottable create/Edit"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs">Lottable Validation Code*<input aria-label="Lottable Validation Code*" maxLength={20} disabled={!!form.id} className="inp mt-1" value={form.lotValCode} onChange={e=>setForm({...form,lotValCode:e.target.value})}/></label><label className="text-xs">Description*<input aria-label="Description*" className="inp mt-1" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="flex items-center gap-2 text-xs"><input aria-label="isDefault" type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/>isDefault</label></div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="bg-slate-50"><th className="p-2 text-left">Lottables Label</th><th>Is Mandatory</th><th>Mandatory for Outward</th><th>Mask</th><th>Length</th></tr></thead><tbody>{form.lottables.map((lot:any,i:number)=><tr key={lot.label} className="border-t"><td className="p-2">{lot.label}{[1,2,3].includes(i)&&<span className="ml-2 text-xs text-slate-400">(Date Field)</span>}</td><td className="text-center"><input aria-label={`${lot.label} Is Mandatory`} type="checkbox" checked={lot.mandatory} onChange={e=>setLot(i,'mandatory',e.target.checked)}/></td><td className="text-center"><input aria-label={`${lot.label} Mandatory for Outward`} type="checkbox" checked={lot.outward} onChange={e=>setLot(i,'outward',e.target.checked)}/></td><td className="p-2">{[0,4,5,6].includes(i)&&<input aria-label={`${lot.label} Mask`} className="inp" value={lot.mask} onChange={e=>setLot(i,'mask',e.target.value)}/>}</td><td className="p-2">{[0,4,5,6].includes(i)&&<input aria-label={`${lot.label} Length`} className="inp" value={lot.length} onChange={e=>setLot(i,'length',e.target.value)}/>}</td></tr>)}</tbody></table></div></Panel></>}{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</Shell>;
}
