import { useEffect, useState } from 'react';
import { Pencil, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Modal from '../../components/Modal';
import { apiSend } from '../../lib/api';
import EnquiryScreen, { StatusPill } from '../EnquiryScreen';
import Shell from '../Shell';
import { Btn, Toast } from '../parts';

export default function PickerZonePreference() {
  const navigate = useNavigate();
  const [rows, setRows] = useState<any[]>([]), [pager, setPager] = useState({ page: 0, total: 0, records: 0, pageSize: 20 }), [loading, setLoading] = useState(false), [editor, setEditor] = useState<any>(null), [form, setForm] = useState<any>({}), [audit, setAudit] = useState<any>(null), [toast, setToast] = useState<any>(null), [last, setLast] = useState<any>({});
  const search = async (filters: any = {}, page = 1, size = pager.pageSize) => { setLast(filters); setLoading(true); try { const result: any = await apiSend('/api/picker-zone-preferences', 'POST', { action: 'search', rows: size, page, sidx: '', sord: 'asc', zoneCode: filters.zone_code || '', pickerId: filters.picker_id || '', status: filters.status === 'Active' ? '1' : filters.status === 'InActive' ? '0' : '-1' }); setRows(result.pickerZonePreferenceEnq || result.gridModel || []); setPager({ page: result.page, total: result.total, records: result.records, pageSize: Number(result.rows) || size }); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } finally { setLoading(false); } };
  useEffect(() => { void search({}, 1, 20); }, []);
  const open = (row: any) => { setEditor(row); setForm({ id: row.id, zoneCode: row.zone_code, pickerId: row.picker_id, zonePreference: row.zone_preference, status: row.status === 'Active' }); };
  const save = async () => { if (!form.zoneCode) { setToast({ msg: 'Zone is mandatory.', type: 'err' }); return; } if (!form.pickerId) { setToast({ msg: 'Picker Id is Mandatory', type: 'err' }); return; } try { const result: any = await apiSend('/api/picker-zone-preferences', 'POST', { action: 'save', ...form, status: form.status ? '1' : '0' }); setToast({ msg: result.jsonMessage, type: 'ok' }); setEditor(null); await search(last); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } };
  const cols: any[] = [{ key: 'zone_code', label: 'Zone Code' }, { key: 'picker_id', label: 'Picker Id' }, { key: 'zone_preference', label: 'Zone Preference', filter: 'none' }, { key: 'status', label: 'Status', filter: 'select', options: ['Active','InActive'], render: (row: any) => <StatusPill active={row.status === 'Active'}/> }, { key: 'actions', label: 'Actions', filter: 'none', render: (row: any) => <span className="flex justify-center gap-1"><button aria-label={`Edit ${row.zone_code} ${row.picker_id}`} onClick={() => open(row)} className="rounded bg-amber-500 p-1 text-white"><Pencil size={13}/></button><button aria-label={`Audit ${row.zone_code} ${row.picker_id}`} onClick={() => setAudit(row)} className="rounded bg-slate-600 px-1.5 text-xs text-white">i</button></span> }];
  return <Shell active="wms" breadcrumb="WMS > Setup > Picker Zone Preference" openScreens={[{ label: 'Picker Zone Preference', to: '#' }]}><EnquiryScreen breadcrumb={[{ label: 'WMS' }, { label: 'Setup' }, { label: 'Picker Zone Preference' }]} sectionTitle="Picker Zone Preference" cols={cols} rows={rows} loading={loading} remote={pager} onSearch={search} onReset={() => void search({}, 1, 20)} actions={[{ label: 'Import', icon: Upload, onClick: () => navigate('/app/admin/common-import?externalImportType=69') }]}/><Modal title="Picker Zone Preference Create/Edit" open={!!editor} onClose={() => setEditor(null)}><div className="grid gap-3"><L label="Zone Code"><input aria-label="Zone Code editor" maxLength={50} disabled className="inp mt-1 bg-slate-100" value={form.zoneCode || ''} readOnly/></L><L label="Picker Id"><input aria-label="Picker Id editor" maxLength={50} disabled className="inp mt-1 bg-slate-100" value={form.pickerId || ''} readOnly/></L><L label="Zone Preference"><input aria-label="Zone Preference editor" maxLength={50} className="inp mt-1" value={form.zonePreference || ''} onChange={(event) => setForm({ ...form, zonePreference: event.target.value })}/></L><label className="flex items-center gap-2 text-sm"><input aria-label="Status editor" type="checkbox" checked={!!form.status} onChange={(event) => setForm({ ...form, status: event.target.checked })}/> Status</label></div><div className="mt-4 flex justify-end gap-2"><Btn onClick={save}>Save</Btn><Btn variant="ghost" onClick={() => setEditor(null)}>Close</Btn></div></Modal><Modal title="Audit Details" open={!!audit} onClose={() => setAudit(null)}><div className="grid grid-cols-2 gap-3 text-sm"><L label="Created By"><span>{audit?.created_by}</span></L><L label="Created Date"><span>{audit?.created_date}</span></L><L label="Modified By"><span>{audit?.modified_by}</span></L><L label="Modified Date"><span>{audit?.modified_date}</span></L></div></Modal>{toast && <Toast {...toast} onClose={() => setToast(null)}/>}</Shell>;
}
function L({ label, children }: any) { return <label className="text-xs text-slate-600"><span>{label}</span>{children}</label>; }
