import { useEffect,useState } from 'react';
import { Download,RotateCcw,Save,Search } from 'lucide-react';
import { apiSend } from '../../lib/api';
import EnquiryScreen from '../EnquiryScreen';
import Shell from '../Shell';
import { Btn,Panel,Toast } from '../parts';
const checks:any[]=[['receiveMoreThanPO','Receive More Than Doc'],['isDefault','Is Default'],['allowOtherThanPOSKUs','Allow Other Than PO SKUs'],['lineLevelInvoiceQty','Line Level Invoice Info'],['headerLevelInvoiceQty','Header Level Invoice Info'],['matchMRP','Match MRP with PO'],['invoiceDateMandatory','Invoice Date Mandatory'],['invoiceAmountMandatory','Invoice Amount Mandatory'],['invoiceTaxMandatory','Invoice Tax Mandatory'],['materialRcvdDate','Material Receive Date'],['allowExcessQty','Allow Excess Qty'],['generateAdvUSN','Generate Advance USN'],['allowVirtualBom','Allow VBOM'],['attachmentMandatory','Attachment Mandatory'],['invoiceAmountValidation','Invoice Amount Validation'],['challanNoMandatory','Challan No Mandatory'],['mrpValidation','Lottable01 MRP Validation'],['reasonMandatory','Reason Mandatory'],['marginValidation','Margin Tolerance'],['withOutMarginValidation','w/o Margin Tolerance'],['restrictShortReceiving','Restrict Less Than Doc Qty']];
const fresh:any={id:null,receivingValidationCode:'',description:'',percentage:'',varianceAllowed:'',mrpVarianceAllowed:'',marginVarianceAllowed:'',withOutMarginVarianceAllowed:'',shortReceivingTolerance:'',...Object.fromEntries(checks.map(([k])=>[k,false]))};
const grid:any[]=[['receivingValidationCode','Receiving Validation Code'],['description','Description'],['isDefault','Default'],['receiveMoreThanPO','Receive More Than Doc'],['allowOtherThanPOSKUs','Allow Other Than PO SKUs'],['headerLevelInvoiceQty','Header Level Invoice Info'],['invoiceDateMandatory','Invoice Date Mandatory'],['invoiceAmountMandatory','Invoice Amount Mandatory'],['invoiceTaxMandatory','Invoice Tax Mandatory'],['materialRcvdDate','Material Receive Date'],['allowExcessQty','Allow Excess Qty'],['allowVirtualBom','Allow VBOM'],['attachmentMandatory','Attachment Mandatory'],['invoiceAmountValidation','Invoice Amount Validation'],['varianceAllowed','Variance Allowed'],['challanNoMandatory','Challan No Mandatory'],['mrpValidation','MRP Validation'],['reasonMandatory','Reason Mandatory'],['mrpVarianceAllowed','Variance Allowed for MRP'],['marginValidation','Margin Tolerance'],['marginVarianceAllowed','Margin Variance Allowed(%)'],['withOutMarginValidation','w/o Margin Tolerance'],['withOutMarginVarianceAllowed','Without Margin Variance Allowed(%)'],['restrictShortReceiving','Restrict Less Than Doc Qty'],['shortReceivingTolerance','Less Receiving Tolerance']];
export default function ReceiptValidation(){
 const [form,setForm]=useState<any>(fresh),[rows,setRows]=useState<any[]>([]),[pager,setPager]=useState({page:0,total:0,records:0,pageSize:20}),[loading,setLoading]=useState(false),[last,setLast]=useState<any>({}),[toast,setToast]=useState<any>(null);const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 const search=async(filters:any={},page=1,size=pager.pageSize)=>{setLast(filters);setLoading(true);try{const payload:any={action:'search',_search:true,rows:size,page,sidx:'id.inboundCode',sord:'desc',receivingValidationCode:filters.receivingValidationCode||'',description:filters.description||'',REQ_SEARCH_FLAG:true};for(const [k] of checks)payload[k]=!!filters[k];const result:any=await apiSend('/api/receipt-validations','POST',payload);setRows(result.rows);setPager({page:result.page,total:result.total,records:result.records,pageSize:size})}catch(e:any){setToast({msg:e.message,type:'err'})}finally{setLoading(false)}};useEffect(()=>{void search({},1,20)},[]);
 const validation=()=>!form.receivingValidationCode?'Please Enter Receipt Validation Code':!form.description?'Please Enter Description':!/^[a-zA-Z0-9]+$/.test(form.receivingValidationCode)?'Please Enter Only AlphaNumerics':form.invoiceAmountValidation&&!/^\+?\d+$/.test(form.varianceAllowed)?'Variance Allowed is mandatory':form.mrpValidation&&!form.mrpVarianceAllowed?'Variance Allowed for MRP is mandatory':form.marginValidation&&!form.marginVarianceAllowed?'Margin Variance Allowed for Margin is mandatory':form.withOutMarginValidation&&!form.withOutMarginVarianceAllowed?'Without Margin Variance Allowed for Without Margin is mandatory':form.restrictShortReceiving&&!form.shortReceivingTolerance?'Less Receiving Tolerance is Mandatory.':form.restrictShortReceiving&&Number(form.shortReceivingTolerance)>100?'Less Receiving Tolerance Percentage cant be greater than 100':'';
 const save=async()=>{const error=validation();if(error){setToast({msg:error,type:'err'});return}try{const result:any=await apiSend('/api/receipt-validations',form.id?'PUT':'POST',{...form,action:'save'});setForm({...form,...result.row,id:result.row.id});setToast({msg:result.jsonMessage,type:'ok'});await search(last)}catch(e:any){setToast({msg:e.message,type:'err'})}};
 const reset=()=>{setForm({...fresh});void search({},1,20)};const download=()=>{const csv=[grid.map(x=>x[1]).join(','),...rows.map(r=>grid.map(([k])=>`"${String(typeof r[k]==='boolean'?(r[k]?'Yes':'No'):(r[k]??'')).replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='receipt-validation.csv';a.click();URL.revokeObjectURL(a.href)};
 const cols:any[]=grid.map(([key,label])=>({key,label,filter:['receivingValidationCode','description'].includes(key)?'text':'none',render:key==='receivingValidationCode'?(r:any)=><button className="text-sky-700 underline" onClick={()=>setForm({...fresh,...r})}>{r[key]}</button>:(r:any)=>typeof r[key]==='boolean'?(r[key]?'Yes':'No'):(r[key]??'')}));
 return <Shell active="wms" breadcrumb="WMS > Setup > Receipt Validation" openScreens={[{label:'Receipt Validation',to:'#'}]}><div className="mb-3 flex justify-end gap-2"><Btn variant="warn" onClick={save}><Save size={15}/>Save</Btn><Btn onClick={()=>void search(form,1,pager.pageSize)}><Search size={15}/>Search</Btn><Btn variant="ghost" onClick={reset}><RotateCcw size={15}/>Reset</Btn><Btn variant="ghost" onClick={download}><Download size={15}/>Export</Btn></div><Panel title="Receipt Validation"><div className="grid gap-3 md:grid-cols-4"><Inp label="Receiving Validation Code*" value={form.receivingValidationCode} disabled={!!form.id} set={(v:string)=>set('receivingValidationCode',v)}/><Inp label="Description*" value={form.description} set={(v:string)=>set('description',v)}/><Check label="Receive More Than Doc" value={form.receiveMoreThanPO} set={(v:boolean)=>set('receiveMoreThanPO',v)}/><Inp label="Percentage" value={form.percentage} set={(v:string)=>set('percentage',v)}/>{checks.slice(1).map(([k,l])=><Check key={k} label={l} value={form[k]} set={(v:boolean)=>set(k,v)}/>)}<Inp label="Variance Allowed" value={form.varianceAllowed} set={(v:string)=>set('varianceAllowed',v)}/><Inp label="MRP Variance allowed(%)" value={form.mrpVarianceAllowed} set={(v:string)=>set('mrpVarianceAllowed',v)}/><Inp label="Margin Variance Allowed(%)" value={form.marginVarianceAllowed} set={(v:string)=>set('marginVarianceAllowed',v)}/><Inp label="Without Margin Variance Allowed(%)" value={form.withOutMarginVarianceAllowed} set={(v:string)=>set('withOutMarginVarianceAllowed',v)}/><Inp label="Less Receiving Tolerance" value={form.shortReceivingTolerance} set={(v:string)=>set('shortReceivingTolerance',v)}/></div></Panel><div className="mt-4"><EnquiryScreen breadcrumb={[]} hideActionBar cols={cols} rows={rows} loading={loading} remote={pager} onSearch={search} onReset={()=>void search({},1,20)}/></div>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</Shell>
}
function Inp({label,value,set,disabled}:any){return <label className="text-xs text-slate-600">{label}<input aria-label={label} className="inp mt-1" value={value??''} disabled={disabled} onChange={e=>set(e.target.value)}/></label>}
function Check({label,value,set}:any){return <label className="flex items-center gap-2 text-xs text-slate-600"><input aria-label={label} type="checkbox" checked={!!value} onChange={e=>set(e.target.checked)}/>{label}</label>}
