import { useEffect, useRef, useState } from 'react';
import { Pencil, UserMinus } from 'lucide-react';
import Modal from '../../components/Modal';
import { apiGet, apiSend } from '../../lib/api';
import EnquiryScreen, { StatusPill, type EField } from '../EnquiryScreen';
import Shell from '../Shell';
import { Btn, Toast } from '../parts';

const orderTypes = ['Inbound QC','abhbill','KitTo','Normal','ORDERTYPE2','Packaging Material','Return','TestDemo','tgeg','CASH','Cash On Delivery','B2BGC-COD','B2CGC-COD','BOPIS-COD','BOSS-COD','BOSSCOIN-COD','COD','EA-COD','ROPIS-COD','VAR_ORDERTYPE2','B2BGC-Prepaid','B2CGC-Prepaid','BOPIS-Prepaid','BOSS-Prepaid','BOSSCOIN-Prepaid','checkmo','Credit','Damage Return','Dispose','EA-Prepaid','JIT','MTSO','Normal Return','not defined','Prepaid','ROPIS-Prepaid','TransferTest','Not Defined','ONLINE','STOTEST'];
const orderTypeCodes = ['43','93','17','14','29','50','16','92','30','32','18','73','75','63','67','71','2','69','65','3','72','74','62','66','70','31','15','10','20','68','13','89','12','28','1','64','91','0','19','90'];
const blank = { id: 0, zoneCode: '', descr: '', picktoLoc: '', kittoLoc: '', qcBin: '', status: true, letDownBin: '', orderTypes: [] as string[], zoneType: 'Normal', dropZone: '', defaultBin: '', locCode: '' };
const cls = 'inp mt-1';

export default function WmsZone() {
  const [meta, setMeta] = useState<any>({ bins: [], locations: [], pickers: [] }), [rows, setRows] = useState<any[]>([]), [pager, setPager] = useState({ page: 0, total: 0, records: 0, pageSize: 20 }), [loading, setLoading] = useState(false), [toast, setToast] = useState<any>(null);
  const [editor, setEditor] = useState(false), [form, setForm] = useState<any>(blank), [audit, setAudit] = useState<any>(null), [linked, setLinked] = useState<any>(null), [pickerAction, setPickerAction] = useState(false), [pickerLink, setPickerLink] = useState(false), [bulkLink, setBulkLink] = useState(false), [zoneId, setZoneId] = useState(0), [selectedPickers, setSelectedPickers] = useState<string[]>([]), [selectedLinked, setSelectedLinked] = useState<string[]>([]), [lastFilters, setLastFilters] = useState<any>({});
  const bulkFile = useRef<HTMLInputElement>(null);
  const search = async (filters: any = {}, page = 1, size = pager.pageSize) => { const effective = { ...filters, locCode: filters.locCode || meta.locations[0]?.code || '' }; setLastFilters(effective); setLoading(true); try { const result: any = await apiSend('/api/wms-zones', 'POST', { rows: size, page, sidx: '', sord: 'asc', zoneCode: effective.zoneCode || effective.zone_code || '', descr: effective.descr || '', picktoLoc: effective.picktoLoc || effective.pick_to_bin || '', kittoLoc: effective.kittoLoc || effective.kit_to_bin || '', qcBin: effective.qcBin || effective.qc_bin || '-1', status: effective.status || '1', locCode: effective.locCode, zoneType: effective.zoneType || effective.zone_type || '', letDownBin: effective.letDownBin || effective.let_down_bin || '', operationFlag: 'add', flag: '', REQ_SEARCH_FLAG: true }); setRows(result.zoneDTOList || result.gridModel || []); setPager({ page: result.page, total: result.total, records: result.records, pageSize: Number(result.rows) || size }); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } finally { setLoading(false); } };
  useEffect(() => { apiGet('/api/wms-zones').then((value: any) => { const locCode = value.locations[0]?.code || ''; setMeta(value); setForm((old: any) => ({ ...old, locCode })); return search({ locCode }, 1, 20); }).catch((error) => setToast({ msg: error.message, type: 'err' })); }, []);
  const reset = () => void search({ locCode: meta.locations[0]?.code || '' }, 1, 20);
  const edit = (row?: any) => { setForm(row ? { id: row.id, zoneCode: row.zone_code, descr: row.descr, picktoLoc: row.pick_to_bin, kittoLoc: row.kit_to_bin, qcBin: row.qc_bin, status: row.status === 'Active', letDownBin: row.let_down_bin, orderTypes: row.order_types || [], zoneType: row.zone_type, dropZone: row.drop_zone, defaultBin: row.default_bin, locCode: row.location || meta.locations[0]?.code || '' } : { ...blank, locCode: meta.locations[0]?.code || '' }); setEditor(true); };
  const save = async () => { const code = form.zoneCode.trim(); if (!code) { setToast({ msg: 'Please enter the valid zone code.', type: 'err' }); return; } if (!/^[A-Za-z0-9]+$/.test(code)) { setToast({ msg: 'Please enter AlphaNumerics only', type: 'err' }); return; } try { const result: any = await apiSend('/api/wms-zones', form.id ? 'PUT' : 'POST', { action: 'save', ...form }); setToast({ msg: result.message, type: 'ok' }); setEditor(false); await search(lastFilters); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } };
  const savePickers = async () => { if (!zoneId) { setToast({ msg: 'Please Select Zone', type: 'err' }); return; } if (!selectedPickers.length) { setToast({ msg: 'Please Select Picker', type: 'err' }); return; } try { const result: any = await apiSend('/api/wms-zones', 'PUT', { action: 'link-pickers', id: zoneId, pickers: selectedPickers }); setToast({ msg: result.message, type: 'ok' }); setPickerLink(false); setPickerAction(false); setSelectedPickers([]); await search(lastFilters); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } };
  const unlink = async () => { if (!selectedLinked.length) { setToast({ msg: 'Please Select a Row For UnLink', type: 'err' }); return; } try { const result: any = await apiSend('/api/wms-zones', 'PUT', { action: 'unlink-pickers', id: linked.id, pickers: selectedLinked }); setToast({ msg: result.message, type: 'ok' }); setLinked(null); setSelectedLinked([]); await search(lastFilters); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } };
  const exportLinks = () => { const csv = ['Zone,Picker', ...rows.flatMap((row) => (row.linked_pickers || []).map((picker: string) => `"${row.zone_code}","${picker}"`))].join('\n'), anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([csv])); anchor.download = 'zone-picker-links.csv'; anchor.click(); URL.revokeObjectURL(anchor.href); setPickerAction(false); };
  const importLinks = async () => { const file = bulkFile.current?.files?.[0]; if (!file) { setToast({ msg: 'Select a CSV file.', type: 'err' }); return; } try { const lines = (await file.text()).split(/\r?\n/).slice(1).filter(Boolean); let count = 0; for (const line of lines) { const [zone, picker] = line.split(',').map((value) => value.replace(/^"|"$/g, '').trim()), row = rows.find((item) => item.zone_code === zone); if (row && picker) { await apiSend('/api/wms-zones', 'PUT', { action: 'link-pickers', id: row.id, pickers: [picker] }); count++; } } setToast({ msg: `${count} picker link(s) imported.`, type: 'ok' }); setBulkLink(false); setPickerAction(false); await search(lastFilters); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } };
  const currentLoc = meta.locations[0]?.code || '';
  const fields: EField[] = [{ key: 'locCode', label: 'Site Location', type: 'select', options: ['--- Select ---', ...meta.locations.map((x: any) => x.code)], disabled: true, value: currentLoc }];
  const cols: any[] = [{ key: 'zone_code', label: 'Zone Code' }, { key: 'descr', label: 'Description' }, { key: 'pick_to_bin', label: 'Pick To Bin', filter: 'select', options: meta.bins }, { key: 'kit_to_bin', label: 'Kit To Bin', filter: 'select', options: meta.bins }, { key: 'qc_bin', label: 'Qc Bin', filter: 'select', options: meta.bins }, { key: 'status', label: 'Status', filter: 'select', options: ['Active', 'InActive'], render: (row: any) => <StatusPill active={row.status === 'Active'}/> }, { key: 'zone_type', label: 'Zone Type', filter: 'select', options: ['Drop Zone', 'Normal', 'Pack Station'] }, { key: 'let_down_bin', label: 'Let Down Bin', filter: 'select', options: meta.bins }, { key: 'actions', label: 'Actions', filter: 'none', render: (row: any) => <span className="flex justify-center gap-1"><button aria-label={`Edit ${row.zone_code}`} onClick={() => edit(row)} className="rounded bg-amber-500 p-1 text-white"><Pencil size={13}/></button><button aria-label={`Audit ${row.zone_code}`} onClick={() => setAudit(row)} className="rounded bg-slate-600 px-1.5 text-xs text-white">i</button></span> }, { key: 'linked_pickers', label: 'Linked Pickers', filter: 'none', render: (row: any) => row.linked_pickers?.length ? <button className="text-sky-700 underline" onClick={() => setLinked(row)}>PickerList</button> : '' }];
  return <Shell active="wms" breadcrumb="WMS > Setup > Zone" openScreens={[{ label: 'Zone', to: '#' }]}>
    <EnquiryScreen breadcrumb={[{ label: 'WMS' }, { label: 'Setup' }, { label: 'Zone' }]} sectionTitle="Zone Details" actionsBeforeResetCount={1} fields={fields} cols={cols} rows={rows} loading={loading} remote={pager} onSearch={search} onReset={reset} actions={[{ label: 'Add New', onClick: () => edit() }, { label: 'PickerAction', onClick: () => setPickerAction(true) }]} />
    <Modal title="Zone Create/Edit" open={editor} onClose={() => setEditor(false)} wide><div className="grid gap-3 md:grid-cols-2"><L label="Zone Code*"><input aria-label="Zone Code editor" maxLength={10} readOnly={!!form.id} className={`${cls} ${form.id ? 'bg-slate-100' : ''}`} value={form.zoneCode} onChange={(e) => setForm({ ...form, zoneCode: e.target.value })}/></L><L label="Zone Description"><input aria-label="Zone Description" maxLength={100} className={cls} value={form.descr} onChange={(e) => setForm({ ...form, descr: e.target.value })}/></L>{[['picktoLoc','Pick to Bin'],['kittoLoc','KIT To Loc'],['letDownBin','Let Down Bin'],['qcBin','QC Bin']].map(([key,label]) => <L key={key} label={label}><select aria-label={label} className={cls} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })}>{key !== 'picktoLoc' && <option value="">--- Select ---</option>}{meta.bins.map((bin: string) => <option key={bin}>{bin}</option>)}</select></L>)}<L label="Zone Type"><select aria-label="Zone Type editor" className={cls} value={form.zoneType} disabled={!!form.id} onChange={(e) => setForm({ ...form, zoneType: e.target.value, dropZone: '', defaultBin: '' })}><option>Drop Zone</option><option>Normal</option><option>Pack Station</option></select></L>{form.zoneType === 'Normal' ? <L label="Drop Zone"><select aria-label="Drop Zone" className={cls} value={form.dropZone} onChange={(e) => setForm({ ...form, dropZone: e.target.value })}><option value="">--- Select ---</option>{rows.filter((row) => row.zone_type === 'Drop Zone').map((row) => <option key={row.id} value={row.zone_code}>{row.zone_code}</option>)}</select></L> : <L label="Default Bin"><select aria-label="Default Bin" className={cls} value={form.defaultBin} onChange={(e) => setForm({ ...form, defaultBin: e.target.value })}><option value="">--- Select ---</option>{meta.bins.map((bin: string) => <option key={bin}>{bin}</option>)}</select></L>}<label className="flex items-center gap-2 pt-6 text-sm"><input aria-label="Is Active" type="checkbox" checked={form.status} onChange={(e) => setForm({ ...form, status: e.target.checked })}/> Is Active</label><L label="Pick Order Types"><select aria-label="Pick Order Types" multiple className={`${cls} h-36`} value={form.orderTypes} onChange={(e) => setForm({ ...form, orderTypes: [...e.target.selectedOptions].map((option) => option.value) })}>{orderTypes.map((type, index) => <option key={type} value={orderTypeCodes[index]}>{type}</option>)}</select></L></div><div className="mt-4 flex justify-end gap-2"><Btn onClick={save}>Save</Btn><Btn variant="ghost" onClick={() => setEditor(false)}>Close</Btn></div></Modal>
    <Modal title="PickerAction" open={pickerAction} onClose={() => setPickerAction(false)}><div className="grid gap-2"><Btn onClick={() => { setZoneId(0); setSelectedPickers([]); setPickerLink(true); }}>Link Picker</Btn><Btn variant="ghost" onClick={() => setBulkLink(true)}>Bulk Link</Btn><Btn variant="ghost" onClick={exportLinks}>Export</Btn></div></Modal>
    <Modal title="Zone Picker Linking" open={pickerLink} onClose={() => setPickerLink(false)} wide><L label="Zone"><select aria-label="Picker Zone" className={cls} value={zoneId} onChange={(e) => setZoneId(Number(e.target.value))}><option value={0}>--- Select ---</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.zone_code}</option>)}</select></L><div className="mt-3 max-h-64 overflow-auto border">{meta.pickers.map((picker: any) => <label key={picker.user_id} className="flex gap-2 border-b p-2 text-sm"><input type="checkbox" aria-label={`Picker ${picker.user_id}`} checked={selectedPickers.includes(picker.user_id)} onChange={(e) => setSelectedPickers(e.target.checked ? [...selectedPickers, picker.user_id] : selectedPickers.filter((id) => id !== picker.user_id))}/>{picker.user_id} — {picker.name}</label>)}</div><div className="mt-4 flex justify-end gap-2"><Btn onClick={savePickers}>Save</Btn><Btn variant="ghost" onClick={() => { setZoneId(0); setSelectedPickers([]); }}>Reset</Btn></div></Modal>
    <Modal title="Bulk Link Picker" open={bulkLink} onClose={() => setBulkLink(false)}><p className="mb-2 text-xs text-slate-500">CSV columns: Zone,Picker</p><input ref={bulkFile} aria-label="Bulk Link CSV" type="file" accept=".csv"/><div className="mt-4 flex justify-end"><Btn onClick={importLinks}>Import</Btn></div></Modal>
    <Modal title="Linked Pickers" open={!!linked} onClose={() => setLinked(null)}><div className="max-h-64 overflow-auto border">{linked?.linked_pickers?.map((picker: string) => <label key={picker} className="flex gap-2 border-b p-2 text-sm"><input type="checkbox" aria-label={`Unlink ${picker}`} checked={selectedLinked.includes(picker)} onChange={(e) => setSelectedLinked(e.target.checked ? [...selectedLinked, picker] : selectedLinked.filter((id) => id !== picker))}/>{picker}</label>)}</div><div className="mt-4 flex justify-end"><Btn variant="danger" onClick={unlink}><UserMinus size={13}/>UnLink</Btn></div></Modal>
    <Modal title="Audit Details" open={!!audit} onClose={() => setAudit(null)}><div className="grid grid-cols-2 gap-3 text-sm"><L label="Created By"><span>{audit?.created_by}</span></L><L label="Created Date"><span>{audit?.created_date}</span></L><L label="Modified By"><span>{audit?.modified_by}</span></L><L label="Modified Date"><span>{audit?.modified_date}</span></L></div></Modal>
    {toast && <Toast {...toast} onClose={() => setToast(null)}/>} 
  </Shell>;
}
function L({ label, children }: any) { return <label className="text-xs text-slate-600"><span>{label}</span>{children}</label>; }
