/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { Download, Plus, RotateCcw, Search, Upload } from 'lucide-react';
import Shell from './Shell'; import Modal from '../components/Modal'; import { Btn, Toast } from './parts'; import { apiGet, apiSend } from '../lib/api'; import { useDownload } from '../context/DownloadContext';
const cls='w-full border border-slate-300 bg-white px-2 py-1.5 text-xs', sizes=[20,50,100,200];
const picks=['--- Select ---','Non Premium Bag','Non Premium Box','Picking Instruction','Premium Bag','Premium Box','This need bubble wrapping.'];
const emptyFilters={clientId:'0',status:'Active',channelType:'-1',channelCode:'',skuCode:'',skuDescription:'',channelSkuCode:'',channelProductId:''};
const emptyForm={channel_code:'',channel_type:'',sku_code:'',sku_description:'',channel_sku_code:'',channel_product_id:'',back_order_qty:'',channel_price:'',status:'Active',pick_instruction:'-1',maximum_sku_qty:'0.00',client_id:'0'};

export default function SkuChannelListing(){
 const {requestDownload}=useDownload(); const[tab,setTab]=useState<'search'|'import'|'unmapped'>('search');
 const[rows,setRows]=useState<any[]>([]),[channels,setChannels]=useState<any[]>([]),[skus,setSkus]=useState<any[]>([]),[filters,setFilters]=useState(emptyFilters),[advanced,setAdvanced]=useState(false),[loading,setLoading]=useState(false),[searched,setSearched]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[records,setRecords]=useState(0),[total,setTotal]=useState(0),[editor,setEditor]=useState(false),[form,setForm]=useState<any>(emptyForm),[notice,setNotice]=useState<any>(null),[importRows,setImportRows]=useState<any[]>([]),[unmapped,setUnmapped]=useState<any[]>([]);
 useEffect(()=>{Promise.all([apiGet<any[]>('/api/channels'),apiGet<any[]>('/api/skus')]).then(([c,s])=>{setChannels(c);setSkus(s)}).catch(()=>{})},[]);
 const search=async(nextPage=1,nextSize=pageSize)=>{setLoading(true);try{const result:any=await apiSend('/api/sku-channel-links','POST',{REQ_SEARCH_FLAG:true,rows:nextSize,page:nextPage,sidx:'',sord:'asc',...filters,channelType:filters.channelType==='-1'?'':filters.channelType,doFetchCount:false});setRows(result.gridModel||[]);setPage(result.page||nextPage);setPageSize(nextSize);setRecords(result.records||0);setTotal(result.total||0);setSearched(true)}catch(e:any){setRows([]);setNotice({msg:e.message,type:'err'})}finally{setLoading(false)}};
 const searchUnmapped=async()=>{setLoading(true);try{const result:any=await apiSend('/api/sku-moderation','POST',{REQ_SEARCH_FLAG:true,rows:pageSize,page:1,sidx:'',sord:'desc',clientId:filters.clientId,locCode:filters.channelCode,SearchChannelStatus:filters.status,linkedUnlinkedFlag:'0',doFetchCount:true});setUnmapped(result.gridModel||[])}catch(e:any){setNotice({msg:e.message,type:'err'})}finally{setLoading(false)}};
 const reset=()=>{setFilters(emptyFilters);setRows([]);setUnmapped([]);setPage(1);setRecords(0);setTotal(0);setSearched(false)};
 const save=async()=>{if(!form.channel_code.trim())return setNotice({msg:'Channel is Mandatory.',type:'err'});if(!form.sku_code.trim())return setNotice({msg:'ERetail Sku is Mandatory.',type:'err'});if(!form.channel_sku_code.trim())return setNotice({msg:'channelSkuCode is Mandatory.',type:'err'});if(!form.status.trim())return setNotice({msg:'Status is Mandatory.',type:'err'});try{await apiSend('/api/sku-channel-links',form.id?'PUT':'POST',form);setNotice({msg:'Record Saved Successfully',type:'ok'});setEditor(false);setForm(emptyForm);if(searched)await search(1)}catch(e:any){setNotice({msg:e.message,type:'err'})}};
 const parseImport=async(file:File)=>{const lines=(await file.text()).split(/\r?\n/).filter(Boolean),heads=lines.shift()?.split(',').map(x=>x.trim())||[];setImportRows(lines.map((line,seq)=>({seq:seq+1,...Object.fromEntries(heads.map((h,i)=>[h,line.split(',')[i]?.trim()||''])),status:'Pending',error_description:''})))};
 const commitImport=async()=>{const next=[];for(const row of importRows){try{await apiSend('/api/sku-channel-links','POST',row);next.push({...row,status:'Success',error_description:''})}catch(e:any){next.push({...row,status:'Error',error_description:e.message})}}setImportRows(next);setNotice({msg:`${next.filter(r=>r.status==='Success').length} Record(s) imported.`,type:'ok'})};
 const exportRows=()=>{if(!rows.length)return setNotice({msg:'No data found in the grid.',type:'err'});requestDownload({title:'SKU Channel Listing Export',module:'sku-channel-listing',baseName:'sku-channel-links',data:{columns:['Client','Channel','Eretail SKU','SKU Description','Channel SKU','Channel Product Id','Channel Price','Picking Instructions','Status','Back Order Inventory','Upd Date','Upd Button'],rows:rows.map(r=>[r.client_id||'0-DummyClient',r.channel_code,r.sku_code,r.sku_description,r.channel_sku_code,r.channel_product_id,r.channel_price,r.pick_instruction,r.status,r.back_order_qty,r.updated_date,r.updated_by])}})};
 const toolbar=tab==='import'?<><Btn variant="ghost" onClick={()=>document.getElementById('sku-link-file')?.click()}><Upload size={13}/>Import</Btn><Btn variant="ghost" onClick={()=>setImportRows([])}><RotateCcw size={13}/>Reset</Btn></>:<>{tab==='search'&&<Btn variant="ghost" onClick={()=>{setForm(emptyForm);setEditor(true)}}><Plus size={13}/>Add new</Btn>}<Btn variant="warn" disabled={loading} onClick={()=>void(tab==='search'?search(1):searchUnmapped())}><Search size={13}/>Search</Btn><Btn variant="ghost" onClick={()=>setAdvanced(!advanced)}>Advance Search</Btn><Btn variant="ghost" onClick={reset}><RotateCcw size={13}/>Reset</Btn><Btn variant="ghost" onClick={tab==='search'?exportRows:()=>setNotice({msg:unmapped.length?'Unmapped SKU export queued.':'No data found in the grid.',type:unmapped.length?'ok':'err'})}><Download size={13}/>Export</Btn></>;
 return <Shell active="sales" breadcrumb="SALES > SKU Link Channel" openScreens={[{label:'SKU Channel Listing',to:'#'}]}><div className="mb-2 flex justify-end gap-2">{toolbar}</div><div className="mb-2 flex border-b bg-white text-sm font-medium text-slate-600">{[['search','SKU/Link Search Channel'],['import','SKU/Channel Link Import'],['unmapped','Unmapped SKU']].map(([key,label])=><button key={key} onClick={()=>setTab(key as any)} className={`px-5 py-2 ${tab===key?'border-b-2 border-sky-600 text-sky-700':''}`}>{label}</button>)}</div>
 {tab!=='import'&&<>{advanced&&<div className="grid grid-cols-3 gap-3 border bg-white p-3"><label>Client<select className={cls} value={filters.clientId} onChange={e=>setFilters({...filters,clientId:e.target.value})}><option value="0">0-DummyClient</option></select></label><label>Status<select className={cls} value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">ALL</option><option>Active</option><option>InActive</option></select></label><label>Channel Type<select className={cls} value={filters.channelType} onChange={e=>setFilters({...filters,channelType:e.target.value})}><option value="-1">--- Select ---</option>{[...new Set(channels.map(c=>c.channel_type))].map(x=><option key={x}>{x}</option>)}</select></label></div>}<div className="grid grid-cols-5 gap-2 border border-t-0 bg-white p-3"><label>Channel<select aria-label="Channel" className={cls} value={filters.channelCode} onChange={e=>setFilters({...filters,channelCode:e.target.value})}><option value="">--- Select ---</option>{channels.map(c=><option key={c.id} value={c.channel_code}>{c.channel_code}-{c.channel_name}</option>)}</select></label>{[['skuCode','Eretail SKU'],['skuDescription','SKU Description'],['channelSkuCode','Channel SKU'],['channelProductId','Channel Product Id']].map(([k,l])=><label key={k}>{l}<input aria-label={l} className={cls} value={(filters as any)[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/></label>)}</div></>}
 {tab==='search'&&<SearchGrid rows={rows} loading={loading} onEdit={(r:any)=>{setForm({...emptyForm,...r});setEditor(true)}}/>}{tab==='import'&&<ImportTab rows={importRows} onFile={parseImport} onCommit={commitImport}/>} {tab==='unmapped'&&<UnmappedGrid rows={unmapped} loading={loading}/>} {tab==='search'&&<div className="flex justify-between border bg-slate-50 p-2 text-xs"><span>Page {records?page:0} of {total}</span><span><button disabled={page<=1} onClick={()=>void search(page-1)}>Previous</button> <select aria-label="Records per Page" value={pageSize} onChange={e=>void search(1,Number(e.target.value))}>{sizes.map(x=><option key={x}>{x}</option>)}</select> <button disabled={!records||page>=total} onClick={()=>void search(page+1)}>Next</button></span><span>{records?`View ${(page-1)*pageSize+1} - ${Math.min(page*pageSize,records)} of ${records}`:'No records to view'}</span></div>}
 <Modal title="Sku Channel Link" open={editor} onClose={()=>setEditor(false)} wide><div className="grid grid-cols-2 gap-3"><label>Channel<select className={cls} value={form.channel_code} onChange={e=>setForm({...form,channel_code:e.target.value})}><option value="">--- Select ---</option>{channels.map(c=><option key={c.id} value={c.channel_code}>{c.channel_code}-{c.channel_name}</option>)}</select></label><label>eRetail SKU<input className={cls} list="sku-options" value={form.sku_code} onChange={e=>{const sku=skus.find(x=>x.sku_code===e.target.value);setForm({...form,sku_code:e.target.value,sku_description:sku?.description||sku?.name||form.sku_description})}}/><datalist id="sku-options">{skus.map(s=><option key={s.id} value={s.sku_code}/>)}</datalist></label>{[['sku_description','SKU Description'],['channel_sku_code','Channel SKU'],['channel_product_id','Channel Product Id'],['back_order_qty','Back Order Qty'],['channel_price','Channel Price'],['maximum_sku_qty','Maximum SKU Qty']].map(([k,l])=><label key={k}>{l}<input className={cls} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Status<select className={cls} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>InActive</option></select></label><label>Picking Instructions<select className={cls} value={form.pick_instruction} onChange={e=>setForm({...form,pick_instruction:e.target.value})}>{picks.map(x=><option key={x} value={x==='--- Select ---'?'-1':x}>{x}</option>)}</select></label></div><div className="mt-4 flex justify-end gap-2"><Btn onClick={()=>void save()}>Save</Btn><Btn variant="ghost" onClick={()=>setForm(emptyForm)}>Reset</Btn><Btn variant="ghost" onClick={()=>setEditor(false)}>Close</Btn></div></Modal>{notice&&<Toast {...notice} onClose={()=>setNotice(null)}/>}</Shell>;
}
function SearchGrid({rows,loading,onEdit}:any){const cols=['Client','Channel Image','Channel','Eretail SKU','SKU Description','Channel SKU','Channel Product Id','Channel Price','Picking Instructions','Status','Back Order Inventory','Upd Date','Upd Button'];return <div className="overflow-auto border bg-white"><table className="min-w-[1500px] w-full text-xs"><thead className="bg-slate-100"><tr>{cols.map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={cols.length} className="p-10 text-center">Loading...</td></tr>:rows.length?rows.map((r:any)=><tr key={r.id} className="border-t"><td>{r.client_id||'0-DummyClient'}</td><td>{r.channel_image||''}</td><td>{r.channel_code}</td><td>{r.sku_code}</td><td>{r.sku_description}</td><td>{r.channel_sku_code}</td><td>{r.channel_product_id}</td><td>{r.channel_price}</td><td>{r.pick_instruction}</td><td>{r.status}</td><td>{r.back_order_qty}</td><td>{r.updated_date}</td><td><button className="text-sky-600" onClick={()=>onEdit(r)}>Update</button></td></tr>):<tr><td colSpan={cols.length} className="p-10 text-center text-slate-400">No records to view</td></tr>}</tbody></table></div>}
function ImportTab({rows,onFile,onCommit}:any){const cols=['Seq No','Channel','Eretail SKU','SKU Description','Channel SKU','Channel Product Id','Back Order Inventory','Channel Price','Status','Error Description'];return <div className="border bg-white p-3"><input id="sku-link-file" className="mb-3" type="file" accept=".csv" onChange={e=>{const file=e.target.files?.[0];if(file)void onFile(file)}}/><table className="w-full text-xs"><thead className="bg-slate-100"><tr>{cols.map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.seq} className="border-t"><td>{r.seq}</td><td>{r.channel_code}</td><td>{r.sku_code}</td><td>{r.sku_description}</td><td>{r.channel_sku_code}</td><td>{r.channel_product_id}</td><td>{r.back_order_qty}</td><td>{r.channel_price}</td><td>{r.status}</td><td>{r.error_description}</td></tr>):<tr><td colSpan={cols.length} className="p-10 text-center text-slate-400">No records to view</td></tr>}</tbody></table>{rows.length>0&&<div className="mt-3 flex justify-end"><Btn onClick={()=>void onCommit()}>Save</Btn></div>}</div>}
function UnmappedGrid({rows,loading}:any){const cols=['Client','Image','SKU Name','Channel','Seller SKU','ERetail Sku','Product ID','Pricing','MRP','Other Info','Action','Created Date'];return <div className="overflow-auto border bg-white"><table className="min-w-[1200px] w-full text-xs"><thead className="bg-slate-100"><tr>{cols.map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={cols.length} className="p-10 text-center">Loading...</td></tr>:rows.length?rows.map((r:any)=><tr key={r.id} className="border-t"><td>{r.client_id||'0-DummyClient'}</td><td>{r.image||''}</td><td>{r.sku_name}</td><td>{r.channel}</td><td>{r.seller_sku}</td><td>{r.eretail_sku}</td><td>{r.product_id}</td><td>{r.pricing}</td><td>{r.mrp}</td><td>{r.other_info}</td><td>Link</td><td>{r.created_date}</td></tr>):<tr><td colSpan={cols.length} className="p-10 text-center text-slate-400">No records to view</td></tr>}</tbody></table></div>}
