/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { Download, Plus, RotateCcw, Search, Upload } from 'lucide-react';
import Shell from './Shell'; import Modal from '../components/Modal'; import { Btn, Toast } from './parts'; import { apiGet, apiSend } from '../lib/api'; import { useDownload } from '../context/DownloadContext';
const cls='w-full border border-slate-300 bg-white px-2 py-1.5 text-xs'; const sizes=[20,50,100,200];
const emptyFilters={clientId:'0',status:'Active',channelType:'',channelCode:'',skuCode:'',skuDescription:'',channelSkuCode:'',channelProductId:''};
const emptyForm={channel_code:'',channel_type:'',sku_code:'',sku_description:'',channel_sku_code:'',channel_product_id:'',back_order_qty:'',channel_price:'',status:'Active',pick_instruction:'',maximum_sku_qty:''};
export default function SkuChannelListing(){
 const {requestDownload}=useDownload(); const[rows,setRows]=useState<any[]>([]),[channels,setChannels]=useState<any[]>([]),[skus,setSkus]=useState<any[]>([]),[filters,setFilters]=useState(emptyFilters),[advanced,setAdvanced]=useState(false),[loading,setLoading]=useState(false),[searched,setSearched]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[records,setRecords]=useState(0),[total,setTotal]=useState(0),[editor,setEditor]=useState(false),[importing,setImporting]=useState(false),[form,setForm]=useState<any>(emptyForm),[notice,setNotice]=useState<any>(null);
 useEffect(()=>{Promise.all([apiGet<any[]>('/api/channels'),apiGet<any[]>('/api/skus')]).then(([c,s])=>{setChannels(c);setSkus(s)}).catch(()=>{})},[]);
 const search=async(nextPage=1,nextSize=pageSize)=>{setLoading(true);try{const result:any=await apiSend('/api/sku-channel-links','POST',{REQ_SEARCH_FLAG:true,rows:nextSize,page:nextPage,sidx:'',sord:'asc',...filters,doFetchCount:false});setRows(result.gridModel||result.rows||[]);setPage(result.page||nextPage);setPageSize(nextSize);setRecords(result.records||0);setTotal(result.total||0);setSearched(true)}catch(e:any){setRows([]);setNotice({msg:e.message,type:'err'})}finally{setLoading(false)}};
 const reset=()=>{setFilters(emptyFilters);setRows([]);setPage(1);setRecords(0);setTotal(0);setSearched(false)};
 const save=async()=>{try{await apiSend('/api/sku-channel-links',form.id?'PUT':'POST',form);setNotice({msg:'SKU Channel Link saved successfully.',type:'ok'});setEditor(false);setForm(emptyForm);if(searched)void search(1)}catch(e:any){setNotice({msg:e.message,type:'err'})}};
 const parseImport=async(file:File)=>{try{const lines=(await file.text()).split(/\r?\n/).filter(Boolean),heads=lines.shift()?.split(',').map(x=>x.trim())||[];for(const line of lines){const values=line.split(',').map(x=>x.trim());await apiSend('/api/sku-channel-links','POST',Object.fromEntries(heads.map((h,i)=>[h,values[i]||''])))}setImporting(false);setNotice({msg:`${lines.length} link(s) imported.`,type:'ok'});if(searched)void search(1)}catch(e:any){setNotice({msg:e.message,type:'err'})}};
 const exportRows=()=>requestDownload({title:'SKU Channel Listing Export',module:'sku-channel-listing',baseName:'sku-channel-links',data:{columns:['Channel','Eretail SKU','SKU Description','Channel SKU','Channel Product Id','Channel Price','Picking Instructions','Status','Back Order Inventory','Updated By'],rows:rows.map(r=>[r.channel_code,r.sku_code,r.sku_description,r.channel_sku_code,r.channel_product_id,r.channel_price,r.pick_instruction,r.status,r.back_order_qty,r.updated_by])}});
 return <Shell active="sales" breadcrumb="SALES > Manage Channels > SKU Channel Listing" openScreens={[{label:'SKU Channel Listing',to:'#'}]}><div className="mb-2 flex justify-end gap-2"><Btn variant="ghost" onClick={()=>setEditor(true)}><Plus size={13}/>Add new</Btn><Btn variant="warn" disabled={loading} onClick={()=>void search(1)}><Search size={13}/>Search</Btn><Btn variant="ghost" onClick={()=>setAdvanced(!advanced)}>Advance Search</Btn><Btn variant="ghost" onClick={reset}><RotateCcw size={13}/>Reset</Btn><Btn variant="ghost" onClick={exportRows}><Download size={13}/>Export</Btn><Btn variant="ghost" onClick={()=>setImporting(true)}><Upload size={13}/>Import</Btn></div>
 <div className="grid grid-cols-3 gap-3 border bg-white p-3"><label>Client<select className={cls} value={filters.clientId} onChange={e=>setFilters({...filters,clientId:e.target.value})}><option value="">--- Select ---</option><option value="0">0-DummyClient</option></select></label><label>Status<select className={cls} value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">ALL</option><option>Active</option><option>Inactive</option></select></label><label>Channel Type<select className={cls} value={filters.channelType} onChange={e=>setFilters({...filters,channelType:e.target.value})}><option value="">--- Select ---</option>{channels.map(c=><option key={c.id} value={c.channel_type}>{c.channel_name}</option>)}</select></label></div>
 {advanced&&<div className="grid grid-cols-4 gap-2 border border-t-0 bg-white p-3">{[['channelCode','Channel'],['skuCode','Eretail SKU'],['skuDescription','SKU Description'],['channelSkuCode','Channel SKU'],['channelProductId','Channel Product Id']].map(([k,l])=><input key={k} aria-label={l} placeholder={l} className={cls} value={(filters as any)[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/>)}</div>}
 <div className="mt-2 overflow-auto border bg-white"><table className="min-w-[1200px] w-full text-xs"><thead className="bg-slate-100"><tr>{['Channel','Eretail SKU','SKU Description','Channel SKU','Channel Product Id','Channel Price','Picking Instructions','Status','Back Order Inventory','Updated By','Update'].map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={11} className="p-10 text-center">Loading...</td></tr>:rows.length?rows.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.channel_code}</td><td>{r.sku_code}</td><td>{r.sku_description}</td><td>{r.channel_sku_code}</td><td>{r.channel_product_id}</td><td>{r.channel_price}</td><td>{r.pick_instruction}</td><td>{r.status}</td><td>{r.back_order_qty}</td><td>{r.updated_by}</td><td><button className="text-sky-600" onClick={()=>{setForm({...emptyForm,...r});setEditor(true)}}>Update</button></td></tr>):<tr><td colSpan={11} className="p-10 text-center text-slate-400">No records to view</td></tr>}</tbody></table><div className="flex justify-between border-t p-2 text-xs"><span>Page {records?page:0} of {total}</span><span><button disabled={page<=1} onClick={()=>void search(page-1)}>Previous</button> <select aria-label="Records per Page" value={pageSize} onChange={e=>void search(1,Number(e.target.value))}>{sizes.map(x=><option key={x}>{x}</option>)}</select> <button disabled={!records||page>=total} onClick={()=>void search(page+1)}>Next</button></span><span>{records?`View ${(page-1)*pageSize+1} - ${Math.min(page*pageSize,records)} of ${records}`:'No records to view'}</span></div></div>
 <Modal title="SKU Channel Link Create/Edit" open={editor} onClose={()=>setEditor(false)} wide><div className="grid grid-cols-2 gap-3">{[['channel_code','Channel'],['sku_code','Eretail SKU'],['sku_description','SKU Description'],['channel_sku_code','Channel SKU'],['channel_product_id','Channel Product Id'],['back_order_qty','Back Order Inventory'],['channel_price','Channel Price'],['pick_instruction','Picking Instructions'],['maximum_sku_qty','Maximum SKU Qty']].map(([k,l])=><label key={k}>{l}<input className={cls} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Status<select className={cls} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label></div><div className="mt-4 flex justify-end gap-2"><Btn onClick={save}>Save</Btn><Btn variant="ghost" onClick={()=>setForm(emptyForm)}>Reset</Btn><Btn variant="ghost" onClick={()=>setEditor(false)}>Close</Btn></div></Modal>
 <Modal title="Import SKU Channel Link" open={importing} onClose={()=>setImporting(false)}><input type="file" accept=".csv" onChange={e=>{const file=e.target.files?.[0];if(file)void parseImport(file)}}/><p className="mt-2 text-xs text-slate-500">CSV columns: channel_code, sku_code, sku_description, channel_sku_code, channel_product_id, back_order_qty, channel_price, status.</p></Modal>{notice&&<Toast {...notice} onClose={()=>setNotice(null)}/>}</Shell>;
}
