/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from 'react';
import { Download, Search, Upload } from 'lucide-react';
import { apiGet, apiSend } from '../lib/api';
import { useDownload } from '../context/DownloadContext';
import Shell from './Shell';

const button = 'inline-flex items-center gap-1.5 rounded border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 hover:bg-slate-50';
const primary = 'inline-flex items-center gap-1.5 rounded bg-[#f5a623] px-3 py-2 text-sm font-medium text-white hover:bg-[#e2940f]';
const field = 'mt-1 w-full rounded border border-slate-300 px-2 py-2 text-sm outline-none focus:border-[#2f9e9e]';
export default function VinLister() {
  const { requestDownload } = useDownload(); const [tab, setTab] = useState('Products'); const [products, setProducts] = useState<any[]>([]); const [meta, setMeta] = useState<any>({ channels: [], categories: [] }); const [imports, setImports] = useState<any[]>([]); const [exports, setExports] = useState<any[]>([]); const [logs, setLogs] = useState<any[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [category, setCategory] = useState(''); const [channel, setChannel] = useState(''); const [upload, setUpload] = useState('');
  const load = () => { apiGet<any[]>('/api/vin-lister').then(setProducts); apiGet('/api/vin-lister?action=meta').then(setMeta); apiGet<any[]>('/api/vin-lister?action=imports').then(setImports); apiGet<any[]>('/api/vin-lister?action=exports').then(setExports); apiGet<any[]>('/api/vin-lister?action=logs').then(setLogs); };
  useEffect(load, []); const call = async (body: any) => { setError(''); try { const result = await apiSend('/api/vin-lister', 'POST', body); setMessage(body.action === 'sku-push' ? 'SKU push processed. View the record in Transmit Enquiry.' : 'Operation completed successfully.'); load(); return result; } catch (e: any) { setError(e.message); } };
  const filtered = products.filter((p) => (!category || p.category === category) && (!upload || `${p.sku_code} ${p.product_name}`.toLowerCase().includes(upload.toLowerCase())));
  const download = (rows: any[], title: string) => requestDownload({ title, module: 'vin-lister', baseName: title.replaceAll(' ', '-'), data: { columns: ['SKU Code', 'Product Name', 'Category', 'Marketplaces', 'Prices'], rows: rows.map((p) => [p.sku_code, p.product_name, p.category, (p.marketplaces || []).join(', '), Object.entries(p.prices || {}).map(([c, price]) => `${c}:${price}`).join(' | ')]) } });
  return <Shell active="master" breadcrumb="VIN LISTER > Catalog Management" openScreens={[{ label: 'Vin Lister', to: '#' }]}><div className="space-y-4"><div className="rounded border border-slate-200 bg-white"><div className="flex flex-wrap border-b bg-slate-50">{['Products', 'Imports', 'Exports', 'SKU Management', 'Transmit Enquiry'].map((name) => <button key={name} onClick={() => setTab(name)} className={`px-4 py-3 text-sm font-medium ${tab === name ? 'border-b-2 border-[#f5a623] bg-white text-slate-800' : 'text-slate-500'}`}>{name}</button>)}</div><div className="p-4">{message && <p className="mb-3 rounded border border-emerald-200 bg-emerald-50 p-2 text-sm text-emerald-700">{message}</p>}{error && <p className="mb-3 rounded border border-rose-200 bg-rose-50 p-2 text-sm text-rose-700">{error}</p>}
    {tab === 'Products' && <><div className="mb-4 grid gap-3 md:grid-cols-4"><label className="text-sm">SKU / Product<input value={upload} onChange={(e) => setUpload(e.target.value)} className={field} /></label><label className="text-sm">Category<select value={category} onChange={(e) => setCategory(e.target.value)} className={field}><option value="">All Categories</option>{meta.categories.map((x: string) => <option key={x}>{x}</option>)}</select></label><div className="flex items-end gap-2"><button className={primary}><Search size={15} /> Filter</button><button onClick={() => download(filtered, 'VinLister Products')} className={button}><Download size={15} /> Price Export</button></div></div><Table rows={filtered} cols={['sku_code', 'product_name', 'category', 'marketplaces', 'prices']} actions={(p: any) => <select aria-label="Assign marketplace" onChange={(e) => e.target.value && call({ action: 'assign-marketplace', id: p.id, channel: e.target.value })} className="border p-1 text-xs"><option value="">Assign marketplace</option>{meta.channels.map((x: string) => <option key={x}>{x}</option>)}</select>} /></>}
    {tab === 'Imports' && <Imports meta={meta} upload={upload} setUpload={setUpload} call={call} imports={imports} />}
    {tab === 'Exports' && <><div className="mb-4 grid gap-3 md:grid-cols-3"><label className="text-sm">Export Type<select className={field}><option>Product by Export Profile</option><option>Channel Pricing Export</option></select></label><label className="text-sm">Channel<select value={channel} onChange={(e) => setChannel(e.target.value)} className={field}><option value="">All</option>{meta.channels.map((x: string) => <option key={x}>{x}</option>)}</select></label><div className="flex items-end"><button onClick={() => call({ action: 'export', export_type: 'Product by Export Profile', channel, category })} className={primary}><Download size={15} /> Generate Export</button></div></div><Table rows={exports} cols={['export_type', 'channel', 'category', 'count', 'status', 'created_at']} actions={(r: any) => <button onClick={() => download(r.rows || [], r.export_type)} className={button}>Download</button>} /></>}
    {tab === 'SKU Management' && <Table rows={products} cols={['sku_code', 'product_name', 'marketplaces', 'status']} actions={(p: any) => <select aria-label="SKU push channel" onChange={(e) => e.target.value && call({ action: 'sku-push', id: p.id, channel: e.target.value })} className="border p-1 text-xs"><option value="">SKU Push</option>{(p.marketplaces || []).map((x: string) => <option key={x}>{x}</option>)}</select>} />}
    {tab === 'Transmit Enquiry' && <Table rows={logs} cols={['sku_code', 'product_name', 'channel', 'operation', 'status', 'processed_at']} />}</div></div></div></Shell>;
}
function Imports({ meta, upload, setUpload, call, imports }: any) { const [type, setType] = useState('Product'); const [channel, setChannel] = useState(''); const [token, setToken] = useState(''); const submit = () => { if (type === 'Product') { const rows = upload.split(/\r?\n/).filter(Boolean).map((line: string) => { const [sku_code, product_name, category] = line.split(',').map((v) => v.trim()); return { sku_code, product_name, category }; }); call({ action: 'product-import', file_name: 'product-import.csv', rows }); } else if (type === 'Image Import') call({ action: 'image-import', access_token: token, sku_codes: upload.split(/\r?\n/).filter(Boolean) }); else { const rows = upload.split(/\r?\n/).filter(Boolean).map((line: string) => { const [sku_code, price] = line.split(','); return { sku_code: sku_code.trim(), price: Number(price) }; }); call({ action: 'price-import', channel, rows }); } }; return <><div className="mb-4 grid gap-3 md:grid-cols-3"><label className="text-sm">Import Type<select value={type} onChange={(e) => setType(e.target.value)} className={field}><option>Product</option><option>Image Import</option><option>Channel Price</option></select></label>{type === 'Channel Price' && <label className="text-sm">Select Channel<select value={channel} onChange={(e) => setChannel(e.target.value)} className={field}><option value="">Select Channel</option>{meta.channels.map((x: string) => <option key={x}>{x}</option>)}</select></label>}{type === 'Image Import' && <label className="text-sm">Dropbox Access Token<input value={token} onChange={(e) => setToken(e.target.value)} className={field} /></label>}</div><p className="mb-2 text-xs text-slate-500">PDF does not specify template columns. Local input uses one CSV line per record: {type === 'Product' ? 'SKU Code, Product Name, documented Category' : type === 'Channel Price' ? 'SKU Code, Price' : 'SKU Code'}.</p><textarea value={upload} onChange={(e) => setUpload(e.target.value)} className="h-36 w-full rounded border border-slate-300 p-2 font-mono text-sm" placeholder={type === 'Product' ? 'SKU-001, Product name, Fashion & Accessories' : type === 'Channel Price' ? 'SKU-001,1299' : 'SKU-001'} /><div className="mt-3 flex gap-2"><button onClick={() => setUpload(type === 'Product' ? 'SKU Code,Product Name,Category\nSKU-001,Sample Product,Fashion & Accessories' : type === 'Channel Price' ? 'SKU Code,Price\nSKU-001,1299' : 'SKU Code\nSKU-001')} className={button}><Download size={15} /> Download Template</button><button onClick={submit} className={primary}><Upload size={15} /> Import</button></div><h3 className="mt-6 font-semibold text-slate-700">Import History</h3><Table rows={imports} cols={['import_type', 'channel', 'file_name', 'count', 'status', 'created_at']} /></> }
function Table({ rows, cols, actions }: any) { return <div className="overflow-auto border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr>{cols.map((c: string) => <th className="whitespace-nowrap border-b px-3 py-2 capitalize" key={c}>{c.replaceAll('_', ' ')}</th>)}{actions && <th className="border-b px-3 py-2">Operation</th>}</tr></thead><tbody>{rows.length ? rows.map((r: any) => <tr className="border-b odd:bg-slate-50" key={r.id}>{cols.map((c: string) => <td className="px-3 py-2" key={c}>{Array.isArray(r[c]) ? r[c].join(', ') : typeof r[c] === 'object' && r[c] ? Object.entries(r[c]).map(([k, v]) => `${k}:${v}`).join(' | ') : r[c] || '—'}</td>)}{actions && <td className="px-3 py-2">{actions(r)}</td>}</tr>) : <tr><td colSpan={cols.length + 1} className="h-24 text-center text-slate-400">No records to view</td></tr>}</tbody></table></div>; }
