/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { Download, FileText, PackageCheck, RefreshCw, Save, Send, Truck } from 'lucide-react';
import Shell from '../Shell';
import Modal from '../../components/Modal';
import { Btn, Pill, Toast } from '../parts';
import { apiGet, apiSend } from '../../lib/api';
import { useDownload } from '../../context/DownloadContext';

const TABS = [
  ['configuration', '1. Channel Maintenance'], ['mappings', '2. Channel Mappings'], ['orders', '3. Orders'],
  ['packing', '4. Order Pack'], ['shipment', '5. Shipment & Returns'], ['logs', '6. MP Inventory Log'],
] as const;
const input = 'w-full rounded-sm border border-slate-300 bg-white px-2 py-1.5 text-xs text-slate-700 outline-none focus:border-cyan-500 disabled:bg-slate-100 disabled:text-slate-400';
const Th = ({ children }: { children?: React.ReactNode }) => <th className="border-r border-slate-300 bg-[#e7edf2] px-2 py-2 text-left text-[11px] font-semibold text-slate-600">{children}</th>;
const Td = ({ children }: { children?: React.ReactNode }) => <td className="border-r border-t border-slate-200 px-2 py-2 text-xs text-slate-600">{children}</td>;
const Field = ({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) => <label className="grid grid-cols-[170px_minmax(0,1fr)] items-center gap-3 text-xs text-slate-500"><span className="text-right">{label}{required && <b className="text-rose-500"> *</b>}</span>{children}</label>;
const REGION_DEFAULTS: Record<string, any> = {
  India: { channel_type: 'Amazon India', country_code: 'IN', endpoint: 'https://mws.amazonservices.in', marketplace_id: 'A21TJRUUN4KGV', developer_id: '073980952359', enable_easy_ship: true, need_invoice: true },
  UAE: { channel_type: 'Amazon UAE', country_code: 'AE', endpoint: 'https://mws.amazonservices.ae', marketplace_id: 'A2VIGQ35RCS4UG', developer_id: '073980952359', enable_easy_ship: false },
  US: { channel_type: 'Amazon US & Other Countries', country_code: 'US', endpoint: 'https://mws.amazonservices.com', marketplace_id: 'ATVPDKIKX0DER', developer_id: '18802594138', enable_easy_ship: false },
};

export default function AmazonMFNWorkflow() {
  const { requestDownload } = useDownload();
  const [tab, setTab] = useState<(typeof TABS)[number][0]>('configuration');
  const [data, setData] = useState<any>({ config: {}, mappings: [], orders: [], inventoryLogs: [], returns: [], shipments: [], skus: [] });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<{ msg: string; type: 'ok' | 'err' } | null>(null);
  const [configure, setConfigure] = useState(false); const [otpModal, setOtpModal] = useState(false); const [otp, setOtp] = useState('');
  const [secrets, setSecrets] = useState({ access_key: '', secret_key: '', mws_token: '', panel_password: '' });
  const [mappingSku, setMappingSku] = useState<Record<number, string>>({}); const [selectedMappings, setSelectedMappings] = useState<number[]>([]);
  const [dimensions, setDimensions] = useState<Record<number, { weight_kg: number; length_cm: number; width_cm: number; height_cm: number }>>({});
  const [shipping, setShipping] = useState<Record<number, { transporter_name: string; tracking_no: string }>>({});

  const load = async () => {
    setLoading(true);
    try {
      const [config, mappings, orders, inventoryLogs, returns, shipments, skus] = await Promise.all([
        apiGet<any[]>('/api/amazon-mfn?entity=config'), apiGet<any[]>('/api/amazon-mfn?entity=mappings'), apiGet<any[]>('/api/amazon-mfn?entity=orders'),
        apiGet<any[]>('/api/amazon-mfn?entity=inventoryLogs'), apiGet<any[]>('/api/amazon-mfn?entity=returns'), apiGet<any[]>('/api/amazon-mfn?entity=shipments'), apiGet<any[]>('/api/skus'),
      ]);
      setData({ config: config[0] || {}, mappings, orders, inventoryLogs, returns, shipments, skus });
    } catch (error: any) { setNotice({ msg: error.message, type: 'err' }); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  const setConfig = (fields: any) => setData({ ...data, config: { ...data.config, ...fields } });
  const act = async (body: any, ok: string, method = 'POST') => {
    setBusy(true);
    try { const result = await apiSend('/api/amazon-mfn', method, body); setNotice({ msg: result.message || ok, type: 'ok' }); await load(); return result; }
    catch (error: any) { setNotice({ msg: error.message, type: 'err' }); return null; }
    finally { setBusy(false); }
  };
  const saveConfig = async () => {
    const result = await act({ action: 'save-config', ...data.config, ...secrets }, 'Amazon MFN channel configuration saved.', 'PUT');
    if (result) { setSecrets({ access_key: '', secret_key: '', mws_token: '', panel_password: '' }); setConfigure(false); }
  };
  const chooseRegion = (region: string) => setConfig({ region, ...REGION_DEFAULTS[region] });
  const dims = (id: number) => dimensions[id] || { weight_kg: 0, length_cm: 0, width_cm: 0, height_cm: 0 };
  const updateDims = (id: number, field: string, value: number) => setDimensions({ ...dimensions, [id]: { ...dims(id), [field]: value } });
  const ship = (id: number) => shipping[id] || { transporter_name: '', tracking_no: '' };
  const printDocuments = (order: any) => requestDownload({ title: `Amazon MFN Documents ${order.amazon_order_id}`, module: 'amazon-mfn-label', baseName: `Amazon-MFN-${order.amazon_order_id}`, data: { columns: ['Amazon Order ID', 'Invoice', 'Shipping Label', 'Tracking No.', 'Weight', 'Dimensions'], rows: [[order.amazon_order_id, order.invoice_no, order.shipping_label, order.tracking_no, `${order.weight_kg} kg`, `${order.length_cm}×${order.width_cm}×${order.height_cm} cm`]] } });

  return <Shell active="sales" breadcrumb="Sales > Manage Channels > Amazon MFN" openScreens={[{ label: 'Amazon MFN Integration', to: '#' }]}>
    <div className="mb-3 flex flex-wrap items-center gap-1 border border-slate-300 bg-white p-2">
      {TABS.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`border-b-2 px-3 py-2 text-xs font-semibold ${tab === key ? 'border-cyan-600 bg-cyan-50 text-cyan-700' : 'border-transparent text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}
      <button onClick={load} className="ml-auto rounded border px-3 py-2 text-xs text-slate-500"><RefreshCw className="inline" size={13}/> Refresh</button>
    </div>

    {tab === 'configuration' && <Section title="Channel Maintenance">
      <div className="mb-4 flex items-center justify-between border-b pb-3"><div><span className="text-xs text-slate-400">Channel Type</span><h3 className="text-2xl font-semibold text-slate-700">{data.config.channel_type || 'Amazon India'} <span className="text-sm font-bold text-slate-500">amazon</span></h3></div><div className="flex gap-2"><span className={`px-3 py-2 text-xs font-semibold ${data.config.interface_status === 'Configured' ? 'bg-emerald-500 text-white' : 'bg-rose-500 text-white'}`}>{data.config.interface_status || 'Not Configured'}</span>{data.config.interface_status === 'OTP Required' && <Btn variant="ghost" onClick={() => setOtpModal(true)}>Channel Connection Status</Btn>}<Btn variant="ghost" onClick={() => setConfigure(true)}>Configuring Interface</Btn><Btn variant="warn" disabled={busy} onClick={saveConfig}><Save size={14}/>Save</Btn></div></div>
      <Accordion title="Channel Detail"><div className="grid grid-cols-2 gap-x-8 gap-y-3">
        <Field label="Channel Code"><input className={input} disabled value={data.config.channel_code || ''}/></Field><Field label="Channel Name" required><input className={input} value={data.config.channel_name || ''} onChange={(e) => setConfig({ channel_name: e.target.value })}/></Field>
        <Field label="Order Fulfillment WH" required><select className={input} value={data.config.order_fulfillment_wh || ''} onChange={(e) => setConfig({ order_fulfillment_wh: e.target.value })}><option>Delhi NCR</option><option>Mumbai WH</option><option>Bengaluru WH</option><option>Kolkata WH</option></select></Field><Field label="Status"><select className={input} value={data.config.status || 'Active'} onChange={(e) => setConfig({ status: e.target.value })}><option>Active</option><option>Inactive</option></select></Field>
        <Field label="Channel SLA(in hrs)"><input type="number" className={input} value={data.config.channel_sla_hours || 48} onChange={(e) => setConfig({ channel_sla_hours: Number(e.target.value) })}/></Field><Field label="Auto Range SKU"><select className={input} value={data.config.auto_range_sku || 'No'} onChange={(e) => setConfig({ auto_range_sku: e.target.value })}><option>No</option><option>Yes</option></select></Field>
        <Field label="Customer"><input className={input} value={data.config.customer || ''} onChange={(e) => setConfig({ customer: e.target.value })}/></Field><Field label="Tax Type"><select className={input} value={data.config.tax_type || 'Tax Inclusive'} onChange={(e) => setConfig({ tax_type: e.target.value })}><option>Tax Inclusive</option><option>Tax Exclusive</option></select></Field>
      </div></Accordion>
      <Accordion title="Orders"><div className="grid grid-cols-2 gap-x-8 gap-y-3">
        <Field label="Order Sync" required><YesNo value={data.config.order_sync} onChange={(value) => setConfig({ order_sync: value })}/></Field><Field label="Order Sync From Date" required><input type="date" className={input} disabled={!data.config.order_sync} value={data.config.order_sync_from_date || ''} onChange={(e) => setConfig({ order_sync_from_date: e.target.value })}/></Field>
        <Field label="Shipping By"><select className={input} value={data.config.shipping_by || ''} onChange={(e) => setConfig({ shipping_by: e.target.value })}><option>Ship By Marketplace</option><option>Ship By Seller</option></select></Field><Field label="Bill To Party & Its Master"><input className={input} value={data.config.bill_to_party || ''} onChange={(e) => setConfig({ bill_to_party: e.target.value })}/></Field>
        <Field label="Invoice No By"><select className={input} value={data.config.invoice_no_by || 'Self'} onChange={(e) => setConfig({ invoice_no_by: e.target.value })}><option>Self</option><option>Marketplace</option></select></Field><Field label="PrePack Enabled"><Check value={data.config.prepack_enabled} onChange={(value) => setConfig({ prepack_enabled: value })}/></Field>
        <Field label="Mark ReadyToShip At"><select className={input} value={data.config.ready_to_ship_at || 'Pack'} onChange={(e) => setConfig({ ready_to_ship_at: e.target.value })}><option>Manifest</option><option>Pack</option></select></Field><Field label="Each Qty Per Line"><Check value={data.config.each_qty_per_line} onChange={(value) => setConfig({ each_qty_per_line: value })}/></Field>
        <Field label="Return Order Sync"><YesNo value={data.config.return_sync} onChange={(value) => setConfig({ return_sync: value })}/></Field><Field label="Return Sync From Date"><input type="date" className={input} disabled={!data.config.return_sync} value={data.config.return_sync_from_date || ''} onChange={(e) => setConfig({ return_sync_from_date: e.target.value })}/></Field>
        <Field label="Use Marketplace Shipping Label"><Check value={data.config.use_marketplace_shipping_label} onChange={(value) => setConfig({ use_marketplace_shipping_label: value })}/></Field><Field label="Domestic Invoice"><input className={input} value={data.config.domestic_invoice || ''} onChange={(e) => setConfig({ domestic_invoice: e.target.value })}/></Field>
        <Field label="Shipping Label"><input className={input} value={data.config.shipping_label || ''} onChange={(e) => setConfig({ shipping_label: e.target.value })}/></Field>
      </div></Accordion>
      <Accordion title="Channel SKU"><div className="grid grid-cols-2 gap-x-8 gap-y-3"><Field label="SKU Pull"><YesNo value={true} onChange={() => undefined}/></Field><Field label="Single Warehouse MFN"><YesNo value={data.config.single_warehouse} onChange={(value) => setConfig({ single_warehouse: value })}/></Field></div></Accordion>
      <Accordion title="Inventory"><div className="grid grid-cols-2 gap-x-8 gap-y-3"><Field label="Inventory Sync"><YesNo value={data.config.inventory_sync} onChange={(value) => setConfig({ inventory_sync: value })}/></Field><Field label="Sync Method"><select className={input} value={data.config.inventory_sync_method || 'Push'} onChange={(e) => setConfig({ inventory_sync_method: e.target.value })}><option>Push</option><option>Pull</option></select></Field><Field label="Safety Stock"><input type="number" min="0" className={input} value={data.config.safety_stock || 0} onChange={(e) => setConfig({ safety_stock: Number(e.target.value) })}/></Field><Field label="Enable Inventory Recon"><YesNo value={data.config.enable_inventory_reconciliation} onChange={(value) => setConfig({ enable_inventory_reconciliation: value })}/></Field></div></Accordion>
      <Note>Amazon MFN is a single warehouse integration. Use a separate seller account per warehouse or Amazon Flex for multi-warehouse fulfillment. Orders normally carry a 24–48 hour SLA.</Note>
    </Section>}

    {tab === 'mappings' && <Section title="Channel Mappings and Inventory Sync">
      <div className="mb-3 flex justify-end gap-2"><Btn variant="ghost" disabled={!selectedMappings.length || busy} onClick={() => act({ action: 'submit-inventory', mapping_ids: selectedMappings }, 'Amazon inventory Feed submitted.')}><Send size={14}/>Synchronize Inventory</Btn><Btn disabled={busy} onClick={() => act({ action: 'reconcile-inventory' }, 'Amazon inventory reconciliation completed.')}><RefreshCw size={14}/>Reconcile Inv</Btn></div>
      <table className="w-full"><thead><tr><Th></Th><Th>Merchant SKU</Th><Th>ASIN</Th><Th>ChannelSKUCode</Th><Th>ChannelProductId</Th><Th>Vin SKU</Th><Th>Mapping</Th><Th>Inventory Feed</Th><Th>Published Inventory</Th><Th>Action</Th></tr></thead><tbody>{data.mappings.map((row: any) => <tr key={row.id}><Td><input type="checkbox" disabled={row.mapping_status !== 'Mapped'} checked={selectedMappings.includes(row.id)} onChange={() => setSelectedMappings(selectedMappings.includes(row.id) ? selectedMappings.filter((id) => id !== row.id) : [...selectedMappings, row.id])}/></Td><Td>{row.merchant_sku}</Td><Td>{row.asin}</Td><Td>{row.merchant_sku}</Td><Td>{row.asin}</Td><Td>{row.mapping_status === 'Mapped' ? row.sku_code : <select className={input} value={mappingSku[row.id] || ''} onChange={(e) => setMappingSku({ ...mappingSku, [row.id]: e.target.value })}><option value="">Select SKU</option>{data.skus.map((sku: any) => <option key={sku.id} value={sku.sku_code}>{sku.sku_code}</option>)}</select>}</Td><Td><Pill status={row.mapping_status}/></Td><Td><Pill status={row.feed_status}/></Td><Td>{row.published_inventory}</Td><Td>{row.mapping_status === 'Mapped' ? 'Mapped' : <Btn variant="ghost" disabled={!mappingSku[row.id]} onClick={() => act({ action: 'map-sku', id: row.id, sku_code: mappingSku[row.id], channel_sku_code: row.merchant_sku, channel_product_id: row.asin }, 'Merchant SKU and ASIN mapped.', 'PUT')}>Map SKU</Btn>}</Td></tr>)}</tbody></table>
      <Note>Amazon Merchant SKU maps to ChannelSKUCode. ASIN maps to ChannelProductId. Inventory Push first creates a Submitted feed; Amazon updates the listing only after the MP Inventory Log becomes Success.</Note>
    </Section>}

    {tab === 'orders' && <Section title="Amazon Order Pull and Create">
      <div className="mb-3 flex justify-end"><Btn disabled={busy} onClick={() => act({ action: 'pull-orders' }, 'Pending and Un-Shipped Amazon orders pulled.')}><Download size={14}/>Order Pull</Btn></div>
      <table className="w-full"><thead><tr><Th>Amazon Order ID</Th><Th>Marketplace Status</Th><Th>Vin Status</Th><Th>Customer</Th><Th>Warehouse</Th><Th>Latest Ship Date</Th><Th>Reservation</Th><Th>Sales Order</Th><Th>Action</Th></tr></thead><tbody>{data.orders.map((row: any) => <tr key={row.id}><Td>{row.amazon_order_id}</Td><Td><Pill status={row.marketplace_status}/></Td><Td><Pill status={row.eretail_status}/></Td><Td>{row.customer_name || 'Unavailable while Pending'}</Td><Td>{row.warehouse}</Td><Td>{row.latest_ship_date}</Td><Td>{row.reservation_status}</Td><Td>{row.sales_order_no || '—'}</Td><Td><span className="flex gap-1">{row.marketplace_status === 'Pending' && !row.cancelled && <Btn variant="ghost" disabled={busy} onClick={() => act({ action: 'confirm-order', id: row.id }, 'Amazon order moved to Un-Shipped and Allocated.')}>Confirm on Amazon</Btn>}{!['Packed', 'Shipped', 'Cancelled'].includes(row.eretail_status) && <Btn variant="warn" disabled={busy} onClick={() => act({ action: 'cancel-order', id: row.id }, 'Order cancellation pushed to Amazon.')}>Cancel</Btn>}</span></Td></tr>)}</tbody></table>
      <Note>Pending orders reserve inventory without customer information. When Amazon confirms an order as Un-Shipped, Vin e-Retail updates the customer information and moves it to Allocated when inventory is available.</Note>
    </Section>}

    {tab === 'packing' && <Section title="Order Pack — Invoice and Shipping Label">
      <table className="w-full"><thead><tr><Th>Amazon Order ID</Th><Th>Vin Status</Th><Th>Amazon Status</Th><Th>Weight (kg)</Th><Th>Length (cm)</Th><Th>Width (cm)</Th><Th>Height (cm)</Th><Th>Label Status</Th><Th>Invoice / Tracking</Th><Th>Action</Th></tr></thead><tbody>{data.orders.filter((row: any) => !['Pending', 'Not Pulled', 'Cancelled', 'Shipped'].includes(row.eretail_status)).map((row: any) => <tr key={row.id}><Td>{row.amazon_order_id}</Td><Td><Pill status={row.eretail_status}/></Td><Td><Pill status={row.marketplace_status}/></Td>{(['weight_kg', 'length_cm', 'width_cm', 'height_cm'] as const).map((field) => <Td key={field}><input type="number" min="0" step="0.01" disabled={row.eretail_status === 'Packed'} className={`${input} w-20`} value={dims(row.id)[field] || row[field] || 0} onChange={(e) => updateDims(row.id, field, Number(e.target.value))}/></Td>)}<Td><Pill status={row.label_status}/><br/><span>{row.pack_status}</span></Td><Td>{row.invoice_no || '—'}<br/>{row.tracking_no || '—'}</Td><Td><span className="flex flex-wrap gap-1">{row.eretail_status === 'Allocated' && <><Btn variant="ghost" disabled={busy} onClick={() => act({ action: 'prefetch-label', id: row.id, ...dims(row.id) }, 'Amazon invoice/label prefetch submitted.')}>Prefetch</Btn><Btn disabled={busy} onClick={() => act({ action: 'pack-order', id: row.id, ...dims(row.id) }, 'Amazon Order Pack submitted.') }><PackageCheck size={14}/>Order Pack</Btn></>}{row.label_status === 'Processing' && <Btn variant="warn" disabled={busy} onClick={() => act({ action: 'process-label', id: row.id }, 'Amazon Feed processed and shipping label generated.')}>Process Scheduled Pack</Btn>}{row.shipping_label && <Btn variant="ghost" onClick={() => printDocuments(row)}><FileText size={14}/>Invoice / Ship Label</Btn>}</span></Td></tr>)}</tbody></table>
      <Note>Amazon label generation uses 8–9 asynchronous API/feed calls, is limited to 30 calls per hour, and is scheduled every six minutes. Feed processing may take 6–10 minutes. Weight and every dimension must be greater than zero.</Note>
      <IssueList/>
    </Section>}

    {tab === 'shipment' && <Section title="Order Shipment and Return Pull">
      <h3 className="mb-2 text-xs font-semibold uppercase text-slate-500">Packed Amazon Orders</h3><table className="w-full"><thead><tr><Th>Amazon Order ID</Th><Th>Invoice</Th><Th>Shipping Label</Th><Th>Transporter Name</Th><Th>Tracking No.</Th><Th>Amazon Status</Th><Th>Action</Th></tr></thead><tbody>{data.orders.filter((row: any) => ['Packed', 'Shipped'].includes(row.eretail_status)).map((row: any) => <tr key={row.id}><Td>{row.amazon_order_id}</Td><Td>{row.invoice_no}</Td><Td>{row.shipping_label}</Td><Td><input disabled={row.eretail_status === 'Shipped'} className={input} value={ship(row.id).transporter_name || row.transporter_name || ''} onChange={(e) => setShipping({ ...shipping, [row.id]: { ...ship(row.id), transporter_name: e.target.value } })}/></Td><Td><input disabled={row.eretail_status === 'Shipped'} className={input} value={ship(row.id).tracking_no || row.tracking_no || ''} onChange={(e) => setShipping({ ...shipping, [row.id]: { ...ship(row.id), tracking_no: e.target.value } })}/></Td><Td><Pill status={row.marketplace_status}/></Td><Td><Btn disabled={row.eretail_status !== 'Packed' || busy} onClick={() => act({ action: 'ship-order', id: row.id, ...ship(row.id), tracking_no: ship(row.id).tracking_no || row.tracking_no }, 'Transporter, Tracking No. and Shipped status updated on Amazon.')}><Truck size={14}/>Ship</Btn></Td></tr>)}</tbody></table>
      <h3 className="mt-6 mb-2 text-xs font-semibold uppercase text-slate-500">Order Return Pull</h3><div className="mb-2 flex justify-end"><Btn variant="ghost" disabled={busy} onClick={() => act({ action: 'pull-returns' }, 'Amazon returns pulled in Confirmed status.')}><Download size={14}/>Return Order Sync</Btn></div><table className="w-full"><thead><tr><Th>Amazon Return ID</Th><Th>Amazon Order ID</Th><Th>SKU</Th><Th>Qty</Th><Th>Reason</Th><Th>Status</Th><Th>Inbound</Th></tr></thead><tbody>{data.returns.map((row: any) => <tr key={row.id}><Td>{row.amazon_return_id}</Td><Td>{row.amazon_order_id}</Td><Td>{row.sku_code}</Td><Td>{row.qty}</Td><Td>{row.reason}</Td><Td><Pill status={row.status}/></Td><Td>{row.inbound_status}</Td></tr>)}</tbody></table>
      <Note>At Shipment, Vin e-Retail pushes Transporter Name, Tracking No. and Status to Amazon. Pulled returns are always created in Confirmed status and require a separate inbound operation.</Note>
    </Section>}

    {tab === 'logs' && <Section title="MP Inventory Log">
      <table className="w-full"><thead><tr><Th>Feed ID</Th><Th>Merchant SKU</Th><Th>ASIN</Th><Th>Quantity</Th><Th>Submitted At</Th><Th>Processed At</Th><Th>Status</Th><Th>Message</Th><Th>Action</Th></tr></thead><tbody>{data.inventoryLogs.length ? data.inventoryLogs.map((row: any) => <tr key={row.id}><Td>{row.feed_id}</Td><Td>{row.merchant_sku}</Td><Td>{row.asin}</Td><Td>{row.quantity}</Td><Td>{row.submitted_at}</Td><Td>{row.processed_at || '—'}</Td><Td><Pill status={row.status}/></Td><Td>{row.message}</Td><Td><Btn variant="ghost" disabled={row.status !== 'Submitted' || busy} onClick={() => act({ action: 'process-feed', id: row.id }, 'Amazon inventory Feed processed successfully.')}>Process Feed</Btn></Td></tr>) : <tr><td colSpan={9} className="p-10 text-center text-sm text-slate-400">No inventory feed submitted</td></tr>}</tbody></table>
      <Note>Submitted means the feed was accepted for asynchronous processing. Success means Amazon processed the feed and the website inventory was updated.</Note>
    </Section>}

    <Modal title="Channel Configure" open={configure} onClose={() => setConfigure(false)} wide><div className="border-b pb-2 text-xs font-semibold text-slate-500">Seller Credentials</div><div className="mt-3 mb-4 grid grid-cols-3 gap-2"><button onClick={() => chooseRegion('India')} className={`rounded border p-2 text-xs ${data.config.region === 'India' ? 'border-cyan-600 bg-cyan-50 text-cyan-700' : ''}`}>Amazon India</button><button onClick={() => chooseRegion('UAE')} className={`rounded border p-2 text-xs ${data.config.region === 'UAE' ? 'border-cyan-600 bg-cyan-50 text-cyan-700' : ''}`}>Amazon UAE</button><button onClick={() => chooseRegion('US')} className={`rounded border p-2 text-xs ${data.config.region === 'US' ? 'border-cyan-600 bg-cyan-50 text-cyan-700' : ''}`}>Amazon US, Canada, Europe, UK, Australia, Mexico</button></div><div className="grid grid-cols-2 gap-x-8 gap-y-3">
      <Field label="Seller Id" required><input className={input} value={data.config.seller_id || ''} onChange={(e) => setConfig({ seller_id: e.target.value })}/></Field><Field label="Access Key" required><input type="password" className={input} value={secrets.access_key} placeholder={data.config.access_key_configured ? 'Configured — enter only to replace' : 'Enter MWS Access Key or _'} onChange={(e) => setSecrets({ ...secrets, access_key: e.target.value })}/></Field>
      <Field label="Marketplace Id" required><input className={input} value={data.config.marketplace_id || ''} onChange={(e) => setConfig({ marketplace_id: e.target.value })}/></Field><Field label="Secret Key" required><input type="password" className={input} value={secrets.secret_key} placeholder={data.config.secret_key_configured ? 'Configured — enter only to replace' : 'Enter MWS Secret Key or _'} onChange={(e) => setSecrets({ ...secrets, secret_key: e.target.value })}/></Field>
      {data.config.region === 'India' && <><Field label="Panel User Id" required><input className={input} value={data.config.panel_user_id || ''} onChange={(e) => setConfig({ panel_user_id: e.target.value })}/></Field><Field label="Panel Password" required><input type="password" className={input} value={secrets.panel_password} placeholder={data.config.panel_password_configured ? 'Configured — enter only to replace' : 'Enter Panel Password'} onChange={(e) => setSecrets({ ...secrets, panel_password: e.target.value })}/></Field><Field label="No Slot on Sunday(1/0)"><select className={input} value={data.config.no_slot_on_sunday ?? 1} onChange={(e) => setConfig({ no_slot_on_sunday: Number(e.target.value) })}><option value="1">1</option><option value="0">0</option></select></Field><Field label="Need Invoice" required><YesNo value={data.config.need_invoice} onChange={(value) => setConfig({ need_invoice: value })}/></Field><Field label="Enable Easy Ship" required><YesNo value={data.config.enable_easy_ship} onChange={(value) => setConfig({ enable_easy_ship: value, otp_verified: value ? false : data.config.otp_verified })}/></Field></>}
      <Field label="MWS Token" required><input type="password" className={input} value={secrets.mws_token} placeholder={data.config.mws_token_configured ? 'Configured — enter only to replace' : 'Enter MWS Auth Token'} onChange={(e) => setSecrets({ ...secrets, mws_token: e.target.value })}/></Field><Field label="DeveloperId" required><input className={input} value={data.config.developer_id || ''} onChange={(e) => setConfig({ developer_id: e.target.value })}/></Field>
      <Field label="Developer Name" required><input className={input} value={data.config.developer_name || 'vinculum'} onChange={(e) => setConfig({ developer_name: e.target.value })}/></Field><Field label="MWS Endpoint"><input className={input} disabled value={data.config.endpoint || ''}/></Field>
    </div><Note>Merchant ID, Marketplace ID, access/secret credentials or MWS Auth Token are confidential. Developer Name must be vinculum in small caps with no spaces.</Note><div className="mt-4 flex justify-end gap-2"><Btn variant="warn" disabled={busy} onClick={saveConfig}>OK</Btn><Btn variant="ghost" onClick={() => setConfigure(false)}>Close</Btn></div></Modal>

    <Modal title="Channel Connection Status" open={otpModal} onClose={() => setOtpModal(false)}><Field label="Amazon OTP" required><input className={input} maxLength={6} value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))}/></Field><Note>When Enable Easy Ship is No, login through Amazon OTP is required. The guide notes that OTP login does not guarantee successful label generation.</Note><div className="mt-4 flex justify-end gap-2"><Btn variant="warn" disabled={busy} onClick={async () => { const result = await act({ action: 'verify-otp', otp }, 'Amazon Channel Connection verified.'); if (result) { setOtp(''); setOtpModal(false); } }}>Verify OTP</Btn><Btn variant="ghost" onClick={() => setOtpModal(false)}>Close</Btn></div></Modal>
    {loading && <div className="fixed inset-0 z-40 grid place-items-center bg-white/50"><div className="h-10 w-10 animate-spin rounded-full border-4 border-slate-200 border-t-cyan-600"/><span className="sr-only">Loading Amazon MFN</span></div>}
    {notice && <Toast {...notice} onClose={() => setNotice(null)}/>}</Shell>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-slate-300 bg-white"><h2 className="border-b-4 border-cyan-600 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-600">{title}</h2><div className="p-4">{children}</div></section>; }
function Accordion({ title, children }: { title: string; children: React.ReactNode }) { return <div className="mb-2 border border-slate-300"><h3 className="bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">{title}</h3><div className="p-3">{children}</div></div>; }
function YesNo({ value, onChange }: { value: boolean; onChange: (value: boolean) => void }) { return <select className={input} value={value ? 'Yes' : 'No'} onChange={(e) => onChange(e.target.value === 'Yes')}><option>Yes</option><option>No</option></select>; }
function Check({ value, onChange }: { value: boolean; onChange: (value: boolean) => void }) { return <input type="checkbox" checked={Boolean(value)} onChange={(e) => onChange(e.target.checked)} className="h-4 w-4 accent-cyan-600"/>; }
function Note({ children }: { children: React.ReactNode }) { return <p className="mt-4 border-l-4 border-sky-400 bg-sky-50 p-3 text-xs leading-5 text-slate-600">{children}</p>; }
function IssueList() { return <div className="mt-4 border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700"><b>Common Amazon Integration responses</b><ul className="mt-2 list-disc space-y-1 pl-5"><li>No Slot available due to incorrect weight and dimensions.</li><li>Feed Submission Results not ready.</li><li>Weight of dimension cannot be zero.</li><li>This order is not allowed to be re-scheduled.</li><li>Duplicate entries suppressed.</li><li>Listing not present on Amazon.</li></ul></div>; }
