import { useEffect, useState } from 'react';
import Shell from '../Shell';
import { Btn, Toast } from '../parts';
import Modal from '../../components/Modal';
import { apiGet, apiSend } from '../../lib/api';

const blank = () => ({ id: 0, poNo: '', inboundNo: '', vendor: '', vendorCode: '', warehouse: '', createdDate: '', GRNNo: '', GRNDate: '', invoiceQty: '', statusChangedDate: '', receivedQty: '', inboundCharge: '', status: '', lines: [] as any[], documents: [] as string[] });
const lineBlank = () => ({ skuCode: '', skuName: '', poQty: 0, rcvdUOMQty: 0, rcvdQty: 0, invoiceQty: 0, binLoc: '', idCode: '', unitPrice: 0, lineAmount: 0, lottable01: '', lottable02: '', lottable03: '', lottable04: '', lottable05: '', lottable06: '', serialNos: [] });

export default function InboundCreateEdit() {
  const [meta, setMeta] = useState<any>({}), [form, setForm] = useState<any>(blank()), [loaded, setLoaded] = useState(false);
  const [tab, setTab] = useState<'form' | 'import'>('form'), [picker, setPicker] = useState<'main' | 'import' | null>(null), [more, setMore] = useState(false);
  const [poRows, setPoRows] = useState<any[]>([]), [poFilters, setPoFilters] = useState<any>({}), [poSelected, setPoSelected] = useState<any>(null), [poPager, setPoPager] = useState({ page: 1, total: 0, records: 0, rows: 20 });
  const [importForm, setImportForm] = useState<any>({ client: '0', poNo: '', inboundType: '-1', fileName: '' }), [results, setResults] = useState<any[]>([]);
  const [selected, setSelected] = useState<number[]>([]), [toast, setToast] = useState<any>(null), [busy, setBusy] = useState(false);
  useEffect(() => { apiGet('/api/inbound-create-edit').then(setMeta).catch((e: any) => setToast({ msg: e.message, type: 'err' })); const q = new URLSearchParams(location.search).get('inboundNo'); if (q) apiGet(`/api/inbound-create-edit?inboundNo=${encodeURIComponent(q)}`).then((r) => { setForm(r); setLoaded(true); }).catch((e: any) => setToast({ msg: e.message, type: 'err' })); }, []);
  const set = (k: string, v: any) => setForm((x: any) => ({ ...x, [k]: v }));

  async function searchPO(page = 1, rows = poPager.rows, filters = poFilters) { try { const r: any = await apiSend('/api/inbound-create-edit', 'POST', { action: 'po-search', page, rows, ...filters }); setPoRows(r.poList); setPoPager({ page: r.page, total: r.total, records: r.records, rows: r.rows }); } catch (e: any) { setToast({ msg: e.message, type: 'err' }); } }
  function openPicker(source: 'main' | 'import') { setPicker(source); setPoSelected(null); void searchPO(1, 20, {}); }
  async function choosePO() { if (!poSelected) return setToast({ msg: 'Please select a PO from Search Results.', type: 'err' }); if (picker === 'import') { setImportForm((x: any) => ({ ...x, poNo: poSelected.poNo })); setPicker(null); return; } try { const r: any = await apiSend('/api/inbound-create-edit', 'POST', { action: 'po', poNo: poSelected.poNo }); setForm((x: any) => ({ ...x, ...r })); setLoaded(true); setPicker(null); } catch (e: any) { setToast({ msg: e.message, type: 'err' }); } }
  async function save(action: 'save' | 'confirm') { if (action === 'confirm' && !confirm('Do you really want to confirm this Inbound?')) return; setBusy(true); try { const r: any = await apiSend('/api/inbound-create-edit', 'POST', { action, ...form }); setForm(r.row); setLoaded(true); setToast({ msg: r.jsonMessage, type: 'ok' }); } catch (e: any) { setToast({ msg: e.message, type: 'err' }); } finally { setBusy(false); } }
  function lineSet(i: number, k: string, v: any) { set('lines', form.lines.map((x: any, n: number) => n === i ? { ...x, [k]: v } : x)); }
  async function importFile(file?: File) { if (!file) return setToast({ msg: 'Please select a file', type: 'err' }); const text = await file.text(), rows = text.split(/\r?\n/).filter(Boolean).slice(1).map((s) => { const [sku_code, sku_name, qty] = s.split(','); return { sku_code: sku_code?.trim(), sku_name: sku_name?.trim(), rcvdUOMQty: Number(qty || 0) }; }); try { const r: any = await apiSend('/api/inbound-create-edit', 'POST', { action: 'import', rows }); setResults(r.DTOList); setImportForm((x: any) => ({ ...x, fileName: file.name })); setToast({ msg: `Total Inbound For Import:${r.totalItems} Successful:${r.successItems} Failed:${r.failedItems} In Process:${r.inProcessItems}`, type: 'ok' }); } catch (e: any) { setToast({ msg: e.message, type: 'err' }); } }

  const heads = [['skuCode', 'SKU Code'], ['skuName', 'SKU Name'], ['poQty', 'PO Qty'], ['rcvdUOMQty', 'Rcvd UOM Qty'], ['rcvdQty', 'Rcvd Qty'], ['invoiceQty', 'Invoice Qty'], ['binLoc', 'Bin Location'], ['idCode', 'LPN'], ['unitPrice', 'Unit Price'], ['lineAmount', 'Line Amount'], ['lottable01', 'MRP'], ['lottable02', 'Expiry Date'], ['lottable03', 'Mfg date'], ['lottable04', 'Lottable04'], ['lottable05', 'Batch No'], ['lottable06', 'Lottable06']];
  const summary = [['inboundNo', 'Inbound No'], ['createdDate', 'Creation Date'], ['GRNNo', 'GRN No'], ['GRNDate', 'GRN Date'], ['invoiceQty', 'Invoice Qty'], ['statusChangedDate', 'Status Changed Date'], ['receivedQty', 'Received Qty'], ['inboundCharge', 'Inbound Charge'], ['vendorCode', 'Vendor Code'], ['vendor', 'Vendor Name']];

  return <Shell active="wms" breadcrumb="WMS > Inbound > Inbound Create/Edit" openScreens={[{ label: 'Inbound Create/Edit', to: '#' }]}>
    <div className="mb-3 rounded border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-800">The screen will be deprecated on 25th Nov 2025. Please use WMS &gt; Inbound &gt; Inbound RealTime</div>
    <div className="mb-2 flex justify-end gap-2">{loaded && <><Btn variant="ghost" onClick={() => setToast({ msg: form.id ? 'Document saved' : 'Save the Inbound before attaching documents', type: form.id ? 'ok' : 'err' })}>Save Document</Btn><Btn onClick={() => void save('save')} disabled={busy}>Save</Btn><Btn onClick={() => void save('confirm')} disabled={busy}>Confirm</Btn></>}<Btn variant="ghost" onClick={() => { setForm(blank()); setLoaded(false); setTab('form'); }}>Add New</Btn><div className="relative"><Btn variant="ghost" onClick={() => setMore(!more)} aria-label="Toggle Dropdown">▾</Btn>{more && <div className="absolute right-0 z-20 w-56 border bg-white shadow"><button className="block w-full p-2 text-left" onClick={() => setToast({ msg: loaded ? 'Additional Charge opened' : 'Please save Inbound first', type: loaded ? 'ok' : 'err' })}>Update Additional Charge</button><button className="block w-full p-2 text-left" onClick={() => setToast({ msg: loaded ? 'Generate PutAway opened' : 'Please save Inbound first', type: loaded ? 'ok' : 'err' })}>Generate PutAway</button></div>}</div></div>
    <div className="rounded border bg-white"><div className="flex border-b"><button className={`px-5 py-3 ${tab === 'form' ? 'border-b-2 border-rose-500 font-semibold' : ''}`} onClick={() => setTab('form')}>Inbound Create/Edit</button><button className={`px-5 py-3 ${tab === 'import' ? 'border-b-2 border-rose-500 font-semibold' : ''}`} onClick={() => setTab('import')}>Import</button></div>
      {tab === 'form' ? <><div className="grid gap-3 p-4 md:grid-cols-4"><label className="text-xs">PO No*<div className="mt-1 flex"><input aria-label="PO No" className="inp rounded-r-none" value={form.poNo} readOnly /><button aria-label="Open PO picker" className="rounded-r border px-3" onClick={() => openPicker('main')}>...</button></div></label>{loaded && summary.map(([k, l]) => <label key={k} className="text-xs">{l}<input aria-label={l} className="inp mt-1" value={form[k] || ''} readOnly /></label>)}</div>{loaded && <><div className="flex gap-2 border-y bg-slate-50 p-3"><Btn variant="ghost" onClick={() => set('lines', [...form.lines, lineBlank()])}>Add New Row</Btn><Btn variant="ghost" onClick={() => { set('lines', form.lines.filter((_: any, i: number) => !selected.includes(i))); setSelected([]); }}>Delete Row</Btn></div><LineGrid heads={heads} lines={form.lines} selected={selected} setSelected={setSelected} lineSet={lineSet} /></>}</> : <div className="p-4"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs">Client*<select aria-label="Import Client" className="inp mt-1" value="0" disabled><option>0-DummyClient</option></select></label><label className="text-xs">PO No<div className="mt-1 flex"><input aria-label="Import PO No" className="inp rounded-r-none" value={importForm.poNo} readOnly /><button aria-label="Open Import PO picker" className="rounded-r border px-3" onClick={() => openPicker('import')}>...</button></div></label><label className="text-xs">Import Type<select aria-label="Import Type" className="inp mt-1" value={importForm.inboundType} onChange={(e) => setImportForm({ ...importForm, inboundType: e.target.value })}>{(meta.importTypes || []).map(([v, l]: any) => <option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs">Upload Template<input aria-label="Upload Template" className="inp mt-1" type="file" accept=".csv,.xls,.xlsx" onChange={(e) => void importFile(e.target.files?.[0])} /></label></div><div className="mt-3 flex gap-2"><Btn variant="ghost" onClick={() => setToast({ msg: 'PO Inbound Import template download prepared', type: 'ok' })}>Download</Btn><Btn onClick={() => setToast({ msg: results.length ? 'Import completed' : 'Please select a file', type: results.length ? 'ok' : 'err' })}>Import</Btn><Btn variant="ghost" disabled={!results.length} onClick={() => setToast({ msg: 'Import result export prepared', type: 'ok' })}>Export</Btn><Btn variant="ghost" onClick={() => { setImportForm({ client: '0', poNo: '', inboundType: '-1', fileName: '' }); setResults([]); }}>Reset</Btn></div><p className="mt-3 text-xs text-slate-500">**Note: Max 200 lines are allowed at a time</p></div>}
    </div>
    <Modal title="PO Pick List" open={picker !== null} onClose={() => setPicker(null)} wide><POPicker rows={poRows} filters={poFilters} setFilters={setPoFilters} selected={poSelected} setSelected={setPoSelected} pager={poPager} search={searchPO} choose={choosePO} close={() => setPicker(null)} /></Modal>
    {toast && <Toast {...toast} onClose={() => setToast(null)} />}
  </Shell>;
}

function LineGrid({ heads, lines, selected, setSelected, lineSet }: any) { return <div className="overflow-auto"><table className="min-w-[1900px] text-xs"><thead className="bg-slate-100"><tr><th className="p-2" />{heads.map(([, l]: any) => <th key={l} className="p-2 text-left">{l}</th>)}</tr></thead><tbody>{lines.length ? lines.map((r: any, i: number) => <tr key={i} className="border-t"><td className="p-2"><input aria-label={`Select row ${i + 1}`} type="checkbox" checked={selected.includes(i)} onChange={(e) => setSelected(e.target.checked ? [...selected, i] : selected.filter((x: number) => x !== i))} /></td>{heads.map(([k, l]: any) => <td key={k} className="p-1"><input aria-label={`${l} ${i + 1}`} className="w-full min-w-24 border p-1" value={r[k] ?? ''} onChange={(e) => lineSet(i, k, ['poQty', 'rcvdUOMQty', 'rcvdQty', 'invoiceQty', 'unitPrice', 'lineAmount'].includes(k) ? Number(e.target.value) : e.target.value)} /></td>)}</tr>) : <tr><td colSpan={17} className="p-12 text-center text-slate-400">No Data Found In The Grid</td></tr>}</tbody></table></div>; }

function POPicker({ rows, filters, setFilters, selected, setSelected, pager, search, choose, close }: any) { const cols = [['poNo', 'PO Number'], ['externalPoNo', 'External PO No'], ['poQty', 'PO Qty'], ['vendor', 'Vendor Name'], ['lastModifiedDate', 'Last modified date'], ['status', 'Status'], ['warehouse', 'Delivery Location']]; return <><div className="overflow-auto"><table className="min-w-full text-xs"><thead><tr>{cols.map(([, l]) => <th className="p-2 text-left" key={l}>{l}</th>)}</tr><tr>{cols.map(([k]) => <th className="p-1" key={k}>{k === 'status' ? <select aria-label="PO Status" className="inp" value={filters[k] || ''} onChange={(e) => setFilters({ ...filters, [k]: e.target.value })}><option value="">--- Select ---</option><option>Partially Received</option><option>Released</option></select> : <input aria-label={`Filter ${k}`} className="inp" value={filters[k] || ''} onChange={(e) => setFilters({ ...filters, [k]: e.target.value })} onKeyDown={(e) => e.key === 'Enter' && search(1, pager.rows, filters)} />}</th>)}</tr></thead><tbody>{rows.map((r: any) => <tr key={r.id} className={`cursor-pointer border-t ${selected?.id === r.id ? 'bg-sky-100' : ''}`} onClick={() => setSelected(r)}>{cols.map(([k]) => <td className="p-2" key={k}>{r[k]}</td>)}</tr>)}</tbody></table></div><div className="mt-3 flex items-center justify-between"><span>View {pager.records ? (pager.page - 1) * pager.rows + 1 : 0} - {Math.min(pager.page * pager.rows, pager.records)} of {pager.records}</span><select aria-label="PO Records per Page" value={pager.rows} onChange={(e) => search(1, Number(e.target.value), filters)}>{[10, 20, 30, 50].map((x) => <option key={x}>{x}</option>)}</select><div className="flex gap-2"><Btn onClick={() => void choose()}>OK</Btn><Btn variant="ghost" onClick={close}>Close</Btn><Btn variant="ghost" onClick={() => { setFilters({}); void search(1, 20, {}); }}>Reset</Btn></div></div></>; }
