import { useEffect, useMemo, useState } from 'react';
import Shell from '../Shell';
import { Toast } from '../parts';
import Modal from '../../components/Modal';
import { apiGet, apiSend } from '../../lib/api';

type Form = { description: string; externalCode: string; active: boolean };
const initial: Form = { description: '', externalCode: '', active: true };
export default function AttributeSet() {
  const [rows, setRows] = useState<any[]>([]), [query, setQuery] = useState(''), [form, setForm] = useState<Form>(initial), [open, setOpen] = useState(false), [toast, setToast] = useState<any>(null);
  const load = async () => { try { setRows(await apiGet<any[]>('/api/generic?module=attribute-set')); } catch { setToast({ msg: 'Unable to load Attribute Set', type: 'err' }); } };
  useEffect(() => { void load(); }, []);
  const shown = useMemo(() => rows.filter((row) => [row.code, row.name, row.extra?.external_code].join(' ').toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const save = async () => {
    if (!form.description.trim()) return setToast({ msg: 'Attribute description is mandatory.', type: 'err' });
    try { await apiSend('/api/generic', 'POST', { module: 'attribute-set', code: `AS${Date.now().toString().slice(-8)}`, name: form.description.trim(), description: form.description.trim(), status: form.active ? 'Active' : 'Inactive', extra: { external_code: form.externalCode.trim() } }); setToast({ msg: 'Attribute Set saved successfully', type: 'ok' }); setForm(initial); setOpen(false); await load(); } catch (error: any) { setToast({ msg: error.message || 'Unable to save Attribute Set', type: 'err' }); }
  };
  const remove = async (id: number) => { try { await apiSend('/api/generic', 'DELETE', { id }); setToast({ msg: 'Attribute Set deleted successfully', type: 'ok' }); await load(); } catch { setToast({ msg: 'Unable to delete Attribute Set', type: 'err' }); } };
  return <Shell active="master" breadcrumb="MASTER > SKU Management > Attribute Set" openScreens={[{ label: 'Attribute Set', to: '#' }]}><div className="space-y-4"><section className="rounded border bg-white p-4"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_auto_auto]"><label className="lbl">Attribute Set Description<input aria-label="Attribute Set search" className="inp mt-1" value={query} onChange={(e) => setQuery(e.target.value)} /></label><button className="self-end rounded border px-4 py-2 text-sm" onClick={() => setQuery('')}>Reset</button><button className="self-end rounded bg-[#2f9e9e] px-4 py-2 text-sm text-white" onClick={() => { setForm(initial); setOpen(true); }}>Add New</button></div></section><section className="overflow-x-auto rounded border bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Attribute Set Code</th><th className="p-3 text-left">Attribute Set Description</th><th className="p-3 text-left">Ext Attribute Set Code</th><th className="p-3 text-left">Is Active</th><th className="p-3 text-left">Actions</th></tr></thead><tbody>{shown.length ? shown.map((row) => <tr className="border-t" key={row.id}><td className="p-3">{row.code}</td><td className="p-3">{row.name}</td><td className="p-3">{row.extra?.external_code || '—'}</td><td className="p-3">{row.status === 'Active' ? 'Yes' : 'No'}</td><td className="p-3"><button onClick={() => remove(row.id)} className="text-rose-600 hover:underline">Delete</button></td></tr>) : <tr><td colSpan={5} className="p-8 text-center text-slate-400">No records to view</td></tr>}</tbody></table></section><Modal title="Add Attribute Set" open={open} onClose={() => setOpen(false)}><div className="grid gap-4"><Field label="Attribute Set Description*"><input aria-label="Attribute Set Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="inp" /></Field><Field label="Ext Attribute Set Code"><input aria-label="Ext Attribute Set Code" value={form.externalCode} onChange={(e) => setForm({ ...form, externalCode: e.target.value })} className="inp" /></Field><label className="flex items-center gap-2 text-sm"><input aria-label="Is Active" type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />Is Active</label></div><div className="mt-5 flex justify-end gap-2"><button className="rounded border px-4 py-2 text-sm" onClick={() => setOpen(false)}>Cancel</button><button className="rounded bg-[#2f9e9e] px-4 py-2 text-sm text-white" onClick={save}>Save</button></div></Modal></div>{toast && <Toast msg={toast.msg} type={toast.type} onClose={() => setToast(null)} />}</Shell>;
}
function Field({ label, children }: any) { return <label className="lbl">{label}{children}</label>; }
