/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { Download, Plus, RotateCcw, Save, Search, X } from 'lucide-react';
import Shell from '../Shell'; import Modal from '../../components/Modal'; import { Btn, Toast } from '../parts'; import { apiSend } from '../../lib/api'; import { useDownload } from '../../context/DownloadContext';
const COUNTRIES=['AFGHANISTAN','ALBANIA','ALGERIA El Djazair','INDIA','UNITED ARAB EMIRATES','UNITED KINGDOM','UNITED STATES']; const STATES=['Delhi','Gujarat','Haryana','Karnataka','Maharashtra','Tamil Nadu','Uttar Pradesh','West Bengal']; const sizes=[20,50,100,200]; const cls='w-full border border-slate-300 bg-white px-2 py-1.5 text-xs';
const blankFilters={client_id:'',client_name:'',client_short_name:'',status:'',country:'',state:'',city:''};
const initial:any={client_name:'',client_id:'',client_short_name:'',status:'Active',client_currency:'INR',billing_required:false,ext_client_code:'',address1:'',address2:'',contact_person:'',phone:'',email:'',country:'INDIA',state:'',city:'',pincode:'',udf1:'',udf2:'',udf3:'',udf4:'',udf5:'',invoice_report:false,label_report:false,total_shelf_life:'',shelf_life_receiving:'',shelf_life_picking:'',location_links:[],users:[]};
export default function ClientMaster(){
 const{requestDownload}=useDownload(); const[rows,setRows]=useState<any[]>([]),[filters,setFilters]=useState(blankFilters),[loading,setLoading]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[records,setRecords]=useState(0),[total,setTotal]=useState(0),[show,setShow]=useState(false),[editing,setEditing]=useState<any>(null),[tab,setTab]=useState('Client Master'),[form,setForm]=useState<any>(initial),[busy,setBusy]=useState(false),[notice,setNotice]=useState<any>(null);
 const search=async(nextPage=1,nextSize=pageSize,nextFilters=filters)=>{setLoading(true);try{const result:any=await apiSend('/api/clients','POST',{REQ_SEARCH_FLAG:true,rows:nextSize,page:nextPage,sidx:'clientId',sord:'desc',clientId:nextFilters.client_id,clientIdName:'',clientName:nextFilters.client_name,clientShortName:nextFilters.client_short_name,status:nextFilters.status,country:nextFilters.country,state:nextFilters.state,city:nextFilters.city});setRows(result.gridModel||result.rows||[]);setPage(result.page||nextPage);setPageSize(nextSize);setRecords(result.records||0);setTotal(result.total||0)}catch(e:any){setRows([]);setNotice({msg:e.message,type:'err'})}finally{setLoading(false)}};
 useEffect(()=>{void search(1,20,blankFilters)},[]);
 const reset=()=>{setFilters(blankFilters);void search(1,pageSize,blankFilters)}; const openNew=()=>{setEditing(null);setForm(initial);setTab('Client Master');setShow(true)}; const openEdit=(row:any)=>{setEditing(row);setForm({...initial,...row});setTab('Client Master');setShow(true)};
 const save=async()=>{setBusy(true);try{await apiSend('/api/clients',editing?'PUT':'POST',editing?{...form,id:editing.id}:form);setNotice({msg:editing?'Client updated successfully':'Client created successfully',type:'ok'});setShow(false);void search(page)}catch(e:any){setNotice({msg:e.message,type:'err'})}finally{setBusy(false)}};
 const download=()=>requestDownload({title:'Client Master',module:'clients',baseName:'ClientEnquiry',data:{columns:['Client ID','Client Name','Client Short Name','Status','Country','State','City'],rows:rows.map(r=>[r.client_id,r.client_name,r.client_short_name,r.status,r.country,r.state,r.city])}});
 return <Shell active="master" breadcrumb="MASTER > Trading Partner > Client Master" openScreens={[{label:'Client Master',to:'#'}]}><div className="mb-2 flex justify-end gap-2"><Btn variant="warn" disabled={loading} onClick={()=>void search(1)}><Search size={13}/>Search</Btn><Btn variant="ghost" onClick={reset}><RotateCcw size={13}/>Reset</Btn><Btn variant="ghost" onClick={openNew}><Plus size={13}/>Add New</Btn><Btn variant="ghost" onClick={download}><Download size={13}/>Download</Btn></div>
 <div className="overflow-auto border bg-white"><table className="min-w-[950px] w-full text-xs"><thead className="bg-slate-100"><tr>{['Client ID','Client Name','Client Short Name','Status','Country','State','City'].map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr><tr><th className="p-1"><input aria-label="Client ID" className={cls} value={filters.client_id} onChange={e=>setFilters({...filters,client_id:e.target.value})}/></th><th className="p-1"><input aria-label="Client Name" className={cls} value={filters.client_name} onChange={e=>setFilters({...filters,client_name:e.target.value})}/></th><th className="p-1"><input aria-label="Client Short Name" className={cls} value={filters.client_short_name} onChange={e=>setFilters({...filters,client_short_name:e.target.value})}/></th><th className="p-1"><select aria-label="Status" className={cls} value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">--- Select ---</option><option>Inactive</option><option>Active</option></select></th><th className="p-1"><select aria-label="Country" className={cls} value={filters.country} onChange={e=>setFilters({...filters,country:e.target.value})}><option value="">--- Select ---</option>{COUNTRIES.map(x=><option key={x}>{x}</option>)}</select></th><th className="p-1"><select aria-label="State" className={cls} value={filters.state} onChange={e=>setFilters({...filters,state:e.target.value})}><option value="">--- Select ---</option>{STATES.map(x=><option key={x}>{x}</option>)}</select></th><th className="p-1"><input aria-label="City" className={cls} value={filters.city} onChange={e=>setFilters({...filters,city:e.target.value})}/></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-12 text-center">Loading...</td></tr>:rows.length?rows.map(r=><tr key={r.id} className="border-t"><td className="p-2"><button className="text-sky-600" onClick={()=>openEdit(r)}>{r.client_id}</button></td><td>{r.client_name}</td><td>{r.client_short_name}</td><td>{r.status}</td><td>{r.country}</td><td>{r.state}</td><td>{r.city}</td></tr>):<tr><td colSpan={7} className="p-12 text-center text-slate-400">No records to view</td></tr>}</tbody></table><div className="flex justify-between border-t p-2 text-xs"><span>Page {records?page:0} of {total}</span><span><button disabled={page<=1} onClick={()=>void search(page-1)}>Previous</button> <select aria-label="Records per Page" value={pageSize} onChange={e=>void search(1,Number(e.target.value))}>{sizes.map(x=><option key={x}>{x}</option>)}</select> <button disabled={!records||page>=total} onClick={()=>void search(page+1)}>Next</button></span><span>{records?`View ${(page-1)*pageSize+1} - ${Math.min(page*pageSize,records)} of ${records}`:'No records to view'}</span></div></div>
 <Modal title="Client Create/Edit" open={show} onClose={()=>setShow(false)} wide><div className="-mx-6 -mt-4 mb-3 flex overflow-auto border-b px-6">{['Client Master','User Defined Fields','Client Location Link','User Creation','Other Settings'].map(x=><button key={x} className={`whitespace-nowrap border-b-2 px-3 py-2 text-xs ${tab===x?'border-sky-600':''}`} onClick={()=>setTab(x)}>{x}</button>)}</div>{tab==='Client Master'?<div className="grid grid-cols-3 gap-3">{[['client_name','Client Name *'],['client_id','Client ID *'],['client_short_name','Client Short Name *'],['ext_client_code','Ext Client Code'],['address1','Address1 *'],['address2','Address2'],['contact_person','Contact Person'],['phone','Phone *'],['email','Email'],['city','City'],['pincode','Pincode']].map(([k,l])=><L key={k} label={l}><input className={cls} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></L>)}<L label="Status *"><select className={cls} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></L><L label="Country *"><select className={cls} value={form.country} onChange={e=>setForm({...form,country:e.target.value})}>{COUNTRIES.map(x=><option key={x}>{x}</option>)}</select></L><L label="State *"><select className={cls} value={form.state} onChange={e=>setForm({...form,state:e.target.value})}><option value="">--- Select ---</option>{STATES.map(x=><option key={x}>{x}</option>)}</select></L></div>:tab==='User Defined Fields'?<div className="grid grid-cols-3 gap-3">{[1,2,3,4,5].map(i=><L key={i} label={`UDF ${i}`}><input className={cls} value={form[`udf${i}`]} onChange={e=>setForm({...form,[`udf${i}`]:e.target.value})}/></L>)}</div>:tab==='Client Location Link'?<LinkRows form={form} setForm={setForm} field="location_links" label="Location"/>:tab==='User Creation'?<LinkRows form={form} setForm={setForm} field="users" label="User Id"/>:<div className="grid grid-cols-3 gap-3">{[['total_shelf_life','Total Shelf Life'],['shelf_life_receiving','Shelf Life on Receiving'],['shelf_life_picking','Shelf Life on Picking']].map(([k,l])=><L key={k} label={l}><input type="number" className={cls} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></L>)}</div>}<div className="mt-4 flex justify-end gap-2 border-t pt-3"><Btn disabled={busy} onClick={save}><Save size={13}/>{busy?'Saving...':'Save'}</Btn><Btn variant="ghost" onClick={()=>setShow(false)}><X size={13}/>Cancel</Btn></div></Modal>{notice&&<Toast {...notice} onClose={()=>setNotice(null)}/>}</Shell>;
}
function L({label,children}:{label:string;children:any}){return <label className="text-xs text-slate-600">{label}{children}</label>}
function LinkRows({form,setForm,field,label}:{form:any;setForm:any;field:string;label:string}){const[value,setValue]=useState('');const list=form[field]||[];return <div><div className="flex gap-2"><input aria-label={label} className={cls} value={value} onChange={e=>setValue(e.target.value)}/><Btn onClick={()=>{if(value){setForm({...form,[field]:[...list,{id:Date.now(),key:value,status:'Active'}]});setValue('')}}}>Save</Btn></div>{list.map((x:any)=><div key={x.id} className="mt-2 flex justify-between border p-2 text-xs"><span>{x.key} — {x.status}</span><button className="text-rose-600" onClick={()=>setForm({...form,[field]:list.filter((v:any)=>v.id!==x.id)})}>Delete</button></div>)}</div>}
