import { useEffect, useMemo, useState } from 'react';
import { Download, Plus, Save, UserPlus, X } from 'lucide-react';
import Shell from '../Shell';
import Modal from '../../components/Modal';
import { Toast } from '../parts';
import EnquiryScreen, { ECol } from '../EnquiryScreen';
import { apiForm, apiGet, apiSend } from '../../lib/api';
import { useDownload } from '../../context/DownloadContext';

type Customer = { id: number; customer_code: string; customer_name: string; type: string; shipping_city?: string; shipping_state?: string; customer_group_code?: string };
const blank = { name: '', status: 'Active', customer_ids: [] as number[] };

export default function CustomerGroupMaster() {
  const { requestDownload } = useDownload();
  const [rows, setRows] = useState<any[]>([]), [customers, setCustomers] = useState<Customer[]>([]), [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1), [pageSize, setPageSize] = useState(20), [records, setRecords] = useState(0), [total, setTotal] = useState(0), [lastFilters, setLastFilters] = useState<Record<string, string>>({});
  const [show, setShow] = useState(false), [edit, setEdit] = useState<any>(null), [view, setView] = useState<any>(null), [form, setForm] = useState(blank), [busy, setBusy] = useState(false), [toast, setToast] = useState<any>(null), [importOpen, setImportOpen] = useState(false), [failedOpen, setFailedOpen] = useState(false), [importCodes, setImportCodes] = useState(''), [failedCodes, setFailedCodes] = useState<string[]>([]);
  const search = async (filters: Record<string, string> = lastFilters, nextPage = 1, nextSize = pageSize) => { setLoading(true); try { const result: any = await apiForm('/api/jsonCustGroupSearch', { _search: true, rows: nextSize, page: nextPage, sidx: 'custGroupCode', sord: 'desc', clientId: '0', custGroupCode: filters.code || '', custGroupName: filters.name || '', status: ({Active:'1',InActive:'0'} as Record<string,string>)[filters.status] ?? '-1', REQ_SEARCH_FLAG: true, doFetchCount: false }); setRows(result.gridModel || result.rows || []); setPage(result.page || nextPage); setPageSize(nextSize); setRecords(result.records || 0); setTotal(result.total || 0); setLastFilters(filters); } catch (error: any) { setRows([]); setToast({ msg: error.message || 'Unable to load Customer Group', type: 'err' }); } finally { setLoading(false); } };
  const load = () => search(lastFilters, page, pageSize);
  useEffect(() => { void apiGet<Customer[]>('/api/customers').then(setCustomers); }, []);
  const openNew = () => { setEdit(null); setForm(blank); setShow(true); };
  const openEdit = (group: any) => { setEdit(group); setForm({ name: group.name || '', status: group.status || 'Active', customer_ids: customers.filter((c) => c.customer_group_code === group.code).map((c) => c.id) }); setShow(true); };
  const save = async () => {
    if (!form.name.trim()) return setToast({ msg: 'Please Enter Customer Group Name.', type: 'err' });
    if (form.name.trim().length > 50) return setToast({ msg: 'Customer Group Name cannot exceed 50 characters.', type: 'err' });
    setBusy(true);
    try { await apiSend('/api/customer-groups', edit ? 'PUT' : 'POST', edit ? { id: edit.id, ...form } : { name: form.name }); setShow(false); setToast({ msg: edit ? 'Record Updated Successfully' : 'Record saved successfully.', type: 'ok' }); load(); } catch (e: any) { setToast({ msg: e.message || 'Unable to save Customer Group', type: 'err' }); } finally { setBusy(false); }
  };
  const cols: ECol[] = useMemo(() => [
    { key: 'code', label: 'CustomerGroup Code', filter: 'text', sortable: true, align: 'center', render: (r) => <button onClick={() => openEdit(r)} className="font-semibold text-[#2179d0] hover:underline">{r.code}</button> },
    { key: 'name', label: 'CustomerGroup Name', filter: 'text', sortable: true, align: 'left' },
    { key: 'status', label: 'Status', filter: 'select', options: ['Active', 'InActive'], sortable: true, render: (r) => <span className={`inline-flex rounded px-2 py-1 text-xs font-semibold text-white ${r.status === 'Active' ? 'bg-[#3aa856]' : 'bg-[#b0b7c0]'}`}>{r.status}</span> },
    { key: 'no_of_customer', label: 'No. of Customer', filter: 'none', sortable: true },
  ], [customers]);
  const exportRows = (source = rows) => source.length?requestDownload({ title: 'Customer Group Enquiry', module: 'customer-groups', baseName: 'CustomerGroupEnquiry', data: { columns: ['CustomerGroup Code', 'CustomerGroup Name', 'Status', 'No. of Customer'], rows: source.map((r) => [r.code, r.name, r.status, r.no_of_customer]) } }):setToast({msg:'No data in grid to export',type:'err'});
  const members = edit ? customers.filter((customer) => customer.customer_group_code === edit.code || form.customer_ids.includes(customer.id)) : [];
  const importCustomers = () => { const codes = importCodes.split(/\r?\n/).map((code) => code.trim()).filter(Boolean); if (!codes.length) return setToast({ msg: 'Please enter at least one Customer Code.', type: 'err' }); if (codes.length > 1000) return setToast({ msg: 'Maximum 1000 customer codes are allowed at a time.', type: 'err' }); const found = customers.filter((customer) => codes.includes(customer.customer_code)); const failed = codes.filter((code) => !found.some((customer) => customer.customer_code === code)); setForm((current) => ({ ...current, customer_ids: [...new Set([...current.customer_ids, ...found.map((customer) => customer.id)])] })); setFailedCodes(failed); setImportOpen(false); setImportCodes(''); setToast({ msg: failed.length ? `${found.length} customer(s) added; ${failed.length} code(s) failed.` : `${found.length} customer(s) added.`, type: failed.length ? 'err' : 'ok' }); };
  return <Shell active="master" breadcrumb="MASTER > Trading Partner > Customer Group" openScreens={[{ label: 'Customer Group', to: '#' }]}>
    <EnquiryScreen breadcrumb={[{ label: 'Master' }, { label: 'Trading Partner' }, { label: 'CustomerGroup Create/Edit' }]} cols={cols} rows={rows} loading={loading} actions={[{ label: 'Download', icon: Download, onClick: (filtered) => exportRows(filtered || rows) }, { label: 'Add New', icon: Plus, onClick: openNew }]} onSearch={(filters, nextPage, nextSize) => void search(filters, nextPage, nextSize)} onReset={() => {setRows([]);setRecords(0);setTotal(0);setLastFilters({});setTimeout(()=>document.querySelector<HTMLInputElement>('thead input')?.focus(),500)}} remote={{ page, pageSize, records, total }} />
    <Modal title={`CustomerGroup Create/Edit${edit ? ` — ${edit.code}` : ''}`} open={show} onClose={() => setShow(false)} wide>
      <div className="grid grid-cols-1 gap-x-5 gap-y-3 py-3 sm:grid-cols-2 lg:grid-cols-4">
        <Read label="CustomerGroup Code" value={edit?.code || ''} /><Input label="CustomerGroup Name" value={form.name} onChange={(name) => setForm((f) => ({ ...f, name }))} maxLength={50} />
        <Read label="No. of Customer" value={edit ? String(members.length) : '0'} /><Read label="Status" value={edit ? form.status : 'Active'} />
      </div>
      <div className="mt-4 flex gap-2"><button className="rounded border border-slate-300 px-3 py-2 text-sm">Add Customer</button><button onClick={() => setImportOpen(true)} className="rounded border border-slate-300 px-3 py-2 text-sm">Import</button></div><Membership customers={customers} selected={form.customer_ids} groupCode={edit?.code||''} onChange={(customer_ids) => setForm((f) => ({ ...f, customer_ids }))} />
      <div className="mt-4 flex justify-end gap-2 border-t pt-4"><button onClick={save} disabled={busy} className="rounded bg-[#f5a623] px-4 py-2 text-sm font-medium text-white disabled:opacity-50"><Save className="mr-1 inline" size={14} />{busy ? 'Saving…' : 'Save'}</button><button onClick={openNew} className="rounded border border-slate-300 px-4 py-2 text-sm"><Plus className="mr-1 inline" size={14}/>Add New</button><button onClick={() => setShow(false)} className="rounded border border-slate-300 px-4 py-2 text-sm text-slate-600"><X className="mr-1 inline" size={14} />Close</button></div>
    </Modal>
    <Modal title={`CustomerGroup Create/Edit — ${view?.code || ''}`} open={!!view} onClose={() => setView(null)} wide>{view && <div className="space-y-5"><div className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><Read label="CustomerGroup Code" value={view.code} /><Read label="CustomerGroup Name" value={view.name} /><Read label="No. of Customer" value={String(view.no_of_customer)} /><Read label="Status" value={view.status} /></div><MemberTable customers={customers.filter((c) => c.customer_group_code === view.code)} /></div>}</Modal>
    <Modal title="Import" open={importOpen} onClose={() => setImportOpen(false)}><p className="mb-3 text-sm">Please enter one Customer Code per line. Maximum 1000 lines are allowed at a time.</p><textarea value={importCodes} onChange={(event) => setImportCodes(event.target.value)} className="h-48 w-full rounded border p-3 font-mono text-sm" aria-label="Customer codes" /><div className="mt-4 text-right"><button onClick={() => setImportOpen(false)} className="mr-2 rounded border px-4 py-2">Close</button><button onClick={importCustomers} className="rounded bg-[#f5a623] px-4 py-2 text-white">OK</button></div></Modal>
    <Modal title="Failed Imports" open={failedOpen} onClose={() => setFailedOpen(false)}><textarea value={failedCodes.join('\n')} onChange={(event) => setFailedCodes(event.target.value.split(/\r?\n/).filter(Boolean))} className="h-48 w-full rounded border p-3 font-mono text-sm" aria-label="Failed customer codes" /><div className="mt-4 text-right"><button onClick={() => setFailedOpen(false)} className="mr-2 rounded border px-4 py-2">OK</button><button onClick={() => setFailedOpen(false)} className="rounded border px-4 py-2">Close</button></div></Modal>
    {toast && <Toast msg={toast.msg} type={toast.type} onClose={() => setToast(null)} />}
  </Shell>;
}

function Read({ label, value }: { label: string; value: string }) { return <div><p className="lbl">{label}</p><p className="min-h-10 rounded border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-medium text-slate-700">{value || '—'}</p></div>; }
function Input({ label, value, onChange, required, maxLength }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; maxLength?: number }) { return <div><label className="lbl">{label}{required && <span className="text-rose-500"> *</span>}</label><input value={value} maxLength={maxLength} onChange={(e) => onChange(e.target.value)} className="inp" /></div>; }
function Membership({ customers, selected, groupCode, onChange }: { customers: Customer[]; selected: number[]; groupCode: string; onChange: (ids: number[]) => void }) { const available = customers.filter((c) => !c.customer_group_code || c.customer_group_code === groupCode); const toggle = (id: number) => onChange(selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id]); return <div className="mt-4 border-t pt-4"><div className="mb-2 flex items-center gap-2"><UserPlus size={16} className="text-[#337ab7]" /><h3 className="text-sm font-semibold text-slate-700">Customers</h3><span className="text-xs text-slate-500">A customer can be assigned to one group.</span></div>{available.length ? <div className="max-h-56 overflow-auto rounded border"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-slate-50"><tr><th className="px-3 py-2" /><th className="px-3 py-2 text-left">Customer Code</th><th className="px-3 py-2 text-left">Customer Name</th><th className="px-3 py-2">Customer Type</th><th className="px-3 py-2 text-left">City</th><th className="px-3 py-2 text-left">State</th></tr></thead><tbody>{available.map((c) => <tr key={c.id} className="border-t"><td className="px-3 py-2 text-center"><input aria-label={`Assign ${c.customer_code}`} type="checkbox" checked={selected.includes(c.id)} onChange={() => toggle(c.id)} className="accent-[#337ab7]" /></td><td className="px-3 py-2">{c.customer_code}</td><td className="px-3 py-2">{c.customer_name}</td><td className="px-3 py-2 text-center">{c.type}</td><td className="px-3 py-2">{c.shipping_city || '—'}</td><td className="px-3 py-2">{c.shipping_state || '—'}</td></tr>)}</tbody></table></div> : <p className="rounded border border-dashed p-4 text-sm text-slate-400">No available customers to add.</p>}</div>; }
function MemberTable({ customers }: { customers: Customer[] }) { return <div><h3 className="mb-2 text-sm font-semibold text-slate-700">Customers</h3>{customers.length ? <div className="overflow-auto rounded border"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{['Customer Code', 'Customer Name', 'Customer Type', 'City', 'State'].map((h) => <th key={h} className="px-3 py-2 text-left">{h}</th>)}</tr></thead><tbody>{customers.map((c) => <tr key={c.id} className="border-t"><td className="px-3 py-2">{c.customer_code}</td><td className="px-3 py-2">{c.customer_name}</td><td className="px-3 py-2">{c.type}</td><td className="px-3 py-2">{c.shipping_city || '—'}</td><td className="px-3 py-2">{c.shipping_state || '—'}</td></tr>)}</tbody></table></div> : <p className="text-sm text-slate-400">No customers assigned.</p>}</div>; }
