import { useEffect, useState } from 'react';
import Shell from '../Shell'; import EnquiryScreen, { type EField } from '../EnquiryScreen'; import Modal from '../../components/Modal'; import { Toast } from '../parts'; import { apiGet, apiSend } from '../../lib/api';
const blank = { code: '', name: '', event_type: 'Regular', start_date: '', end_date: '', location_code: '', customer: 'All', is_active: 'Yes', organisation_hierarchy: '', owner: '', vendor: '', brand: '', merch_hierarchy: '', sku_code: '', scheme_on: '', operation: '', discount_type: '', price_zone_code: '', sku_rules: [] as any[] };
const cols = [{ key: 'code', label: 'Pricing Event Code' }, { key: 'name', label: 'Pricing Event Name' }, { key: 'location_code', label: 'Location Code' }, { key: 'customer', label: 'Customer' }, { key: 'start_date', label: 'Start Date' }, { key: 'end_date', label: 'End Date' }, { key: 'event_type', label: 'Pricing Event' }, { key: 'status', label: 'Status' }, { key: 'is_active', label: 'IsActive' }];
const fields: EField[] = [{ key: 'startDate', label: 'Start Date' }, { key: 'orgId', label: 'Organisation Hierarchy' }, { key: 'owner', label: 'Owner', type: 'select', options: ['--- Select ---'] }, { key: 'vendor', label: 'Vendor', type: 'select', options: ['--- Select ---'] }, { key: 'brand', label: 'Brand' }, { key: 'isActive', label: 'isActive', type: 'select', options: ['--- Select ---', 'Yes', 'No'] }, { key: 'merchIdBySku', label: 'Merchandising Hierarchy' }, { key: 'sku', label: 'SKU Code' }, { key: 'customerName', label: 'Customer Name' }, { key: 'schemeOn', label: 'Scheme On', type: 'select', options: ['--- Select ---', 'Base Cost', 'MRP', 'Sale Price'] }, { key: 'operation', label: 'Operation', type: 'select', options: ['--- Select ---', 'Mark Down', 'Mark Up'] }, { key: 'discountType', label: 'Discount Type', type: 'select', options: ['--- Select ---', 'Absolute', 'Fixed value', 'Percentage'] }, { key: 'priceZoneCode', label: 'Price Zone Code', type: 'select', options: ['--- Select ---'] }, { key: 'selectedlocCode', label: 'Location', type: 'select', options: ['--- Select ---'] }];
export default function PricingEvents() {
  const [rows, setRows] = useState<any[]>([]), [pager, setPager] = useState({ page: 0, total: 0, records: 0, pageSize: 20 }), [meta, setMeta] = useState<any>({}), [loading, setLoading] = useState(false), [advanced, setAdvanced] = useState(false), [open, setOpen] = useState(false), [form, setForm] = useState<any>(blank), [toast, setToast] = useState<any>(null);
  useEffect(() => { apiGet('/api/pricing-events').then(setMeta).catch(() => setMeta({})); }, []);
  const liveFields = fields.map((f) => f.key === 'owner' ? { ...f, options: ['--- Select ---', ...(meta.buyers || []).map((x: any) => x.name) ] } : f.key === 'vendor' ? { ...f, options: ['--- Select ---', ...(meta.vendors || []).map((x: any) => x.vendor_name || x.name) ] } : f.key === 'selectedlocCode' ? { ...f, options: ['--- Select ---', ...(meta.locations || []).map((x: any) => x.location_code) ] } : f);
  const search = async (filters: any = {}, page = 1, size = pager.pageSize) => { setLoading(true); try { const response: any = await apiSend('/api/pricing-events', 'POST', { rows: size, page, sidx: 'pricingSchemeCode', sord: 'desc', ...filters, REQ_SEARCH_FLAG: true }); setRows(response.rows); setPager({ page: response.page, total: response.total, records: response.records, pageSize: size }); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } finally { setLoading(false); } };
  const save = async (status = 'Pending Confirmation') => { try { await apiSend('/api/pricing-events', 'POST', { ...form, status }); setOpen(false); setForm(blank); setToast({ msg: 'Pricing Event saved successfully', type: 'ok' }); } catch (error: any) { setToast({ msg: error.message, type: 'err' }); } };
  const exportRows = () => { const csv = [cols.map((x) => x.label), ...rows.map((r) => cols.map((x) => r[x.key] ?? ''))].map((r) => r.join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'pricing-events.csv'; a.click(); URL.revokeObjectURL(a.href); };
  return <Shell active="master" breadcrumb="MASTER > Pricing Event > Pricing Event Enquiry" openScreens={[{ label: 'Pricing Event', to: '#' }]}><EnquiryScreen breadcrumb={[{ label: 'Master' }, { label: 'Pricing Event' }, { label: 'Pricing Event Enquiry' }]} fields={advanced ? liveFields : liveFields.slice(0, 5)} cols={cols} rows={rows} loading={loading} remote={pager} onSearch={search} onReset={() => { setRows([]); setPager({ page: 0, total: 0, records: 0, pageSize: 20 }); }} actions={[{ label: 'Advanced Search', onClick: () => setAdvanced(!advanced) }, { label: 'Export', onClick: exportRows }, { label: 'Detail Export', onClick: exportRows }, { label: 'Add New', onClick: () => setOpen(true), variant: 'green' }]} />
    <Modal title="Pricing Event Create/Edit" open={open} onClose={() => setOpen(false)} wide><div className="grid gap-3 md:grid-cols-3">{[['name','Pricing Event Desc'],['start_date','Start Date'],['end_date','End Date'],['location_code','Location Code'],['customer','Customer'],['brand','Brand'],['sku_code','SKU Code']].map(([key,label]) => <label key={key} className="text-xs">{label}<input aria-label={label} type={key.includes('date') ? 'date' : 'text'} className="inp mt-1" value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className="text-xs">Pricing Event<select aria-label="Pricing Event" className="inp mt-1" value={form.event_type} onChange={(e) => setForm({ ...form, event_type: e.target.value })}><option>Regular</option><option>Temporary</option></select></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => save()} className="rounded bg-[#f5a623] px-4 py-2 text-white">Save</button><button onClick={() => save('Confirmed')} className="rounded border px-4 py-2">Confirm</button><button onClick={() => setOpen(false)} className="rounded border px-4 py-2">Cancel</button></div></Modal>{toast && <Toast {...toast} onClose={() => setToast(null)} />}</Shell>;
}
