import { useEffect, useMemo, useState } from 'react';
import { Plus, Save, X } from 'lucide-react';
import Shell from '../Shell';
import Modal from '../../components/Modal';
import { Toast } from '../parts';
import EnquiryScreen, { ECol } from '../EnquiryScreen';
import { apiGet, apiSend } from '../../lib/api';
const initial = { code: '', name: '', status: 'Active' };

export default function TaxCategory() {
  const [rows, setRows] = useState<any[]>([]), [loading, setLoading] = useState(true), [show, setShow] = useState(false), [edit, setEdit] = useState<any>(null), [form, setForm] = useState(initial), [busy, setBusy] = useState(false), [toast, setToast] = useState<any>(null), [errors, setErrors] = useState<Record<string, string>>({});
  const [page, setPage] = useState(1), [pageSize, setPageSize] = useState(20), [records, setRecords] = useState(0), [total, setTotal] = useState(0), [lastFilters, setLastFilters] = useState<Record<string, string>>({});
  const search = async (filters: Record<string, string> = lastFilters, nextPage = 1, nextSize = pageSize) => { setLoading(true); try { const result: any = await apiSend('/api/tax-categories', 'POST', { REQ_SEARCH_FLAG: true, rows: nextSize, page: nextPage, sidx: '', sord: 'asc', taxCatName: filters.code || '', taxCatdesc: filters.name || '', active: '', displayIsActive: filters.status || '', createdDate: '', updatedBy: '', updatedDate: '' }); setRows(result.gridModel || result.rows || []); setPage(result.page || nextPage); setPageSize(nextSize); setRecords(result.records || 0); setTotal(result.total || 0); setLastFilters(filters); } catch (error: any) { setRows([]); setToast({ msg: error.message || 'Unable to load Tax Categories', type: 'err' }); } finally { setLoading(false); } };
  const load = () => search(lastFilters, page, pageSize);
  useEffect(() => { void search({}, 1, 20); }, []);
  const openNew = () => { setEdit(null); setForm(initial); setErrors({}); setShow(true); };
  const openEdit = (row: any) => { setEdit(row); setForm({ code: row.code, name: row.name, status: row.status || 'Active' }); setErrors({}); setShow(true); };
  const save = async () => { const next: Record<string, string> = {}; if (!form.code.trim()) next.code = 'Please Enter Tax Category Name'; if (!form.name.trim()) next.name = 'Please Enter Description'; setErrors(next); if (Object.keys(next).length) return setToast({ msg: Object.values(next)[0], type: 'err' }); setBusy(true); try { await apiSend('/api/tax-categories', edit ? 'PUT' : 'POST', edit ? { id: edit.id, ...form } : form); setShow(false); setToast({ msg: edit ? 'Tax Category updated successfully' : 'Record saved successfully.', type: 'ok' }); load(); } catch (e: any) { setToast({ msg: e.message || 'Unable to save Tax Category', type: 'err' }); } finally { setBusy(false); } };
  const cols: ECol[] = useMemo(() => [
    { key: 'code', label: 'Tax Category (HSN/SAC)', filter: 'text', sortable: true, align: 'center' },
    { key: 'name', label: 'Description', filter: 'text', sortable: true, align: 'left' },
    { key: 'status', label: 'Status', filter: 'select', options: ['Active', 'Inactive'], sortable: true, render: (row) => <span className={`inline-flex rounded px-2 py-1 text-xs font-semibold text-white ${row.status === 'Active' ? 'bg-[#3aa856]' : 'bg-[#b0b7c0]'}`}>{row.status}</span> },
  ], []);
  return <Shell active="master" breadcrumb="MASTER > Tax Management > Tax Category (HSN/SAC)" openScreens={[{ label: 'Tax Category (HSN/SAC)', to: '#' }]}><EnquiryScreen breadcrumb={[{ label: 'Master' }, { label: 'Tax Management' }, { label: 'Tax Category (HSN/SAC)' }]} cols={cols} rows={rows} loading={loading} actions={[{ label: 'Add New', icon: Plus, onClick: openNew }]} onRowEdit={openEdit} onSearch={(filters, nextPage, nextSize) => void search(filters, nextPage, nextSize)} onReset={() => void search({}, 1, pageSize)} remote={{ page, pageSize, records, total }} />
    <Modal title={edit ? `Tax Category Create/Edit — ${edit.code}` : 'Tax Category Create/Edit'} open={show} onClose={() => setShow(false)} wide><div className="grid grid-cols-1 gap-4 py-3 sm:grid-cols-2"><Field label="Tax Category (HSN/SAC)" value={form.code} onChange={(code) => setForm((f) => ({ ...f, code }))} error={errors.code} required /><Field label="Description" value={form.name} onChange={(name) => setForm((f) => ({ ...f, name }))} error={errors.name} required /><Select label="Status" value={form.status} values={['Active', 'Inactive']} onChange={(status) => setForm((f) => ({ ...f, status }))} /></div><div className="mt-4 flex justify-end gap-2 border-t pt-4"><button onClick={() => setShow(false)} className="rounded border border-slate-300 px-4 py-2 text-sm text-slate-600"><X className="mr-1 inline" size={14} />Cancel</button><button onClick={save} disabled={busy} className="rounded bg-[#f5a623] px-4 py-2 text-sm font-medium text-white disabled:opacity-50"><Save className="mr-1 inline" size={14} />{busy ? 'Saving…' : 'Save'}</button></div></Modal>{toast && <Toast msg={toast.msg} type={toast.type} onClose={() => setToast(null)} />}</Shell>;
}
function Field({ label, value, onChange, error, required, maxLength }: { label: string; value: string; onChange: (value: string) => void; error?: string; required?: boolean; maxLength?: number }) { return <div><label className="lbl">{label}{required && <span className="text-rose-500"> *</span>}</label><input value={value} maxLength={maxLength} onChange={(event) => onChange(event.target.value)} className={`inp ${error ? 'border-rose-400' : ''}`} />{error && <p className="mt-1 text-xs text-rose-500">{error}</p>}</div>; }
function Select({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <div><label className="lbl">{label}</label><select value={value} onChange={(event) => onChange(event.target.value)} className="inp">{values.map((item) => <option key={item}>{item}</option>)}</select></div>; }
