import { useEffect, useState } from 'react';
import { Save } from 'lucide-react';
import Shell from '../Shell';
import { Toast } from '../parts';
import { apiGet, apiSend } from '../../lib/api';

type TaxRow = { id: number; level: string };
type TaxGroupForm = { extTaxGroupCode: string; applied_on: string; startDate: string; status: 'Active' | 'Inactive'; taxCodeId: string; taxLevel: string; rows: TaxRow[] };
const emptyForm = (): TaxGroupForm => ({ extTaxGroupCode: '', applied_on: '--- Select ---', startDate: '', status: 'Active', taxCodeId: '--- Select ---', taxLevel: '--- Select ---', rows: [] });
const pageSizes = [20, 50, 100, 200];

export default function TaxGroup() {
  const [groups, setGroups] = useState<any[]>([]), [codes, setCodes] = useState<any[]>([]), [loading, setLoading] = useState(true);
  const [form, setForm] = useState<TaxGroupForm>(emptyForm), [search, setSearch] = useState({ code: '', appliedOn: '--- Select ---', startDate: '', status: 'Active' as 'Active' | 'Inactive' });
  const [pageSize, setPageSize] = useState(20), [page, setPage] = useState(1), [records, setRecords] = useState(0), [total, setTotal] = useState(0), [nestedPageSize, setNestedPageSize] = useState(20);
  const [toast, setToast] = useState<{ msg: string; type: 'ok' | 'err' } | null>(null), [busy, setBusy] = useState(false);
  const runSearch = async (nextPage: any = 1, nextSize = pageSize, next = search) => { if (typeof nextPage !== 'number') { applySearch(); return; } setLoading(true); try { const result: any = await apiSend('/api/tax-groups', 'POST', { REQ_SEARCH_FLAG: true, rows: nextSize, page: nextPage, sidx: '', sord: 'asc', extTaxGroupCode: next.code, appliedOn: next.appliedOn === '--- Select ---' ? '' : next.appliedOn, displayStartDate: next.startDate, displayIsActive: next.status === 'Active' ? 'Yes' : 'No' }); setGroups(result.gridModel || result.rows || []); setPage(result.page || nextPage); setPageSize(nextSize); setRecords(result.records || 0); setTotal(result.total || 0); } catch (error: any) { setGroups([]); setToast({ msg: error.message || 'Unable to load Tax Groups', type: 'err' }); } finally { setLoading(false); } };
  const load = () => runSearch(page, pageSize);
  useEffect(() => { void Promise.all([runSearch(1, 20, search), apiGet<any[]>('/api/taxcodes').then(setCodes)]); }, []);
  useEffect(() => { if (page !== 1 || pageSize !== 20) void runSearch(page, pageSize); }, [page, pageSize]);
  const reset = () => setForm(emptyForm());
  const resetNested = () => setForm((current) => ({ ...current, taxCodeId: '--- Select ---', taxLevel: '--- Select ---' }));
  const add = () => { if (form.taxCodeId === '--- Select ---' || form.taxLevel === '--- Select ---') return; const id = Number(form.taxCodeId); if (!id || form.rows.some((row) => row.id === id)) return; setForm((current) => ({ ...current, rows: [...current.rows, { id, level: current.taxLevel }], taxCodeId: '--- Select ---', taxLevel: '--- Select ---' })); };
  const save = async () => { if (!form.extTaxGroupCode.trim() || form.applied_on === '--- Select ---' || !form.startDate || !form.rows.length) { setToast({ msg: 'Please complete the required Tax Group fields.', type: 'err' }); return; } setBusy(true); try { await apiSend('/api/tax-groups', 'POST', { code: form.extTaxGroupCode, name: form.extTaxGroupCode, applied_on: form.applied_on, start_date: form.startDate, status: form.status, tax_code_ids: form.rows.map((row) => row.id) }); setToast({ msg: 'Tax Group created successfully', type: 'ok' }); reset(); load(); } catch (error: any) { setToast({ msg: error.message || 'Unable to save Tax Group', type: 'err' }); } finally { setBusy(false); } };
  const applySearch = () => { const next = { code: form.extTaxGroupCode, appliedOn: form.applied_on, startDate: form.startDate, status: form.status }; setSearch(next); void runSearch(1, pageSize, next); };
  const filtered = { length: records } as any, pages = total, visibleGroups = groups;
  const codeFor = (id: number) => codes.find((code) => Number(code.id) === id)?.tax_code || String(id);
  return <Shell active="master" breadcrumb="MASTER > Tax Management > Tax Group" openScreens={[{ label: 'Tax Group', to: '#' }]}>
    <div className="space-y-4">
      <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-3"><h1 className="text-base font-semibold text-slate-700">Tax Group</h1><div className="flex flex-wrap gap-2"><button type="button" onClick={runSearch} className="rounded border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Search</button><button type="button" onClick={save} disabled={busy} className="rounded bg-[#f5a623] px-4 py-2 text-sm font-medium text-white disabled:opacity-50"><Save className="mr-1 inline" size={14} />{busy ? 'Saving…' : 'Save'}</button><button type="button" onClick={reset} className="rounded border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Reset</button></div></div>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <div><label className="lbl">Tax Group Code <span className="text-rose-500">*</span></label><input aria-label="Tax Group Code" value={form.extTaxGroupCode} onChange={(event) => setForm((current) => ({ ...current, extTaxGroupCode: event.target.value }))} className="inp" /></div>
          <div><label className="lbl">Applied On <span className="text-rose-500">*</span></label><select aria-label="Applied On" value={form.applied_on} onChange={(event) => setForm((current) => ({ ...current, applied_on: event.target.value }))} className="inp"><option>--- Select ---</option><option>Cost</option><option>MRP</option><option>RSP</option></select></div>
          <div><label className="lbl">Start Date <span className="text-rose-500">*</span></label><input aria-label="Start Date" type="date" value={form.startDate} onChange={(event) => setForm((current) => ({ ...current, startDate: event.target.value }))} className="inp" /></div>
          <label className="flex items-center gap-2 self-end pb-2 text-sm font-medium text-slate-700"><input aria-label="Is Active" type="checkbox" checked={form.status === 'Active'} onChange={(event) => setForm((current) => ({ ...current, status: event.target.checked ? 'Active' : 'Inactive' }))} />Is Active</label>
        </div>
        <div className="mt-5 border-t border-slate-100 pt-4"><div className="grid gap-4 md:grid-cols-4"><div><label className="lbl">Tax Code <span className="text-rose-500">*</span></label><select aria-label="Tax Code" value={form.taxCodeId} onChange={(event) => setForm((current) => ({ ...current, taxCodeId: event.target.value }))} className="inp"><option>--- Select ---</option>{codes.map((code) => <option key={code.id} value={code.id}>{code.tax_code}</option>)}</select></div><div><label className="lbl">Tax Level</label><select aria-label="Tax Level" value={form.taxLevel} onChange={(event) => setForm((current) => ({ ...current, taxLevel: event.target.value }))} className="inp"><option>--- Select ---</option>{[1, 2, 3, 4, 5].map((level) => <option key={level}>{level}</option>)}</select></div><div className="flex items-end gap-2 md:col-span-2"><button type="button" onClick={add} className="rounded bg-[#2f9e9e] px-4 py-2 text-sm font-medium text-white">Add</button><button type="button" onClick={resetNested} className="rounded border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Reset</button></div></div>
          <GridPager count={form.rows.length} pageSize={nestedPageSize} onSize={setNestedPageSize} label="nested" />
          <div className="overflow-x-auto rounded border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-3 py-2 font-medium">Tax Code Id</th><th className="px-3 py-2 font-medium">Tax Level</th></tr></thead><tbody>{form.rows.length ? form.rows.slice(0, nestedPageSize).map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="px-3 py-2">{codeFor(row.id)}</td><td className="px-3 py-2">{row.level}</td></tr>) : <tr><td colSpan={2} className="px-3 py-5 text-center text-slate-400">No records to view</td></tr>}</tbody></table></div>
        </div>
      </section>
      <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-slate-700">Tax Group Enquiry</h2><GridPager count={filtered.length} pageSize={pageSize} onSize={(size) => { setPageSize(size); setPage(1); }} label="enquiry" /></div><div className="overflow-x-auto rounded border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr>{['Tax Group Code', 'Applied On', 'Start Date', 'Is Active', 'Audit'].map((label) => <th key={label} className="px-3 py-2 font-medium">{label}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={5} className="px-3 py-5 text-center text-slate-400">Loading…</td></tr> : visibleGroups.length ? visibleGroups.map((group) => <tr key={group.id} className="border-t border-slate-100"><td className="px-3 py-2">{group.code}</td><td className="px-3 py-2">{group.applied_on}</td><td className="px-3 py-2">{group.start_date}</td><td className="px-3 py-2">{group.status === 'Active' ? 'Yes' : 'No'}</td><td className="px-3 py-2" /></tr>) : <tr><td colSpan={5} className="px-3 py-5 text-center text-slate-400">No records to view</td></tr>}</tbody></table></div><div className="mt-3 flex items-center justify-end gap-2 text-sm text-slate-600"><button type="button" disabled={page === 1} onClick={() => setPage((current) => current - 1)} className="rounded border px-2 py-1 disabled:opacity-40">Previous</button><span>View {filtered.length ? (page - 1) * pageSize + 1 : 0} - {Math.min(page * pageSize, filtered.length)} of {filtered.length}</span><button type="button" disabled={page >= pages} onClick={() => setPage((current) => current + 1)} className="rounded border px-2 py-1 disabled:opacity-40">Next</button></div></section>
    </div>{toast && <Toast msg={toast.msg} type={toast.type} onClose={() => setToast(null)} />}
  </Shell>;
}

function GridPager({ count, pageSize, onSize, label }: { count: number; pageSize: number; onSize: (size: number) => void; label: string }) { return <div className="mb-2 flex items-center justify-end gap-2 text-xs text-slate-500"><label htmlFor={`${label}-page-size`}>Show</label><select id={`${label}-page-size`} aria-label={`${label} page size`} value={pageSize} onChange={(event) => onSize(Number(event.target.value))} className="rounded border border-slate-300 px-2 py-1">{pageSizes.map((size) => <option key={size}>{size}</option>)}</select><span>View {count ? 1 : 0} - {Math.min(count, pageSize)} of {count}</span></div>; }
