export const transporterTypes = [
  "--- Select ---",
  "Delhivery (Recommended)",
  "Delhivery International",
  "Delhivery International (New)",
  "Delhivery B2B",
  "2GO",
  "AFL express",
  "AFN",
  "Air Speed",
  "AJEX Transporter",
  "Alfatrex",
  "AllJoy",
  "Amazon Distribution B2B",
  "Amazon Ship Domestic ( India )",
  "Ante Air",
  "Apptymz",
  "Aramex",
  "Aramex International",
  "Arihant Intl. (AICS)",
  "Australia Post",
  "BARQ",
  "Blitz",
  "BLOWHORN",
  "Blue Dart",
  "Blue Dart (defunct)",
  "Blue Dart International V9",
  "Blue Dart V10",
  "Blue Dart V8",
  "Blue Dart V9",
  "Blue Dart V9 UAT",
  "Blue Dart-Demo V8",
  "Bombax",
  "Book A Wheel",
  "Book My Pocket",
  "Borzo",
  "BVC Logistics",
  "CityLink Express",
  "CLICKPOST",
  "DelhiveryRapid",
  "Delnet Express",
  "DHL Domestic",
  "DHL Ecommerce logistics",
  "DHL Ecommerce logistics UAT",
  "DHL Express",
  "DHL Express Sandbox",
  "DHL India V6",
  "DHL International",
  "DHL service",
  "DHL Version 10",
  "DHL version 6.2",
  "DHL-TMS",
  "DotZot",
  "DPD Local",
  "DTDC",
  "DTDC International",
  "DTDC LTL",
  "DTDC V4",
  "DTDC Version3",
  "DTDC/DotZot",
  "Dunzo",
  "Ecom Express",
  "Ecom Express UAT",
  "ECourierz",
  "Eflit",
  "Ekart",
  "Ekart Version 2",
  "Elite Transporter",
  "Emirates Post",
  "Emirates SkyCargo",
  "Endicia-Live",
  "Endicia-Test",
  "EShipz",
  "Eshopbox",
  "EVRi",
  "Far Eye Lite",
  "Fareye",
  "FASTWAY",
  "Fedex",
  "Fedex International",
  "FedEx International v26",
  "FedEx International v26 UAT",
  "FedexInternationalV25",
  "FedexInternationalV25-UAT",
  "FedexV25",
  "FedexV25-UAT",
  "Fetchr",
  "First Flight",
  "Flash Exress",
  "Fleetx",
  "FlowCourier",
  "FSHIP",
  "FutureSupplyChain_Surface",
  "Gati",
  "Gati B2B",
  "GHN",
  "GoJavas",
  "GoPigeon",
  "Hanjin",
  "hipship",
  "Holisol Transporter Service",
  "Hong Kong",
  "IdFleet",
  "India Post",
  "India Post V2",
  "Innovex",
  "InstaShipin",
  "InTargos",
  "IThink Logistic V3",
  "IThink Logistics",
  "IWExpress",
  "J&T Singapore",
  "J&T Vietnam",
  "J&TTransporter",
  "JAK Transporter",
  "JANIO",
  "JNE Express",
  "JNE Express V2",
  "JNEV2-dedicated",
  "JV express",
  "JV Express",
  "Kart2Door",
  "Kwikship",
  "Last Mile",
  "Lion Parcel",
  "Load Share",
  "Loginext Service",
  "Logistics",
  "LYVE Transporter",
  "MyHermes",
  "MyPacco",
  "Naqel",
  "Naqel Return",
  "Naqel_UAT",
  "NECC",
  "Nimbuspost",
  "Ninja Van",
  "NinjaVan MY v4.1",
  "NinjaVan v4.1 UAT",
  "Ninjavan4.1INT",
  "Nuvoex",
  "OnLine Xpress",
  "Others",
  "Others",
  "OTO",
  "Overnite",
  "Overseas",
  "OYS-01 Oyster Logistics",
  "Paket",
  "Park N Parcel",
  "Partnr",
  "Pepcart",
  "Pickrr",
  "PicoXpress",
  "Piekart",
  "PIKKOL",
  "PIKNDEL Transporter",
  "Porter India",
  "Porter Xpress",
  "POS Laju",
  "Posta Plus",
  "PROZO Transporter",
  "Purple Drone",
  "Quantium Int Std",
  "Quickshift",
  "Quiqup Transporter",
  "QWQER TRANSPORTER",
  "QWQER TRANSPORTER UAT",
  "Rapid Delivery",
  "Rapid Ship Courier",
  "Redexpress",
  "Rivigo",
  "ROCKETBOX TRANSPORTER",
  "Royal Mail Latest",
  "RoyalMail",
  "RoyalMail Express",
  "Safe Express V3",
  "SafeExpress2",
  "Safexpress",
  "Sandbox Fedex International",
  "SAP Express",
  "Saudi Post",
  "SCM4You",
  "SEKO AU",
  "Self Delivery",
  "SelloShip",
  "Shadowfax",
  "ShadowFax HyperLocal",
  "Shadowfax MPS",
  "Shadowfax_v3",
  "ShadowFax_Warehouse",
  "Ship Delight",
  "Ship Engine",
  "Ship Mozo",
  "Ship Station V2",
  "SHIPA",
  "SHIPA UAT",
  "Shipa Version 2",
  "SHIPEASE Transporter",
  "Shiperfecto",
  "Shiplog Transporter",
  "SHIPPER Transporter",
  "Shipper V3",
  "Shippigo",
  "ShipRocket",
  "Shiprocket Cargo",
  "Shipsy B2C",
  "Shipsy B2C V2",
  "SHIPSY Hyperlocal",
  "Shipway",
  "Shipway V2",
  "SHIPX",
  "Shipyaari",
  "Shipyaari V2",
  "Shyplite",
  "Sky Express",
  "SkyNet",
  "Smartr",
  "SmartShip",
  "Speed Post",
  "Stamp",
  "swftbox",
  "Swift",
  "Ta-Q-Bin",
  "TCI-XPS",
  "Think Root",
  "TIMES",
  "Tirupati",
  "TKXP TRANSPORTER",
  "TOOKAN",
  "Trackon Transporter",
  "Tradeling Stage",
  "Tradeling Testing",
  "Trust On",
  "UPSV",
  "US Fedex",
  "US Fedex sandbox",
  "VAMASHIP",
  "VAMASHIP Surface",
  "Velocity Shipping",
  "Vulcan Exp",
  "Whistle",
  "Whizzard",
  "Wing",
  "WingV2-Shipox",
  "Wow Express",
  "WOWExpress_V2",
  "XpressBee",
  "XpressBee",
  "XpressBees Wallet",
  "XpressBeesV6",
  "XpressBeesV7",
  "Yamato"
] as const;

export const transporterCountries = [
  "---Select Country ---",
  "AFGHANISTAN",
  "ALAND ISLANDS",
  "ALBANIA",
  "ALDERNEY",
  "ALGERIA El Djazair",
  "AMERICAN SAMOA",
  "ANDORRA",
  "ANGOLA",
  "ANGUILLA",
  "ANTARCTICA",
  "ANTIGUA AND BARBUDA",
  "ARGENTINA",
  "ARMENIA",
  "ARUBA",
  "ASCENSION ISLAND",
  "AUSTRALIA",
  "AUSTRIA",
  "AZERBAIJAN",
  "BAHAMAS",
  "BAHRAIN",
  "BANGLADESH",
  "BARBADOS",
  "BELARUS",
  "BELGIUM",
  "BELIZE",
  "BENIN",
  "BERMUDA",
  "BHUTAN",
  "BOLIVIA",
  "BONAIRE ST EUSTATIUS AND SABA",
  "BOSNIA AND HERZEGOVINA",
  "BOTSWANA",
  "BOUVET ISLAND",
  "BRAZIL",
  "BRITISH INDIAN OCEAN TERRITORY",
  "BRUNEI DARUSSALAM",
  "BULGARIA",
  "BURKINA FASO",
  "BURUNDI",
  "CAMBODIA",
  "CAMEROON",
  "CANADA",
  "CAPE VERDE",
  "CAYMAN ISLANDS",
  "CENTRAL AFRICAN REPUBLIC",
  "CHAD Tchad",
  "CHANNEL ISLANDS",
  "CHILE",
  "CHINA",
  "CHRISTMAS ISLAND",
  "COCOS KEELING ISLANDS",
  "COLOMBIA",
  "COMOROS",
  "CONGO REPUBLIC OF",
  "COOK ISLANDS",
  "COSTA RICA",
  "COTE",
  "CROATIA Hrvatska",
  "CUBA",
  "CURAAO",
  "CYPRUS",
  "CZECH REPUBLIC",
  "DENMARK",
  "DJIBOUTI",
  "DOMINICA",
  "DOMINICAN REPUBLIC",
  "ECUADOR",
  "EGYPT",
  "EL SALVADOR",
  "EQUATORIAL GUINEA",
  "ERITREA",
  "ESTONIA",
  "ETHIOPIA",
  "EUROPEAN UNION",
  "FAEROE ISLANDS",
  "FALKLAND ISLANDS MALVINAS",
  "FIJI",
  "FINLAND",
  "FRANCE",
  "FRENCH GUIANA",
  "FRENCH POLYNESIA",
  "FRENCH SOUTHERN TERRITORIES",
  "GABON",
  "GAMBIA THE",
  "GEORGIA",
  "GERMANY Deutschland",
  "GHANA",
  "GIBRALTAR",
  "GREAT BRITAIN United Kingdom",
  "GREECE",
  "GREENLAND",
  "GRENADA",
  "GUADELOUPE",
  "GUAM",
  "GUATEMALA",
  "GUERNSEY",
  "GUINEA",
  "GUINEA BISSAU",
  "GUYANA",
  "HAITI",
  "HEARD ISLAND AND MCDONALD ISLANDS",
  "HONDURAS",
  "HONG KONG Special Administrative Region of China",
  "HUNGARY",
  "ICELAND",
  "INDIA",
  "INDONESIA",
  "IRAN Islamic Republic of Iran",
  "IRAQ",
  "IRELAND",
  "ISLE OF MAN",
  "ISRAEL",
  "ITALY",
  "JAMAICA",
  "JAPAN",
  "JERSEY",
  "JORDAN Hashemite Kingdom of Jordan",
  "KAZAKHSTAN",
  "KENYA",
  "KIRIBATI",
  "North Korea",
  "South Korea",
  "KUWAIT",
  "KYRGYZSTAN",
  "LAO PEOPLES DEMOCRATIC REPUBLIC",
  "LATVIA",
  "LEBANON",
  "LESOTHO",
  "LIBERIA",
  "LIBYA Libyan Arab Jamahirya",
  "LIECHTENSTEIN Furstentum Liechtenstein",
  "LITHUANIA",
  "LUXEMBOURG",
  "MACAO Special Administrative Region of China",
  "MACEDONIA Former Yugoslav Republic of Macedonia",
  "MADAGASCAR",
  "MALAWI",
  "MALAYSIA",
  "MALDIVES",
  "MALI",
  "MALTA",
  "MARSHALL ISLANDS",
  "MARTINIQUE",
  "MAURITANIA",
  "MAURITIUS",
  "MAYOTTE",
  "MEXICO",
  "MICRONESIA Federated States of Micronesia",
  "MOLDOVA",
  "MONACO",
  "MONGOLIA",
  "MONTENEGRO",
  "MONTSERRAT",
  "MOROCCO",
  "MOZAMBIQUE Mocambique",
  "MYANMAR formerly Burma",
  "NAMIBIA",
  "NAURU",
  "NEPAL",
  "NETHERLANDS",
  "NETHERLANDS ANTILLES obsolete",
  "NEW CALEDONIA",
  "NEW ZEALAND",
  "NICARAGUA",
  "NIGER",
  "NIGERIA",
  "NIUE",
  "NORFOLK ISLAND",
  "NORTHERN MARIANA ISLANDS",
  "NORWAY",
  "OMAN",
  "PAKISTAN",
  "PALAU",
  "PALESTINIAN TERRITORIES",
  "PANAMA",
  "PAPUA NEW GUINEA",
  "PARAGUAY",
  "PERU",
  "PHILIPPINES",
  "PITCAIRN",
  "POLAND",
  "PORTUGAL",
  "PUERTO RICO",
  "QATAR",
  "RÉUNION",
  "ROMANIA",
  "RUSSIAN FEDERATION",
  "RWANDA",
  "SAINT BARTHELEMY",
  "SAINT HELENA",
  "SAINT KITTS AND NEVIS",
  "SAINT LUCIA",
  "SAINT MARTIN French portion",
  "SAINT PIERRE AND MIQUELON",
  "SAINT VINCENT AND THE GRENADINES",
  "SAMOA formerly Western Samoa",
  "SAN MARINO Republic of",
  "SAO TOME AND PRINCIPE",
  "SAUDI ARABIA (Kingdom of Saudi Arabia)",
  "SENEGAL",
  "SERBIA Republic of Serbia",
  "SEYCHELLES",
  "SIERRA LEONE",
  "SINGAPORE",
  "SINT MAARTEN",
  "SLOVAKIA Slovak Republic",
  "SLOVENIA",
  "SOLOMON ISLANDS",
  "SOMALIA",
  "SOUTH AFRICA Zuid Afrika",
  "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
  "SOVIET UNION",
  "SPAIN Espana",
  "SRI LANKA formerly Ceylon",
  "SUDAN",
  "SURINAME",
  "SVALBARD AND JAN MAYEN",
  "SWAZILAND",
  "SWEDEN",
  "SWITZERLAND Confederation of Helvetia",
  "SYRIAN ARAB REPUBLIC",
  "TAIWAN Chinese Taipei for IOC",
  "TAJIKISTAN",
  "TANGANYIKA",
  "TANZANIA",
  "THAILAND",
  "TIMOR LESTE formerly East Timor",
  "TOGO",
  "TOKELAU",
  "TONGA",
  "TRINIDAD AND TOBAGO",
  "TUNISIA",
  "TURKEY",
  "TURKMENISTAN",
  "TURKS AND CAICOS ISLANDS",
  "TUVALU",
  "UKRAINE",
  "UNITED ARAB EMIRATES",
  "UNITED KINGDOM",
  "UNITED STATES",
  "UNITED STATES MINOR OUTLYING ISLANDS",
  "URUGUAY",
  "UZBEKISTAN",
  "VANUATU",
  "VATICAN CITY Holy See",
  "VENEZUELA",
  "VIET NAM",
  "VIRGIN ISLANDS BRITISH",
  "VIRGIN ISLANDS US",
  "YUGOSLAVIA",
  "WALLIS AND FUTUNA",
  "WESTERN SAHARA formerly Spanish Sahara",
  "YEMEN Yemen Arab Republic",
  "ZAMBIA formerly Northern Rhodesia",
  "ZANZIBAR",
  "ZIMBABWE",
  "NA",
  "Taiwan",
  "Hong Kong SAR China",
  "Switzerland",
  "Germany",
  "Spain",
  "Saudi Arabia",
  "Croatia",
  "Slovakia",
  "Moldova Republic of",
  "Serbia",
  "Hong Kong",
  "Jordan",
  "COTE",
  "Faroe Islands",
  "Liechtenstein",
  "North Macedonia",
  "Cote dIvoi",
  "Cote dIvoire",
  "Congo The Democratic Republic Of The",
  "Brunei",
  "Cote dIvoire",
  "Moldova, Republic of",
  "السعودية"
] as const;

export const transporterStates = [
  "---Select State ---",
  "Uttar Pradesh",
  "Assam",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Andaman Nicobar",
  "UTTAR PRADESH",
  "Karnataka",
  "apna",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Orissa",
  "Punjab",
  "Dadra and Nagar Haveli",
  "Rajasthan",
  "Daman Diu",
  "Sikkim",
  "Tamil Nadu",
  "Tripura",
  "ARUNACHAL PRADESH",
  "Uttarakhand",
  "West Bengal",
  "Chandigarh",
  "Lakshadweep",
  "Pondicherry",
  "Uttaranchal",
  "meeee",
  "Andaman And Nicobar Islands",
  "UP",
  "Name",
  "Xã Long Điền A",
  "Huyện Sóc Sơn",
  "Xã Lương Thiện",
  "Xã Hương Cần",
  "Xã Lâm Kiết",
  "Phường 11",
  "Quận Hoàn Kiếm",
  "Phường Trung Thành",
  "Thị Xã Thuận An",
  "Thị trấn Long Hải",
  "Xã An Phụ",
  "Huyện Vĩnh Thạnh",
  "Xã Bình Hưng",
  "Phường Thái Hòa",
  "Phường Cống Vị",
  "Phường Tăng Nhơn Phú B",
  "Phường Tây Thạnh",
  "Phường Nghĩa Đô",
  "Xã Giao Thanh",
  "Quận Ngũ Hành Sơn",
  "Xã Cư Dliê M'nông",
  "Phường Thượng Đình",
  "Thành Phố Nha Trang",
  "Huyện Văn Lâm",
  "Huyện Xuyên Mộc",
  "Phường Trường Thọ",
  "Phường Trung Hòa",
  "Thành Phố Thủ Dầu Một",
  "Phường Phú Mỹ",
  "Huyện Tam Đường",
  "Phường Yên Thịnh",
  "Xã Quảng Tiến",
  "Thị trấn Trần Văn Thời",
  "Phường Hưng Phúc",
  "Phường An Phú",
  "Phường Xuân An",
  "Phường Bình Hưng Hòa A",
  "Phường An Dương",
  "Phường Mỹ Long",
  "Phường Ngô Mây",
  "Xã Minh Tân",
  "Thành Phố Biên Hòa",
  "Thị trấn Phú Hòa",
  "Phường Định Công",
  "Thị trấn Chùa Hang",
  "Huyện Đan Phượng",
  "Phường Trà An",
  "Quận 5",
  "Phường Tam Bình",
  "Thị trấn Xuân Mai",
  "Xã Dang Kang",
  "Quận Tân Bình",
  "Thành Phố Bảo Lộc",
  "Huyện Điện Bàn",
  "Huyện Hàm Yên",
  "Phường Trương Định",
  "Xã Xuân Ninh",
  "Phường Thống Nhất",
  "Thị trấn Cầu Kè",
  "Xã Cẩm La",
  "Huyện Trảng Bom",
  "Thị trấn Phố Ràng",
  "Phường Vĩnh Nguyên",
  "Xã Bình Thạnh",
  "Phường Vĩnh Bảo",
  "Phường Linh Xuân",
  "Xã Phú Hội",
  "Phường Ba Láng",
  "Xã Quất Động",
  "Phường Đức Thắng",
  "Phường Cam Phúc Bắc",
  "Xã Tân Dương",
  "Phường Hòa Thuận Tây",
  "Phường Khương Trung",
  "Thị trấn Núi Sập",
  "Phường Tân Thuận Đông",
  "Xã Đức Hoà Hạ",
  "Xã Hội Nghĩa",
  "Phường Phú Thạnh",
  "Phường Phan Chu Trinh",
  "Phường Bình Hưng Hòa B",
  "Xã Đông Phương",
  "Quận Thủ Đức",
  "Thị trấn Buôn Trấp",
  "Phường An Bình",
  "Huyện Châu Thành",
  "Thị trấn Lai Cách",
  "Thị Xã Đồng Xoài",
  "Phường Tân Phong",
  "Quận Bình Thạnh",
  "Thị trấn Long Phú",
  "Xã Tân Xuân",
  "Phường Phú Đức",
  "Xã Bình Thới",
  "Phường Tam Thanh",
  "Quận Hà Đông",
  "Xã Ngũ Lạc",
  "Xã Lộc Phú",
  "Phường An Lạc",
  "Xã Phước Đông",
  "Huyện Cư Jút",
  "Phường Linh Chiểu",
  "Xã Trung Sơn",
  "Xã Mỹ Thủy",
  "Đà Nẵng",
  "Xã Bàu Hàm 2",
  "Thị trấn Võ Xu",
  "Xã Tân Thành",
  "Xã Việt Tiến",
  "Xã Tân Thới",
  "Xã Tập Sơn",
  "Phường Phú Trinh",
  "Xã Thịnh Vượng",
  "Xã Long Hiệp",
  "Phường Long Hưng",
  "Phường Phú Khương",
  "Thành Phố Long Xuyên",
  "Thành Phố Bắc Ninh",
  "Phường Hoàng Liệt",
  "Huyện Đông Hải",
  "Phường Tứ Liên",
  "Phường Hà Lầm",
  "Thị trấn Văn Điển",
  "Xã Kim Chung",
  "Phường Bình Trị Đông A",
  "Xã Phúc Thành A",
  "Thị trấn Tĩnh Gia",
  "Phường Tân Thới Nhất",
  "Huyện Diên Khánh",
  "Xã Lạc Đạo",
  "Huyện Chơn Thành",
  "Huyện Tân Thành",
  "Xã Long Điền B",
  "Thành Phố Thái Nguyên",
  "Xã Hòa Hiệp Trung",
  "Phường Phạm Ngũ Lão",
  "Xã Xuân Thới Thượng",
  "Quận Thanh Xuân",
  "Thị trấn Bình Dương",
  "Huyện Bình Chánh",
  "Thành Phố Phủ Lý",
  "Thị trấn Trâu Quỳ",
  "Phường Láng Thượng",
  "Thị trấn Điện Biên Đông",
  "Quận Nam Từ Liêm",
  "Xã Nghi Trung",
  "Thành Phố Hạ Long",
  "Huyện Long Điền",
  "Thị trấn Dương Đông",
  "Phường Mỹ Phước",
  "Phường Bình Trưng Tây",
  "Phường Thọ Quang",
  "Xã Vĩnh Lộc B",
  "Thị trấn Lâm",
  "Phường Bến Thành",
  "Xã Phước Vân",
  "Phường Tân Giang",
  "Xã Tập Ngãi",
  "Huyện Hạ Lang",
  "Xã Thụy Lâm",
  "Xã Việt Ngọc",
  "PB",
  "Hồ Chí Minh",
  "Kiên Giang",
  "Defaulted",
  "Telangana",
  "Odisha",
  "Jammu and Kashmir",
  "ANDAMANNICOBARISLANDS",
  "North Eastern",
  "Puducherry",
  "Laguna",
  "Tagas",
  "n",
  "J Vargas Cor. Edsa",
  "Metro Manila",
  "Batangas",
  "s",
  "Aklan",
  "Socorro",
  "Cubao",
  "c",
  "r",
  "Cagayan",
  "Cotabato (north Cot.)",
  "Bulacan",
  "o",
  "Palawan",
  "z",
  "l",
  "Abra",
  "a",
  "Camarines Sur",
  "Basilan",
  "t",
  "Lanao Del Sur",
  "m",
  "Zamboanga Del Norte",
  "Bataan",
  "Albay",
  "Laoag City",
  "Rizal",
  "Baguio",
  "BRANCH_PROVINCE",
  "SINGAPORE",
  "SINGAPORE",
  "null",
  "StateChanged",
  "Delhi",
  "abcd & vfga",
  "Allamuru",
  "test",
  "sadasdasdasd",
  "asasas",
  "assadsad",
  "Uttar pardeh",
  "JAMMU &amp; KASHMIR",
  "Bengal",
  "New Delhi",
  "J & K",
  "Bengluru",
  "Bombay",
  "London",
  "New York",
  "himachal",
  "JAMMU AND KASHM",
  "Uttar Paresh",
  "Andaman and Nicobar",
  "KA",
  "DADRA & NAGAR HAVELI",
  "HP",
  "HR",
  "Sector-48, Sohna Road, Gurgaon",
  "MP",
  "rehan456",
  "JAKARTA",
  "test234",
  "HCMC",
  "Quận Thanh Khê",
  "Quận 4",
  "Quận Ba Đình",
  "Quận 1",
  "Huyện Đông Hòa",
  "Quận 6",
  "-",
  "NA",
  "Quận 10",
  "Hồ Chí Minh",
  "Quận 11",
  "2*****************************2",
  "Quận Đống Đa",
  "2*******************a",
  "4***************n",
  "Đường chợ chim",
  "Q****7",
  "Quận 7",
  "California",
  "Thị xã Bến Cát",
  "Thành phố Tam Kỳ",
  "Thành phố Rạch Giá",
  "Quận Gò Vấp",
  "Thị xã Long Khánh",
  "Huyện Ninh Giang",
  "Quận 2",
  "Huyện Thống Nhất",
  "Phường 3",
  "Phường 12",
  "Phường 26",
  "Phường Chính Gián",
  "Huyện Củ Chi",
  "Huyện Krông Ana",
  "Huyện Hóc Môn",
  "Phường Đakao",
  "Thành phố Cà Mau",
  "Malibu",
  "Quận 8",
  "Q1",
  "Quận Phú Nhuận",
  "Phường Cầu Kho",
  "Quận+Hà+Đông",
  "Huyện Mường Ảng",
  "Quận Hải Châu",
  "Thành phố Châu Đốc",
  "Quận Bắc Từ Liêm",
  "Huyện U Minh Thượng",
  "Quận Bình Tân",
  "Huyện Bảo Lâm",
  "Huyện Nậm Pồ",
  "Thành phố Điện Biên Phủ",
  "Huyện Điện Biên Đông",
  "Huyện đảo Côn Đảo",
  "Quận 3",
  "Thị xã Sơn Tây",
  "Huyện Thanh Bình",
  "Huyện Càng Long",
  "Thành phố Cam Ranh",
  "Huyện Cẩm Mỹ",
  "Quận Cầu Giấy",
  "Huyện Thoại Sơn",
  "Quận Bình Thủy",
  "Quận 10",
  "Quận Sơn Trà",
  "Huyện Châu Đức",
  "Thành phố Bà Rịa",
  "Huyện Tân Phú",
  "Huyện Lắk",
  "Huyện Gia Lâm",
  "Thành Phố Tuy Hòa",
  "Huyện đảo Hoàng Sa",
  "H**********è",
  "H*********ú",
  "Q****2",
  "Q*************h",
  "Thành phố Đà Lạt",
  "Q**********ú",
  "Q*********p",
  "Huyện An Phú",
  "H***********à",
  "Q**n C** **",
  "Q00n C00 00",
  "Q**n ** Đ**g",
  "Q**n *** **",
  "Quận Cẩm Lệ",
  "Q****4",
  "Q************n",
  "***************",
  "***********",
  "*************",
  "************",
  "Q**n 0",
  "*** ** *** ***",
  "Q**n *** B**h",
  "H***n C**u ***",
  "Q**n B**h ***",
  "Q**n H**n K**m",
  "*****0",
  "**************",
  "DUBAI",
  "H***n ** ***",
  "P****g *** ***",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Dadra and Nagar Haveli and Daman and Diu",
  "N/A",
  "T***h *** P****u",
  "H***n B**h C***h",
  "T*********y",
  "Q********g",
  "BIHAR",
  "P**********o",
  "Q*******ệ",
  "satan's arsehole",
  "Q**********m",
  "Andhra Pradesh",
  "Q***1",
  "H************y",
  "Q***7",
  "H*********ổ",
  "Q***********m",
  "T**********n",
  "Q********ú",
  "Q*********h",
  "T********ỹ",
  "T*************h",
  "Q***3",
  "Q****0",
  "H**********c",
  "Q***9",
  "Q*********y",
  "Jammu & Kashmir",
  "Dadra & Nagar Haveli & Daman & Diu",
  "Q***8",
  "T***********n",
  "H***********c",
  "T**********h",
  "Q***********h",
  "H*********m",
  "T*******n",
  "Q***********c",
  "Q*******p",
  "H*********n",
  "H*******ì",
  "T*********t",
  "UttarPradesh",
  "T**************g",
  "Q*********t",
  "T*************n",
  "H********è",
  "T*************c",
  "H************h",
  "H*********h",
  "Q*********n",
  "H**********h",
  "H*********i",
  "H********i",
  "T***************n",
  "H************g",
  "T***********o",
  "H***********h",
  "H***********m",
  "H***********g",
  "H*************g",
  "Q***4",
  "Q********h",
  "H*************i",
  "T***************t",
  "H*********g",
  "0",
  "H********ú",
  "H**********m",
  "Maharastra",
  "H**********ú",
  "H**************g",
  "H********k",
  "Kolkata",
  "fggfhj",
  "38",
  "Kerela",
  "Mumbai",
  "indore mp",
  "hisar",
  "Jharkhand",
  "test state",
  "Test-State",
  "Dummy",
  "******",
  "*****",
  "Hawada",
  "BR",
  "DEL",
  "NOIDA",
  "Patna",
  "AP",
  "U.P",
  "17",
  "2322",
  "2574",
  "2900",
  "2679",
  "Daman and Diu",
  "T***********t",
  "23",
  "test2",
  "test5",
  "4282",
  "uttarpardesh",
  "testnoewstate",
  "DREAMS",
  "Andaman & Nicobar",
  "UTTAR PRDESH",
  "Bengaluru",
  "532",
  "400051",
  "Darkhan",
  "Maharashtra",
  "dhdjxjxjx",
  "Kerala",
  "Gdbbd",
  "KOTADEPOK",
  "Faridabad",
  "IN",
  "Tamilnadu",
  "MH",
  "Srijana",
  "dellhi",
  "45764785",
  "*********"
] as const;

