/* eslint-disable @typescript-eslint/no-explicit-any -- Admin records have deliberately heterogeneous, recording-derived payloads. */
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Download, HelpCircle, Pencil, Plus, RefreshCw, Search, Upload, X } from 'lucide-react';
import Shell from '../Shell';
import { apiGet, apiSend } from '../../lib/api';
import { RecordedAuditLogs, RecordedManageApi, RecordedUserEnquiry } from './RecordedAdminWorkflows';

type Row = Record<string, any> & { id: number; type: string; status?: string; version?: number };
type ToastState = { message: string; tone: 'success' | 'error' } | null;

const screenMeta: Record<string, { title: string; crumb: string }> = {
  'user-enquiry': { title: 'User Enquiry', crumb: 'Admin > User Management > User Enquiry' },
  'user-create-edit': { title: 'User Create/Edit', crumb: 'Admin > User Management > User Create/Edit' },
  'role-create-edit': { title: 'Role Create/Edit', crumb: 'Admin > User Management > Role Create/Edit' },
  'order-import': { title: 'Order Import', crumb: 'Admin > Imports > Order Import' },
  'common-import': { title: 'Common Import', crumb: 'Admin > Imports > Common Import' },
  exports: { title: 'Exports', crumb: 'Home > Pending Report' },
  'force-order-pull': { title: 'Force Order Pull', crumb: 'Admin > Force Order Pull' },
  settings: { title: 'Settings', crumb: 'Admin > Settings' },
  'manage-api': { title: 'Manage Api', crumb: 'Admin > Api > Manage Api' },
  'audit-logs': { title: 'Audit Logs', crumb: 'Admin > Audit Logs' },
  'api-dashboard': { title: 'API Dashboard', crumb: 'Admin > Api > API Dashboard' },
};

const input = 'h-8 w-full rounded border border-slate-300 bg-white px-2 text-sm text-slate-700 outline-none focus:border-sky-500';
const label = 'whitespace-nowrap text-right text-sm text-slate-600';
const primary = 'inline-flex items-center gap-1.5 rounded bg-[#ec9818] px-3 py-2 text-sm font-medium text-white hover:bg-[#d98608] disabled:opacity-50';
const success = 'inline-flex items-center gap-1.5 rounded bg-[#0aad56] px-3 py-2 text-sm font-medium text-white hover:bg-[#069548] disabled:opacity-50';
const neutral = 'inline-flex items-center gap-1.5 rounded border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50';

function Toast({ toast, close }: { toast: ToastState; close: () => void }) {
  if (!toast) return null;
  return <div className={`fixed right-5 top-20 z-[100] flex min-w-72 items-center justify-between rounded border px-4 py-3 text-sm shadow-lg ${toast.tone === 'success' ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-rose-300 bg-rose-50 text-rose-800'}`}><span>{toast.message}</span><button onClick={close}><X size={15} /></button></div>;
}

function Grid({ columns, rows, empty = 'No records to view', actions }: { columns: { key: string; label: string; value?: (row: Row) => React.ReactNode }[]; rows: Row[]; empty?: string; actions?: (row: Row) => React.ReactNode }) {
  return <div className="overflow-hidden border border-slate-300 bg-white">
    <div className="overflow-x-auto">
      <table className="min-w-full border-collapse text-sm">
        <thead className="bg-[#e9e8f3] text-slate-700"><tr>{columns.map((c) => <th key={c.key} className="border-r border-slate-300 px-3 py-1.5 text-center font-bold">{c.label}</th>)}{actions && <th className="px-3 py-1.5 text-center font-bold">Actions</th>}</tr></thead>
        <tbody>{rows.map((row, index) => <tr key={row.id} className={index % 2 ? 'bg-[#f7f6fc]' : 'bg-white'}>{columns.map((c) => <td key={c.key} className="max-w-80 truncate border-t border-slate-200 px-3 py-1.5 text-center text-slate-700">{c.value ? c.value(row) : row[c.key] || ''}</td>)}{actions && <td className="border-t border-slate-200 px-3 py-1 text-center">{actions(row)}</td>}</tr>)}</tbody>
      </table>
    </div>
    <div className="flex h-8 items-center justify-between bg-[#e9e8f3] px-3 text-xs text-slate-500"><span>◀ ◀ Page <b>1</b> of {Math.max(1, Math.ceil(rows.length / 20))} ▶ ▶ <select className="ml-2 border border-slate-300 bg-white px-1"><option>20</option><option>50</option><option>100</option></select></span><span>{rows.length ? `View 1 - ${Math.min(20, rows.length)} of ${rows.length}` : empty}</span></div>
  </div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="mb-1 overflow-hidden rounded border border-slate-200 bg-white"><div className="flex items-center justify-between bg-[#f4f4f8] px-3 py-1 font-semibold text-slate-600"><span>{title}</span><span>−</span></div>{children}</section>;
}

function UserEnquiry({ openEditor }: { openEditor: () => void }) {
  const [rows, setRows] = useState<Row[]>([]); const [filter, setFilter] = useState({ username: '', firstName: '', lastName: '', status: '', email: '', userType: 'Normal' }); const [toast, setToast] = useState<ToastState>(null);
  const load = () => apiGet<Row[]>('/api/admin?type=user').then(setRows).catch(() => setToast({ message: 'Unable to load users', tone: 'error' }));
  useEffect(() => { void load(); }, []);
  const results = useMemo(() => rows.filter((r) => Object.entries(filter).every(([key, value]) => !value || String(r[key] || '').toLowerCase().includes(value.toLowerCase()))), [rows, filter]);
  const exportRows = () => {
    const csv = ['User Name,First Name,Last Name,Status,Email,User Type', ...results.map((r) => [r.username, r.firstName, r.lastName, r.status, r.email || '', r.userType || 'Normal'].join(','))].join('\n');
    const href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const a = document.createElement('a'); a.href = href; a.download = 'user-enquiry.csv'; a.click(); URL.revokeObjectURL(href);
  };
  return <><div className="mb-3 flex justify-end gap-2"><button className={primary} onClick={load}><Search size={16} />Search</button><button className={neutral} onClick={() => setFilter({ username: '', firstName: '', lastName: '', status: '', email: '', userType: 'Normal' })}>✖ Reset</button><button className={neutral}>✥ Advance Search</button><button className={neutral}><Upload size={15} /> Import</button><button className={neutral} onClick={exportRows}><Download size={15} /> Export</button><button className={neutral} onClick={openEditor}><Plus size={15} /> Add New</button><HelpCircle className="mt-2 text-[#287cc0]" size={24} /></div>
    <Grid columns={[
      { key: 'username', label: 'User Name', value: (r) => r.username }, { key: 'firstName', label: 'First Name' }, { key: 'lastName', label: 'Last Name' }, { key: 'status', label: 'Status' }, { key: 'email', label: 'Email' }, { key: 'userType', label: 'User Type' },
    ]} rows={results} />
    <Toast toast={toast} close={() => setToast(null)} /></>;
}

function UserEditor() {
  const empty = { username: '', firstName: '', middleName: '', lastName: '', title: '', designation: '', birthDate: '', status: 'Active', userType: 'Normal', poLimit: '', mfa: false, email: '', phone: '', roles: [] as { company: string; location: string; description: string }[] };
  const [form, setForm] = useState(empty); const [role, setRole] = useState({ company: '', location: '', description: '' }); const [udf, setUdf] = useState(false); const [toast, setToast] = useState<ToastState>(null); const [saving, setSaving] = useState(false);
  const set = (key: string, value: any) => setForm((f) => ({ ...f, [key]: value }));
  const save = async () => { setSaving(true); try { await apiSend('/api/admin', 'POST', { type: 'user', ...form }); setToast({ message: 'User saved successfully', tone: 'success' }); } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Unable to save user', tone: 'error' }); } finally { setSaving(false); } };
  const addRole = () => { if (!role.company || !role.location || !role.description) { setToast({ message: 'Company, Location and Role Desc are Mandatory', tone: 'error' }); return; } set('roles', [...form.roles, role]); setRole({ company: '', location: '', description: '' }); };
  return <><div className="mb-3 flex justify-end gap-2"><button className={neutral}>ℹ Audit</button><button className={primary} disabled={saving} onClick={save}>▣ {saving ? 'Saving...' : 'Save'}</button><button className={neutral}>▣ Reset Password</button><button className={neutral}>▣ Reset MFA</button><button className={neutral} onClick={() => { setForm(empty); setRole({ company: '', location: '', description: '' }); }}><Plus size={15} /> Add New</button><HelpCircle className="mt-2 text-[#287cc0]" size={24} /></div>
    <Section title="User Details"><div className="grid grid-cols-3 gap-x-12 gap-y-2 p-3"><Field label="User Name*" value={form.username} onChange={(v) => set('username', v)} /><Field label="Designation" value={form.designation} onChange={(v) => set('designation', v)} /><SelectField label="Title*" value={form.title} onChange={(v) => set('title', v)} options={['--- Select ---', 'Mr', 'Ms', 'Mrs']} /><Field label="First Name*" value={form.firstName} onChange={(v) => set('firstName', v)} /><Field label="Middle Name" value={form.middleName} onChange={(v) => set('middleName', v)} /><Field label="Last Name*" value={form.lastName} onChange={(v) => set('lastName', v)} /><Field label="Date Of Birth" type="date" value={form.birthDate} onChange={(v) => set('birthDate', v)} /><SelectField label="Status" value={form.status} onChange={(v) => set('status', v)} options={['Active', 'Inactive']} /><SelectField label="User Type*" value={form.userType} onChange={(v) => set('userType', v)} options={['Normal', 'External']} /><Field label="Purchase Order Limit" value={form.poLimit} onChange={(v) => set('poLimit', v)} /><label className="flex items-center gap-3 text-sm text-slate-600">Enable Multifactor Authentication <input type="checkbox" checked={form.mfa} onChange={(e) => set('mfa', e.target.checked)} /></label><button className="text-left text-sm font-semibold text-[#287cc0]" onClick={() => setUdf(true)}>View/Update UDF</button></div></Section>
    <Section title="Contact Details"><div className="grid grid-cols-2 gap-3 p-3"><Field label="Email" value={form.email} onChange={(v) => set('email', v)} /><Field label="Phone" value={form.phone} onChange={(v) => set('phone', v)} /></div></Section>
    <fieldset className="border border-slate-200 bg-white p-3"><legend className="px-1 text-sm font-semibold text-slate-500">Role Details</legend><div className="grid grid-cols-[470px_1fr] gap-8"><div className="space-y-3"><SelectField label="Company" value={role.company} onChange={(v) => setRole({ ...role, company: v })} options={['--- Select ---', 'Enterprise', 'Company']} /><SelectField label="Location" value={role.location} onChange={(v) => setRole({ ...role, location: v })} options={['--- Select ---', 'JX Karawaci', 'Demo CMS']} /><div className="grid grid-cols-[130px_1fr] items-start gap-3"><label className={label}>Role Desc</label><div><textarea className="h-32 w-full border border-slate-400 p-2 text-sm" value={role.description} onChange={(e) => setRole({ ...role, description: e.target.value })} /><div className="mt-2 flex gap-2"><button className={success} onClick={addRole}>↪ Add</button><button className={primary} onClick={() => set('roles', [])}>↩ Remove</button></div></div></div></div><Grid rows={form.roles.map((r, index) => ({ ...r, id: index, type: 'role' }))} columns={[{ key: 'company', label: 'Company' }, { key: 'location', label: 'Location' }, { key: 'description', label: 'Role Desc' }, { key: 'id', label: 'Role Id' }]} /></div></fieldset>
    {udf && <div className="fixed inset-0 z-[90] grid place-items-center bg-black/45"><div className="w-[440px] bg-white shadow-xl"><div className="bg-[#3b8fc4] px-3 py-2 text-sm font-semibold text-white">User Defined Field</div><div className="grid grid-cols-2 gap-3 p-4 text-sm"><Field label="UDF1" value="" onChange={() => {}} /><Field label="UDF2" value="" onChange={() => {}} /><Field label="UDF3" value="" onChange={() => {}} /><Field label="UDF4" value="" onChange={() => {}} /></div><div className="flex justify-end gap-2 p-3"><button className={primary} onClick={() => setUdf(false)}>Save</button><button className={neutral} onClick={() => setUdf(false)}>Close</button></div></div></div>}
    <Toast toast={toast} close={() => setToast(null)} /></>;
}

function Field({ label: text, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid grid-cols-[150px_1fr] items-center gap-3"><span className={label}>{text}</span><input className={input} type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function SelectField({ label: text, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="grid grid-cols-[150px_1fr] items-center gap-3"><span className={label}>{text}</span><select className={input} value={value} onChange={(e) => onChange(e.target.value)}>{options.map((option) => <option key={option} value={option === '--- Select ---' ? '' : option}>{option}</option>)}</select></label>; }

function Roles() {
  const [rows, setRows] = useState<Row[]>([]); const [form, setForm] = useState({ roleType: '', description: '', isActive: true }); const [tab, setTab] = useState<'roles' | 'process'>('roles'); const [toast, setToast] = useState<ToastState>(null);
  const load = () => apiGet<Row[]>('/api/admin?type=role').then(setRows).catch(() => setToast({ message: 'Unable to load roles', tone: 'error' })); useEffect(() => { void load(); }, []);
  const save = async () => { try { await apiSend('/api/admin', 'POST', { type: 'role', ...form, status: form.isActive ? 'Active' : 'Inactive' }); setForm({ roleType: '', description: '', isActive: true }); setToast({ message: 'Role saved successfully', tone: 'success' }); load(); } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Unable to save role', tone: 'error' }); } };
  return <><div className="mb-3 flex justify-end gap-2"><button className={primary} onClick={load}><Search size={16} />Search</button><button className={neutral}>✖ Reset</button><button className={success} onClick={save}>▣ Save</button><button className={neutral}>ℹ Audit</button><button className={neutral}><Plus size={15} /> Add New</button></div><div className="grid grid-cols-[1fr_1fr_1fr_auto] items-center gap-5 border border-slate-200 bg-white p-3"><span className="text-sm text-slate-600">Role Id</span><SelectField label="Role Type*" value={form.roleType} onChange={(v) => setForm({ ...form, roleType: v })} options={['--- Select ---', 'Enterprise', 'Company']} /><Field label="Description*" value={form.description} onChange={(v) => setForm({ ...form, description: v })} /><label className="flex items-center gap-2 text-sm">Is Active <input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} /></label></div><div className="mt-2 flex border-b border-slate-300"><button onClick={() => setTab('roles')} className={`border-b-2 px-4 py-2 font-semibold ${tab === 'roles' ? 'border-red-500 text-slate-800' : 'border-transparent text-slate-600'}`}>Roles</button><button onClick={() => setTab('process')} className={`border-b-2 px-4 py-2 font-semibold ${tab === 'process' ? 'border-red-500 text-slate-800' : 'border-transparent text-slate-600'}`}>Process Mapping</button></div>{tab === 'roles' ? <Grid rows={rows} columns={[{ key: 'id', label: 'Role Id', value: (r) => String(r.id).padStart(5, '0') }, { key: 'roleType', label: 'Role Type' }, { key: 'description', label: 'Description' }, { key: 'isActive', label: 'Is Active', value: (r) => r.isActive ? 'Yes' : 'No' }]} /> : <div className="border border-t-0 border-slate-200 bg-white p-8 text-center text-sm text-slate-500">Process mapping was selected in the recording; its mapped controls were not shown.</div>}<Toast toast={toast} close={() => setToast(null)} /></>;
}

function ImportScreen({ common }: { common: boolean }) {
  const [importType, setImportType] = useState(''); const [file, setFile] = useState<File | null>(null); const [tab, setTab] = useState('Import'); const [toast, setToast] = useState<ToastState>(null); const [rows, setRows] = useState<Row[]>([]);
  const load = () => apiGet<Row[]>('/api/admin?type=import').then((records) => setRows(records.filter((r) => r.importScreen === (common ? 'common' : 'order')))).catch(() => {});
  useEffect(() => { void apiGet<Row[]>('/api/admin?type=import').then((records) => setRows(records.filter((r) => r.importScreen === (common ? 'common' : 'order')))).catch(() => {}); }, [common]);
  const choose = (event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] || null);
  const doImport = async () => { if (!importType || !file) { setToast({ message: 'Import Type and Upload Template are Mandatory', tone: 'error' }); return; } try { await apiSend('/api/admin', 'POST', { type: 'import', importScreen: common ? 'common' : 'order', importType, fileName: file.name, status: 'Success' }); setToast({ message: 'Import submitted successfully', tone: 'success' }); setFile(null); load(); } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Import failed', tone: 'error' }); } };
  const choices = common ? ['--- Select ---', 'BulkReturnClose', 'Create_UpdateMerchHierarchy', 'POSTSUPDATE', 'BulkUnkit', 'Amazon_Order_Import', 'STOSTSUPDATE', 'ASNImport', 'B2B Sort Sequence', 'Channel Active/Inactive Import', 'Bulk Link Picker', 'NDR Import', 'PoImport', 'PoShortCloseImport', 'STOImport', 'Customer Master Import', 'PutawayImport', 'OrderImport'] : ['Normal Order Import'];
  return <><div className="mb-3 flex justify-end gap-2"><button className={primary} onClick={doImport}><Upload size={15} /> Import</button><button className={neutral} onClick={() => { setImportType(''); setFile(null); }}>✖ Reset</button><HelpCircle className="mt-2 text-[#287cc0]" size={24} /></div>{common && <div className="mb-2 flex border-b border-slate-300">{['Import', 'Download', 'File Detail'].map((name) => <button key={name} onClick={() => setTab(name)} className={`border-b-2 px-4 py-2 font-semibold ${tab === name ? 'border-red-500' : 'border-transparent'}`}>{name}</button>)}</div>}{tab === 'Import' && <><div className="rounded border border-slate-200 bg-white p-4"><div className="grid grid-cols-2 items-center gap-x-28 gap-y-4"><SelectField label="Import Type" value={importType} onChange={setImportType} options={choices} /><label className="grid grid-cols-[150px_1fr] items-center gap-3"><span className={label}>Upload Template</span><input type="file" onChange={choose} /></label>{!common && <><span className="text-right text-sm text-slate-600">Import Batch No</span><span className="text-sm italic font-semibold text-slate-600">**Note: Max 1000 rows can be imported in an attempt of Import.</span></>}</div>{!common && <div className="mt-4 text-center text-base font-bold italic text-red-600">Import Type &gt;Normal Order Import will be deprecated on 17th March 2026. Please use <span className="text-[#287cc0]">Common Import &gt; Order Import</span></div>}</div>{!common && <div className="mt-2 flex border-b border-slate-300"><button className="border-b-2 border-red-500 px-4 py-2 font-semibold">Success</button><button className="px-4 py-2 font-semibold">Failure</button></div>}<div className="mt-3"><Grid rows={rows} columns={common ? [{ key: 'importType', label: 'Import Type' }, { key: 'fileName', label: 'Import File Name' }, { key: 'status', label: 'Status' }] : [{ key: 'orderNo', label: 'Order No' }, { key: 'externalOrderNo', label: 'Extern OrderNo' }, { key: 'fileName', label: 'Import File Name' }, { key: 'importType', label: 'Import Type' }, { key: 'sku', label: 'SKU' }, { key: 'status', label: 'Status' }, { key: 'remarks', label: 'Remarks' }, { key: 'createdAt', label: 'Uploaded Date', value: (r) => r.createdAt ? new Date(r.createdAt).toLocaleString() : '' }]} /></div></>}{tab !== 'Import' && <div className="border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">{tab} is available as a navigation tab in the recording; no contents were demonstrated.</div>}<Toast toast={toast} close={() => setToast(null)} /></>;
}

function Exports() { return <><div className="mb-2 flex justify-end text-sm text-slate-600"><div>* Only last 20 reports generated can be downloaded.<br />* Force Pull option will be enabled after 300 seconds.</div></div><Grid rows={[]} columns={[{ key: 'id', label: 'Report ID' }, { key: 'status', label: 'Status' }, { key: 'requested', label: 'Report Request Date' }, { key: 'name', label: 'Report Names' }, { key: 'completed', label: 'Report Complete Date' }, { key: 'download', label: 'Download' }, { key: 'error', label: 'Error Msg' }]} /></>; }

function ForcePull() {
  const [location, setLocation] = useState(''); const [orders, setOrders] = useState(''); const [addWhHo, setAddWhHo] = useState(false); const [toast, setToast] = useState<ToastState>(null); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); try { await apiSend('/api/admin', 'POST', { action: 'force-pull', location, orders, addWhHo }); setToast({ message: 'Orders Pulled Successfully', tone: 'success' }); } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Unable to pull orders', tone: 'error' }); } finally { setSaving(false); } };
  return <><div className="mb-3 flex justify-end gap-2"><button className={primary} onClick={save} disabled={saving}>▣ {saving ? 'Saving...' : 'Save'}</button><button className={neutral} onClick={() => { setLocation(''); setOrders(''); setAddWhHo(false); }}>✖ Reset</button></div><div className="rounded border border-slate-200 bg-white px-10 py-5"><div className="mx-auto grid max-w-3xl grid-cols-[120px_440px_auto] items-center gap-x-4 gap-y-3"><label className={label}>Location</label><select className={input} value={location} onChange={(e) => setLocation(e.target.value)}><option value="">--- Select ---</option><option>QA11</option><option>QA12</option><option>Jeevacare Magento</option><option>Demo CMS</option></select><label className="flex items-center gap-3 text-sm">Add WH/HO <input type="checkbox" checked={addWhHo} onChange={(e) => setAddWhHo(e.target.checked)} /></label><label className={label}>Order Number</label><input className={input} value={orders} onChange={(e) => setOrders(e.target.value)} /><span /></div><p className="mt-5 text-center font-bold italic text-slate-700">(Enter comma separated order numbers if more than one order numbers, Max 20 order numbers are allowed)</p></div><Toast toast={toast} close={() => setToast(null)} /></>;
}

function ManageApi() {
  const [rows, setRows] = useState<Row[]>([]); const [editing, setEditing] = useState<Row | null>(null); const [toast, setToast] = useState<ToastState>(null);
  const load = () => apiGet<Row[]>('/api/admin?type=api-key').then(setRows).catch(() => setToast({ message: 'Unable to load API keys', tone: 'error' })); useEffect(() => { void load(); }, []);
  const add = () => setEditing({ id: 0, type: 'api-key', apiKey: crypto.randomUUID().replaceAll('-', ''), owner: '', timezone: '', billToParty: '', maskStatus: '', allowedIps: '', apiType: 'All', apiCategory: '', apiName: '', apiUrl: '', accessRights: false, keyForVinLister: false, status: 'Active', permissions: [] });
  const save = async () => { if (!editing) return; try { if (editing.id) await apiSend('/api/admin', 'PUT', editing); else await apiSend('/api/admin', 'POST', editing); setEditing(null); setToast({ message: 'API key saved successfully', tone: 'success' }); load(); } catch (e) { setToast({ message: e instanceof Error ? e.message : 'Unable to save API key', tone: 'error' }); } };
  if (editing) return <ApiEditor row={editing} setRow={setEditing} save={save} cancel={() => setEditing(null)} />;
  return <><div className="mb-3 flex justify-end gap-2"><button className={success} onClick={add}><Plus size={15} />Add</button><button className={neutral} onClick={load}><RefreshCw size={15} />Refresh</button><button className={neutral}>⚙ Register Webhook</button><HelpCircle className="mt-2 text-[#287cc0]" size={24} /></div><Grid rows={rows} columns={[{ key: 'apiKey', label: 'API Key' }, { key: 'owner', label: 'API Owner' }, { key: 'createdAt', label: 'Created Date', value: (r) => r.createdAt ? new Date(r.createdAt).toLocaleString() : '' }, { key: 'expiryDate', label: 'Expiry Date' }, { key: 'status', label: 'Status', value: (r) => <span className="inline-block bg-[#0aad56] px-4 py-0.5 text-white">{r.status || 'Active'}</span> }]} actions={(row) => <button onClick={() => setEditing(row)} className="text-[#ec9818]"><Pencil size={16} /></button>} /><Toast toast={toast} close={() => setToast(null)} /></>;
}

function ApiEditor({ row, setRow, save, cancel }: { row: Row; setRow: (row: Row) => void; save: () => void; cancel: () => void }) {
  const set = (key: string, value: any) => setRow({ ...row, [key]: value }); const permissions = (row.permissions || []) as Row[];
  return <><div className="mb-3 flex justify-end gap-2"><button className={primary} onClick={save}>Save</button><button className="inline-flex items-center gap-1.5 rounded bg-[#db2d3c] px-3 py-2 text-sm font-medium text-white" onClick={cancel}>⊗ Cancel</button></div><div className="space-y-2"><div className="grid grid-cols-2 gap-x-20 rounded border border-slate-200 bg-white p-4"><div className="space-y-3"><p className="text-sm"><b>API Key</b> {row.apiKey}</p><p className="text-sm"><b>API Owner</b> {row.owner || '—'}</p><SelectField label="Timezone" value={row.timezone || ''} onChange={(v) => set('timezone', v)} options={['--- Select ---', 'Asia/Kolkata', 'Asia/Jakarta']} /><Field label="isMonitor" value={row.isMonitor || ''} onChange={(v) => set('isMonitor', v)} /></div><div className="space-y-3"><SelectField label="Bill to Party" value={row.billToParty || ''} onChange={(v) => set('billToParty', v)} options={['--- Select ---', 'Enterprise', 'Company']} /><Field label="Mask Status" value={row.maskStatus || ''} onChange={(v) => set('maskStatus', v)} /><label className="grid grid-cols-[150px_1fr] items-start gap-3"><span className={label}>Allowed IPs</span><textarea className="h-14 w-full border border-slate-300 p-2 text-sm" value={row.allowedIps || ''} onChange={(e) => set('allowedIps', e.target.value)} /></label></div></div><div className="grid grid-cols-2 gap-x-20 rounded border border-slate-200 bg-white p-4"><div className="space-y-3"><SelectField label="API Type" value={row.apiType || 'All'} onChange={(v) => set('apiType', v)} options={['All', 'Inbound', 'Outbound']} /><SelectField label="API Name" value={row.apiName || ''} onChange={(v) => set('apiName', v)} options={['--- Select ---', 'Create Return', 'Order Cancellation', 'Order Create', 'Order Status Update', 'Return Update']} /><label className="ml-40 flex items-center gap-2 text-sm">Access Rights <input type="checkbox" checked={!!row.accessRights} onChange={(e) => set('accessRights', e.target.checked)} /></label></div><div className="space-y-3"><SelectField label="API Category" value={row.apiCategory || ''} onChange={(v) => set('apiCategory', v)} options={['--- Select ---', 'Order', 'Customer', 'Inventory']} /><Field label="API URL" value={row.apiUrl || ''} onChange={(v) => set('apiUrl', v)} /><label className="ml-40 flex items-center gap-2 text-sm">Key For Vin Lister <input type="checkbox" checked={!!row.keyForVinLister} onChange={(e) => set('keyForVinLister', e.target.checked)} /></label></div></div></div><Grid rows={permissions.map((permission, index) => ({ ...permission, id: index, type: 'permission' }))} columns={[{ key: 'name', label: 'API Name', value: (r) => r.name || row.apiName || '' }, { key: 'url', label: 'API URL', value: (r) => r.url || row.apiUrl || '' }, { key: 'rights', label: 'Access Rights', value: (r) => r.rights || (row.accessRights ? 'Yes' : 'No') }]} actions={() => <span className="text-[#ec9818]">✎ ▣</span>} /></>;
}

function ApiDashboard() {
  const [data, setData] = useState<any>(null); useEffect(() => { apiGet('/api/admin?action=dashboard').then(setData).catch(() => {}); }, []); const max = Math.max(...(data?.hits || [1]));
  return <div className="space-y-4"><div className="grid grid-cols-4 gap-3">{[['API Hit Status', '17', '#19a857'], ['Response Time', '65.51 ms', '#ed9a19'], ['Failure Count', '287', '#dd3e35'], ['Hit Count By Execution Time', '1,368', '#19a857']].map(([title, value, color]) => <div key={title} className="rounded border border-slate-200 bg-white p-3"><div className="text-xs text-slate-500">{title}</div><div className="mt-2 rounded p-2 text-xl font-bold text-white" style={{ background: color }}>{value}</div></div>)}</div><div className="grid grid-cols-[1fr_1fr_2fr] gap-4"><Donut title="Top APIs by Hits" values={data?.topApis || []} /><Donut title="Hits By Servers" values={[{ label: 'prd-set01-app01:web', value: 100 }]} single /><div className="rounded border border-slate-200 bg-white p-4"><h3 className="mb-4 font-semibold text-slate-600">Hits By Time</h3><div className="flex h-72 items-end gap-1 border-b border-l border-slate-300 px-5 pb-2">{(data?.hits || []).map((hit: number, index: number) => <div key={index} className="flex-1 bg-[#48b5e5]" style={{ height: `${(hit / max) * 100}%` }} title={`${hit} hits`} />)}</div></div></div></div>;
}
function Donut({ title, values, single = false }: { title: string; values: { label: string; value: number }[]; single?: boolean }) { const grad = single ? '#756087 0 100%' : '#51c0e4 0 78%, #f26a16 78% 94%, #e1248a 94% 97%, #8a957a 97% 100%'; return <div className="rounded border border-slate-200 bg-white p-4"><h3 className="mb-4 font-semibold text-slate-600">{title}</h3><div className="mx-auto grid h-64 w-64 place-items-center rounded-full" style={{ background: `conic-gradient(${grad})` }}><div className="h-32 w-32 rounded-full bg-white" /></div><div className="mt-3 text-center text-xs text-slate-500">{values.map((v) => v.label).join(' · ')}</div></div>; }

function Settings() { return <div className="rounded border border-slate-200 bg-white p-8 text-sm text-slate-600"><h2 className="mb-2 text-base font-semibold">Settings</h2><p>The recording opens this screen but does not show its loaded controls. No settings fields or save behavior have been inferred.</p></div>; }

export default function AdminModule() {
  const { screen = 'user-enquiry' } = useParams(); const navigate = useNavigate(); const meta = screenMeta[screen] || screenMeta['user-enquiry'];
  const content = screen === 'user-enquiry' ? <RecordedUserEnquiry /> : screen === 'audit-logs' ? <RecordedAuditLogs /> : screen === 'user-create-edit' ? <UserEditor /> : screen === 'role-create-edit' ? <Roles /> : screen === 'order-import' ? <ImportScreen common={false} /> : screen === 'common-import' ? <ImportScreen common /> : screen === 'exports' ? <Exports /> : screen === 'force-order-pull' ? <ForcePull /> : screen === 'manage-api' ? <RecordedManageApi /> : screen === 'api-dashboard' ? <ApiDashboard /> : <Settings />;
  return <Shell active="admin" breadcrumb={meta.crumb} openScreens={[{ label: meta.title, to: '#' }]}><div className="min-h-full text-[14px]">{content}</div></Shell>;
}
