import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Check, ChevronLeft, ChevronRight, Download, Pencil, Plus, Search, Settings, X } from 'lucide-react';
import { apiGet, apiSend } from '../../lib/api';

type Row = Record<string, unknown> & { id: number; type: string; version?: number };
type Message = { text: string; error?: boolean } | null;

const button = 'inline-flex h-10 items-center gap-2 rounded border border-slate-300 bg-white px-5 text-[15px] font-medium text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50';
const orange = `${button} border-[#dd9000] bg-[#e89a00] text-white hover:bg-[#d78e00]`;
const green = `${button} border-[#079748] bg-[#08a84f] text-white hover:bg-[#079748]`;
const cellInput = 'h-9 w-full border border-slate-300 bg-white px-2 text-sm outline-none focus:border-[#3b8fc4]';

function Notice({ value, close }: { value: Message; close: () => void }) {
  if (!value) return null;
  return <div className={`fixed right-5 top-[72px] z-[110] flex min-h-20 w-[500px] items-start justify-between border px-8 py-5 text-lg shadow ${value.error ? 'border-red-300 bg-red-50' : 'border-red-200 bg-[#fff4f4]'}`}><span>{value.text}</span><button aria-label="Close notification" onClick={close}><X size={18} /></button></div>;
}

function Spinner() {
  return <div className="absolute inset-0 z-10 grid place-items-center bg-[#e8e8e8]/80"><div className="h-8 w-8 animate-spin rounded-full border-4 border-[#269bd3] border-r-transparent" /></div>;
}

function Footer({ shown, total, page, pages }: { shown: number; total: number; page: number; pages: number }) {
  return <div className="flex h-10 items-center justify-between border-t border-slate-300 bg-[#e8e8f0] px-3 text-sm text-slate-600"><div /><div className="flex items-center gap-3"><button disabled={page <= 1}><ChevronLeft size={17} /></button><span>Page <b className="rounded bg-white px-4 py-1">{total ? page : 0}</b> of {total ? pages : 0}</span><button disabled={page >= pages}><ChevronRight size={17} /></button><select className="border border-slate-300 bg-white px-2 py-1" defaultValue="20"><option>20</option><option>50</option><option>100</option><option>200</option></select></div><span>{total ? `View 1 - ${shown} of ${total}` : 'No records to view'}</span></div>;
}

export function RecordedUserEnquiry() {
  const navigate = useNavigate();
  const empty = { userId: '', firstName: '', lastName: '', userStatus: '-1', email: '', userType: '1', role: '-1', company: '-1', location: '-1', clientIdList: '' };
  const [filter, setFilter] = useState(empty);
  const [meta, setMeta] = useState<any>({ statuses: [], userTypes: [], roles: [], companies: [], locations: [], pageSizes: [20, 50, 100, 200] });
  const [source, setSource] = useState<Row[]>([]);
  const [searched, setSearched] = useState(false);
  const [loading, setLoading] = useState(false);
  const [advanced, setAdvanced] = useState(false);
  const [message, setMessage] = useState<Message>(null);
  const [pager, setPager] = useState({ page: 1, total: 0, records: 0, size: 20 });
  useEffect(() => { void apiGet('/api/user-enquiry').then(setMeta).catch(() => setMessage({ text: 'Unable to load user search catalogs', error: true })); }, []);
  const search = async (page = 1, size = pager.size) => { setLoading(true); try { const response = await apiSend<any>('/api/user-enquiry', 'POST', { _search: true, rows: size, page, sidx: '', sord: 'asc', ...filter, REQ_SEARCH_FLAG: true }); setSource(response.userList || []); setPager({ page: response.page, total: response.total, records: response.records, size }); setSearched(true); } catch (error) { setMessage({ text: error instanceof Error ? error.message : 'Unable to load users', error: true }); } finally { setLoading(false); } };
  const reset = () => { setFilter(empty); setSource([]); setPager({ page: 1, total: 0, records: 0, size: 20 }); setSearched(false); setAdvanced(false); };
  const exportRows = async () => { try { await apiSend('/api/user-enquiry', 'POST', { action: 'export', gridDataLen: source.length }); } catch (error) { setMessage({ text: error instanceof Error ? error.message : 'No data found', error: true }); } };
  const headers = [['username', 'User Name'], ['firstName', 'First Name'], ['lastName', 'Last Name'], ['status', 'Status'], ['email', 'Email'], ['userType', 'User Type']] as const;
  const select = (key: keyof typeof empty, options: string[][]) => <select aria-label={key} className={cellInput} value={filter[key]} onChange={(e) => setFilter({ ...filter, [key]: e.target.value })}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>;
  return <div className="relative min-h-[calc(100vh-190px)] border border-slate-300 bg-[#e8e8e8]">
    <div className="flex justify-end gap-2 border-b border-slate-300 bg-white p-2"><button className={orange} onClick={() => void search()}><Search size={18} />Search</button><button className={button} onClick={reset}><X size={18} />Reset</button><button className={button} onClick={() => setAdvanced((v) => !v)}>Advance Search</button><button className={button} onClick={() => navigate('/app/admin/common-import?ExternalImportType=40')}>Import</button><button className={button} onClick={() => void exportRows()}><Download size={18} />Export</button><button className={button} onClick={() => navigate('/app/admin/user-create-edit')}><Plus size={18} />Add New</button></div>
    {advanced && <fieldset className="grid grid-cols-3 gap-3 border-b border-slate-300 bg-white p-3"><legend className="px-2 font-semibold text-slate-600">Advance Search</legend><label>Role{select('role', meta.roles)}</label><label>Company{select('company', meta.companies)}</label><label>Location{select('location', meta.locations)}</label><label>Email<input aria-label="email" className={cellInput} value={filter.email} onChange={(e) => setFilter({ ...filter, email: e.target.value })} /></label><label>Status{select('userStatus', meta.statuses)}</label><label>User Type{select('userType', meta.userTypes)}</label></fieldset>}
    <table className="w-full table-fixed border-collapse text-[15px]"><thead><tr className="bg-[#dddde5]">{headers.map(([, label]) => <th key={label} className="border-r border-slate-400 px-2 py-2">{label}</th>)}</tr><tr className="bg-[#eeeef3]">{headers.map(([key]) => <th key={key} className="border-r border-slate-300 p-1">{key === 'status' ? select('userStatus', meta.statuses) : key === 'userType' ? select('userType', meta.userTypes) : <div className="relative"><input aria-label={key} className={`${cellInput} pr-8`} value={filter[key === 'username' ? 'userId' : key]} onChange={(e) => setFilter({ ...filter, [key === 'username' ? 'userId' : key]: e.target.value })} /><Search className="absolute right-2 top-2 text-slate-500" size={17} /></div>}</th>)}</tr></thead>
      <tbody>{searched && source.map((row, index) => <tr key={row.id} className={index % 2 ? 'bg-[#e8e8f1]' : 'bg-white'}>{headers.map(([key]) => <td key={key} className="truncate px-2 py-2">{key === 'username' ? <button className="font-semibold text-[#287cc0]" onClick={() => navigate(`/app/admin/user-create-edit?userIdVal=${encodeURIComponent(String(row.username))}`)}>{String(row.username ?? '')}</button> : String(row[key] ?? '')}</td>)}</tr>)}</tbody></table>
    {!searched && <div className="absolute inset-x-0 top-44 grid place-items-center text-4xl font-black text-slate-500/25">eRETAIL</div>}
    <div className="absolute inset-x-0 bottom-0"><div className="flex h-10 items-center justify-between border-t border-slate-300 bg-[#e8e8f0] px-3 text-sm text-slate-600"><span /><span>Page <b>{searched ? pager.page : 0}</b> of {searched ? pager.total : 0} <select aria-label="Records per Page" value={pager.size} onChange={(e) => void search(1, Number(e.target.value))}>{meta.pageSizes.map((size: number) => <option key={size}>{size}</option>)}</select></span><span>{pager.records ? `View ${(pager.page - 1) * pager.size + 1} - ${Math.min(pager.page * pager.size, pager.records)} of ${pager.records}` : 'No records to view'}</span></div></div>
    {loading && <Spinner />}<Notice value={message} close={() => setMessage(null)} />
  </div>;
}

export function RecordedAuditLogs() {
  const empty = { date: '', processGroup: '', keyValue1: '', action: '', user: '', attribute: '' };
  const [filter, setFilter] = useState(empty); const [allRows, setRows] = useState<Row[]>([]); const [searched, setSearched] = useState(false); const [loading, setLoading] = useState(false);
  const search = async () => { setLoading(true); try { setRows(await apiGet<Row[]>('/api/admin?type=audit')); setSearched(true); } finally { setLoading(false); } };
  const rows = useMemo(() => allRows.filter((row) => Object.entries(filter).every(([key, value]) => !value || String(row[key] ?? '').toLowerCase().includes(value.toLowerCase()))), [filter, allRows]);
  const columns = [['date', 'Date'], ['processGroup', 'Process Group'], ['keyValue1', 'Key Value1'], ['keyValue2', 'Key Value2'], ['keyValue3', 'Key Value3'], ['action', 'Action'], ['user', 'User'], ['attribute', 'Attribute'], ['oldValue', 'Old Value'], ['newValue', 'New Value']] as const;
  return <div className="relative min-h-[calc(100vh-190px)] border border-slate-300 bg-[#e8e8e8]"><div className="flex justify-end gap-2 border-b border-slate-300 bg-white p-2"><button className={orange} onClick={search}><Search size={18} />Search</button><button className={button} onClick={() => { setFilter(empty); setRows([]); setSearched(false); }}>✖ Reset</button><button className={button}><Download size={18} />Export</button></div><div className="overflow-x-auto"><table className="min-w-[1500px] w-full table-fixed border-collapse text-[14px]"><thead><tr className="bg-[#dddde5]">{columns.map(([, label]) => <th key={label} className="border-r border-slate-400 px-2 py-2">{label}</th>)}</tr><tr className="bg-[#eeeef3]">{columns.map(([key]) => <th key={key} className="border-r border-slate-300 p-1">{['processGroup', 'action', 'attribute'].includes(key) ? <select className={cellInput} value={String(filter[key as keyof typeof filter] ?? '')} onChange={(e) => setFilter({ ...filter, [key]: e.target.value })}><option value="">--- Select ---</option>{key === 'processGroup' && <><option>Vendor Maintenance</option><option>SKU Maintenance</option></>}{key === 'action' && <><option>INSERT</option><option>UPDATE</option><option>DELETE</option></>}</select> : ['date', 'keyValue1', 'user'].includes(key) ? <div className="relative"><input className={`${cellInput} pr-8`} value={String(filter[key as keyof typeof filter] ?? '')} onChange={(e) => setFilter({ ...filter, [key]: e.target.value })} /><Search className="absolute right-2 top-2 text-slate-500" size={17} /></div> : null}</th>)}</tr></thead><tbody>{searched && rows.slice(0, 20).map((row, index) => <tr key={row.id} className={index % 2 ? 'bg-[#e8e8f1]' : 'bg-white'}>{columns.map(([key]) => <td key={key} className="truncate px-2 py-2">{String(row[key] ?? '')}</td>)}</tr>)}</tbody></table></div>{!searched && <div className="absolute inset-x-0 top-44 grid place-items-center text-4xl font-black text-slate-500/25">eRETAIL</div>}<div className="absolute inset-x-0 bottom-0"><Footer shown={Math.min(20, rows.length)} total={searched ? 390 : 0} page={1} pages={searched ? 20 : 0} /></div>{loading && <Spinner />}</div>;
}

const apiNames = ['Amazon Login Broken API', 'Amazon Login Fixed API', 'Bulk Order Create', 'Create ASN', 'Create Return', 'Customer Detail', 'Fetch Inventory', 'Fetch Inventory'];
const locations = ['1mg', 'A POS Store', 'amazon', 'Amazon FBA', 'Amazon Flex', 'Amazon Flex New', 'Amazon Flex_XSBH', 'Amazon Fulfilled', 'Amazon Warehouse', 'AMAZON3type', 'API_TEST'];

export function RecordedManageApi() {
  const [rows, setRows] = useState<Row[]>([]); const [editing, setEditing] = useState<Row | null>(null); const [message, setMessage] = useState<Message>(null); const [loading, setLoading] = useState(true); const [locationFor, setLocationFor] = useState<number | null>(null);
  const load = async () => { setLoading(true); try { setRows(await apiGet<Row[]>('/api/admin?type=api-key')); } catch { setMessage({ text: 'Unable to load API keys', error: true }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const activate = async (row: Row) => { if (row.status === 'Active') return; const updated = await apiSend<Row>('/api/admin', 'PUT', { ...row, status: 'Active' }); setRows((old) => old.map((item) => item.id === row.id ? updated : item)); setMessage({ text: 'Successfully Activated!' }); };
  const save = async () => { if (!editing) return; await apiSend('/api/admin', editing.id ? 'PUT' : 'POST', editing); setEditing(null); setMessage({ text: 'Successfully saved!' }); await load(); };
  const add = () => setEditing({ id: 0, type: 'api-key', owner: '', apiKey: crypto.randomUUID().replaceAll('-', ''), expiryDate: '', status: 'Active', permissions: apiNames.map((name) => ({ name, access: false, locations: [] })) });
  if (editing) {
    const permissions = (editing.permissions as Array<{ name: string; access: boolean; locations: string[] }> | undefined) ?? apiNames.map((name) => ({ name, access: false, locations: [] }));
    const updatePermission = (index: number, patch: Partial<(typeof permissions)[number]>) => setEditing({ ...editing, permissions: permissions.map((permission, i) => i === index ? { ...permission, ...patch } : permission) });
    const current = locationFor === null ? null : permissions[locationFor];
    return <div className="relative"><div className="mb-2 flex justify-end gap-2"><button className={orange} onClick={save}>Save</button><button className={`${button} border-red-500 bg-red-500 text-white`} onClick={() => setEditing(null)}>⊗ Cancel</button><button className={green}><Plus size={17} />Add</button></div><div className="mb-4 grid grid-cols-[180px_1fr_180px_3fr] bg-[#278eb8] text-center text-lg text-white"><b className="border-r border-white/50 p-3">API Owner</b><b className="border-r border-white/50 p-3">{String(editing.owner ?? '')}</b><b className="border-r border-white/50 p-3">API Key</b><b className="p-3">{String(editing.apiKey ?? '')}</b></div><table className="w-full border-collapse bg-white text-[16px]"><thead className="bg-[#278eb8] text-white"><tr><th className="p-3">API Name</th><th className="p-3">Access Rights</th><th className="p-3">Allowed Locations</th></tr></thead><tbody>{permissions.map((permission, index) => <tr key={`${permission.name}-${index}`} className="border-b border-slate-300"><td className="p-3 text-center">{permission.name}</td><td className="p-3 text-center"><input type="checkbox" checked={permission.access} onChange={(e) => updatePermission(index, { access: e.target.checked })} /></td><td className="p-3 text-center"><button aria-label={`Edit locations for ${permission.name}`} className="rounded border bg-white p-2 text-[#e89a00]" onClick={() => setLocationFor(index)}><Pencil size={16} /></button></td></tr>)}</tbody></table>{current && <LocationModal value={current.locations} onClose={() => setLocationFor(null)} onSave={(value) => { updatePermission(locationFor!, { locations: value }); setLocationFor(null); }} />}<Notice value={message} close={() => setMessage(null)} /></div>;
  }
  return <div className="relative min-h-[560px]"><div className="mb-10 flex justify-end"><button className={green} onClick={add}><Plus size={18} />Add</button></div><table className="w-full border-collapse bg-white text-[15px]"><thead className="bg-[#278eb8] text-white"><tr>{['API Key', 'API Owner', 'Created Date', 'Expiry Date', 'Status', 'Settings'].map((label) => <th className="border-r border-white/40 p-3 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-slate-300"><td className="p-3 text-center">{String(row.apiKey ?? '')}</td><td className="p-3 text-center">{String(row.owner ?? '')}</td><td className="p-3 text-center">{String(row.createdAt ?? '')}</td><td className="p-3 text-center">{String(row.expiryDate ?? '')}</td><td className="p-3 text-center"><button onClick={() => void activate(row)} className={row.status === 'Active' ? 'bg-[#10ad40] px-3 py-1 font-bold text-black' : 'border border-slate-400 bg-white px-3 py-1'}>{String(row.status ?? '')}</button></td><td className="p-3 text-center"><button aria-label={`Settings for ${String(row.owner)}`} className="text-[#18a6c7]" onClick={() => setEditing(row)}><Settings size={38} fill="currentColor" /></button></td></tr>)}</tbody></table>{loading && <Spinner />}<Notice value={message} close={() => setMessage(null)} /></div>;
}

function LocationModal({ value, onSave, onClose }: { value: string[]; onSave: (value: string[]) => void; onClose: () => void }) {
  const [linked, setLinked] = useState(value); const [selectedLeft, setSelectedLeft] = useState<string[]>([]); const [selectedRight, setSelectedRight] = useState<string[]>([]); const unlinked = locations.filter((location) => !linked.includes(location));
  return <div className="fixed inset-0 z-[120] grid place-items-center bg-black/50"><div className="w-[1020px] bg-white shadow-2xl"><div className="flex items-center justify-between bg-[#3b99c6] px-3 py-2 text-xl text-white"><b>Link To Store</b><button onClick={onClose}><X /></button></div><div className="grid grid-cols-[1fr_70px_1fr] gap-4 p-3"><LocationList title="Unlinked Location" rows={unlinked} selected={selectedLeft} setSelected={setSelectedLeft} /><div className="flex flex-col items-center justify-start gap-3 pt-12"><button className="rounded bg-[#08a84f] p-3 text-white" onClick={() => { setLinked([...linked, ...selectedLeft]); setSelectedLeft([]); }}>↪</button><button className="rounded bg-[#e89a00] p-3 text-white" onClick={() => { setLinked(linked.filter((item) => !selectedRight.includes(item))); setSelectedRight([]); }}>↩</button></div><LocationList title="Linked Location" rows={linked} selected={selectedRight} setSelected={setSelectedRight} /></div><div className="flex justify-end gap-2 p-4"><button className={orange} onClick={() => onSave(linked)}><Check size={18} />OK</button><button className={button} onClick={onClose}>✖ Close</button></div></div></div>;
}

function LocationList({ title, rows, selected, setSelected }: { title: string; rows: string[]; selected: string[]; setSelected: (rows: string[]) => void }) {
  return <div className="h-[500px] overflow-y-auto border border-slate-400"><div className="sticky top-0 bg-[#eeeef3] p-2 text-center text-lg font-bold">{title}</div>{rows.map((row) => <label key={row} className="flex gap-4 px-4 py-2 odd:bg-[#eeeeF4]"><input type="checkbox" checked={selected.includes(row)} onChange={(e) => setSelected(e.target.checked ? [...selected, row] : selected.filter((item) => item !== row))} />{row}</label>)}</div>;
}
