import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { apiGet, apiSend } from '../../lib/api';

type Pair = [string,string,boolean?];
type Role = {company:string;location:string;role:string;roleIdGrid:string;orgId:string};
const control='h-8 w-full border border-slate-300 bg-white px-2 text-sm';
const btn='rounded border border-slate-300 bg-white px-4 py-2 text-sm text-slate-700';
const orange=`${btn} border-[#db9100] bg-[#e89a00] text-white`;
const empty={userId:'',designation:'',title:'-1',firstName:'',middleName:'',lastName:'',dobStr:'',status:'1',userType:'1',purchaseOrderLimit:'',isMFA:false,address1:'',address2:'',address3:'',country:'-1',state:'-1',city:'',pincode:'',phone1:'',phone2:'',emailId1:'',emailId2:'',udf:['','','','',''],roles:[] as Role[]};

function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div role="dialog" aria-label={title} className="fixed inset-0 z-[120] grid place-items-center bg-black/45"><div className="w-[620px] bg-white shadow-xl"><div className="flex justify-between bg-[#3b99c6] px-4 py-2 text-white"><b>{title}</b><button aria-label="Close" onClick={close}>×</button></div>{children}</div></div>}
function Select({label,value,set,options,disabled=false,multiple=false}:{label:string;value:string|string[];set:(v:any)=>void;options:Pair[];disabled?:boolean;multiple?:boolean}){return <label className="grid grid-cols-[150px_1fr] items-center gap-3 text-sm"><span className="text-right text-slate-600">{label}</span><select aria-label={label.replace('*','').trim()} multiple={multiple} disabled={disabled} className={control} value={value} onChange={e=>set(multiple?[...e.currentTarget.selectedOptions].map(o=>o.value):e.target.value)}>{options.map(([v,t,d])=><option key={v} value={v} disabled={d}>{t}</option>)}</select></label>}
function Input({label,value,set,type='text',max}:{label:string;value:string;set:(v:string)=>void;type?:string;max?:number}){return <label className="grid grid-cols-[150px_1fr] items-center gap-3 text-sm"><span className="text-right text-slate-600">{label}</span><input aria-label={label.replace('*','').trim()} type={type} maxLength={max} className={control} value={value} onChange={e=>set(e.target.value)}/></label>}

export default function UserEditorReplica(){
 const [params]=useSearchParams(),userIdVal=params.get('userIdVal')||'';
 const [meta,setMeta]=useState<any>({titles:[],statuses:[],userTypes:[],companies:[],roles:[],countries:[],states:[],roleColumns:[]});
 const [form,setForm]=useState<any>(empty),[role,setRole]=useState({company:'-1',location:'-1',roleIds:[] as string[]}),[locations,setLocations]=useState<Pair[]>([['-1','--- Select ---']]);
 const [modal,setModal]=useState<'udf'|'audit'|'password'|null>(null),[notice,setNotice]=useState(''),[pwd,setPwd]=useState({one:'',two:''}),[strength,setStrength]=useState('Weak'),[saving,setSaving]=useState(false);
 const set=(key:string,value:any)=>setForm((old:any)=>({...old,[key]:value}));
 useEffect(()=>{void apiGet<any>('/api/user-editor').then(async m=>{setMeta(m);if(userIdVal){const x=await apiGet<any>(`/api/user-editor?userId=${encodeURIComponent(userIdVal)}`),r=x.row,statusMap:Record<string,string>={Active:'1',InActive:'0',Locked:'9'};setForm({...empty,...r,userId:r.username,emailId1:r.emailId1||r.email||'',status:r.statusId||(statusMap[String(r.status)]||'1'),userType:r.userTypeId||'1',udf:r.udf||empty.udf,roles:r.roles||[]})}}).catch(e=>setNotice(e.message))},[userIdVal]);
 const catalog=async(kind:string,value:string)=>{const x=await apiSend<any>('/api/user-editor','POST',{action:'catalog',kind,[kind==='states'?'country':'company']:value,userType:form.userType});if(kind==='states')setMeta((m:any)=>({...m,states:x.states}));else{setLocations(x.locations);setMeta((m:any)=>({...m,roles:x.roles}))}};
 const addRole=async()=>{try{const x=await apiSend<any>('/api/user-editor','POST',{action:'role-add',...role,locationName:locations.find(x=>x[0]===role.location)?.[1]||''});set('roles',[...form.roles,...x.roles]);setNotice('Role added successfully');}catch(e){setNotice(e instanceof Error?e.message:'Unable to add role')}};
 const save=async()=>{setSaving(true);try{const x=await apiSend<any>('/api/user-editor','POST',{action:'save',...form,state:form.state});setForm((f:any)=>({...f,...x.row,userId:x.row.username,emailId1:x.row.emailId1||x.row.email}));setNotice(x.message)}catch(e){setNotice(e instanceof Error?e.message:'Unable to save user')}finally{setSaving(false)}};
 const reset=()=>{setForm(empty);setRole({company:'-1',location:'-1',roleIds:[]});setNotice('')};
 const resetMfa=async()=>{try{const x=await apiSend<any>('/api/user-editor','POST',{action:'reset-mfa',userId:form.userId});setNotice(x.jsonMessage)}catch(e){setNotice(e instanceof Error?e.message:'Unable to reset MFA')}};
 const passwordStrength=(value:string)=>{let score=0;if(value&&!value.toLowerCase().includes(form.userId.toLowerCase()))score++;if(!/(?:012|123|234|345|456|567|678|789)/.test(value))score++;if(value.length>=8)score++;if(/[a-zA-Z]/.test(value))score++;if(/[0-9]/.test(value))score++;if(/[A-Z]/.test(value))score++;if(/[^a-zA-Z0-9]/.test(value))score++;setStrength(score<3?'Weak':score<7?'Medium':'Strong')};
 const changePassword=async()=>{if(!pwd.one){setNotice('Please enter password.');return}if(!pwd.two){setNotice('Type the new password again.');return}if(pwd.one!==pwd.two){setNotice('Password mismatch.');return}try{const x=await apiSend<any>('/api/user-editor','POST',{action:'change-password',userId:form.userId,password:pwd.one});setModal(null);setNotice(`Password reset successfully [${x.userId}].`)}catch(e){setNotice(e instanceof Error?e.message:'Unable to reset password')}};
 return <div className="min-h-[calc(100vh-190px)] border border-slate-300 bg-white text-sm">
  <div className="flex justify-end gap-2 border-b p-2"><button className={btn} onClick={()=>setModal('audit')}>Audit</button><button className={orange} onClick={()=>void save()} disabled={saving}>Save</button><button className={btn} disabled={!form.userId} onClick={()=>setModal('password')}>Reset Password</button>{form.userType==='1'&&<button className={btn} disabled={!form.userId} onClick={()=>void resetMfa()}>Reset MFA</button>}<button className={btn} onClick={reset}>Add New</button></div>
  {notice&&<div role="alert" className="m-2 border border-rose-300 bg-rose-50 p-3 text-rose-700">{notice}<button className="float-right" onClick={()=>setNotice('')}>×</button></div>}
  <fieldset className="m-2 border p-3"><legend className="px-2 font-semibold">User Details</legend><div className="grid grid-cols-3 gap-x-8 gap-y-2"><Input label="User Name*" max={10} value={form.userId} set={v=>set('userId',v)}/><Input label="Designation" max={50} value={form.designation} set={v=>set('designation',v)}/><Select label="Title*" value={form.title} set={v=>set('title',v)} options={meta.titles}/><Input label="First Name*" max={50} value={form.firstName} set={v=>set('firstName',v)}/><Input label="Middle Name" max={50} value={form.middleName} set={v=>set('middleName',v)}/><Input label="Last Name*" max={50} value={form.lastName} set={v=>set('lastName',v)}/><Input label="Date Of Birth" type="date" value={form.dobStr} set={v=>set('dobStr',v)}/><Select label="Status" value={form.status} set={v=>set('status',v)} options={meta.statuses}/><Select label="User Type*" value={form.userType} set={v=>set('userType',v)} options={meta.userTypes}/><Input label="Purchase Order Limit" value={form.purchaseOrderLimit} set={v=>set('purchaseOrderLimit',v)}/>{form.userType==='1'&&<label className="flex items-center justify-end gap-3 text-slate-600">Enable Multifactor Authentication<input aria-label="Enable Multifactor Authentication" type="checkbox" checked={form.isMFA} onChange={e=>set('isMFA',e.target.checked)}/></label>}<button className="text-left font-semibold text-[#287cc0]" onClick={()=>setModal('udf')}>View/Update UDF</button></div></fieldset>
  <fieldset className="m-2 border p-3"><legend className="px-2 font-semibold">Contact Details</legend><div className="grid grid-cols-3 gap-x-8 gap-y-2"><Input label="Address 1*" value={form.address1} set={v=>set('address1',v)}/><Input label="Address 2" value={form.address2} set={v=>set('address2',v)}/><Input label="Address 3" value={form.address3} set={v=>set('address3',v)}/><Select label="Country*" value={form.country} set={v=>{set('country',v);set('state','-1');void catalog('states',v)}} options={meta.countries}/><Select label="State*" value={form.state} set={v=>set('state',v)} options={meta.states}/><Input label="City*" value={form.city} set={v=>set('city',v)}/><Input label="PinCode" value={form.pincode} set={v=>set('pincode',v)}/><Input label="Phone*" value={form.phone1} set={v=>set('phone1',v)}/><Input label="Alternate Phone" value={form.phone2} set={v=>set('phone2',v)}/><Input label="Email*" type="email" value={form.emailId1} set={v=>set('emailId1',v)}/><Input label="Alternate Email" type="email" value={form.emailId2} set={v=>set('emailId2',v)}/></div></fieldset>
  <fieldset className="m-2 border p-3"><legend className="px-2 font-semibold">Role Details</legend><div className="grid grid-cols-[430px_1fr] gap-8"><div className="space-y-2"><Select label="Company" value={role.company} set={v=>{setRole(r=>({...r,company:v,location:'-1'}));void catalog('roles',v)}} options={meta.companies}/><Select label="Location" value={role.location} set={v=>setRole(r=>({...r,location:v}))} options={locations} disabled={role.company==='**'}/><Select label="Role Desc" value={role.roleIds} set={v=>setRole(r=>({...r,roleIds:v}))} options={meta.roles} multiple/><div className="flex justify-end gap-2"><button className={`${btn} bg-[#08a84f] text-white`} onClick={()=>void addRole()}>Add</button><button className={orange} onClick={()=>set('roles',form.roles.filter((_:Role,i:number)=>i!==form.selectedRole))}>Remove</button></div></div><table className="w-full border-collapse"><thead className="bg-[#e8e8f0]"><tr>{meta.roleColumns.map((h:string)=><th className="border p-2" key={h}>{h}</th>)}</tr></thead><tbody>{form.roles.map((r:Role,i:number)=><tr key={`${r.roleIdGrid}-${i}`} onClick={()=>set('selectedRole',i)} className={form.selectedRole===i?'bg-sky-100':''}><td className="border p-2">{r.company}</td><td className="border p-2">{r.location}</td><td className="border p-2">{r.role}</td><td className="border p-2">{r.roleIdGrid}</td></tr>)}</tbody></table></div></fieldset>
  {modal==='udf'&&<Modal title="User Defined Field" close={()=>setModal(null)}><div className="grid grid-cols-2 gap-3 p-4">{form.udf.map((v:string,i:number)=><Input key={i} label={`UDF${i+1}`} value={v} set={x=>set('udf',form.udf.map((a:string,n:number)=>n===i?x:a))}/>)}</div><div className="flex justify-end gap-2 p-3"><button className={orange} onClick={()=>setModal(null)}>Save</button><button className={btn} onClick={()=>setModal(null)}>Close</button></div></Modal>}
  {modal==='audit'&&<Modal title="Audit" close={()=>setModal(null)}><div className="grid grid-cols-2 gap-4 p-5">{[['Created By',form.createdBy],['Created Date',form.createdAt],['Modified By',form.modifiedBy],['Modified Date',form.updatedAt]].map(([l,v])=><div key={l}><b>{l}</b><div>{v||''}</div></div>)}</div></Modal>}
  {modal==='password'&&<Modal title="Reset Password" close={()=>setModal(null)}><div className="space-y-3 p-5"><Input label="Type new Password" type="password" value={pwd.one} set={v=>{setPwd({...pwd,one:v});passwordStrength(v)}}/><div className={`h-2 ${strength==='Weak'?'w-1/3 bg-red-500':strength==='Medium'?'w-2/3 bg-orange-500':'w-full bg-green-500'}`}/><div>{strength}</div><Input label="Type the new password again" type="password" value={pwd.two} set={v=>setPwd({...pwd,two:v})}/></div><div className="flex justify-end gap-2 p-3"><button className={orange} onClick={()=>void changePassword()}>Reset Password</button><button className={btn} onClick={()=>setModal(null)}>Close</button></div></Modal>}
 </div>
}
