/* eslint-disable @typescript-eslint/no-explicit-any */
import {useEffect,useMemo,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import Shell from '../Shell';
import {Btn,Toast} from '../parts';
import {apiGet,apiSend} from '../../lib/api';

const fresh=()=>({rtv_source:'-1',po_no:'',grn_no:'',remarks:'',site_location:'UWH',return_type:'10',vendor_code:'',vendor_name:'',ext_rtv_no:'',order_processing:'0',status:'',lines:[] as any[],udf:Array(10).fill(''),shipping:[] as any[],comments:[] as any[],attachments:[] as any[],tags:[] as string[],eway_bill:{} as any});
const tabs=['Vendor Details','User Defined Fields','Shipment Details','Activity and Remarks','Import'];
const more=['Attachments','RTV Tags','E-Way Bill'];
function Field({label,children}:any){return <label className="text-xs text-slate-600">{label}<div className="mt-1">{children}</div></label>}
function Pick({title,rows,close,pick}:any){const[q,setQ]=useState('');const shown=rows.filter((x:any)=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40"><div role="dialog" aria-label={title} className="w-[760px] max-w-[94vw] bg-white"><h3 className="bg-sky-700 p-3 font-semibold text-white">{title}</h3><div className="flex gap-2 p-3"><input aria-label={`${title} Search`} className="inp" value={q} onChange={e=>setQ(e.target.value)}/><Btn>Search</Btn><Btn variant="ghost" onClick={()=>setQ('')}>Reset</Btn></div><div className="max-h-80 overflow-auto border-y">{shown.map((x:any)=><button className="block w-full border-b p-2 text-left text-sm hover:bg-sky-50" key={x.id} onClick={()=>pick(x)}>{x.po_no||x.grn_no||x.vendor_code||x.sku_code} — {x.vendor_name||x.vendor||x.name||x.sku_name||''}</button>)}</div><div className="flex justify-end p-3"><Btn variant="ghost" onClick={close}>Close</Btn></div></div></div>}

export default function VendorReturnEditor(){const nav=useNavigate(),[sp]=useSearchParams(),id=Number(sp.get('id')||0);const[meta,setMeta]=useState<any>({}),[f,setF]=useState<any>(fresh),[tab,setTab]=useState('Vendor Details'),[drop,setDrop]=useState(false),[pick,setPick]=useState<string|null>(null),[selected,setSelected]=useState<number[]>([]),[toast,setToast]=useState<any>(null),[comment,setComment]=useState(''),[importText,setImportText]=useState(''),[tagInput,setTagInput]=useState(''),[attachment,setAttachment]=useState({doc_type:'-1',delivery_no:'',file_name:''});
useEffect(()=>{apiGet('/api/vendor-return-editor').then(setMeta);if(id)apiGet(`/api/vendor-return-editor?id=${id}`).then(setF).catch((e:any)=>setToast({msg:e.message,type:'err'}))},[id]);
const set=(p:any)=>setF((x:any)=>({...x,...p}));const source=f.rtv_source;const total=useMemo(()=>f.lines.reduce((s:number,x:any)=>s+Number(x.qty||0)*Number(x.base_cost||0),0),[f.lines]);
async function save(action='save'){try{if(action==='confirm'&&!confirm('Do you really want to confirm?'))return;const r:any=await apiSend('/api/vendor-return-editor',id?'PUT':'POST',{...f,id:f.id||id,action,return_type_label:(meta.returnTypes||[]).find((x:any)=>x[0]===f.return_type)?.[1]});setF(r);setToast({msg:action==='confirm'?'RTV confirmed successfully':`RTV ${r.rtv_no} saved`,type:'ok'});if(!id)nav(`/app/returns/vendor-return?id=${r.id}`,{replace:true})}catch(e:any){setToast({msg:e.message,type:'err'})}}
function choose(kind:string,x:any){if(kind==='vendor')set({vendor_code:x.vendor_code,vendor_name:x.vendor_name});if(kind==='po'){const v=(meta.vendors||[]).find((a:any)=>a.vendor_name===x.vendor);set({po_no:x.po_no,vendor_code:v?.vendor_code||'',vendor_name:x.vendor||''})}if(kind==='grn')set({grn_no:x.grn_no||x.code||''});if(kind==='sku'&&!f.lines.some((a:any)=>a.sku_code===x.sku_code))set({lines:[...f.lines,{sku_code:x.sku_code,sku_name:x.name||x.sku_name||'',base_cost:Number(x.cost||0),qty:1,reason:''}]});setPick(null)}
async function commentSave(){try{const r:any=await apiSend('/api/vendor-return-editor','POST',{action:'comment',id:f.id,comment});setF(r);setComment('')}catch(e:any){setToast({msg:e.message,type:'err'})}}
async function attachmentSave(){try{const r:any=await apiSend('/api/vendor-return-editor','POST',{action:'attachment',id:f.id,...attachment});setF(r);setAttachment({doc_type:'-1',delivery_no:'',file_name:''})}catch(e:any){setToast({msg:e.message,type:'err'})}}
async function tagsSave(){try{const r:any=await apiSend('/api/vendor-return-editor','POST',{action:'tags',id:f.id,tags:f.tags});setF(r);setToast({msg:'RTV Tags saved successfully',type:'ok'})}catch(e:any){setToast({msg:e.message,type:'err'})}}
function importLines(){if(!importText.trim()){setToast({msg:'No file chosen to import.',type:'err'});return}const lines=importText.split(/\r?\n/).filter(Boolean).map(s=>{const[a,b]=s.split(',');const item=(meta.inventory||[]).find((x:any)=>x.sku_code===a.trim());return{sku_code:a.trim(),sku_name:item?.name||'',qty:Number(b),base_cost:Number(item?.cost||0),reason:''}});if(lines.length>2000||lines.some(x=>!x.sku_code||x.qty<=0)){setToast({msg:'Please upload valid SKU and quantity data',type:'err'});return}set({lines});setToast({msg:`Imported ${lines.length} SKU line(s)`,type:'ok'})}
const Input=(p:any)=><input className="inp" {...p}/>;const Select=({value,onChange,options,label}:any)=><select aria-label={label} className="inp" value={value} onChange={onChange}>{options?.map((x:any)=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select>;
return <Shell active="returns" breadcrumb="RETURNS & TRANSFERS > Vendor Return Create/Edit" openScreens={[{label:'Vendor Return Create/Edit',to:'#'}]}><div className="border bg-white"><div className="relative flex justify-end gap-2 border-b p-3"><Btn variant="ghost" onClick={()=>{setF(fresh());nav('/app/returns/vendor-return')}}>Add New</Btn>{tab==='Import'?<><Btn onClick={importLines}>Import</Btn><Btn variant="ghost" onClick={()=>setImportText('')}>Reset</Btn></>:<><Btn variant="warn" onClick={()=>void save()}>Save</Btn><Btn onClick={()=>void save('confirm')} disabled={!f.id}>Confirm</Btn></>}<Btn variant="ghost" onClick={()=>setDrop(!drop)}>Toggle Dropdown</Btn>{drop&&<div className="absolute right-3 top-12 z-20 w-52 border bg-white shadow">{more.map(x=><button className="block w-full p-2 text-left text-sm hover:bg-slate-50" onClick={()=>{setTab(x);setDrop(false)}} key={x}>{x}</button>)}</div>}</div><div className="flex flex-wrap border-b bg-slate-50">{tabs.map(x=><button className={`px-4 py-3 text-sm ${tab===x?'border-b-2 border-rose-400 bg-white':''}`} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
{tab==='Vendor Details'&&<div className="p-4"><div className="grid gap-3 md:grid-cols-3"><Field label="RTV Source*"><Select label="RTV Source" value={source} options={meta.sources} onChange={(e:any)=>set({rtv_source:e.target.value,po_no:'',grn_no:'',lines:[]})}/></Field>{source==='1'&&<Field label="PO Code*"><div className="flex"><Input aria-label="PO Code" readOnly value={f.po_no}/><button className="border px-3" onClick={()=>setPick('po')}>...</button></div></Field>}{source==='3'&&<Field label="GRN No."><div className="flex"><Input aria-label="GRN No." readOnly value={f.grn_no}/><button className="border px-3" onClick={()=>setPick('grn')}>...</button></div></Field>}<Field label="Remarks"><textarea aria-label="Remarks" className="inp h-16" value={f.remarks} onChange={e=>set({remarks:e.target.value})}/></Field><Field label="Site Location"><Select label="Site Location" value={f.site_location} options={meta.locations} onChange={(e:any)=>set({site_location:e.target.value})}/></Field><Field label="Return Type"><Select label="Return Type" value={f.return_type} options={meta.returnTypes} onChange={(e:any)=>set({return_type:e.target.value})}/></Field><Field label="Vendor Code"><div className="flex"><Input aria-label="Vendor Code" value={f.vendor_code} onChange={(e:any)=>set({vendor_code:e.target.value})}/><button className="border px-3" onClick={()=>setPick('vendor')}>...</button></div></Field><Field label="Vendor Name"><Input aria-label="Vendor Name" value={f.vendor_name} readOnly/></Field><Field label="Extern RTV No"><Input aria-label="Extern RTV No" value={f.ext_rtv_no} onChange={(e:any)=>set({ext_rtv_no:e.target.value})}/></Field><Field label="Order Processing"><Select label="Order Processing" value={f.order_processing} options={meta.processing} onChange={(e:any)=>set({order_processing:e.target.value})}/></Field><Field label="Status"><Input aria-label="Status" value={f.status||''} readOnly/></Field></div><div className="my-4 flex justify-end gap-2"><Btn onClick={()=>setPick('sku')}>Add SKU</Btn><Btn variant="ghost" onClick={()=>set({lines:f.lines.filter((_:any,i:number)=>!selected.includes(i))})}>Remove SKU</Btn><Btn variant="ghost" onClick={()=>setTab('Import')}>Import</Btn><Btn variant="ghost" disabled={!['1','3'].includes(source)}>Edit Return Qty</Btn></div><LineTable lines={f.lines} selected={selected} setSelected={setSelected} update={(i:number,p:any)=>set({lines:f.lines.map((x:any,j:number)=>j===i?{...x,...p}:x)})}/><div className="mt-4 grid grid-cols-2 gap-2 text-sm md:grid-cols-4"><b>RTV No: {f.rtv_no||''}</b><b>RTV Amount: {total.toFixed(2)}</b><b>RTV Quantity: {f.lines.reduce((s:number,x:any)=>s+Number(x.qty||0),0)}</b><b>Hold: {f.on_hold?'Yes':'No'}</b></div></div>}
{tab==='User Defined Fields'&&<div className="grid gap-3 p-4 md:grid-cols-2">{f.udf.map((x:string,i:number)=><Field label={`UDF${i+1}`} key={i}><Input aria-label={`UDF${i+1}`} value={x} onChange={(e:any)=>{const udf=[...f.udf];udf[i]=e.target.value;set({udf})}}/></Field>)}</div>}
{tab==='Shipment Details'&&<div className="p-4"><div className="mb-3 grid grid-cols-3"><b>PO Code: {f.po_no}</b><b>GRN No.: {f.grn_no}</b><b>RTV No.: {f.rtv_no}</b></div><Simple heads={['Delivery No','Invoice No','Invoice Date','Status']} rows={f.shipping||[]}/></div>}
{tab==='Activity and Remarks'&&<div className="p-4"><div className="flex gap-2"><textarea aria-label="Add Comments" className="inp h-20" value={comment} onChange={e=>setComment(e.target.value)}/><Btn onClick={()=>void commentSave()} disabled={!f.id}>Submit Comments</Btn></div><Simple heads={['Date','AddedBy','Status','Comments']} rows={(f.comments||[]).map((x:any)=>[x.date,x.added_by,x.status,x.comment])}/></div>}
{tab==='Import'&&<div className="p-4"><p className="mb-2 text-sm">Import Batch No</p><Btn variant="ghost">Download Template</Btn><p className="my-3 text-xs">Maximum 2000 lines are allowed at a time</p><textarea aria-label="Upload Template" className="inp h-48 font-mono" placeholder="SKU,Qty" value={importText} onChange={e=>setImportText(e.target.value)}/><Simple heads={['SKU Code','Quantity','Status']} rows={[]}/></div>}
{tab==='Attachments'&&<div className="p-4"><div className="grid gap-3 md:grid-cols-3"><Field label="Document Type*"><Select label="Document Type" value={attachment.doc_type} options={meta.documentTypes} onChange={(e:any)=>setAttachment({...attachment,doc_type:e.target.value})}/></Field><Field label="Delivery No"><Input aria-label="Delivery No" value={attachment.delivery_no} onChange={(e:any)=>setAttachment({...attachment,delivery_no:e.target.value})}/></Field><Field label="Attachment*"><Input aria-label="Attachment" type="file" onChange={(e:any)=>setAttachment({...attachment,file_name:e.target.files?.[0]?.name||''})}/></Field></div><div className="my-3 flex gap-2"><Btn onClick={()=>void attachmentSave()}>Save</Btn><Btn variant="ghost" onClick={()=>setAttachment({doc_type:'-1',delivery_no:'',file_name:''})}>Reset</Btn><Btn variant="ghost" onClick={async()=>{try{const r:any=await apiSend('/api/vendor-return-editor','POST',{action:'delete-attachments',id:f.id,indexes:selected});setF(r);setSelected([]);setToast({msg:r.jsonMessage,type:'ok'})}catch(e:any){setToast({msg:e.message,type:'err'})}}}>Delete</Btn></div><Simple heads={['Document Name','Document Type','Delivery No','Download']} rows={(f.attachments||[]).map((x:any)=>[x.document_name,x.document_type,x.delivery_no,'Download'])}/></div>}
{tab==='RTV Tags'&&<div className="p-4"><Field label="RTV Tags"><Input aria-label="RTV Tags" value={tagInput} onChange={(e:any)=>setTagInput(e.target.value)}/></Field><div className="my-3 flex gap-2"><Btn onClick={()=>{if(!tagInput.trim()){setToast({msg:'Please select RTV Tags',type:'err'});return}set({tags:[...new Set([...(f.tags||[]),tagInput.trim()])]});setTagInput('')}}>Add Tags</Btn><Btn onClick={()=>void tagsSave()}>Save Tags</Btn><Btn variant="ghost" onClick={()=>set({tags:[]})}>Remove Tags</Btn></div><Simple heads={['RTV Tag','Status','Tag Date','Tagged By']} rows={(f.tags||[]).map((x:string)=>[x,f.status||'Created','', 'sa'])}/></div>}
{tab==='E-Way Bill'&&<Eway f={f} meta={meta} save={async(eway_bill:any)=>{try{const r:any=await apiSend('/api/vendor-return-editor','POST',{action:'eway-save',id:f.id,eway_bill});setF(r);setToast({msg:'Eway Bill Number saved successfully.',type:'ok'})}catch(e:any){setToast({msg:e.message,type:'err'})}}}/>}</div>{pick&&<Pick title={pick==='po'?'PO Pick List':pick==='grn'?'GRN Picklist':pick==='vendor'?'Select Vendor':'ADD SKUs'} rows={pick==='po'?meta.purchaseOrders||[]:pick==='grn'?meta.grns||[]:pick==='vendor'?meta.vendors||[]:meta.inventory||[]} close={()=>setPick(null)} pick={(x:any)=>choose(pick,x)}/>} {toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</Shell>}
function LineTable({lines,selected,setSelected,update}:any){return <div className="overflow-auto border"><table className="w-full text-xs"><thead><tr>{['','SKU Code','SKU','Base Cost','RTV Qty','Reason'].map(x=><th className="border p-2" key={x}>{x}</th>)}</tr></thead><tbody>{lines.map((x:any,i:number)=><tr key={i}><td className="border p-2"><input type="checkbox" checked={selected.includes(i)} onChange={e=>setSelected(e.target.checked?[...selected,i]:selected.filter((n:number)=>n!==i))}/></td><td className="border p-2">{x.sku_code}</td><td className="border p-2">{x.sku_name}</td><td className="border p-2">{Number(x.base_cost||0).toFixed(2)}</td><td className="border p-2"><input aria-label={`RTV Qty ${i+1}`} type="number" min="0" className="w-20 border p-1" value={x.qty} onChange={e=>update(i,{qty:Number(e.target.value)})}/></td><td className="border p-2"><input className="border p-1" value={x.reason||''} onChange={e=>update(i,{reason:e.target.value})}/></td></tr>)}</tbody></table>{!lines.length&&<div className="p-12 text-center text-slate-400">No records to view</div>}</div>}
function Simple({heads,rows}:any){return <table className="mt-4 w-full text-xs"><thead><tr>{heads.map((h:string)=><th className="border p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}>{(Array.isArray(r)?r:heads.map((h:string)=>r[h])).map((x:any,j:number)=><td className="border p-2" key={j}>{x}</td>)}</tr>)}</tbody></table>}
function Eway({f,meta,save}:any){const[e,setE]=useState<any>(f.eway_bill||{document_type:'9',sub_type:'13',sub_supply_desc:'',trans_mode:'1',vehicle_no:'',distance:'',eway_no:'',valid_upto:'',vehicle_size:'10',adhoc_reason:'1',device_id:'',crate_count:''});const I=({l,k}:any)=><Field label={l}><input aria-label={l} className="inp" value={e[k]||''} onChange={x=>setE({...e,[k]:x.target.value})}/></Field>;return <div className="p-4"><h3 className="mb-3 font-semibold">Part-A</h3><div className="grid gap-3 md:grid-cols-3"><I l="Invoice No" k="invoice_no"/><Field label="Document Type*"><select aria-label="E-Way Document Type" className="inp"><option value="9">OTHERS</option></select></Field><Field label="Sub Type*"><select aria-label="Sub Type" className="inp"><option value="13">OTHERS</option></select></Field><I l="Sub Supply Desc" k="sub_supply_desc"/><I l="Transporter Name" k="transporter_name"/><I l="Transporter GSTIN/CIN" k="transporter_gstin"/><Field label="Vehicle Size"><select aria-label="Vehicle Size" className="inp"><option value="-1">--- Select ---</option><option value="10">14ft dry</option></select></Field><Field label="Adhoc Reason"><select aria-label="Adhoc Reason" className="inp"><option value="-1">--- Select ---</option><option value="1">Scheduled/Regular vehicle</option></select></Field><I l="Device ID" k="device_id"/><I l="Crate Count" k="crate_count"/><I l="IRN" k="irn"/></div><h3 className="my-3 font-semibold">Part-B</h3><div className="grid gap-3 md:grid-cols-3"><Field label="Mode of Transport"><select aria-label="Mode of Transport" className="inp" value={e.trans_mode} onChange={x=>setE({...e,trans_mode:x.target.value})}>{(meta.transportModes||[]).map((x:any)=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></Field><I l="Vehicle No.*" k="vehicle_no"/><I l="Distance*" k="distance"/><I l="E-Way Bill Number" k="eway_no"/><I l="Valid Upto" k="valid_upto"/><I l="CEWB No" k="cewb_no"/></div><div className="mt-4 flex flex-wrap gap-2">{['Edit','Back','Extend E-way Bill Validity','Save Eway Bill','Generate E-way Bill','Print','Update','Cancel'].map(x=><Btn key={x} variant={x==='Save Eway Bill'?'warn':'ghost'} onClick={()=>x==='Save Eway Bill'&&save(e)}>{x}</Btn>)}</div><Simple heads={['HSN Code','Taxable Value','Tax Rate','CESS']} rows={[]}/></div>}
