import { useEffect, useState } from 'react';
import { apiGet, apiSend } from '../lib/api';
import PageHeader from '../components/PageHeader';

const titles: Record<string,string> = { 'inv-move':'Inventory Move', 'inv-move-scan':'Inventory Move By Scan', 'inv-move-history':'Inventory Move History', 'intercompany-move':'Intercompany Move', 'bulk-lottables':'Bulk update Lottables', 'stock-adjustment':'Stock Adjustment', 'outbound-gate-pass':'Outbound Gate Pass', 'outbound-memo':'Manage Outbound Memo', 'sku-transaction-history':'SKU Transaction History', 'sku-lot-transfer':'Manage SKU Lot Transfer' };
const cls='inp w-full';
export default function InventoryOperations({ operation }: { operation:string }) {
  const [rows,setRows]=useState<any[]>([]); const [inventory,setInventory]=useState<any[]>([]); const [form,setForm]=useState<any>({sku_code:'',from_warehouse:'Delhi NCR',to_warehouse:'Mumbai WH',quantity:'',reason:'',reference:''}); const [message,setMessage]=useState('');
  const title=titles[operation]||operation; const load=()=>{apiGet<any[]>(`/api/inventory-ops?entity=${operation==='inv-move-history'?'history':operation}`).then(setRows);apiGet<any[]>('/api/inventory').then(setInventory)};
  useEffect(()=>{load()},[operation]);
  const submit=async()=>{try{const entity=operation==='stock-adjustment'?'adjustments':operation==='inv-move-history'?'moves':operation;const payload=entity==='adjustments'?{entity,inventory_id:form.inventory_id,quantity:form.quantity,reason:form.reason}:{entity,...form};await apiSend('/api/inventory-ops','POST',payload);setMessage(`${title} completed successfully.`);setForm({...form,quantity:'',reason:'',reference:''});load()}catch(e:any){setMessage(e.message)}};
  const move=['inv-move','inv-move-scan','intercompany-move'].includes(operation); const adjust=operation==='stock-adjustment';
  return <div><PageHeader title={title} breadcrumb={`WMS / ${title}`} actions={<button onClick={load} className="rounded border bg-white px-3 py-2 text-sm">Refresh</button>}/>{(move||adjust||!['inv-move-history'].includes(operation))&&<div className="mb-4 rounded border bg-white p-4"><div className="grid gap-3 md:grid-cols-4">{adjust?<select className={cls} value={form.inventory_id||''} onChange={e=>setForm({...form,inventory_id:e.target.value})}><option value="">Select inventory record</option>{inventory.map(r=><option key={r.id} value={r.id}>{r.sku_code} — {r.warehouse} ({r.available})</option>)}</select>:<input className={cls} placeholder="SKU Code" value={form.sku_code} onChange={e=>setForm({...form,sku_code:e.target.value})}/>} {move&&<><select className={cls} value={form.from_warehouse} onChange={e=>setForm({...form,from_warehouse:e.target.value})}><option>Delhi NCR</option><option>Mumbai WH</option><option>Bengaluru WH</option></select><select className={cls} value={form.to_warehouse} onChange={e=>setForm({...form,to_warehouse:e.target.value})}><option>Mumbai WH</option><option>Delhi NCR</option><option>Bengaluru WH</option></select></>}<input className={cls} type="number" placeholder="Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input className={cls} placeholder="Reason / Reference" value={form.reason||form.reference} onChange={e=>setForm({...form,reason:e.target.value,reference:e.target.value})}/></div><button onClick={submit} className="mt-3 rounded bg-[#2f9e9e] px-4 py-2 text-sm text-white">Save</button>{message&&<p className="mt-2 text-sm text-rose-600">{message}</p>}</div>}<div className="overflow-auto rounded border bg-white"><table className="w-full text-left text-xs"><thead><tr className="bg-slate-100">{(rows[0]?Object.keys(rows[0]):['SKU','Warehouse','Quantity','Status','Created']).map(k=><th key={k} className="border-b px-3 py-2">{k}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{Object.keys(r).filter(k=>k!=='id').map(k=><td key={k} className="border-b px-3 py-2">{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></div>;
}
