import{useEffect,useState}from'react';import{useSearchParams}from'react-router-dom';import Shell from'../Shell';import{Btn,Panel,Toast}from'../parts';import{apiGet,apiSend}from'../../lib/api';
const tabs=['Order Detail','Address','UDF','Outbound Delivery','Activity & Remarks','Payment Details','Order Tags','Gift Wrap','E-way Bill','Attachment','Returns','CRM Tickets'];
const field=(label:string,key:string,value:any,set:(k:string,v:any)=>void,type='text',disabled=false)=><label className="text-xs text-slate-600">{label}<input aria-label={label} disabled={disabled} type={type} className="inp mt-1" value={value??''} onChange={e=>set(key,type==='checkbox'?e.target.checked:e.target.value)}/></label>;
const Grid=({heads,rows}:{heads:string[],rows:any[]})=><div className="overflow-auto rounded border"><table className="min-w-full text-xs"><thead className="bg-slate-100"><tr>{heads.map(x=><th className="whitespace-nowrap p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr className="border-t" key={r.id||i}>{heads.map(h=><td className="whitespace-nowrap p-2" key={h}>{String(r[h.toLowerCase().replaceAll(' ','_')]??r[h]??'')}</td>)}</tr>):<tr><td className="p-4 text-center text-slate-400" colSpan={heads.length}>No records found</td></tr>}</tbody></table></div>;
export default function OrderMaintenance(){const[q]=useSearchParams(),orderNo=q.get('orderNo')||'', [data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[tab,setTab]=useState(tabs[0]),[toast,setToast]=useState<any>(null),[comment,setComment]=useState(''),[tag,setTag]=useState(''),[payment,setPayment]=useState<any>({}),[file,setFile]=useState<File|null>(null),[attachmentIds,setAttachmentIds]=useState<number[]>([]),[more,setMore]=useState(false),[closeOpen,setCloseOpen]=useState(false),[closeReason,setCloseReason]=useState(''),[ewayManual,setEwayManual]=useState(false),[ewayDialog,setEwayDialog]=useState<any>(null);const load=async()=>{try{const x:any=await apiGet(`/api/order-maintenance?orderNo=${encodeURIComponent(orderNo)}`);setData(x);setForm({...x.order,lines:x.order.lines?.length?x.order.lines:[{sku_code:x.order.sku_code||'ORDER-SKU',qty:x.order.qty||1,open_qty:x.order.qty||1,unit_price:x.order.amount||0,status:x.order.status,source_wh:x.order.fulfillment_location||x.order.city}]})}catch(e:any){setToast({msg:e.message,type:'err'})}};useEffect(()=>{void load()},[orderNo]);const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v})),send=async(action:string,body:any={},ok?:string)=>{try{const x:any=await apiSend('/api/order-maintenance','POST',{orderNo,action,...body});setToast({msg:x.message||ok||'Saved Successfully.',type:'ok'});if(action==='copy'&&x.orderNo){location.href=`/app/order-maintenance?orderNo=${encodeURIComponent(x.orderNo)}`;return}await load()}catch(e:any){setToast({msg:e.message,type:'err'})}};
if(!data)return <Shell active="sales" breadcrumb="SALES > Order Create/Edit"><div className="p-6">Loading Order {orderNo}…</div>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</Shell>;
const Detail=<div className="space-y-4"><div className="grid gap-3 md:grid-cols-4">{field('Ext Order No','ext_order_no',form.ext_order_no,set)}{field('Site Location','site_location',form.site_location||'ADA',set,'text',true)}{field('Remarks','remarks',form.remarks,set)}<label className="text-xs">Change Type<select aria-label="Change Type" className="inp mt-1" value={form.order_type||''} onChange={e=>set('order_type',e.target.value)}><option>Normal</option><option>Replacement</option><option>Exchange</option></select></label>{field('Customer Type','customer_type',form.customer_type||'B2C',set,'text',true)}{field('Customer Code','customer_code',form.customer_code||'180635',set,'text',true)}{field('Order Currency','currency',form.currency||'INR',set,'text',true)}<label className="text-xs">Priority<select aria-label="Priority" className="inp mt-1" value={form.priority||''} onChange={e=>set('priority',e.target.value)}><option>--- Select ---</option><option>High</option><option>Medium</option><option>Normal</option></select></label>{field('Delivery Slot','delivery_slot',form.delivery_slot,set)}{field('Expected Delivery Date','expected_delivery_date',form.expected_delivery_date,set,'date')}{field('Source WH','source_wh',form.source_wh||'UWH',set,'text',true)}{field('Ship Date','ship_date',form.ship_date,set,'date')}{field('Shipping Charges','shipping_charges',form.shipping_charges,set,'number')}{field('Other Charges','other_charges',form.other_charges,set,'number')}{field('Store Credit','store_credit',form.store_credit,set,'number')}{field('Gift Voucher','gift_voucher',form.gift_voucher,set,'number')}{field('Discount Code','discount_code',form.discount_code,set)}{field('Order Amount','amount',form.amount,set,'number',true)}{field('Price Zone','price_zone',form.price_zone,set,'text',true)}<label className="text-xs">Order Processing<select aria-label="Order Processing" className="inp mt-1" value={form.customer_type||'B2C'} onChange={e=>set('customer_type',e.target.value)}><option>B2B</option><option>B2C</option><option>Q2C</option></select></label></div><Grid heads={['SKU Code','Status','Qty','Unit Price','Source WH']} rows={form.lines}/></div>;
const Address=<div className="grid gap-5 md:grid-cols-2">{['Shipping','Billing'].map(kind=><Panel title={`${kind} Address`} key={kind}><div className="grid gap-3 md:grid-cols-2">{['Customer Code','Customer Name','Address 1','Address 2','Address 3','Address 4','Landmark','Latitude','Longitude','Phone','Alt Phone','Country','State','City','Pincode','Email','Address Type','TIN','Geocode Type','Geocode Address'].map(x=>field(`${kind} ${x}`,`${kind.toLowerCase()}_${x.toLowerCase().replaceAll(' ','_')}`,form[`${kind.toLowerCase()}_${x.toLowerCase().replaceAll(' ','_')}`],set))}</div></Panel>)}</div>;
const Udf=<div><div className="grid gap-3 md:grid-cols-5">{Array.from({length:15},(_,i)=>field(`UDF${i+1}`,`udf${i+1}`,form[`udf${i+1}`],set))}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{field('Pick Instruction','pick_instruction',form.pick_instruction,set)}{field('Shipping Instruction','shipping_instruction',form.shipping_instruction,set)}</div><Grid heads={['ID','Instruction Type','Instruction Description']} rows={data.instructions}/></div>;
const Activity=<div className="space-y-3"><textarea aria-label="Add Order Comments" className="inp min-h-24" value={comment} onChange={e=>setComment(e.target.value)}/>
<Btn onClick={()=>void send('comment',{comments:comment})}>Submit Comments</Btn><Grid heads={['Activity Date','Comments','Status','Activity User']} rows={data.activities}/></div>;
const Payments=<div className="space-y-3"><div className="grid gap-3 md:grid-cols-4"><label className="text-xs">Payment Type*<select aria-label="Payment Type" className="inp mt-1" value={payment.payment_type||''} onChange={e=>setPayment((x:any)=>({...x,payment_type:e.target.value}))}><option value="">--- Select ---</option>{['Cash','Adyen','Credit Card','Debit Card','UPI','COD'].map(x=><option key={x}>{x}</option>)}</select></label>{['Doc No','Doc Date','Bank','IFSC','Doc Amount','Branch','Auth Code','EDC No','Amount Received'].map(x=>field(x,x.toLowerCase().replaceAll(' ','_'),payment[x.toLowerCase().replaceAll(' ','_')],(k,v)=>setPayment((p:any)=>({...p,[k]:v}))) )}</div><div className="flex gap-2">
<Btn onClick={()=>void send('payment',payment)}>Save Payment</Btn>
<Btn variant="ghost" onClick={()=>setPayment({})}>Reset</Btn></div><Grid heads={['Payment Type','Doc No','Doc Date','Bank','IFSC','Doc Amount','Amount Received']} rows={data.payments}/></div>;
const Tags=<div className="space-y-3"><label className="text-xs">Order Tags*<select aria-label="Order Tags" className="inp mt-1" value={tag} onChange={e=>setTag(e.target.value)}><option value="">--- Select ---</option><option>VIP</option><option>Priority</option><option>Gift</option></select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={!!form.notify_req} onChange={e=>set('notify_req',e.target.checked)}/>Send Notification</label>
<Btn onClick={()=>void send('tag',{tags:tag?[tag]:[],notify:form.notify_req})}>Add Tags</Btn><Grid heads={['Tag','Status','Tag Date','Tagged By']} rows={data.tags}/></div>;
const Gift=<div className="space-y-3"><label className="flex gap-2"><input aria-label="Gift Wrap Enabled" type="checkbox" checked={!!form.gift_wrap_enabled} onChange={e=>set('gift_wrap_enabled',e.target.checked)}/>Enabled</label><textarea aria-label="Gift Wrap Message" maxLength={500} disabled={!form.gift_wrap_enabled} className="inp min-h-28" value={form.gift_wrap_message||''} onChange={e=>set('gift_wrap_message',e.target.value)}/>
<Btn onClick={()=>void send('gift-wrap',{enabled:form.gift_wrap_enabled,message:form.gift_wrap_message})}>Save Gift-Wrap</Btn></div>;
const Eway=<div className="space-y-3"><div className="grid gap-3 md:grid-cols-4"><label className="text-xs">Invoice/Document Type*<select aria-label="Invoice/Document Type" className="inp mt-1" value={form.eway_document_type||''} onChange={e=>set('eway_document_type',e.target.value)}><option value="">--- Select ---</option><option>TaxInvoice</option><option>DeliveryChallan</option><option>OTHERS</option></select></label>{field('Sender GSTIN','sender_gstin',form.sender_gstin,set)}{field('Customer GSTIN','customer_gstin',form.customer_gstin,set)}{field('Transporter Name','transporter_name',form.transporter_name,set)}{field('Transporter GSTIN','transporter_gstin',form.transporter_gstin,set)}<label className="text-xs">Mode<select aria-label="Mode" className="inp mt-1" value={form.eway_mode||'Road'} onChange={e=>set('eway_mode',e.target.value)}>{['Road','Rail','Air','Ship','Part A','In Transit'].map(x=><option key={x}>{x}</option>)}</select></label>{field('Vehicle No','vehicle_no',form.vehicle_no,set)}{field('Distance','distance',form.distance,set,'number')}{field('E-way Bill No','eway_bill_no',form.eway_bill_no,set,'text',!ewayManual)}{field('Valid Upto','valid_upto',form.valid_upto,set,'date',!ewayManual)}</div><div className="flex flex-wrap gap-2">
<Btn variant="ghost" onClick={()=>void send('eway',{operation:'extra',document_type:form.eway_document_type,mode:form.eway_mode||'Road',vehicle_no:form.vehicle_no,distance:form.distance,eway_bill_no:form.eway_bill_no})}>Save</Btn>
<Btn variant="ghost" onClick={()=>setEwayManual(true)}>Edit</Btn>
<Btn variant="ghost" onClick={()=>setEwayManual(false)}>Back</Btn>
<Btn variant="ghost" onClick={()=>setEwayDialog({operation:'extend',reason:'1',status:'1',remarks:''})}>Extend E-way Bill Validity</Btn>
<Btn variant="ghost" onClick={()=>void send('eway',{operation:'save',document_type:form.eway_document_type,mode:form.eway_mode||'Road',vehicle_no:form.vehicle_no,distance:form.distance,eway_bill_no:form.eway_bill_no,valid_upto:form.valid_upto})}>Save Eway Bill</Btn>
<Btn variant="ghost" onClick={()=>void send('eway',{operation:'generate',document_type:form.eway_document_type,mode:form.eway_mode||'Road',vehicle_no:form.vehicle_no,distance:form.distance,eway_bill_no:form.eway_bill_no})}>Generate E-way Bill</Btn>
<Btn variant="ghost" onClick={()=>{const a=document.createElement('a');a.href=`/api/order-maintenance?orderNo=${encodeURIComponent(orderNo)}&download=eway-pdf`;a.download=`EwayBill-${orderNo}.pdf`;a.click()}}>Print</Btn>
<Btn variant="ghost" onClick={()=>setEwayDialog({operation:'update',reason:'Due to Breakdown',remarks:''})}>Update</Btn>
<Btn variant="danger" onClick={()=>setEwayDialog({operation:'cancel',reason:'Duplicate',remarks:''})}>Cancel</Btn></div><Grid heads={['HSN Code','Description','Taxable Value','Tax Rate']} rows={data.eway.hsn||[]}/></div>;
const Attachment=<div className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs">Document Type*<select aria-label="Document Type" className="inp mt-1" value={form.attachment_type||''} onChange={e=>set('attachment_type',e.target.value)}><option value="">--- Select ---</option><option>POD</option><option>OTHERS</option></select></label>{field('Delivery No','attachment_delivery',form.attachment_delivery,set)}<label className="text-xs">Attachment*<input aria-label="Attachment" className="inp mt-1" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="flex gap-2">
<Btn onClick={async()=>{if(!file)return void setToast({msg:'Attachment is mandatory.',type:'err'});const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)});void send('attachment',{document_type:form.attachment_type,delivery_no:form.attachment_delivery,file_name:file.name,base64})}}>Save Attachment</Btn>
<Btn variant="ghost" onClick={()=>{setFile(null);set('attachment_type','');set('attachment_delivery','')}}>Reset</Btn><Btn variant="danger" onClick={()=>void send('attachment-delete',{ids:attachmentIds})}>Delete</Btn></div><p className="text-xs text-slate-500">Packaging Image cannot be deleted.</p><div className="overflow-auto rounded border"><table className="min-w-full text-xs"><thead className="bg-slate-100"><tr><th className="p-2"><span className="sr-only">Select</span></th>{['File Name','Document Type','Delivery No','Download'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{data.attachments.length?data.attachments.map((r:any)=><tr className="border-t" key={r.id}><td className="p-2"><input aria-label={`Select attachment ${r.file_name}`} type="checkbox" checked={attachmentIds.includes(r.id)} onChange={e=>setAttachmentIds(xs=>e.target.checked?[...xs,r.id]:xs.filter(x=>x!==r.id))}/></td><td className="p-2">{r.file_name}</td><td className="p-2">{r.document_type}</td><td className="p-2">{r.delivery_no}</td><td className="p-2"><button className="text-blue-700 underline" onClick={()=>{const a=document.createElement('a');a.href=`data:application/octet-stream;base64,${r.base64}`;a.download=r.file_name;a.click()}}>Download</button></td></tr>):<tr><td className="p-4 text-center text-slate-400" colSpan={5}>No records found</td></tr>}</tbody></table></div></div>;
const bodies:any={'Order Detail':Detail,'Address':Address,UDF:Udf,'Outbound Delivery':<Grid heads={['Delivery No','Source WH','Create Date','Transporter','AWB','Status','Qty','Ship Date','Delivery Date']} rows={data.deliveries}/>,'Activity & Remarks':Activity,'Payment Details':Payments,'Order Tags':Tags,'Gift Wrap':Gift,'E-way Bill':Eway,Attachment,'Returns':<Grid heads={['Return No','Delivery No','Reverse Tracking No','Ext Invoice No','Replacement Order No','Return Type','Return Date','Status']} rows={data.returns}/>,'CRM Tickets':<div className="rounded border border-dashed p-8 text-center text-sm text-slate-500">No CRM Tickets found for this order.</div>};
return <Shell active="sales" breadcrumb="SALES > Order Create/Edit" openScreens={[{label:'Order Enquiry',to:'/app/order-enquiry'},{label:`Order Create/Edit - ${orderNo}`,to:'#'}]}><div className="mb-3 flex flex-wrap gap-2">
<Btn onClick={()=>void send('save',{...form,lines:form.lines})}>Save</Btn>
<Btn disabled={!/complete|verified/i.test(form.verification_status||'')} onClick={()=>void send('quick-ship')}>Quick Ship</Btn>
<Btn variant="ghost" onClick={()=>void send('change-type',{orderType:form.order_type})}>Change Type</Btn><div className="relative">
<Btn variant="ghost" onClick={()=>setMore(x=>!x)}>Toggle Dropdown</Btn>{more&&<div className="absolute left-0 z-30 mt-1 min-w-48 rounded border bg-white p-1 shadow-xl">{[[form.on_hold?'UnHold':'Hold',()=>void send('hold',{onHold:!form.on_hold})],['Close SO',()=>setCloseOpen(true)],['Copy',()=>{if(confirm('Do you want to copy this Order?'))void send('copy')}],['Print',()=>window.print()],['Proforma Invoice',()=>window.print()]].map(([x,fn]:any)=><button key={x} className="block w-full rounded px-3 py-2 text-left text-sm hover:bg-slate-100" onClick={()=>{setMore(false);fn()}}>{x}</button>)}</div>}</div>
<Btn variant="ghost" disabled>Customer Picker</Btn>
<Btn variant="ghost" disabled>Add SKU</Btn></div>{closeOpen&&<div role="dialog" aria-label="Close Sales Order" className="mb-3 rounded border bg-white p-4 shadow"><h3 className="font-semibold">Close Sales Order</h3><p className="mt-1 text-sm text-slate-500">Select the open order lines and provide a closing reason.</p><Grid heads={['SKU Code','Open Qty','Status']} rows={form.lines}/><label className="mt-3 block text-xs">Reason<textarea aria-label="Close Reason" className="inp mt-1" value={closeReason} onChange={e=>setCloseReason(e.target.value)}/></label><div className="mt-3 flex gap-2">
<Btn variant="danger" onClick={()=>{setCloseOpen(false);void send('close',{reason:closeReason})}}>Close SO</Btn>
<Btn variant="ghost" onClick={()=>setCloseOpen(false)}>Cancel</Btn></div></div>}
{ewayDialog&&<div role="dialog" aria-label={ewayDialog.operation==='cancel'?'Select Reason For Cancellation':'Select Reason For Updation'} className="mb-3 rounded border bg-white p-4 shadow"><h3 className="font-semibold">{ewayDialog.operation==='cancel'?'Select Reason For Cancellation':'Select Reason For Updation'}</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs">Select Reason<select aria-label="E-way Reason" className="inp mt-1" value={ewayDialog.reason} onChange={e=>setEwayDialog((x:any)=>({...x,reason:e.target.value}))}>{ewayDialog.operation==='cancel'?['Duplicate','Order Cancelled','Data Entry mistake','Others'].map(x=><option key={x}>{x}</option>):ewayDialog.operation==='update'?['Due to Breakdown','Due to Transshipment','Others'].map(x=><option key={x}>{x}</option>):<><option value="1">Natural Calamity</option><option value="2">Law and Order Situation</option><option value="3">Transshipment</option><option value="4">Accident</option><option value="5">Others</option></>}</select></label>{ewayDialog.operation==='extend'&&<label className="text-xs">Consignment Status<select aria-label="Consignment Status" className="inp mt-1" value={ewayDialog.status} onChange={e=>setEwayDialog((x:any)=>({...x,status:e.target.value}))}><option value="1">In Transit</option><option value="2">In Movement</option></select></label>}<label className="text-xs">Remarks<textarea aria-label="E-way Remarks" className="inp mt-1" value={ewayDialog.remarks} onChange={e=>setEwayDialog((x:any)=>({...x,remarks:e.target.value}))}/></label></div><div className="mt-3 flex gap-2"><Btn variant={ewayDialog.operation==='cancel'?'danger':'primary'} onClick={()=>{void send('eway',ewayDialog);setEwayDialog(null)}}>{ewayDialog.operation==='cancel'?'Cancel EwayBillNo':'Update'}</Btn><Btn variant="ghost" onClick={()=>setEwayDialog(null)}>Close</Btn></div></div>}<div className="mb-3 flex overflow-auto border-b bg-white">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap px-4 py-3 text-sm ${tab===x?'border-b-2 border-rose-500 font-semibold':''}`}>{x}</button>)}</div><Panel title={`${tab} · ${orderNo}`}>{bodies[tab]}</Panel>{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}</Shell>}
