import { find, findOne, insert, update, remove, cors } from './mongo.js';

const collections = { links: 'ars_sku_links', rules: 'ars_rules', logs: 'ars_execution_logs', settings: 'ars_settings' };
const text = (value) => String(value ?? '').trim();
const today = () => new Date().toISOString().slice(0, 10);
const addHours = (date, hours) => new Date(date.getTime() + Number(hours) * 3600000).toISOString().slice(0, 10);

function validateLink(body) {
  if (!text(body.sku_code) || !text(body.location) || !text(body.ars_flag)) return 'SKU, Location and ARS Flag are required.';
  if (body.wh_lead_time !== '' && (!Number.isFinite(Number(body.wh_lead_time)) || Number(body.wh_lead_time) < 0)) return 'WH Lead Time must be zero or greater.';
  if (body.stock_cover_days !== '' && (!Number.isFinite(Number(body.stock_cover_days)) || Number(body.stock_cover_days) < 0)) return 'Stock Cover Days must be zero or greater.';
  return '';
}

function validateRule(body) {
  const locations = Array.isArray(body.locations) ? body.locations.filter(Boolean) : (text(body.location) ? [body.location] : []);
  if (!locations.length) return 'Please Enter Location.';
  if (!text(body.ars_method)) return 'Please Enter ARS Method.';
  if (body.ars_method === 'Min-Max') {
    if (!text(body.minimum_qty) || !text(body.maximum_qty)) return 'Please Enter Min And Max values.';
    if (!Number.isFinite(Number(body.minimum_qty)) || !Number.isFinite(Number(body.maximum_qty)) || Number(body.minimum_qty) < 0 || Number(body.maximum_qty) <= Number(body.minimum_qty)) return 'Maximum Quantity must be greater than Minimum Quantity.';
  }
  if (body.ars_method === 'Sales History' && !text(body.ros_period)) return 'Please Enter ROS.';
  if (!Array.isArray(body.sku_sets) || !body.sku_sets.length) return 'Please Add atleast one SKU Set';
  if (!text(body.description)) return 'Please Enter Rule Description.';
  if (!text(body.vendor_type)) return 'Please Enter Vendor Type.';
  if (!text(body.output_type)) return 'Please Enter Output Type.';
  if (!text(body.status)) return 'Please Enter Status.';
  if (!text(body.start_date)) return 'Please Enter Start Date.';
  return '';
}

function matchesSet(link, sets) {
  return sets.every((set) => {
    const actual = set.type === 'SKU' ? link.sku_code : set.type === 'Brand' ? link.brand : set.type === 'Vendor' ? link.primary_vendor : set.type === 'Hierarchy' ? link.category : link.sku_group;
    return set.operand === 'Exclude' ? text(actual) !== text(set.value) : text(actual) === text(set.value);
  });
}

async function runRule(rule) {
  const settings = (await find('ars_settings'))[0];
  if (!settings?.enable_ars) throw Object.assign(new Error('ARS is disabled in B2B Configuration.'), { statusCode: 409 });
  if (rule.status !== 'Active') throw Object.assign(new Error('Only an Active ARS Rule can be run.'), { statusCode: 409 });
  const currentDate = today();
  if ((rule.start_date && currentDate < rule.start_date) || (rule.end_date && currentDate > rule.end_date)) {
    throw Object.assign(new Error('ARS Rule is outside its applicable date range.'), { statusCode: 409 });
  }
  const started = new Date();
  const locations = Array.isArray(rule.locations) && rule.locations.length ? rule.locations : [rule.location].filter(Boolean);
  const links = (await find('ars_sku_links')).filter((link) => link.ars_flag === 'Active' && locations.includes(link.location) && matchesSet(link, rule.sku_sets || []));
  const inventory = await find('inventory');
  const skus = await find('skus');
  const vendors = await find('vendors');
  const generated = [];
  const executionDetails = [];
  for (const link of links) {
    const stock = inventory.filter((row) => row.sku_code === link.sku_code && row.warehouse === link.location).reduce((sum, row) => sum + Number(row.available || 0), 0);
    let quantity = 0;
    if (rule.ars_method === 'Min-Max' && stock <= Number(rule.minimum_qty)) quantity = Number(rule.maximum_qty) - stock;
    if (rule.ars_method === 'Sales History') quantity = Math.max(0, Number(link.stock_cover_days || 0) - stock);
    if (quantity <= 0) continue;
    const sku = skus.find((row) => row.sku_code === link.sku_code) || {};
    const vendor = vendors.find((row) => row.vendor_code === link.primary_vendor) || {};
    const poCode = `ARSPO${Date.now().toString().slice(-7)}${generated.length + 1}`;
    await insert('purchase_orders', {
      po_no: poCode, vendor: vendor.vendor_name || link.primary_vendor, vendor_code: link.primary_vendor, warehouse: link.location,
      po_date: today(), expected_date: addHours(started, Number(link.wh_lead_time || 1) * 24), items: 1, qty: quantity,
      amount: quantity * Number(sku.cost_price || 0), status: rule.output_type === 'Confirmed' ? 'Confirmed' : 'Pending Confirmation',
      buyer_name: 'ARS Scheduler', po_type: 'ARS', recv_validation_code: 'Standard', external_po_no: '', reference_no: rule.rule_id,
      notes: `Auto replenishment generated by ARS Rule ${rule.rule_id}`, discount_type: 'Amount', discount_value: 0, currency_code: 'INR',
      po_method: 'Single Location', delivery_locations: [link.location], source_order_no: '',
      line_items: [{ sku_code: link.sku_code, description: link.sku_name, po_qty: quantity, unit_cost: Number(sku.cost_price || 0) }], allocation: [],
      udf: ['', '', '', '', ''], terms: '', comments: [], tags: ['ARS'], ars_rule_id: rule.rule_id, revision_no: 0, revisions: [],
    });
    generated.push(poCode);
    executionDetails.push({ location: link.location, sku_code: link.sku_code, vendor: link.primary_vendor, inventory: stock, ars_calculated: quantity, ars_approved: quantity, status: 'Document Created', document_generated: poCode });
  }
  const frequencyHours = { 1: 720, 2: 1440, 3: 168, 4: 336, 5: 24, 6: 0 };
  const nextRun = frequencyHours[Number(rule.frequency)] ? addHours(started, frequencyHours[Number(rule.frequency)]) : '';
  await update('ars_rules', rule.id, { last_run_date: today(), next_run_date: nextRun, updated_by: 'ArsSchdulr', updated_date: today() });
  return insert('ars_execution_logs', {
    execution_id: `ARSEX-${Date.now()}`, rule_id: rule.rule_id, description: rule.description, location: locations.join(', '), locations,
    frequency: rule.frequency, frequency_desc: ({ 1: 'Monthly', 2: 'Bimonthly', 3: 'Weekly', 4: 'Biweekly', 5: 'Daily', 6: 'Never' })[Number(rule.frequency)] || '',
    vendor_type: rule.vendor_type, output_type: rule.output_type,
    started_at: started.toISOString(), completed_at: new Date().toISOString(), status: 'Document Generated', evaluated_skus: links.length,
    generated_orders: generated.length, generated_po_codes: generated, execution_details: executionDetails, message: generated.length ? `${generated.length} Purchase Order(s) created.` : 'Rule evaluated successfully; no SKU reached its replenishment threshold.',
  });
}

export default async function handler(req, res) {
  if (cors(req, res)) return;
  try {
    const endpoint = text(req.path).split('/').pop();
    const liveLinkEndpoint = ['fetchArsAttributes', 'addAndUpdateArsAttributes', 'bulkUpdateArsAttributes', 'downloadArsAttribute'].includes(endpoint);
    const entity = text(req.query.entity || req.body?.entity || (liveLinkEndpoint ? 'links' : ''));
    const collection = collections[entity];
    if (!collection) return res.status(400).json({ error: 'Unknown ARS entity.' });
    if (req.method === 'GET') return res.status(200).json(await find(collection, {}, { sort: { id: entity === 'settings' ? 1 : -1 } }));

    if (req.method === 'POST' && endpoint === 'downloadArsAttribute') {
      const reportId = `ARS-${Date.now()}`;
      await insert('downloads', { filename: `ars-sku-location-${today()}.xlsx`, format: 'XLSX', module: 'ARS SKU-Location Link', row_count: (await find(collection)).length, size: 0, exported_by: 'super admin', status: 'Processing', report_id: reportId, created_at: new Date().toISOString() });
      return res.status(200).json({ jsonMessage: null, skuLocLinkDTO: { reportId }, reportDTO: { jsonMessage: 'Report request submitted.' } });
    }

    if (req.method === 'POST' && entity === 'links' && endpoint !== 'bulkUpdateArsAttributes' && (req.body?.REQ_SEARCH_FLAG || endpoint === 'fetchArsAttributes')) {
      const body = req.body; const has = (value, query) => !text(query) || text(value).toLowerCase().includes(text(query).toLowerCase());
      const selectedLocations = text(body.location).split('\u0017').filter(Boolean);
      const locationMaster = await find('generic_records', { module: 'location' });
      const locationMatches = selectedLocations.flatMap((value) => {
        const match = locationMaster.find((row) => [row.id, row.code, row.location_code, row.name, row.location_name].some((candidate) => text(candidate) === text(value)));
        return match ? [value, match.code, match.location_code, match.name, match.location_name].map(text).filter(Boolean) : [value];
      });
      const filtered = (await find(collection)).filter((row) => (!locationMatches.length || locationMatches.some((value) => has(row.location, value) || has(row.location_id, value)))
        && has(row.location_type, body.locationTypeId) && has(row.sku_code, body.skuCode || body.sku)
        && has(row.sku_name, body.skuName) && has(row.category, body.category) && has(row.brand, body.brand)
        && has(row.primary_vendor, body.primaryVendor) && has(row.fulfilment_method, body.fullFillmentMethod)
        && has(row.fulfilment_wh, body.fullFillmentWH || body.fullFillmentWh) && has(row.wh_lead_time, body.whLeadTime || body.fullfillmentWhLeadTime)
        && has(row.stock_cover_days, body.stockCoverDays)
        && (!text(body.arsFlag) || text(row.ars_flag).toLowerCase() === (text(body.arsFlag) === '1' ? 'active' : text(body.arsFlag) === '0' ? 'inactive' : text(body.arsFlag).toLowerCase()))
        && has(row.sku_location_tag, body.skuLocationTag) && has(row.udf1, body.udf1) && has(row.udf2, body.udf2));
      const size = [20, 50, 100, 200].includes(Number(body.rows)) ? Number(body.rows) : 20;
      const page = Math.max(1, Number(body.page) || 1); const records = filtered.length; const total = Math.ceil(records / size);
      const gridModel = filtered.slice((page - 1) * size, page * size);
      return res.status(200).json({ gridModel, rows: gridModel, page, records, total });
    }

    if (req.method === 'POST' && endpoint === 'addAndUpdateArsAttributes') {
      const body = req.body || {};
      if (!text(body.skuCode)) return res.status(400).json({ error: 'SkuCode is mandatory' });
      if (body.id && !text(body.transferUnitFactor)) return res.status(400).json({ error: 'Transfer Unit Factor is mandatory' });
      if (body.id && !text(body.minimumTransferQty)) return res.status(400).json({ error: 'Minimum Transfer Qty is mandatory' });
      if (text(body.transferUnitFactor) && Number(body.transferUnitFactor) < 1) return res.status(400).json({ error: 'Transfer Unit Factor cannot be Zero.' });
      if (text(body.minimumTransferQty) && Number(body.minimumTransferQty) < 1) return res.status(400).json({ error: 'Minimum Transfer Qty cannot be Zero.' });
      if (!text(body.location) || text(body.location) === '-1') return res.status(400).json({ error: 'Location is mandatory' });
      if (!text(body.arsFlag) || text(body.arsFlag) === '-1') return res.status(400).json({ error: 'ArsFlag is mandatory' });
      if (text(body.isCICO) === '1' && !text(body.caseSize)) return res.status(400).json({ error: 'Case Size is Mandatory.' });
      if (text(body.caseSize) && (!Number.isInteger(Number(body.caseSize)) || Number(body.caseSize) <= 0)) return res.status(400).json({ error: 'Case Size must be positive integer.' });
      const fields = {
        sku_code: text(body.skuCode), location: text(body.location), fulfilment_method: text(body.fullFillMentMethod),
        fulfilment_wh: text(body.fullFillMentWH), wh_lead_time: Number(body.whLeadTime || 0), primary_vendor: text(body.primaryVendor),
        stock_cover_days: Number(body.stockCoverDays || 0), minimum_transfer_qty: Number(body.minimumTransferQty || 1),
        transfer_unit_factor: Number(body.transferUnitFactor || 1), ars_flag: text(body.arsFlag) === '1' ? 'Active' : text(body.arsFlag) === '0' ? 'Inactive' : text(body.arsFlag),
        maximum_order_qty: Number(body.maximumOrderQty || 0), sku_location_tag: text(body.skuLocationTag), is_cico: text(body.isCICO) === '1',
        case_size: text(body.caseSize), updated_date: today(), updated_by: 'super admin',
      };
      const sku = await findOne('skus', { sku_code: fields.sku_code });
      if (!sku) return res.status(400).json({ error: 'SKU does not exist in SKU Master.' });
      const locationMaster = await find('generic_records', { module: 'location' });
      const location = locationMaster.find((row) => [row.id, row.code, row.location_code, row.name, row.location_name].some((candidate) => text(candidate) === text(body.location)));
      const fulfilmentWarehouse = locationMaster.find((row) => [row.id, row.code, row.location_code, row.name, row.location_name].some((candidate) => text(candidate) === text(body.fullFillMentWH)));
      Object.assign(fields, { sku_name: sku.name, category: sku.category, brand: sku.brand,
        location_id: text(body.location), location: text(location?.location_name || location?.name || body.location),
        location_type: text(location?.location_type || location?.loc_type), fulfilment_wh_id: text(body.fullFillMentWH),
        fulfilment_wh: text(fulfilmentWarehouse?.location_name || fulfilmentWarehouse?.name || body.fullFillMentWH) });
      if (body.id) {
        const changed = await update(collection, Number(body.id), fields);
        if (!changed.length) return res.status(404).json({ error: 'ARS record not found.' });
        return res.status(200).json({ jsonMessage: null, skuLocLinkDTO: changed[0] });
      }
      const duplicate = (await find(collection)).find((row) => row.sku_code === fields.sku_code && row.location === fields.location);
      if (duplicate) return res.status(409).json({ error: 'This SKU and Location are already linked.' });
      const row = await insert(collection, { ...fields, created_date: today() });
      return res.status(200).json({ jsonMessage: null, skuLocLinkDTO: row });
    }

    if (req.method === 'POST' && endpoint === 'bulkUpdateArsAttributes') {
      const body = req.body || {};
      if (!text(body.locationType_bulk) || text(body.locationType_bulk) === '-1') return res.status(400).json({ error: 'Location Type is mandatory' });
      const checked = [body.arsCheckBox, body.stockCoverDaysCheckBox, body.primaryVendorCheckBox, body.fullfillmentMethodCheckBox,
        body.fullfillmentWHCheckBox, body.fullfillmentWhLeadTimeCheckBox, body.minimumTransferQtyCheckBox,
        body.transferUnitFactorCheckBox, body.maximumOrderQtyCheckBox, body.skuLocationTagCheckBox, body.caseSizeCheckBox, body.isCICOCheckBox]
        .some((value) => value === true || text(value) === 'true');
      if (!checked) return res.status(400).json({ error: 'Select at least one attribute to update' });
      const match = (row, key, value) => {
        if (!text(value) || text(value) === '-1') return true;
        if (key === 'location_type') {
          const types = { 2: ['wh', 'warehouse'], 3: ['store'], 6: ['franchise'] };
          return (types[text(value)] || [text(value).toLowerCase()]).includes(text(row[key]).toLowerCase());
        }
        return text(row[key]).toLowerCase().includes(text(value).toLowerCase());
      };
      const candidates = (await find(collection)).filter((row) => match(row, 'location_type', body.locationType_bulk)
        && match(row, 'location', body.location_bulk) && match(row, 'category', body.categoryCode)
        && match(row, 'sku_group', body.skuGroup_bulk) && match(row, 'primary_vendor', body.vendorCode)
        && match(row, 'brand', body.brand_bulk) && match(row, 'sku_code', body.sku_bulk));
      const fields = {};
      const use = (check, key, value) => { if (check === true || text(check) === 'true') fields[key] = value; };
      use(body.arsCheckBox, 'ars_flag', text(body.arsFlag_bulk) === '1' ? 'Active' : text(body.arsFlag_bulk) === '0' ? 'Inactive' : text(body.arsFlag_bulk));
      use(body.stockCoverDaysCheckBox, 'stock_cover_days', Number(body.stockCoverDays_bulk || 0));
      use(body.primaryVendorCheckBox, 'primary_vendor', text(body.primaryVendor_bulk));
      use(body.fullfillmentMethodCheckBox, 'fulfilment_method', text(body.fullfillmentMethod_bulk));
      use(body.fullfillmentWHCheckBox, 'fulfilment_wh', text(body.fullfillmentWH_bulk));
      use(body.fullfillmentWhLeadTimeCheckBox, 'wh_lead_time', Number(body.whLeadTime_bulk || 0));
      use(body.minimumTransferQtyCheckBox, 'minimum_transfer_qty', Number(body.minimumTransferQty_bulk || 1));
      use(body.transferUnitFactorCheckBox, 'transfer_unit_factor', Number(body.transferUnitFactor_bulk || 1));
      use(body.maximumOrderQtyCheckBox, 'maximum_order_qty', Number(body.maximumOrderQty_bulk || 0));
      use(body.skuLocationTagCheckBox, 'sku_location_tag', text(body.skuLocationTag_bulk));
      use(body.caseSizeCheckBox, 'case_size', text(body.caseSize_bulk));
      use(body.isCICOCheckBox, 'is_cico', body.isCICO_ValueCB === true || text(body.isCICO_ValueCB) === 'true');
      const changed = candidates.length ? await update(collection, candidates.map((row) => row.id), { ...fields, updated_date: today(), updated_by: 'super admin' }) : [];
      return res.status(200).json({ skuLocLinkDTO: { updatedRowCount: changed.length }, jsonMessage: null });
    }

    if (req.method === 'POST' && entity === 'rules' && req.body?.REQ_SEARCH_FLAG) {
      const body = req.body;
      const has = (value, query) => !text(query) || text(value).toLowerCase().includes(text(query).toLowerCase());
      const frequencyLabels = { 0: 'Never', 1440: 'Daily', 10080: 'Weekly', 20160: 'Biweekly', 43200: 'Monthly', 86400: 'Bimonthly' };
      const filtered = (await find(collection)).filter((row) => {
        const locations = Array.isArray(row.locations) ? row.locations : [row.location].filter(Boolean);
        const productSets = Array.isArray(row.sku_sets) ? row.sku_sets.map((set) => set.type) : [];
        return (!text(body.location) || locations.some((value) => has(value, body.location)))
          && (!text(body.productSet) || productSets.some((value) => has(value, body.productSet)))
          && has(row.rule_id, body.arsRuleId) && has(row.description, body.desc)
          && (!text(body.status) || text(row.status).toLowerCase() === text(body.status).toLowerCase())
          && has(row.status_code, body.statusCode) && has(row.ars_method, body.arsMethod)
          && (!text(body.frequency) || has(frequencyLabels[row.frequency] || row.frequency, body.frequency))
          && has(row.last_run_date, body.lastARSRunDate) && has(row.next_run_date, body.nextARSRunDate)
          && has(row.updated_date, body.modifiedDateText);
      });
      const size = [20, 50, 100, 200].includes(Number(body.rows)) ? Number(body.rows) : 20;
      const page = Math.max(1, Number(body.page) || 1); const records = filtered.length; const total = Math.ceil(records / size);
      const gridModel = filtered.slice((page - 1) * size, page * size);
      return res.status(200).json({ gridModel, rows: gridModel, page, records, total });
    }

    if (req.method === 'POST' && entity === 'logs' && req.body?.REQ_SEARCH_FLAG) {
      const body = req.body; const has = (value, query) => !text(query) || text(value).toLowerCase().includes(text(query).toLowerCase());
      const rules = await find('ars_rules');
      const filtered = (await find(collection)).map((row) => {
        const rule = rules.find((item) => text(item.rule_id) === text(row.rule_id)) || {};
        return { ...row, arsExecId: row.execution_id, execTime: row.started_at, ruleDesc: row.description || rule.description, frequencyDesc: row.frequency_desc || '', vendorTypeDesc: row.vendor_type || rule.vendor_type || '', outPutTypeDesc: row.output_type || rule.output_type || '', statusDesc: row.status };
      }).filter((row) => has(row.location, body.location) && has(row.arsExecId, body.arsExecId) && has(row.execTime, body.execTime)
        && has(row.rule_id, body.ruleId) && has(row.ruleDesc, body.ruleDesc) && has(row.frequencyDesc, body.frequency)
        && has(row.vendorTypeDesc, body.vendorType) && has(row.outPutTypeDesc, body.outputType) && has(row.statusDesc, body.status));
      const size = [20, 50, 100, 200].includes(Number(body.rows)) ? Number(body.rows) : 20;
      const page = Math.max(1, Number(body.page) || 1); const records = filtered.length; const total = Math.ceil(records / size);
      const gridModel = filtered.slice((page - 1) * size, page * size);
      return res.status(200).json({ gridModel, rows: gridModel, page, records, total });
    }

    if (req.method === 'POST' && entity === 'logs' && ['approve-all', 'process-all'].includes(req.body?.action)) {
      const log = await findOne(collection, { id: Number(req.body.id) });
      if (!log) return res.status(404).json({ error: 'ARS Execution Log not found.' });
      const nextStatus = req.body.action === 'approve-all' ? 'Approved' : 'Document Inprocess';
      const details = (log.execution_details || []).map((row) => ({ ...row, status: nextStatus, approved_by: req.body.action === 'approve-all' ? 'super admin' : row.approved_by, approved_date: req.body.action === 'approve-all' ? today() : row.approved_date }));
      const changed = (await update(collection, log.id, { execution_details: details, status: nextStatus }))[0];
      return res.status(200).json({ jsonMessage: null, count: details.length, log: changed });
    }

    if (req.method === 'POST' && entity === 'links') {
      if (req.body.action === 'import') {
        const rows = Array.isArray(req.body.rows) ? req.body.rows : [];
        if (!rows.length || rows.length > 2000) return res.status(400).json({ error: 'Import must contain between 1 and 2000 rows.' });
        const results = [];
        for (const row of rows) {
          const error = validateLink(row); if (error) return res.status(400).json({ error: `${row.sku_code || 'Row'}: ${error}` });
          results.push(await insert(collection, { ...row, wh_lead_time: Number(row.wh_lead_time || 0), stock_cover_days: Number(row.stock_cover_days || 0), created_date: today(), updated_date: today() }));
        }
        return res.status(201).json(results);
      }
      const error = validateLink(req.body); if (error) return res.status(400).json({ error });
      const sku = await findOne('skus', { sku_code: text(req.body.sku_code) });
      if (!sku) return res.status(400).json({ error: 'SKU does not exist in SKU Master.' });
      const duplicate = (await find(collection)).find((row) => row.sku_code === req.body.sku_code && row.location === req.body.location);
      if (duplicate) return res.status(409).json({ error: 'This SKU and Location are already linked.' });
      const { entity: _entity, action: _action, ...linkFields } = req.body;
      return res.status(201).json(await insert(collection, { ...linkFields, sku_name: sku.name, category: sku.category, brand: sku.brand, wh_lead_time: Number(req.body.wh_lead_time || 0), stock_cover_days: Number(req.body.stock_cover_days || 0), created_date: today(), updated_date: today() }));
    }

    if (req.method === 'POST' && entity === 'rules') {
      const error = validateRule(req.body); if (error) return res.status(400).json({ error });
      const rows = await find(collection); const rule_id = String(Math.max(1000, ...rows.map((row) => Number(row.rule_id) || 0)) + 1);
      const { entity: _entity, action: _action, ...ruleFields } = req.body;
      const locations = Array.isArray(req.body.locations) && req.body.locations.length ? req.body.locations : [req.body.location].filter(Boolean);
      return res.status(201).json(await insert(collection, { ...ruleFields, locations, location: locations[0] || '', rule_id, minimum_qty: Number(req.body.minimum_qty || 0), maximum_qty: Number(req.body.maximum_qty || 0), frequency: Number(req.body.frequency), status: req.body.status || 'Pending', last_run_date: '', next_run_date: '', created_by: 'super admin', updated_by: 'super admin', updated_date: today() }));
    }

    if (req.method === 'PUT' && entity === 'settings') {
      const enabled = Array.isArray(req.body.custom_period_enabled) ? req.body.custom_period_enabled : [false, false, false];
      const periods = Array.isArray(req.body.custom_periods) ? req.body.custom_periods : ['', '', ''];
      for (let index = 0; index < 3; index += 1) {
        if (enabled[index] && !text(periods[index])) return res.status(400).json({ error: 'Please Enter Days in Textbox to Make it Active.' });
        if (text(periods[index]) && (!/^\d+$/.test(text(periods[index])) || Number(periods[index]) < 2 || Number(periods[index]) > 365)) return res.status(400).json({ error: 'Please Enter Days between 2 and 365' });
      }
      const activeRos = [req.body.ros_lifetime, req.body.ros_12_weeks, req.body.ros_6_weeks, req.body.ros_1_month, req.body.ros_2_weeks, ...enabled].filter(Boolean).length;
      if (req.body.enable_ars && activeRos < 2) return res.status(400).json({ error: 'Minimum 2 ROS Calculation parameters should be Active' });
      const current = (await find(collection))[0];
      const payload = { ...req.body, updated_date: today(), updated_by: 'super admin' }; delete payload.entity;
      const rows = current ? await update(collection, current.id, payload) : [await insert(collection, payload)];
      return res.status(200).json(rows[0]);
    }

    if (req.method === 'PUT' && entity === 'links' && req.body.action === 'bulk-update') {
      const all = await find(collection); const f = req.body.filters || {}; const fields = req.body.fields || {};
      const ids = all.filter((row) => Object.entries(f).every(([key, value]) => !text(value) || text(row[key]) === text(value))).map((row) => row.id);
      if (!ids.length) return res.status(404).json({ error: 'No ARS SKU-Location records match the bulk-update criteria.' });
      const changed = await update(collection, ids, { ...fields, updated_date: today() });
      return res.status(200).json(changed);
    }

    if (req.method === 'PUT' && entity === 'rules' && req.body.action === 'run') {
      const rule = await findOne(collection, { id: Number(req.body.id) }); if (!rule) return res.status(404).json({ error: 'ARS Rule not found.' });
      return res.status(200).json(await runRule(rule));
    }

    if (req.method === 'PUT') {
      const id = Number(req.body.id); const current = await findOne(collection, { id }); if (!current) return res.status(404).json({ error: 'ARS record not found.' });
      const { entity: _entity, id: _id, action, ...fields } = req.body;
      if (entity === 'rules' && action === 'confirm') {
        if (current.status !== 'Pending') return res.status(409).json({ error: 'Only a Pending ARS Rule can be confirmed.' });
        fields.status = 'Active';
      } else if (entity === 'rules') {
        const error = validateRule({ ...current, ...fields }); if (error) return res.status(400).json({ error });
        if (Array.isArray(fields.locations)) fields.location = fields.locations[0] || '';
      } else if (entity === 'links') {
        const error = validateLink({ ...current, ...fields }); if (error) return res.status(400).json({ error });
      }
      fields.updated_date = today(); fields.updated_by = 'super admin';
      const changed = await update(collection, id, fields); return res.status(200).json(changed[0]);
    }

    if (req.method === 'DELETE') {
      const row = await findOne(collection, { id: Number(req.body.id) }); if (!row) return res.status(404).json({ error: 'ARS record not found.' });
      if (entity === 'rules' && row.status !== 'Pending') return res.status(409).json({ error: 'Only a Pending ARS Rule can be deleted. Use Inactive or Discontinued for an audited rule.' });
      return res.status(200).json(await remove(collection, Number(req.body.id)));
    }
    res.status(405).json({ error: 'Method not allowed.' });
  } catch (error) {
    console.error('ARS API error:', error);
    res.status(error.statusCode || 500).json({ error: error.message || 'ARS request failed.' });
  }
}
