import{cors,find,insert}from'./mongo.js';
export const importTypes=[['44','BulkReturnClose'],['66','Create_UpdateMerchHierarchy'],['23','POSTSUPDATE'],['45','BulkUnkit'],['67','Amazon_Order_Import'],['24','STOSTSUPDATE'],['46','ASNImport'],['68','B2B Sort Sequence'],['47','Channel Active/Inactive Import'],['69','Bulk Link Picker'],['48','NDR Import'],['27','PoImport'],['28','PoShortCloseImport'],['29','STOImport'],['70','Customer Master Import'],['73','PutawayImport'],['30','OrderImport'],['74','SkuLotTransfer'],['75','CreateWaveFilterImport'],['76','ExecuteWaveFilterImport'],['11','Transhipment'],['33','ARSSkuLocationLinkImport'],['77','Bulk Order Allocation/Un-Allocation'],['12','POS Config Import'],['34','FNVRePackImport'],['79','ShiftMasterImport'],['14','InventoryMovement'],['15','StockAdjustment'],['59','InboundImportwithIGP'],['38','SkuUpdateImport'],['3','VendorImport'],['4','OrderReturn'],['5','VendorSkuLocationCatalogue'],['6','PORevisionBulk'],['7','InboundImportWithPO'],['8','InboundImportWithoutPO'],['80','ShiftAssignmentImport'],['9','InboundImportWithASN'],['81','Picklist Assign/unAssign'],['60','PermanentLpnImport'],['82','ShiftVarianceImport'],['61','SkuCreateImport'],['40','UserCreateUpdate'],['62','Pack Status Update'],['63','InboundImportWithSTO'],['65','BackToStatusImport']];
const pageSizes=[20,50,100,200], statuses=[['-1','--- Select ---'],['1','Processed'],['0','UnProcessed'],['9','Failed'],['11','InProcessing']];
const one=(id)=>importTypes.find(x=>x[0]===String(id));
const page=(items,b)=>{const rows=pageSizes.includes(+b.rows)?+b.rows:20,p=Math.max(1,+b.page||1);return{rows:items.slice((p-1)*rows,p*rows),page:p,total:Math.ceil(items.length/rows),records:items.length,pageSize:rows}};
export default async function handler(req,res){if(cors(req,res))return;try{if(req.method==='GET')return res.json({importTypes:[['-1','--- Select ---'],...importTypes],statuses,pageSizes,maxRows:10000,organisation:'USPL',database:'09',endpoints:{subtypes:'getImportSubTypeConfig',classifications:'getImportClassifications',upload:'CommonImportExcel',search:'commonJsonSearch',details:'fetchimportFileDetails',dateValidation:'jsonValidateDateRange',template:'downloadDocumentFromAWS'}});if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{};
if(b.action==='config'){const t=one(b.importType);if(!t)return res.status(400).json({error:'Please Select Import Type'});return res.json({subtypes:[['0',t[1]]],classifications:[['1','Default']],classificationLabel:'Classifications',templateHidden:b.importType==='67',notes:[...(b.importType==='66'?['MerchHierarchay import can have maximum of rows: 1000']:[]),...(b.importType==='46'?['**Note : 1 Asn can have maximum of rows : 1200']:[])]});}
if(b.action==='template'){const t=one(b.importType);if(!t)return res.status(400).json({error:'Please Select Import Type'});const subtype=b.subtypeText||t[1],classification=b.classificationText||'Default',fileName=`VIN_REP_${t[1]}_USPL_${subtype}_${classification}.xlsx`;return res.json({fileName,downloadUrl:`downloadDocumentFromAWS?fileWithTime=${encodeURIComponent('imports/'+fileName)}&source=importTemplate`});}
if(b.action==='search'){if(!b.fromDate||!b.toDate)return res.status(400).json({error:'Upload Date is mendatory'});const all=await find('admin_records',{type:'common-import-batch'}),items=all.filter(x=>(!b.importType||b.importType==='-1'||x.importType===b.importType)&&(!b.status||b.status==='-1'||x.statusCode===b.status));return res.json(page(items,b));}
if(b.action==='details'){const all=await find('admin_records',{type:'common-import-detail'}),items=all.filter(x=>(!b.batchId||x.batchId===b.batchId)&&(!b.importType||b.importType==='-1'||x.importType===b.importType));return res.json(page(items,b));}
if(b.action!=='import')return res.status(400).json({error:'Unsupported Common Import action'});if(!one(b.importType))return res.status(400).json({error:'Please Select Import Type'});if(b.subtype==='-1')return res.status(400).json({error:'Please SelectImport SubType'});if(b.classification==='-1')return res.status(400).json({error:'Please Select Classification'});if(!b.fileName)return res.status(400).json({error:'No file chosen to import.'});const lines=String(b.content||'').split(/\r?\n/).filter(x=>x.trim());if(lines.length>10000)return res.status(400).json({error:'Maximum rows can be imported in an attempt of Import: 10000'});const t=one(b.importType),batchId=`CIB${Date.now()}`,now=new Date().toISOString(),source=lines.length?lines:[''];let failed=0;for(let i=0;i<source.length;i++){const cols=source[i].split(','),fail=/fail|error|invalid/i.test(source[i]);if(fail)failed++;await insert('admin_records',{type:'common-import-detail',batchId,importType:t[1],importTypeKey:t[0],seqNo:cols[0]||String(i+1),generatedKey:fail?'':cols[1]||`${t[1]}-${i+1}`,errorCode:fail?(cols[2]||'Import validation failed'):'',remarks:fail?'Failed':'Processed',key1:cols[1]||'',clientID:''});}const status=failed?'Failed':'Processed',record=await insert('admin_records',{type:'common-import-batch',importType:t[0],importTypeText:t[1],requestId:batchId,fileName:b.fileName,uploadDate:now,successRecords:source.length-failed,failedRecords:failed,status,statusCode:failed?'9':'1',uploadBy:'LOCAL',storedFile:`${batchId}_${b.fileName}`});return res.status(201).json({record,message:'Import submitted successfully'});}catch(e){console.error('common import error:',e);return res.status(500).json({error:e.message})}}
