import { cors, find, findOne, update, insert } from './mongo.js';
const text=v=>String(v??'').trim();
const reasons=[['22','Myntra - Missing Product'],['01','Expired'],['02','Near Expiry'],['10','wrong print'],['12','Damage 1212'],['13','Wrong Item'],['15','may9nehra989'],['16','ra989'],['17','Myntra - Different Product'],['18','Myntra - Fake Product'],['19','Myntra - Received in Damaged State'],['1','Damaged Product'],['2','Wrong Product'],['3','Delay'],['5','EXPIRY PRODUCT'],['6','Broken Boxes'],['7','Test'],['8','Job Work Required'],['9','asdf'],['20','Myntra - Used and seal Broken'],['21','Myntra - Weight Difference']];
const norm=x=>({id:x.id,inboundNo:x.inbound_no||x.grn_no||'',grnNo:x.grn_no||'',grnDate:x.grn_date||'',qcStatus:x.qc_done?'QC Done':x.qc_started?'in QC':'',status:x.status||'',lines:(x.lines||x.line_items||[]).map((l,i)=>({id:i+1,skuCode:l.skuCode||l.sku_code||'',skuDesc:l.skuDesc||l.product_name||l.sku_name||'',rcvQty:Number(l.rcvdQty||l.received_qty||l.qty||0),qcQty:Number(l.qcQty||0),binCode:l.binLoc||l.bin_code||'',binQty:Number(l.binQty||0),lotNo:l.lotCode||l.lot_no||'',toLPN:l.toLPN||''})),rejected:x.qc_rejected||[]});
export default async function handler(req,res){if(cors(req,res))return;try{const all=await find('grn');if(req.method==='GET')return res.json({scanTypes:[['3','Hold'],['1','Pass'],['2','Reject']],reasons,inbounds:all.map(norm),pageSizes:[20,50,100,200]});if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{};
 if(b.action==='search'){if(!text(b.inboundNo)&&!text(b.grnNo))return res.status(400).json({error:'Please fill either Inbound No or GRN No'});const row=all.find(x=>(!text(b.inboundNo)||text(x.inbound_no||x.grn_no).includes(text(b.inboundNo)))&&(!text(b.grnNo)||text(x.grn_no).includes(text(b.grnNo))));if(!row)return res.status(404).json({error:'No Data Found'});return res.json({row:norm(row),jsonMessage:null});}
 const row=await findOne('grn',{id:+b.id});if(!row)return res.status(404).json({error:'Cannot Save as Either of Inbound or GRN is not valid.'});
 if(b.action==='scan'){if(!text(b.skuCode))return res.status(400).json({error:'SKU Code is mandatory.'});if(b.scanType==='2'&&(!text(b.reasonCode)||b.reasonCode==='-1'))return res.status(400).json({error:'Reason is mandatory.'});const line=(row.lines||row.line_items||[]).find(x=>[x.skuCode,x.sku_code,x.barcode].some(v=>text(v).toLowerCase()===text(b.skuCode).toLowerCase()));if(!line)return res.status(404).json({error:'Invalid SKU Code'});const rejected=row.qc_rejected||[],entry={skuNo:line.skuCode||line.sku_code,uniqueNo:'',skuDesc:line.skuDesc||line.product_name||'',rejQty:Number(b.qty||1),reason:b.reason,remarks:text(b.remarks),toLPN:text(b.toLPN),referenceNo:row.grn_no||''};if(b.scanType==='2')rejected.push(entry);await update('grn',row.id,{qc_started:true,qc_rejected:rejected});return res.json({jsonMessage:'SKU processed successfully',row:norm({...row,qc_started:true,qc_rejected:rejected})});}
 if(b.action==='confirm'){await update('grn',row.id,{qc_started:true,qc_done:true,qc_completed_date:new Date().toISOString()});return res.json({jsonMessage:'Inbound QC confirmed successfully',row:norm({...row,qc_done:true})});}
 if(b.action==='create-rtv'){if(!(row.qc_rejected||[]).length)return res.status(400).json({error:'No data to create RTV '});const rtv=await insert('generic_records',{module:'inbound-rtv',code:`RTV${Date.now()}`,inbound_no:row.inbound_no||row.grn_no,status:'Created',lines:row.qc_rejected,created_date:new Date().toISOString()});return res.json({jsonMessage:'RTV created successfully',rtv});}
 return res.status(400).json({error:'Invalid action'});
}catch(e){console.error('Inbound QC error:',e);res.status(500).json({error:e.message})}}
