import{cors,find,update,insert}from'./mongo.js';
const t=v=>String(v??'').trim(),has=(v,q)=>!t(q)||t(q)==='-1'||t(v).toLowerCase().includes(t(q).toLowerCase());
const statuses={1:'Pending Confirmation',2:'Pending Hold',3:'GRN In Process',4:'Confirmed',7:'Cancelled'},types={6:'With QC',8:'Against ASN',3:'Delivered Return',4:'Non Delivered Return',1:'With PO',5:'With STO',2:'Without PO'};
const code=x=>String(x.status_code||({Confirmed:4,'Pending Confirmation':1,'Pending Hold':2,'GRN In Process':3,Cancelled:7,Received:4}[x.status]||1));
const norm=x=>({id:x.id,clientId:'0',inboundNo:x.inbound_no||x.grn_no||x.asn_no||`INB${x.id}`,extInboundCode:x.ext_inbound_no||x.ext_asn_no||'',transferNo:x.transfer_no||'',asnNumber:x.asn_no||'',poNo:x.po_no||'',GRNNo:x.grn_no||'',GRNDate:x.grn_date||'',createdDate:x.created_date||x.grn_date||x.asn_date||'',displayInboundType:x.inbound_type||x.asn_type_text||x.asn_type||x.type||'With PO',invoiceNo:x.invoice_no||'',vendorCode:x.vendor_code||x.vendor||'',vendorName:x.vendor||'',expQty:Number(x.expected_qty||x.qty||x.received_qty||0),rcvQty:Number(x.received_qty||0),status:x.status==='Received'?'Confirmed':x.status||'Pending Confirmation',qcStatus:x.qc_done?'QC Done':x.qc_started?'in QC':'',inboundLoc:x.warehouse||'JX Karawaci',statusCode:code(x),refNo:x.asn_no||'',commonInboundType:x.common_inbound_type||'',extCustReturnNo:x.ext_return_no||'',extInvoiceNo:x.ext_invoice_no||'',skuCode:x.sku_code||'',orderNo:x.order_no||'',lotCode:x.lot||'',usnNo:x.usn_no||'',inbLpn:x.inbound_lpn||'',hierarchyCode:x.hierarchy_code||'',putAwayCount:Number(x.putaway_count||0)});
const paged=(items,b)=>{const rows=[20,50,100,200].includes(+b.rows)?+b.rows:20,p=Math.max(1,+b.page||1),records=items.length,total=Math.ceil(records/rows),slice=items.slice((p-1)*rows,p*rows);return{inboundList:slice,gridModel:slice,rows,page:p,total,records,sidx:t(b.sidx)||'inbound0_.crtDate',sord:t(b.sord)||'desc',loadonce:false,jsonMessage:null,putAwayCount:0}};
const matchOption=(value,q,map)=>!t(q)||t(q)==='-1'||has(value,map[q]||q);
export default async function handler(req,res){if(cors(req,res))return;try{const b=req.body||{},raw=await find('grn'),all=raw.map(norm);
if(req.method==='GET'){const partners=await find('partners'),products=await find('products');const hierarchies=[...new Map(products.filter(x=>x.category||x.department).map(x=>[x.category||x.department,{code:x.category_code||x.category||x.department,name:x.category||x.department}])).values()];return res.json({clients:[['0','0-DummyClient']],locations:[['UWH','UWH-JX Karawaci']],statuses:Object.entries(statuses),inboundTypes:['6','8','3','4','1','5','2'].map(k=>[k,types[k]]),qcStatuses:[['0','in QC'],['1','QC Done']],vendors:partners.filter(x=>x.partner_type==='Vendor').map(x=>({id:x.id,code:x.vendor_code||String(x.id),name:x.name})),hierarchies,pageSizes:[20,50,100,200]})}
if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
if(b.action==='search'||b.REQ_SEARCH_FLAG){if((t(b.ExtCustReturnNo)||t(b.ExtInvoiceNo))&&!['3','4','Delivered Return','Non Delivered Return'].includes(t(b.inboundType)))return res.status(400).json({error:'To search with return no or invoice no inbound type should be either delivered return or non delivered return'});const lots=t(b.lotNoArr).split(/\r?\n/).filter(Boolean);if(lots.length>100)return res.status(400).json({error:'Max 100 Records Can Be Entered'});let rows=all.filter(x=>has(x.inboundNo,b.fromInboundNo)&&has(x.extInboundCode,b.fromExtInboundNo)&&has(x.transferNo,b.transferNo)&&has(x.asnNumber,b.asnNumber)&&has(x.poNo,b.PONo)&&has(x.GRNNo,b.fromGRNNo)&&has(x.invoiceNo,b.fromInvoiceNo)&&has(x.vendorCode,b.vendorCode)&&matchOption(x.displayInboundType,b.inboundType,types)&&matchOption(x.status,b.status,statuses)&&matchOption(x.qcStatus,b.qcStatus,{0:'in QC',1:'QC Done'})&&has(x.skuCode,b.skuCode)&&has(x.orderNo,b.orderNo)&&has(x.lotCode,b.lotCode)&&(!lots.length||lots.some(v=>has(x.lotCode,v)))&&has(x.usnNo,b.usnNo)&&has(x.inbLpn,b.inbLpn)&&has(x.hierarchyCode,b.mhierachyCode)&&has(x.extCustReturnNo,b.ExtCustReturnNo)&&has(x.extInvoiceNo,b.ExtInvoiceNo)&&(!t(b.fromCreatedDate)||x.createdDate>=b.fromCreatedDate)&&(!t(b.toCreatedDate)||x.createdDate.slice(0,10)<=b.toCreatedDate)&&(!t(b.fromGRNDate)||x.GRNDate>=b.fromGRNDate)&&(!t(b.toGRNDate)||x.GRNDate.slice(0,10)<=b.toGRNDate));rows.sort((a,z)=>t(a.createdDate).localeCompare(t(z.createdDate))*(t(b.sord)==='asc'?1:-1));return res.json(paged(rows,b))}
if(['qc','putaway'].includes(b.action)){if(!b.id)return res.status(400).json({error:'Please select a row.'});const row=raw.find(x=>x.id===+b.id);if(!row)return res.status(404).json({error:'Inbound record not found'});const n=norm(row);if(n.displayInboundType==='With QC')return res.status(400).json({error:'inboundMaintenance.FNVType.inbound'});if(!['3','4'].includes(n.statusCode))return res.status(400).json({error:'Inbound Status should be Confirmed or GRN in process'});if(b.action==='qc'){await update('grn',row.id,{qc_started:true});return res.json({jsonMessage:'Inbound opened for QC',target:`/app/r/inbound-qc?inboundNo=${encodeURIComponent(n.inboundNo)}`})}if(!n.putAwayCount){await update('grn',row.id,{putaway_requested:true,putaway_count:1});await insert('generic_records',{module:'putaway',code:`PA${Date.now()}`,inbound_no:n.inboundNo,status:'Open',created_date:new Date().toISOString()})}return res.json({jsonMessage:n.putAwayCount?'Existing PutAway opened':'PutAway generated successfully',target:`/app/r/putaway-enquiry?inboundNo=${encodeURIComponent(n.inboundNo)}`})}
return res.status(400).json({error:'Invalid action'})}catch(e){console.error('Inbound Enquiry error:',e);res.status(500).json({error:e.message})}}
