import{find,findOne,insert,update,cors}from'./mongo.js';
const M='kitting-order',t=v=>String(v??'').trim(),has=(v,q)=>!t(q)||t(q)==='-1'||t(v).toLowerCase().includes(t(q).toLowerCase());
const paged=(rows,b,sizes=[20,50,100,200])=>{const size=sizes.includes(Number(b.rows))?Number(b.rows):sizes[0],page=Math.max(1,Number(b.page)||1),records=rows.length,total=Math.ceil(records/size),gridModel=rows.slice((page-1)*size,page*size);return{gridModel,rows:gridModel,page,records,total}};
export default async function handler(req,res){if(cors(req,res))return;try{const list=await find('generic_records',{module:M});
if(req.method==='GET')return res.json({locations:await find('generic_records',{module:'location'}),skus:await find('skus',{}),orders:await find('sale_orders',{}),comments:await find('generic_records',{module:'kitting-order-comment'}),deliveries:await find('generic_records',{module:'order_delivery'})});
const b=req.body||{};
if(req.method==='POST'&&b.action==='unkit-search'){let rows=(await find('skus',{})).map(r=>({id:r.id,bom_sku_code:r.sku_code||r.code,sku_code:r.sku_code||r.code,sku_desc:r.name||r.description||'',lot_no:r.lot_no||'',bin:r.bin||'',available_qty:Number(r.available_qty??r.stock??10),qty:'',lpn:r.lpn||'',client:r.client||'DummyClient'})).filter(r=>has(r.sku_code,b.searchSku)&&has(r.sku_desc,b.searchSkuDescr)&&has(r.lot_no,b.lotNo)&&has(r.bin,b.binLoc)&&has(r.lpn,b.LPNID));return res.json(paged(rows,b,[20,50,100]))}
if(req.method==='POST'&&b.REQ_SEARCH_FLAG){let rows=list.filter(r=>has(r.code,b.fromOrderNo)&&has(r.ext_order_no,b.fromExternOrderNo)&&has(r.status,b.status)&&has(r.created_date,b.orderDate)&&has(r.type,b.odrCreateType)&&has(r.created_by,b.crtby)&&has(r.updated_by,b.updby)&&has(r.error_description,b.errorDesc)&&has(r.site_code,b.siteLoc)&&has(r.order_type,b.orderType)&&has(r.order_source,b.orderSource)&&has(r.source_wh,b.srcWH)&&has(r.sku_code,b.SkuCode)&&has(r.customer_name,b.customerName)&&has(r.customer_code,b.custCode)&&has(r.external_status,b.extStatus)&&has(r.sub_order_id,b.subOrderId)&&has(r.transporter_status,b.transporterStatus)&&has(r.order_tag,b.orderTag));rows.sort((a,c)=>t(a.code).localeCompare(t(c.code))*(t(b.sord)==='desc'?-1:1));return res.json(paged(rows,b))}
if(req.method==='POST'&&['save','confirm'].includes(b.action)){const lines=Array.isArray(b.lines)?b.lines:[];if(!lines.length)return res.status(400).json({error:'Please select SKUs for an Order'});if(!t(b.site_code))return res.status(400).json({error:'Site Location is mandatory.'});const old=b.id?await findOne('generic_records',{id:Number(b.id)}):null,code=t(b.code)||old?.code||`KIT${Date.now()}`,data={module:M,code,ext_order_no:t(b.ext_order_no),status:b.action==='confirm'?'Confirmed':old?.status||'Pending',created_date:old?.created_date||new Date().toISOString().slice(0,10),bom_qty:lines.reduce((n,x)=>n+Number(x.qty||0),0),child_qty:lines.reduce((n,x)=>n+Number(x.child_qty||0),0),type:t(b.type)||'SKU',created_by:old?.created_by||'Local User',updated_by:'Local User',error_description:'',client_id:t(b.client_id)||'0',site_code:t(b.site_code),remarks:t(b.remarks),on_hold:!!b.on_hold,udf1:t(b.udf1),udf2:t(b.udf2),udf3:t(b.udf3),udf4:t(b.udf4),udf5:t(b.udf5),lines};let row;if(old){await update('generic_records',old.id,data);row=await findOne('generic_records',{id:old.id})}else row=await insert('generic_records',data);return res.status(old?200:201).json({message:b.action==='confirm'?'Order Confirmed Successfully.':'Order Saved Successfully.',order:row})}
if(req.method==='POST'&&b.action==='comment'){if(!t(b.comments))return res.status(400).json({error:'Add Order Comments is mandatory.'});return res.status(201).json({message:'User Activity Comments Saved Successfully.',row:await insert('generic_records',{module:'kitting-order-comment',order_id:Number(b.id),comments:t(b.comments),activity_date:new Date().toISOString(),activity_user:'Local User'})})}
if(req.method==='POST'&&b.action==='complete'){const ids=Array.isArray(b.ids)?b.ids.map(Number):[];if(!ids.length)return res.status(400).json({error:'No row selected'});let updated=0;for(const id of ids){const row=await findOne('generic_records',{id});if(row?.module===M){await update('generic_records',id,{status:'Completed',updated_by:'Local User',completed_at:new Date().toISOString()});updated++}}return res.json({message:'Order Complete successfully.',updated})}
return res.status(400).json({error:'Unknown action'});
}catch(e){console.error('kitting orders error:',e);return res.status(500).json({error:e.message})}}
