import { cors,find,insert,update,remove } from './mongo.js';
const text=v=>String(v??'').trim(),has=(v,q)=>!text(q)||text(q)==='-1'||text(v).toLowerCase().includes(text(q).toLowerCase());
const normalize=r=>({...r,ruleId:r.rule_id||r.code||'',ruleDesc:r.rule_desc||r.name||'',locCode:r.loc_code||'UWH',location:r.location||'JX Karawaci',method:r.method||'Approx Qty',methodId:r.method_id||'1',uom:r.uom||'Kg',active:r.active!==false,ruleParameter:r.rule_parameter||'1',merchHierarchy:r.merch_hierarchy||'',skuCode:r.sku_code||'',brand:r.brand||'',vendor:r.vendor||'',skuGroup:r.sku_group||'',skuLocationTags:r.sku_location_tags||[],skuNature:r.sku_nature||'-1',isFragile:!!r.is_fragile,isCICO:!!r.is_cico,searchPriorities:r.search_priorities||['10','20','30','40','50','60'],noOfIteration:r.no_of_iteration||'1',steps:r.steps||[]});
const headerError=b=>!text(b.ruleDesc)?'Please Enter Rule Description.':!text(b.locCode)||b.locCode==='-1'?'Please select location':!text(b.methodId)?'PutAway Method cannot be empty.':!text(b.uom)?'Please select uom':!text(b.ruleParameter)||b.ruleParameter==='-1'?'Priority Can Not be Blank':b.ruleParameter==='2'&&!text(b.skuCode)?'SKU Code is Mandatory.':['3','4','5'].includes(b.ruleParameter)&&!text(b.merchHierarchy)?'Please select any one Hierarchy except parent level Hierarchy.':b.ruleParameter==='6'&&!text(b.brand)?'Please select Brand.':b.ruleParameter==='7'&&!text(b.vendor)?'Please Enter Vendor Code':'';
const stepError=(s,steps=[])=>!text(s.stepNo)?'Please enter Step No.':s.invBucket==='-1'&&(!text(s.zone)||s.zone==='-1')&&!text(s.fromBin)&&!text(s.toBin)?'Please fill either Zone or Bin':s.invBucket==='-1'&&(!text(s.zone)||s.zone==='-1')&&!text(s.fromBin)?'Please enter From Bin.':s.invBucket==='-1'&&(!text(s.zone)||s.zone==='-1')&&!text(s.toBin)?'Please enter To Bin.':steps.some(x=>text(x.stepNo)===text(s.stepNo))?'step no already exists':'';
export default async function handler(req,res){if(cors(req,res))return;try{const b=req.body||{},all=await find('generic_records',{module:'putaway-rule'});
 if(req.method==='GET'){const generic=await find('generic_records');return res.json({zones:generic.filter(x=>x.module==='wms-zone').map(x=>({code:x.code,description:x.description||x.name})),bins:generic.filter(x=>x.module==='bin-enquiry').map(x=>x.code),rules:all.map(normalize),locations:[{code:'UWH',name:'JX Karawaci'}],uoms:['Kg','Each','Case','INNER PACK','CASEPACK10','palette','KGS','Litres'],brands:['@Home by Nilkamal','(NIL)','Nike','Adidas'],skuLocationTags:['TAG1','TAG10','TAG2','TAG3','TAG4','TAG5','TAG6','TAG7','TAG8','TAG9']})}
 if(req.method==='POST'&&(b.REQ_SEARCH_FLAG||b.action==='search')){let rows=all.map(normalize).filter(r=>has(r.ruleId,b.ruleId)&&has(r.ruleDesc,b.ruleDesc)&&has(r.locCode,b.locCode)&&has(r.methodId,b.methodId)&&has(r.merchHierarchy,b.merchHierarchy)&&has(r.skuCode,b.skuCode)&&has(r.brand,b.brand)&&has(r.vendor,b.vendor)&&(b.isActive!==true||r.active));rows.sort((a,c)=>text(a.ruleId).localeCompare(text(c.ruleId))*(text(b.sord)==='asc'?1:-1));const size=[20,50,100,200].includes(Number(b.rows))?Number(b.rows):20,page=Math.max(1,Number(b.page)||1),records=rows.length,total=Math.ceil(records/size),gridModel=rows.slice((page-1)*size,page*size);return res.json({gridModel,rows:gridModel,page,records,total})}
 if(req.method==='POST'&&b.action==='validate-step'){const error=stepError(b.step,b.steps);return error?res.status(400).json({error}):res.json({ok:true})}
 if((req.method==='POST'&&b.action==='save')||req.method==='PUT'){const error=headerError(b);if(error)return res.status(400).json({error});for(let i=0;i<(b.steps||[]).length;i++){const se=stepError(b.steps[i],(b.steps||[]).slice(0,i));if(se)return res.status(400).json({error:se})}let existing=b.id?all.find(x=>x.id===Number(b.id)):null;if(!existing&&b.ruleId)existing=all.find(x=>normalize(x).ruleId===b.ruleId);const next=Math.max(0,...all.map(x=>Number(text(normalize(x).ruleId).replace(/\D/g,''))||0))+1,ruleId=existing?normalize(existing).ruleId:`PAR${String(next).padStart(6,'0')}`;const fields={module:'putaway-rule',code:ruleId,rule_id:ruleId,name:text(b.ruleDesc),rule_desc:text(b.ruleDesc),loc_code:text(b.locCode),location:'JX Karawaci',method_id:text(b.methodId),method:b.methodId==='2'?'Cubic Volume':'Approx Qty',uom:text(b.uom),active:!!b.active,rule_parameter:text(b.ruleParameter),merch_hierarchy:text(b.merchHierarchy),sku_code:text(b.skuCode),brand:text(b.brand),vendor:text(b.vendor),sku_group:text(b.skuGroup),sku_location_tags:b.skuLocationTags||[],sku_nature:text(b.skuNature),is_fragile:!!b.isFragile,is_cico:!!b.isCICO,search_priorities:b.searchPriorities||[],no_of_iteration:text(b.noOfIteration),steps:b.steps||[],modified_by:'super admin',modified_date:new Date().toISOString()};if(existing){const changed=await update('generic_records',existing.id,fields);return res.json({row:normalize(changed[0]),jsonMessage:'Data saved successfully.'})}const row=await insert('generic_records',{...fields,created_by:'super admin',created_date:new Date().toISOString()});return res.status(201).json({row:normalize(row),jsonMessage:'Data saved successfully.'})}
 if(req.method==='DELETE'){const current=all.find(x=>x.id===Number(b.id));if(!current)return res.status(404).json({error:'PutAway Rule was not found.'});await remove('generic_records',current.id);return res.json({jsonMessage:'PutAway Rule deleted successfully.'})}return res.status(405).json({error:'Method not allowed'});
 }catch(error){console.error('PutAway Rule error:',error);return res.status(500).json({error:error.message})}}
