import { cors, find, insert, update } from './mongo.js';
const text=v=>String(v??'').trim(), has=(v,q)=>!text(q)||text(v).toLowerCase().includes(text(q).toLowerCase());
const parse=v=>{const s=text(v).slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return new Date(s+'T00:00:00Z');const m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?new Date(`${m[3]}-${m[2]}-${m[1]}T00:00:00Z`):null};
const fmt=v=>{const d=parse(v);return d?`${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`:text(v)};
const norm=r=>({...r,putAwayId:r.putAwayId||r.putaway_no||r.code,status:r.status||'Open',hdnStatus:r.hdnStatus||({Open:'1',Confirmed:'4','Part Confirmed':'5',Cancelled:'7',Closed:'13'}[r.status]||'10'),createDate:r.createDate||r.created_date||'',confirmedDate:r.confirmedDate||r.confirmed_date||'',putAwayType:r.putAwayType||r.putaway_type||r.name||'Selected Inbound RealTime',toQty:Number(r.toQty??r.putaway_qty??r.qty??0),locCode:r.locCode||r.location_name||'JX Karawaci',siteLocCode:r.siteLocCode||r.location_code||'UWH',inboundNo:r.inboundNo||r.inbound_no||'',remarks:r.remarks||'',createdBy:r.createdBy||r.created_by||'local.user',modifiedBy:r.modifiedBy||r.modified_by||'local.user',details:r.details||[]});
const nextCode=rows=>`UWH${String(Math.max(0,...rows.map(r=>Number(text(r.putAwayId||r.code).replace(/\D/g,''))))+1).padStart(9,'0')}`;
export default async function handler(req,res){if(cors(req,res))return;try{
 if(req.method==='GET'){const rows=(await find('generic_records',{module:'putaway'})).map(norm);const id=text(req.query?.putAwayNo);return res.json(id?{row:rows.find(r=>r.putAwayId===id)||null}:{statuses:[['-1','--- Select ---'],['7','Cancelled'],['13','Closed'],['4','Confirmed'],['1','Open'],['5','Part Confirmed'],['10','Undefined']],types:[['-1','--- Select ---'],['1','Cancelled Order'],['2','Selected Inbound'],['5','Selected Inbound RealTime'],['3','User defined_Cancelled Order']],locations:[['UWH','UWH-JX Karawaci']],pageSizes:[20,50,100,200],maxDateRangeDays:90})}
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{},rows=(await find('generic_records',{module:'putaway'})).map(norm);
 if(b.action==='export'||b.action==='detail-export'){if(!Number(b.gridDataLen))return res.status(400).json({error:'No data found'});const reportId=`${b.action==='detail-export'?'PAD':'PAE'}-${Date.now()}`;await insert('generic_records',{module:'pending-report',code:reportId,name:b.action==='detail-export'?'PutAway Detail Export':'PutAway Export',status:'Pending',created_date:new Date().toISOString()});return res.json({jsonMessage:null,reportId})}
 if(b.action==='create'){if(text(b.type)==='-1'||!text(b.type))return res.status(400).json({error:'Putaway Type is mandatory'});if(['2','5'].includes(text(b.type))&&!text(b.inboundNo))return res.status(400).json({error:'Select atleast one inbound for putaway'});if(text(b.type)==='5'&&(!text(b.mode)||text(b.mode)==='-1'))return res.status(400).json({error:'Putaway Mode is Mandatory'});if(text(b.type)==='2'&&!Array.isArray(b.qcstatus))return res.status(400).json({error:'QC Status is Mandatory'});const type={1:'Cancelled Order',2:'Selected Inbound',5:'Selected Inbound RealTime',3:'User defined_Cancelled Order'}[b.type],putAwayId=nextCode(rows),now=new Date().toISOString(),row=await insert('generic_records',{module:'putaway',code:putAwayId,putAwayId,status:'Open',putAwayType:type,putaway_type:type,inboundNo:text(b.inboundNo),inbound_no:text(b.inboundNo),remarks:text(b.remarks),toQty:Number(b.qty||1),putaway_qty:Number(b.qty||1),locCode:'JX Karawaci',siteLocCode:'UWH',created_date:now,createdBy:'local.user',details:[{skuCode:'DS10',skuName:'Local PutAway SKU',inboundNo:text(b.inboundNo),lineNo:1,lpn:'LPN-LOCAL',lot:'LOT-LOCAL',fromBin:'BIN-A',suggestedBin:'BIN-B',qty:Number(b.qty||1),putawayQty:0}]});return res.status(201).json({row:norm(row)})}
 if(['save','confirm','cancel'].includes(b.action)){const row=rows.find(r=>r.putAwayId===text(b.putAwayId));if(!row)return res.status(404).json({error:'PutAway not found'});if(!row.details.length)return res.status(400).json({error:b.action==='confirm'?'Nothing to confirm':b.action==='cancel'?'Nothing to cancel':'Nothing to save'});const status=b.action==='confirm'?'Confirmed':b.action==='cancel'?'Cancelled':row.status,confirmedDate=b.action==='confirm'?new Date().toISOString():row.confirmedDate;await update('generic_records',row.id,{status,confirmedDate,confirmed_date:confirmedDate,modifiedBy:'local.user',modified_date:new Date().toISOString(),details:b.details||row.details});return res.json({row:{...row,status,confirmedDate,details:b.details||row.details}})}
 if(!b.REQ_SEARCH_FLAG)return res.status(400).json({error:'REQ_SEARCH_FLAG is required'});if(!text(b.CreatedDate)&&!text(b.putAwayNo))return res.status(400).json({error:'common.putAwayDateValid.message04'});const from=parse(b.fromCreatedDate||text(b.CreatedDate).split(' - ')[0]),to=parse(b.toCreatedDate||text(b.CreatedDate).split(' - ')[1]);if(from&&to&&(to-from)/86400000>90)return res.status(400).json({error:'PutAwayDate range can not be greater than 90 days'});
 let filtered=rows.filter(r=>has(r.putAwayId,b.putAwayNo)&&has(r.inboundNo,b.inboundNo)&&(!text(b.status)||text(b.status)==='-1'||r.hdnStatus===text(b.status))&&(!text(b.putAwayType)||text(b.putAwayType)==='-1'||r.putAwayType===({1:'Cancelled Order',2:'Selected Inbound',5:'Selected Inbound RealTime',3:'User defined_Cancelled Order'}[b.putAwayType])));if(from&&to)filtered=filtered.filter(r=>{const d=parse(r.createDate);return d&&d>=from&&d<=to});filtered.sort((a,z)=>text(z.putAwayId).localeCompare(text(a.putAwayId)));const size=[20,50,100,200].includes(+b.rows)?+b.rows:20,page=Math.max(1,+b.page||1),records=filtered.length,total=Math.ceil(records/size),gridModel=filtered.slice((page-1)*size,page*size).map(r=>({...r,createDate:fmt(r.createDate),confirmedDate:fmt(r.confirmedDate)}));return res.json({gridModel,putAwayList:gridModel,rows:size,page,records,total});
 }catch(e){console.error('putaway enquiry error:',e);return res.status(500).json({error:e.message})}}
