// Initial data used to seed MongoDB (on first connect) and the in-memory
// fallback store. Mirrors the original dataset exactly.
export const SEED = {
  fulfillment_audit: [],
  delivery_shipping_audit: [],
  inventory_moves: [],
  inventory_lottables: [],
  stock_adjustments: [],
  outbound_gate_passes: [],
  outbound_memos: [],
  sku_transactions: [],
  sku_lot_transfers: [],
  vin_lister_products: [
    { sku_code: 'TSHIRT-BLK-M', product_name: 'Cotton Crew Neck T-Shirt - Black', category: 'Fashion & Accessories', images: [], marketplaces: ['Amazon', 'Shopify'], prices: { Amazon: 1299, Shopify: 1299 }, status: 'Ready' },
    { sku_code: 'SERUM-VITC-30', product_name: 'Vitamin C Face Serum 30ml', category: 'Health n Beauty', images: [], marketplaces: ['Amazon'], prices: { Amazon: 899 }, status: 'Ready' },
  ],
  vin_lister_imports: [],
  vin_lister_exports: [],
  vin_lister_transmit_logs: [],
  ars_sku_links: [
    { sku_code: 'SERUM-VITC-30', sku_name: 'Vitamin C Face Serum 30ml', location: 'Mumbai WH', location_type: 'Warehouse', category: 'Beauty', brand: 'GlowLab', primary_vendor: 'VEN004', fulfilment_method: 'Direct Store Purchase', fulfilment_wh: 'Mumbai WH', wh_lead_time: 2, stock_cover_days: 2, ars_flag: 'Active', created_date: '2019-04-18', updated_date: '2019-04-18' },
    { sku_code: 'TSHIRT-BLK-M', sku_name: 'Cotton Crew Neck T-Shirt - Black', location: 'Delhi NCR', location_type: 'Warehouse', category: 'Apparel', brand: 'UrbanEdge', primary_vendor: 'VEN001', fulfilment_method: 'Distribution Centre', fulfilment_wh: 'Delhi NCR', wh_lead_time: 3, stock_cover_days: 7, ars_flag: 'Active', created_date: '2024-05-14', updated_date: '2024-05-14' },
  ],
  ars_rules: [
    { rule_id: '1003', description: 'Reebok', remarks: '', ars_method: 'Min-Max', minimum_qty: 5, maximum_qty: 20, ros_period: '', vendor_type: 'Primary', output_type: 'Confirmed', location: 'Mumbai WH', start_date: '2019-04-01', end_date: '2019-12-31', status: 'Active', frequency: 168, sku_sets: [{ type: 'Brand', operand: 'Equals', value: 'GlowLab' }], last_run_date: '2019-04-30', next_run_date: '2019-05-06', created_by: 'sa', updated_by: 'ArsSchdulr', updated_date: '2019-04-30' },
    { rule_id: '1002', description: 'Deltol', remarks: '', ars_method: 'Min-Max', minimum_qty: 10, maximum_qty: 30, ros_period: '', vendor_type: 'Min Cost', output_type: 'Pending', location: 'Delhi NCR', start_date: '2019-04-01', end_date: '2019-12-31', status: 'Active', frequency: 24, sku_sets: [{ type: 'Hierarchy', operand: 'Equals', value: 'Apparel' }], last_run_date: '2019-04-30', next_run_date: '2019-05-01', created_by: 'sa', updated_by: 'ArsSchdulr', updated_date: '2019-04-30' },
    { rule_id: '1001', description: 'Demo1', remarks: '', ars_method: 'Min-Max', minimum_qty: 2, maximum_qty: 10, ros_period: '', vendor_type: 'Primary', output_type: 'Pending', location: 'Delhi NCR', start_date: '2019-03-01', end_date: '2019-12-31', status: 'Active', frequency: 24, sku_sets: [{ type: 'SKU', operand: 'Equals', value: 'TSHIRT-BLK-M' }], last_run_date: '2019-03-31', next_run_date: '2019-04-19', created_by: 'sa', updated_by: 'sa', updated_date: '2019-04-18' },
  ],
  ars_execution_logs: [
    { execution_id: 'ARSEX-20190430-1003', rule_id: '1003', description: 'Reebok', location: 'Mumbai WH', started_at: '2019-04-30T00:00:00.000Z', completed_at: '2019-04-30T00:00:01.000Z', status: 'Completed', evaluated_skus: 1, generated_orders: 0, generated_po_codes: [], message: 'Rule evaluated successfully.' },
  ],
  ars_settings: [
    { enable_ars: true, calculation_hour: 2, ros_lifetime: true, ros_12_weeks: true, ros_6_weeks: false, ros_1_month: false, ros_2_weeks: false, custom_periods: ['', '', ''], updated_date: '2019-04-18', updated_by: 'sa' },
  ],
  ajio_config: [
    { channel_code: 'ABR', channel_type: 'AJIO JIT', channel_name: 'Ajio Seller', status: 'Active', order_fulfillment_wh: 'Delhi NCR', auto_range_sku: 'No', channel_sla_hours: 48, customer: 'AJIO JIT', tax_type: 'Tax Inclusive', order_sync: true, order_sync_from_date: '2026-08-08', order_sync_from_order_no: '', shipping_by: 'Ship By Marketplace', bill_to_party: 'AJIO JIT', invoice_no_by: 'Self', prepack_enabled: false, ready_to_ship_at: 'Manifest', each_qty_per_line: false, return_sync: false, return_sync_from_date: '', use_marketplace_invoice: true, use_marketplace_shipping_label: true, international_invoice: '', domestic_invoice: 'AJIO JIT', shipping_label: 'ShippingLabel_AJIO', inventory_sync_method: 'Pull', enable_inventory_reconciliation: false, reconciliation_frequency: 'Once Daily', seller_id: 'DVSELLER01', password_configured: true, is_b2b: true, enable_e_invoicing: false, e_invoicing_username: '', e_invoicing_password_configured: false, b2b_invoice_series: 'AJIOJIT', sku_sync: 'Pull', sku_create: 'Moderate', fetch_backorder: true, scan_lpn_on_picking: true, lpn_reuse_after_ship: true, unpack_access: false, shipping_label_report: 'ShippingLabel_AJIO', interface_status: 'Configured', updated_by: 'demo-admin', updated_date: '2026-08-08' },
  ],
  ajio_sku_mappings: [
    { article_code: 'AJIO-ART-1001', article_name: 'Cotton Crew Neck T-Shirt - Black', channel_sku_code: 'AJIO-ART-1001', channel_product_id: 'PID1001~VID1001', sku_code: 'TSHIRT-BLK-M', mapping_status: 'Mapped', inventory_sync: 'Active', published_inventory: 180, last_sync: '2026-08-08T10:30:00.000Z' },
    { article_code: 'AJIO-ART-1002', article_name: 'Slim Fit Denim Jeans - Blue', channel_sku_code: 'AJIO-ART-1002', channel_product_id: 'PID1002~VID1002', sku_code: 'JEANS-BLU-32', mapping_status: 'Mapped', inventory_sync: 'Active', published_inventory: 95, last_sync: '2026-08-08T10:30:00.000Z' },
    { article_code: 'AJIO-ART-1006', article_name: 'Laptop Backpack 25L - Grey', channel_sku_code: 'AJIO-ART-1006', channel_product_id: 'PID1006~VID1006', sku_code: '', mapping_status: 'Un-Mapped', inventory_sync: 'Waiting for Mapping', published_inventory: 0, last_sync: '' },
  ],
  ajio_backorders: [
    { ajio_po_no: '40184244', seller_order_no: 'AJIO-SO-884244', warehouse: 'Delhi NCR', received_at: '2026-08-08T08:15:00.000Z', status: 'Pending Pull', reservation_status: 'Not Reserved', released: false, lines: [{ sku_code: 'TSHIRT-BLK-M', qty: 4 }, { sku_code: 'JEANS-BLU-32', qty: 2 }] },
  ],
  ajio_orders: [
    { ajio_po_no: '40184240', sales_order_no: 'SO-AJIO-8240', customer: 'AJIO JIT', warehouse: 'Delhi NCR', order_date: '2026-08-08', status: 'Allocated', picklist_no: '', delivery_ids: [], lines: [{ sku_code: 'TSHIRT-BLK-M', sku_name: 'Cotton Crew Neck T-Shirt - Black', qty: 2, unit_price: 1299 }, { sku_code: 'BOTTLE-STL-1L', sku_name: 'Insulated Steel Bottle 1L', qty: 1, unit_price: 1199 }] },
  ],
  ajio_deliveries: [],
  ajio_invoices: [],
  ajio_manifests: [],
  amazon_mfn_config: [
    { channel_code: 'AMF', channel_type: 'Amazon India', channel_name: 'Amazon India MFN', region: 'India', country_code: 'IN', status: 'Active', order_fulfillment_wh: 'Delhi NCR', single_warehouse: true, auto_range_sku: 'No', channel_sla_hours: 48, customer: 'Amazon Customer', tax_type: 'Tax Inclusive', order_sync: true, order_sync_from_date: '2026-08-08', shipping_by: 'Ship By Marketplace', bill_to_party: 'Amazon India', invoice_no_by: 'Self', prepack_enabled: true, ready_to_ship_at: 'Pack', each_qty_per_line: false, return_sync: true, return_sync_from_date: '2026-08-08', use_marketplace_shipping_label: true, domestic_invoice: 'Amazon_MFN_Invoice', shipping_label: 'Amazon_MFN_Label', inventory_sync: true, inventory_sync_method: 'Push', safety_stock: 0, enable_inventory_reconciliation: true, reconciliation_frequency: 'Once Daily', seller_id: 'A2MFNSELLER01', marketplace_id: 'A21TJRUUN4KGV', endpoint: 'https://mws.amazonservices.in', access_key_configured: true, secret_key_configured: true, mws_token_configured: true, panel_user_id: 'amazon.mfn@example.invalid', panel_password_configured: true, developer_id: '073980952359', developer_name: 'vinculum', no_slot_on_sunday: 1, need_invoice: true, enable_easy_ship: true, enable_tracking_no_pull: false, otp_verified: false, interface_status: 'Configured', last_reconciliation_date: '', updated_by: 'demo-admin', updated_date: '2026-08-08' },
  ],
  amazon_mfn_mappings: [
    { merchant_sku: 'AMZ-TSHIRT-BLK-M', asin: 'B0AMZN1001', sku_code: 'TSHIRT-BLK-M', product_name: 'Cotton Crew Neck T-Shirt - Black', mapping_status: 'Mapped', listing_present: true, feed_status: 'Success', published_inventory: 180, last_sync: '2026-08-08T10:30:00.000Z' },
    { merchant_sku: 'AMZ-JEANS-BLU-32', asin: 'B0AMZN1002', sku_code: 'JEANS-BLU-32', product_name: 'Slim Fit Denim Jeans - Blue', mapping_status: 'Mapped', listing_present: true, feed_status: 'Success', published_inventory: 95, last_sync: '2026-08-08T10:30:00.000Z' },
    { merchant_sku: 'AMZ-BACKPACK-GRY', asin: 'B0AMZN1006', sku_code: '', product_name: 'Laptop Backpack 25L - Grey', mapping_status: 'Un-Mapped', listing_present: true, feed_status: 'Waiting for Mapping', published_inventory: 0, last_sync: '' },
    { merchant_sku: 'AMZ-NOT-LISTED', asin: 'B0MISSING999', sku_code: 'BOTTLE-STL-1L', product_name: 'Insulated Steel Bottle 1L', mapping_status: 'Mapped', listing_present: false, feed_status: 'Not Submitted', published_inventory: 0, last_sync: '' },
  ],
  amazon_mfn_orders: [
    { amazon_order_id: '408-7111111-1000001', marketplace_status: 'Pending', eretail_status: 'Not Pulled', customer_name: '', remote_customer_name: 'Amazon Buyer', city: '', remote_city: 'New Delhi', warehouse: 'Delhi NCR', order_date: '2026-08-08', latest_ship_date: '2026-08-10', reservation_status: 'Not Reserved', sales_order_no: '', invoice_no: '', shipping_label: '', tracking_no: '', transporter_name: '', label_status: 'Not Requested', pack_status: 'Not Packed', weight_kg: 0, length_cm: 0, width_cm: 0, height_cm: 0, cancelled: false, lines: [{ merchant_sku: 'AMZ-TSHIRT-BLK-M', sku_code: 'TSHIRT-BLK-M', qty: 2, unit_price: 1299 }] },
    { amazon_order_id: '408-7222222-2000002', marketplace_status: 'Un-Shipped', eretail_status: 'Not Pulled', customer_name: '', remote_customer_name: 'Priya Amazon', city: '', remote_city: 'Gurugram', warehouse: 'Delhi NCR', order_date: '2026-08-08', latest_ship_date: '2026-08-10', reservation_status: 'Not Reserved', sales_order_no: '', invoice_no: '', shipping_label: '', tracking_no: '', transporter_name: '', label_status: 'Not Requested', pack_status: 'Not Packed', weight_kg: 0, length_cm: 0, width_cm: 0, height_cm: 0, cancelled: false, lines: [{ merchant_sku: 'AMZ-JEANS-BLU-32', sku_code: 'JEANS-BLU-32', qty: 1, unit_price: 2499 }] },
  ],
  amazon_mfn_inventory_logs: [],
  amazon_mfn_returns: [
    { amazon_return_id: 'RET-AMZ-1001', amazon_order_id: '408-7000000-9000009', return_date: '2026-08-08', sku_code: 'TSHIRT-BLK-M', qty: 1, reason: 'Customer Return', status: 'Pending Pull', inbound_status: 'Not Started' },
  ],
  amazon_mfn_shipments: [],
  amazon_mfn_label_calls: [],
  procurement_buyers: [
    { buyer_code: '37', buyer_name: 'Test Buyer', description: 'Test Buyer - Person', phone: '8197755500', email: 'test@vin.com', active: true, alternate_phone: '', categories: ['media'], udf: ['', '', '', '', ''], location: 'UPSL Warehouse', created_by: 'super admin', created_date: '2019-03-29' },
    { buyer_code: '36', buyer_name: 'Munich Event', description: 'test', phone: '1404185531', email: 'vinay@viniculum.com.sg', active: true, alternate_phone: '', categories: [], udf: ['', '', '', '', ''], location: 'UPSL Warehouse', created_by: 'Demo User', created_date: '2019-03-19' },
    { buyer_code: '34', buyer_name: 'RM', description: 'procurement team', phone: '99828288', email: 'rk@vin.com', active: true, alternate_phone: '', categories: ['Apparel'], udf: ['', '', '', '', ''], location: 'UPSL Warehouse', created_by: 'super admin', created_date: '2019-03-18' },
  ],
  vendor_invoices: [
    { document_invoice_no: '1', vendor_code: '00001', vendor_name: 'Bitiqure', vendor_invoice_no: '0001', invoice_date: '2019-03-20', posting_date: '2019-03-20', invoice_amount: 6000, currency: 'INR', grn_codes: [], status: 'Confirmed', created_date: '2019-03-20' },
    { document_invoice_no: '23455', vendor_code: '00002', vendor_name: 'Demo123', vendor_invoice_no: '23455', invoice_date: '2019-03-19', posting_date: '2019-03-19', invoice_amount: 200, currency: 'INR', grn_codes: [], status: 'Confirmed', created_date: '2019-03-19' },
    { document_invoice_no: '11221', vendor_code: '0011', vendor_name: 'Supermart', vendor_invoice_no: '11221', invoice_date: '2018-12-05', posting_date: '2019-03-13', invoice_amount: 12312, currency: 'INR', grn_codes: [], status: 'Pending', created_date: '2019-03-13' },
  ],
  otb_budgets: [
    { otb_id: '1', description: 'Budget_Healthcare', location: '', start_date: '2019-03-19', end_date: '2019-07-27', status: 'Cancelled', total_budget: 2000, consumed: 0, open_to_buy: 2000, operand_type: 'Category', operand: 'Healthcare', vendor_code: '', updated_by: 'super admin', updated_date: '2019-03-19' },
    { otb_id: '2', description: 'Budget_BooksOff', location: '', start_date: '2019-03-19', end_date: '2019-07-27', status: 'Confirmed', total_budget: 1000, consumed: 999.3, open_to_buy: 0.7, operand_type: 'Category', operand: 'Books', vendor_code: '', updated_by: 'super admin', updated_date: '2019-03-19' },
    { otb_id: '3', description: 'Budget_Face', location: '', start_date: '2019-03-19', end_date: '2019-03-20', status: 'Confirmed', total_budget: 10000, consumed: 0, open_to_buy: 10000, operand_type: 'Category', operand: 'Face', vendor_code: '', updated_by: 'super admin', updated_date: '2019-03-19' },
    { otb_id: '4', description: 'test', location: 'UPSL Warehouse', start_date: '2019-04-05', end_date: '2019-04-05', status: 'Confirmed', total_budget: 10000, consumed: 0, open_to_buy: 10000, operand_type: 'Category', operand: 'media', vendor_code: '00000', updated_by: 'rk', updated_date: '2019-04-05' },
  ],
  skus: [
    { master_sku_code: 'MSKU-1001', sku_code: 'TSHIRT-BLK-M', name: 'Cotton Crew Neck T-Shirt - Black', category: 'Apparel', brand: 'UrbanEdge', uom: 'PCS', mrp: 1299, cost_price: 540, hsn: '6109' },
    { master_sku_code: 'MSKU-1002', sku_code: 'JEANS-BLU-32', name: 'Slim Fit Denim Jeans - Blue', category: 'Apparel', brand: 'DenimCo', uom: 'PCS', mrp: 2499, cost_price: 980, hsn: '6203' },
    { master_sku_code: 'MSKU-1003', sku_code: 'SNEAK-WHT-9', name: 'Running Sneakers - White', category: 'Footwear', brand: 'StridePro', uom: 'PAIR', mrp: 3499, cost_price: 1450, hsn: '6404' },
    { master_sku_code: 'MSKU-1004', sku_code: 'WATCH-SS-BLK', name: 'Analog Steel Watch - Black', category: 'Accessories', brand: 'Chronos', uom: 'PCS', mrp: 5999, cost_price: 2600, hsn: '9102' },
    { master_sku_code: 'MSKU-1005', sku_code: 'EARBUD-TWS-01', name: 'Wireless Earbuds TWS', category: 'Electronics', brand: 'SonicWave', uom: 'PCS', mrp: 2999, cost_price: 1100, hsn: '8518' },
    { master_sku_code: 'MSKU-1006', sku_code: 'BACKPACK-GRY', name: 'Laptop Backpack 25L - Grey', category: 'Accessories', brand: 'TrekMate', uom: 'PCS', mrp: 1899, cost_price: 720, hsn: '4202' },
    { master_sku_code: 'MSKU-1007', sku_code: 'SERUM-VITC-30', name: 'Vitamin C Face Serum 30ml', category: 'Beauty', brand: 'GlowLab', uom: 'PCS', mrp: 899, cost_price: 320, hsn: '3304' },
    { master_sku_code: 'MSKU-1008', sku_code: 'KURTA-MAROON-L', name: 'Cotton Kurta - Maroon', category: 'Apparel', brand: 'Ethnika', uom: 'PCS', mrp: 1599, cost_price: 610, hsn: '6205' },
    { master_sku_code: 'MSKU-1009', sku_code: 'BOTTLE-STL-1L', name: 'Insulated Steel Bottle 1L', category: 'Home & Living', brand: 'HydroFlask', uom: 'PCS', mrp: 1199, cost_price: 430, hsn: '9617' },
    { master_sku_code: 'MSKU-1010', sku_code: 'LAMP-LED-DSK', name: 'LED Desk Lamp Adjustable', category: 'Home & Living', brand: 'LumosHome', uom: 'PCS', mrp: 1499, cost_price: 560, hsn: '9405' },
    { master_sku_code: 'MSKU-1011', sku_code: 'SUNGLASS-AVT', name: 'Aviator Sunglasses UV400', category: 'Accessories', brand: 'SunVeil', uom: 'PCS', mrp: 1799, cost_price: 640, hsn: '9004' },
    { master_sku_code: 'MSKU-1012', sku_code: 'HOODIE-NVY-XL', name: 'Fleece Hoodie - Navy', category: 'Apparel', brand: 'UrbanEdge', uom: 'PCS', mrp: 1999, cost_price: 780, hsn: '6110' },
  ],
  partners: [
    { code: 'VEN001', name: 'Apex Apparel Mfg Pvt Ltd', type: 'Vendor', contact: 'Suresh Nair', phone: '9820011223', email: 'sales@apexapparel.in', city: 'Tirupur', state: 'Tamil Nadu', gstin: '33ABCDE1234F1Z5' },
    { code: 'VEN002', name: 'NovaTech Electronics', type: 'Vendor', contact: 'Priya Menon', phone: '9900122334', email: 'orders@novatech.in', city: 'Bengaluru', state: 'Karnataka', gstin: '29NOVAT5678K1Z2' },
    { code: 'VEN003', name: 'StrideFoot Industries', type: 'Vendor', contact: 'Amit Deshmukh', phone: '9711223344', email: 'supply@stridefoot.in', city: 'Agra', state: 'Uttar Pradesh', gstin: '09STRID9012L1Z8' },
    { code: 'VEN004', name: 'GlowLab Cosmetics', type: 'Vendor', contact: 'Neha Kapoor', phone: '9833445566', email: 'b2b@glowlab.in', city: 'Mumbai', state: 'Maharashtra', gstin: '27GLOWL3456M1Z1' },
    { code: 'CUS001', name: 'Rahul Sharma', type: 'Customer', contact: 'Rahul Sharma', phone: '9876543210', email: 'rahul.s@gmail.com', city: 'Delhi', state: 'Delhi', gstin: '' },
    { code: 'CUS002', name: 'Ananya Iyer', type: 'Customer', contact: 'Ananya Iyer', phone: '9765432108', email: 'ananya.i@gmail.com', city: 'Pune', state: 'Maharashtra', gstin: '' },
    { code: 'CUS003', name: 'Vikram Reddy', type: 'Customer', contact: 'Vikram Reddy', phone: '9654321087', email: 'vikram.r@gmail.com', city: 'Hyderabad', state: 'Telangana', gstin: '' },
    { code: 'TRN001', name: 'BlueDart Express', type: 'Transporter', contact: 'Ops Desk', phone: '1860233123', email: 'support@bluedart.com', city: 'Chennai', state: 'Tamil Nadu', gstin: '33BLUED7890T1Z4' },
    { code: 'TRN002', name: 'Delhivery Logistics', type: 'Transporter', contact: 'Fleet Team', phone: '1244841441', email: 'care@delhivery.com', city: 'Gurugram', state: 'Haryana', gstin: '06DELHI4567V1Z9' },
  ],
  sale_orders: [
    { order_no: 'SO10004521', channel: 'Amazon', customer: 'Rahul Sharma', city: 'Delhi', order_date: '2024-06-01', items: 2, qty: 3, amount: 4297, status: 'Shipped', payment_mode: 'Prepaid' },
    { order_no: 'SO10004522', channel: 'Flipkart', customer: 'Ananya Iyer', city: 'Pune', order_date: '2024-06-02', items: 1, qty: 1, amount: 3499, status: 'Delivered', payment_mode: 'Prepaid' },
    { order_no: 'SO10004523', channel: 'Myntra', customer: 'Vikram Reddy', city: 'Hyderabad', order_date: '2024-06-03', items: 3, qty: 4, amount: 6296, status: 'Ready to Ship', payment_mode: 'COD' },
    { order_no: 'SO10004524', channel: 'Website', customer: 'Sneha Gupta', city: 'Kolkata', order_date: '2024-06-04', items: 1, qty: 2, amount: 2598, status: 'Confirmed', payment_mode: 'Prepaid' },
    { order_no: 'SO10004525', channel: 'Store POS', customer: 'Karan Malhotra', city: 'Chandigarh', order_date: '2024-06-04', items: 2, qty: 2, amount: 8998, status: 'Delivered', payment_mode: 'Prepaid' },
    { order_no: 'SO10004526', channel: 'Amazon', customer: 'Divya Nair', city: 'Kochi', order_date: '2024-06-05', items: 1, qty: 1, amount: 5999, status: 'Confirmed', payment_mode: 'COD' },
    { order_no: 'SO10004527', channel: 'Nykaa', customer: 'Pooja Verma', city: 'Jaipur', order_date: '2024-06-05', items: 2, qty: 3, amount: 2697, status: 'Ready to Ship', payment_mode: 'Prepaid' },
    { order_no: 'SO10004528', channel: 'Flipkart', customer: 'Arjun Singh', city: 'Lucknow', order_date: '2024-06-06', items: 1, qty: 1, amount: 1899, status: 'Shipped', payment_mode: 'COD' },
    { order_no: 'SO10004529', channel: 'Website', customer: 'Meera Joshi', city: 'Ahmedabad', order_date: '2024-06-06', items: 3, qty: 5, amount: 7495, status: 'Confirmed', payment_mode: 'Prepaid' },
    { order_no: 'SO10004530', channel: 'Amazon', customer: 'Rohit Kumar', city: 'Patna', order_date: '2024-06-07', items: 1, qty: 2, amount: 5998, status: 'Cancelled', payment_mode: 'COD' },
    { order_no: 'SO10004531', channel: 'Myntra', customer: 'Ishita Rao', city: 'Bengaluru', order_date: '2024-06-07', items: 2, qty: 2, amount: 3898, status: 'Delivered', payment_mode: 'Prepaid' },
    { order_no: 'SO10004532', channel: 'Store POS', customer: 'Nikhil Jain', city: 'Indore', order_date: '2024-06-08', items: 1, qty: 1, amount: 2999, status: 'Shipped', payment_mode: 'Prepaid' },
    { order_no: 'SO10004533', channel: 'Nykaa', customer: 'Tanya Bhat', city: 'Mumbai', order_date: '2024-06-08', items: 2, qty: 4, amount: 3596, status: 'Ready to Ship', payment_mode: 'Prepaid' },
    { order_no: 'SO10004534', channel: 'Website', customer: 'Aditya Menon', city: 'Chennai', order_date: '2024-06-09', items: 1, qty: 1, amount: 1499, status: 'Confirmed', payment_mode: 'COD' },
  ],
  purchase_orders: [
    { po_no: 'PO20003011', vendor: 'Apex Apparel Mfg Pvt Ltd', warehouse: 'Delhi NCR', po_date: '2024-05-20', expected_date: '2024-06-05', items: 4, qty: 500, amount: 245000, status: 'Received' },
    { po_no: 'PO20003012', vendor: 'NovaTech Electronics', warehouse: 'Bengaluru WH', po_date: '2024-05-25', expected_date: '2024-06-10', items: 2, qty: 200, amount: 220000, status: 'Open' },
    { po_no: 'PO20003013', vendor: 'StrideFoot Industries', warehouse: 'Mumbai WH', po_date: '2024-05-28', expected_date: '2024-06-12', items: 1, qty: 150, amount: 217500, status: 'Open' },
    { po_no: 'PO20003014', vendor: 'GlowLab Cosmetics', warehouse: 'Mumbai WH', po_date: '2024-06-01', expected_date: '2024-06-15', items: 2, qty: 300, amount: 96000, status: 'Open' },
    { po_no: 'PO20003015', vendor: 'Apex Apparel Mfg Pvt Ltd', warehouse: 'Kolkata WH', po_date: '2024-06-03', expected_date: '2024-06-18', items: 3, qty: 400, amount: 234000, status: 'Open' },
  ],
  grn: [
    { grn_no: 'GRN50001201', po_no: 'PO20003011', vendor: 'Apex Apparel Mfg Pvt Ltd', warehouse: 'Delhi NCR', grn_date: '2024-06-05', received_qty: 500, status: 'Received' },
  ],
  inventory: [
    { sku_code: 'TSHIRT-BLK-M', name: 'Cotton Crew Neck T-Shirt - Black', warehouse: 'Delhi NCR', bin: 'A-01-03', available: 180, reserved: 20, on_hand: 200 },
    { sku_code: 'JEANS-BLU-32', name: 'Slim Fit Denim Jeans - Blue', warehouse: 'Delhi NCR', bin: 'A-02-01', available: 95, reserved: 15, on_hand: 110 },
    { sku_code: 'SNEAK-WHT-9', name: 'Running Sneakers - White', warehouse: 'Mumbai WH', bin: 'B-04-02', available: 12, reserved: 8, on_hand: 20 },
    { sku_code: 'WATCH-SS-BLK', name: 'Analog Steel Watch - Black', warehouse: 'Bengaluru WH', bin: 'C-01-05', available: 45, reserved: 5, on_hand: 50 },
    { sku_code: 'EARBUD-TWS-01', name: 'Wireless Earbuds TWS', warehouse: 'Bengaluru WH', bin: 'C-02-01', available: 8, reserved: 12, on_hand: 20 },
    { sku_code: 'BACKPACK-GRY', name: 'Laptop Backpack 25L - Grey', warehouse: 'Delhi NCR', bin: 'A-05-04', available: 60, reserved: 10, on_hand: 70 },
    { sku_code: 'SERUM-VITC-30', name: 'Vitamin C Face Serum 30ml', warehouse: 'Mumbai WH', bin: 'B-01-01', available: 220, reserved: 30, on_hand: 250 },
    { sku_code: 'KURTA-MAROON-L', name: 'Cotton Kurta - Maroon', warehouse: 'Kolkata WH', bin: 'D-03-02', available: 140, reserved: 10, on_hand: 150 },
    { sku_code: 'BOTTLE-STL-1L', name: 'Insulated Steel Bottle 1L', warehouse: 'Delhi NCR', bin: 'A-06-01', available: 15, reserved: 5, on_hand: 20 },
    { sku_code: 'LAMP-LED-DSK', name: 'LED Desk Lamp Adjustable', warehouse: 'Kolkata WH', bin: 'D-01-03', available: 88, reserved: 12, on_hand: 100 },
    { sku_code: 'SUNGLASS-AVT', name: 'Aviator Sunglasses UV400', warehouse: 'Mumbai WH', bin: 'B-02-04', available: 130, reserved: 20, on_hand: 150 },
    { sku_code: 'HOODIE-NVY-XL', name: 'Fleece Hoodie - Navy', warehouse: 'Delhi NCR', bin: 'A-03-02', available: 18, reserved: 12, on_hand: 30 },
  ],
  stock_transfers: [
    { transfer_no: 'STO70001001', sku_code: 'SERUM-VITC-30', from_wh: 'Mumbai WH', to_wh: 'Delhi NCR', qty: 50, transfer_date: '2024-06-04', status: 'Completed' },
    { transfer_no: 'STO70001002', sku_code: 'WATCH-SS-BLK', from_wh: 'Bengaluru WH', to_wh: 'Mumbai WH', qty: 20, transfer_date: '2024-06-06', status: 'In Transit' },
    { transfer_no: 'STO70001003', sku_code: 'KURTA-MAROON-L', from_wh: 'Kolkata WH', to_wh: 'Delhi NCR', qty: 40, transfer_date: '2024-06-07', status: 'In Transit' },
  ],
  returns: [
    { rma_no: 'RMA90001001', order_no: 'SO10004521', customer: 'Rahul Sharma', sku_code: 'TSHIRT-BLK-M', qty: 1, reason: 'Size Issue', return_date: '2024-06-08', status: 'Approved' },
    { rma_no: 'RMA90001002', order_no: 'SO10004525', customer: 'Karan Malhotra', sku_code: 'WATCH-SS-BLK', qty: 1, reason: 'Damaged Product', return_date: '2024-06-09', status: 'Requested' },
    { rma_no: 'RMA90001003', order_no: 'SO10004522', customer: 'Ananya Iyer', sku_code: 'SNEAK-WHT-9', qty: 1, reason: 'Wrong Item', return_date: '2024-06-09', status: 'Refunded' },
  ],
  fulfillment_orders: [
    { order_no: 'WO500123', channel: 'Amazon', customer: 'Rahul Sharma', city: 'Delhi', warehouse: 'Delhi NCR', order_date: '2024-06-09', sku_code: 'TSHIRT-BLK-M', sku_name: 'Cotton Crew Neck T-Shirt - Black', qty: 2, amount: 2598, payment_mode: 'Prepaid', status: 'Pending', priority: 'High', acknowledged: false },
    { order_no: 'WO500124', channel: 'Flipkart', customer: 'Ananya Iyer', city: 'Pune', warehouse: 'Mumbai WH', order_date: '2024-06-09', sku_code: 'SNEAK-WHT-9', sku_name: 'Running Sneakers - White', qty: 1, amount: 3499, payment_mode: 'Prepaid', status: 'Pending', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500125', channel: 'Myntra', customer: 'Vikram Reddy', city: 'Hyderabad', warehouse: 'Bengaluru WH', order_date: '2024-06-09', sku_code: 'WATCH-SS-BLK', sku_name: 'Analog Steel Watch - Black', qty: 1, amount: 5999, payment_mode: 'COD', status: 'Pending', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500126', channel: 'Website', customer: 'Sneha Gupta', city: 'Kolkata', warehouse: 'Kolkata WH', order_date: '2024-06-08', sku_code: 'KURTA-MAROON-L', sku_name: 'Cotton Kurta - Maroon', qty: 2, amount: 3198, payment_mode: 'Prepaid', status: 'Allocated', priority: 'High', acknowledged: false },
    { order_no: 'WO500127', channel: 'Amazon', customer: 'Karan Malhotra', city: 'Chandigarh', warehouse: 'Delhi NCR', order_date: '2024-06-08', sku_code: 'BACKPACK-GRY', sku_name: 'Laptop Backpack 25L - Grey', qty: 1, amount: 1899, payment_mode: 'Prepaid', status: 'Allocated', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500128', channel: 'Nykaa', customer: 'Pooja Verma', city: 'Jaipur', warehouse: 'Mumbai WH', order_date: '2024-06-08', sku_code: 'SERUM-VITC-30', sku_name: 'Vitamin C Face Serum 30ml', qty: 3, amount: 2697, payment_mode: 'Prepaid', status: 'Allocated', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500129', channel: 'Flipkart', customer: 'Arjun Singh', city: 'Lucknow', warehouse: 'Delhi NCR', order_date: '2024-06-07', sku_code: 'BOTTLE-STL-1L', sku_name: 'Insulated Steel Bottle 1L', qty: 1, amount: 1199, payment_mode: 'COD', status: 'Picklist Generated', picklist_no: 'PL800045', priority: 'High', acknowledged: false },
    { order_no: 'WO500130', channel: 'Website', customer: 'Meera Joshi', city: 'Ahmedabad', warehouse: 'Delhi NCR', order_date: '2024-06-07', sku_code: 'HOODIE-NVY-XL', sku_name: 'Fleece Hoodie - Navy', qty: 2, amount: 3998, payment_mode: 'Prepaid', status: 'Picklist Generated', picklist_no: 'PL800045', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500131', channel: 'Myntra', customer: 'Ishita Rao', city: 'Bengaluru', warehouse: 'Bengaluru WH', order_date: '2024-06-06', sku_code: 'SUNGLASS-AVT', sku_name: 'Aviator Sunglasses UV400', qty: 1, amount: 1799, payment_mode: 'Prepaid', status: 'Picking', picklist_no: 'PL800042', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500132', channel: 'Amazon', customer: 'Nikhil Jain', city: 'Indore', warehouse: 'Bengaluru WH', order_date: '2024-06-06', sku_code: 'EARBUD-TWS-01', sku_name: 'Wireless Earbuds TWS', qty: 1, amount: 2999, payment_mode: 'Prepaid', status: 'Picked', picklist_no: 'PL800042', box_no: 'BOX-A12', priority: 'High', acknowledged: false },
    { order_no: 'WO500133', delivery_no: 'DEL500133', invoice_no: 'INV500133', ewb_no: '181009876543', ewb_validity: '2026-09-01', vehicle_no: 'MH04AB1234', channel: 'Store POS', customer: 'Tanya Bhat', city: 'Mumbai', warehouse: 'Mumbai WH', order_date: '2024-06-05', sku_code: 'SERUM-VITC-30', sku_name: 'Vitamin C Face Serum 30ml', qty: 2, amount: 1798, payment_mode: 'Prepaid', status: 'Packed', picklist_no: 'PL800040', courier: 'BlueDart Express', awb: 'BD77120045', box_no: 'BOX-M03', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500134', delivery_no: 'DEL500134', invoice_no: 'INV500134', ewb_no: '181009876544', ewb_validity: '2026-09-01', vehicle_no: 'MH04AB1234', channel: 'Flipkart', customer: 'Aditya Menon', city: 'Chennai', warehouse: 'Mumbai WH', order_date: '2024-06-05', sku_code: 'JEANS-BLU-32', sku_name: 'Slim Fit Denim Jeans - Blue', qty: 1, amount: 2499, payment_mode: 'COD', status: 'Ready to Ship', picklist_no: 'PL800040', courier: 'Delhivery Logistics', awb: 'DL55098233', box_no: 'BOX-M04', priority: 'High', acknowledged: false },
    { order_no: 'WO500135', delivery_no: 'DEL500135', invoice_no: 'INV500135', ewb_no: '181009876545', ewb_validity: '2026-09-01', vehicle_no: 'DL01CD5678', channel: 'Amazon', customer: 'Ravi Kapoor', city: 'Noida', warehouse: 'Delhi NCR', order_date: '2024-06-04', sku_code: 'LAMP-LED-DSK', sku_name: 'LED Desk Lamp Adjustable', qty: 1, amount: 1499, payment_mode: 'Prepaid', status: 'Manifested', picklist_no: 'PL800038', courier: 'BlueDart Express', awb: 'BD77120099', box_no: 'BOX-A08', priority: 'Normal', acknowledged: false },
    { order_no: 'WO500136', channel: 'Website', customer: 'Deepa Nair', city: 'Kochi', warehouse: 'Mumbai WH', order_date: '2024-06-03', sku_code: 'SNEAK-WHT-9', sku_name: 'Running Sneakers - White', qty: 1, amount: 3499, payment_mode: 'Prepaid', status: 'Handed Over', picklist_no: 'PL800035', courier: 'Delhivery Logistics', awb: 'DL55098100', box_no: 'BOX-M01', priority: 'Normal', acknowledged: true },
  ],
  picklists: [
    { picklist_no: 'PL800045', warehouse: 'Delhi NCR', order_count: 2, sku_count: 2, total_qty: 3, pick_mode: 'Pick by Order', status: 'Open', created_date: '2024-06-07', picker: 'Unassigned' },
    { picklist_no: 'PL800042', warehouse: 'Bengaluru WH', order_count: 2, sku_count: 2, total_qty: 2, pick_mode: 'Pick by SKU', status: 'In Progress', created_date: '2024-06-06', picker: 'Ramesh K' },
    { picklist_no: 'PL800040', warehouse: 'Mumbai WH', order_count: 2, sku_count: 2, total_qty: 3, pick_mode: 'Batch Pick', status: 'Completed', created_date: '2024-06-05', picker: 'Sunita M' },
    { picklist_no: 'PL800038', warehouse: 'Delhi NCR', order_count: 1, sku_count: 1, total_qty: 1, pick_mode: 'Pick by Order', status: 'Completed', created_date: '2024-06-04', picker: 'Amit S' },
  ],
  shipments: [
    { manifest_no: 'MF900021', courier: 'BlueDart Express', warehouse: 'Delhi NCR', shipment_count: 1, status: 'Pending Handover', handover_date: '2024-06-04' },
    { manifest_no: 'MF900018', courier: 'Delhivery Logistics', warehouse: 'Mumbai WH', shipment_count: 1, status: 'Handed Over', handover_date: '2024-06-03' },
  ],
  vendor_promotions: [],
  generic_records: [
    { module: 'tax-code', code: 'GST18', name: 'GST 18%', description: 'Standard GST rate 18%', status: 'Active', created_date: '2024-05-10', rate: 18, tax_type: 'GST', is_compound: 0 },
    { module: 'tax-code', code: 'GST12', name: 'GST 12%', description: 'Reduced GST rate 12%', status: 'Active', created_date: '2024-05-10', rate: 12, tax_type: 'GST', is_compound: 0 },
    { module: 'tax-code', code: 'GST05', name: 'GST 5%', description: 'Essential goods GST 5%', status: 'Active', created_date: '2024-05-10', rate: 5, tax_type: 'GST', is_compound: 0 },
    { module: 'tax-group', code: 'TG-APPAREL', name: 'Apparel Tax Group', description: 'Tax group for apparel category', status: 'Active', created_date: '2024-05-11' },
    { module: 'tax-zone', code: 'TZ-NORTH', name: 'North Zone', description: 'Delhi, UP, Punjab, Haryana', status: 'Active', created_date: '2024-05-11' },
    { module: 'sku-group', code: 'SG-FOOT', name: 'Footwear Group', description: 'All footwear SKUs', status: 'Active', created_date: '2024-05-12' },
    { module: 'merch-hierarchy', code: 'MH-01', name: 'Apparel > Men > Topwear', description: 'Merchandising node', status: 'Active', created_date: '2024-05-12' },
    { module: 'manage-attribute', code: 'ATTR-SIZE', name: 'Size', description: 'Size attribute (S/M/L/XL)', status: 'Active', created_date: '2024-05-12', data_type: 'List', values: 'S, M, L, XL', mandatory: 1 },
    { module: 'manage-attribute', code: 'ATTR-COLOR', name: 'Color', description: 'Color attribute', status: 'Active', created_date: '2024-05-12', data_type: 'List', values: 'Black, Blue, Red, White', mandatory: 0 },
    { module: 'coupons', code: 'WELCOME10', name: 'Welcome 10% Off', description: 'New customer coupon', status: 'Active', created_date: '2024-05-15', discount_type: 'Percentage', discount_value: 10, min_order: 999, valid_from: '2024-05-01', valid_to: '2024-12-31', usage_limit: 500 },
    { module: 'coupons', code: 'FEST500', name: 'Festive Rs.500 Off', description: 'Festive season flat discount', status: 'Inactive', created_date: '2024-05-15', discount_type: 'Flat Amount', discount_value: 500, min_order: 2999, valid_from: '2024-10-01', valid_to: '2024-11-15', usage_limit: 1000 },
    { module: 'location', code: 'LOC-DEL', name: 'Delhi NCR Warehouse', description: 'Primary north fulfillment center', status: 'Active', created_date: '2024-04-01', loc_type: 'Warehouse', city: 'Delhi', state: 'Delhi', gstin: '07AABCU9603R1ZP' },
    { module: 'location', code: 'LOC-MUM', name: 'Mumbai Warehouse', description: 'West region fulfillment center', status: 'Active', created_date: '2024-04-01', loc_type: 'Warehouse', city: 'Mumbai', state: 'Maharashtra', gstin: '27AABCU9603R1ZX' },
    { module: 'ars-rules', code: 'ARS-FAST', name: 'Fast Movers Replenishment', description: 'Auto-reorder for A-class SKUs', status: 'Active', created_date: '2024-05-20' },
    { module: 'vendor-promotions', code: 'VP-APEX-Q2', name: 'Apex Q2 Scheme', description: '5% off on orders above 500 units', status: 'Active', created_date: '2024-05-22' },
    { module: 'oms-rules', code: 'OMS-NEAREST', name: 'Nearest Warehouse Sourcing', description: 'Allocate from geographically nearest WH', status: 'Active', created_date: '2024-05-25' },
    // ---- Master extras ----
    { module: 'customer-group', code: 'CG-RETAIL', name: 'Retail Buyers', description: 'B2C retail customers', status: 'Active', created_date: '2024-05-02' },
    { module: 'customer-group', code: 'CG-B2B', name: 'B2B Wholesale', description: 'Bulk wholesale accounts', status: 'Active', created_date: '2024-05-02' },
    { module: 'voucher-condition', code: 'VC-MIN999', name: 'Min Order 999', description: 'Applies above ₹999', status: 'Active', created_date: '2024-05-03' },
    { module: 'vouchers', code: 'GV-500', name: 'Gift Voucher ₹500', description: 'Prepaid gift voucher', status: 'Active', created_date: '2024-05-04' },
    { module: 'tax-category', code: '6109', name: 'T-Shirts HSN 6109', description: 'Knitted apparel', status: 'Active', created_date: '2024-05-05', type: 'HSN (Goods)', gst_rate: 12, cess: 0 },
    { module: 'tax-category', code: '6404', name: 'Footwear HSN 6404', description: 'Sports footwear', status: 'Active', created_date: '2024-05-05' },
    { module: 'tax-application', code: 'TA-INTRA', name: 'Intra-State (CGST+SGST)', description: 'Within same state', status: 'Active', created_date: '2024-05-06' },
    { module: 'tax-application', code: 'TA-INTER', name: 'Inter-State (IGST)', description: 'Across states', status: 'Active', created_date: '2024-05-06' },
    { module: 'org-hierarchy', code: 'ORG-IN', name: 'India Operations', description: 'Top-level org node', status: 'Active', created_date: '2024-04-01' },
    { module: 'store-group', code: 'SG-NORTH', name: 'North Stores', description: 'Delhi, Chandigarh, Lucknow', status: 'Active', created_date: '2024-04-02' },
    { module: 'sku-company-link', code: 'TSHIRT-BLK-M', name: 'Linked to UrbanEdge', description: 'Company SKU mapping', status: 'Active', created_date: '2024-05-08' },
    { module: 'sku-barcode', code: '8901234567890', name: 'TSHIRT-BLK-M barcode', description: 'EAN-13', status: 'Active', created_date: '2024-05-08' },
    { module: 'other-masters', code: 'OM-UOM', name: 'Unit of Measure Master', description: 'PCS, PAIR, SET, BOX', status: 'Active', created_date: '2024-05-09' },
    { module: 'pricing-event', code: 'PE-EOSS', name: 'End of Season Sale', description: 'Flat 40% off', status: 'Active', created_date: '2024-05-09' },
    { module: 'price-zone', code: 'PZ-METRO', name: 'Metro Pricing Zone', description: 'Tier-1 cities', status: 'Active', created_date: '2024-05-10' },
    { module: 'order-refund', code: 'RF-UPI', name: 'UPI Refund Mode', description: 'Instant UPI refunds', status: 'Active', created_date: '2024-05-11' },
    { module: 'sales-rep', code: 'SR-101', name: 'Ankit Verma', description: 'North region rep', status: 'Active', created_date: '2024-05-12' },
    // ---- Procurement extras ----
    { module: 'purchase-charge', code: 'PC-FREIGHT', name: 'Freight Charges', description: 'Inbound freight', status: 'Active', created_date: '2024-05-13' },
    { module: 'category-buyers', code: 'CB-APPAREL', name: 'Apparel Buyer Desk', description: 'Category buying team', status: 'Active', created_date: '2024-05-13' },
    { module: 'ars-sku-location', code: 'ARS-DEL-01', name: 'Delhi NCR ARS link', description: 'SKU-location replenishment', status: 'Active', created_date: '2024-05-14' },
    { module: 'ars-log', code: 'LOG-20240601', name: 'ARS Run 01-Jun', description: '48 SKUs reordered', status: 'Active', created_date: '2024-06-01' },
    // ---- Sales extras ----
    { module: 'kitting-order', code: 'KIT-COMBO1', name: 'Festive Combo Kit', description: 'T-shirt + Cap bundle', status: 'Active', created_date: '2024-05-16' },
    { module: 'cod-recon', code: 'COD-20240605', name: 'COD Batch 05-Jun', description: '₹42,300 reconciled', status: 'Active', created_date: '2024-06-05' },
    // ---- WMS: Setup ----
    { module: 'wms-zone', code: 'Z-FAST', name: 'Fast Pick Zone', description: 'High-velocity SKUs', status: 'Active', created_date: '2024-04-10' },
    { module: 'wms-zone', code: 'Z-BULK', name: 'Bulk Storage Zone', description: 'Pallet storage', status: 'Active', created_date: '2024-04-10' },
    { module: 'picker-zone-pref', code: 'PZP-RAMESH', name: 'Ramesh → Fast Zone', description: 'Picker preference', status: 'Active', created_date: '2024-04-11' },
    { module: 'bin-enquiry', code: 'A-01-03', name: 'Bin A-01-03', description: 'Delhi NCR · 42 units', status: 'Active', created_date: '2024-04-12' },
    { module: 'bin-create-edit', code: 'A-07-01', name: 'Bin A-07-01', description: 'New pick face', status: 'Active', created_date: '2024-04-12' },
    { module: 'lottable-validation', code: 'LV-EXPIRY', name: 'Expiry Validation', description: 'Block expired lots', status: 'Active', created_date: '2024-04-13' },
    { module: 'receipt-validation', code: 'RV-PO', name: 'PO Match Validation', description: 'Match against PO', status: 'Active', created_date: '2024-04-13' },
    { module: 'sku-label-print', code: 'TSHIRT-BLK-M', name: 'Label Template A4', description: '24-up label sheet', status: 'Active', created_date: '2024-04-14' },
    // ---- WMS: Logistics ----
    { module: 'manage-awb', code: 'BD77120045', name: 'BlueDart AWB Pool', description: '500 pre-allocated', status: 'Active', created_date: '2024-05-01' },
    { module: 'transporter-pref', code: 'TP-METRO', name: 'Metro → BlueDart', description: 'Preferred courier rule', status: 'Active', created_date: '2024-05-01' },
    { module: 'service-pin-code', code: '110001', name: 'New Delhi Serviceable', description: 'BlueDart + Delhivery', status: 'Active', created_date: '2024-05-02' },
    // ---- WMS: Inbound ----
    { module: 'inbound-gate-pass', code: 'GP-20240605', name: 'Gate Pass 05-Jun', description: 'Apex Apparel inbound', status: 'Active', created_date: '2024-06-05' },
    { module: 'inbound-enquiry', code: 'IN-20240605', name: 'Inbound 05-Jun', description: '500 units received', status: 'Active', created_date: '2024-06-05' },
    { module: 'inbound-realtime', code: 'RT-DOCK1', name: 'Dock 1 Live', description: 'Real-time receiving', status: 'Active', created_date: '2024-06-05' },
    { module: 'inbound-qc', code: 'QC-20240605', name: 'QC Batch 05-Jun', description: '2% rejected', status: 'Active', created_date: '2024-06-05' },
    // ---- WMS: Inventory ----
    { module: 'inv-move-history', code: 'MV-1001', name: 'Move A-01→B-04', description: '20 units relocated', status: 'Active', created_date: '2024-06-06' },
    { module: 'inv-move', code: 'MV-NEW', name: 'New Move Task', description: 'Bin-to-bin move', status: 'Active', created_date: '2024-06-06' },
    { module: 'inv-move-scan', code: 'SCAN-01', name: 'Scan Move Session', description: 'Handheld move', status: 'Active', created_date: '2024-06-06' },
    { module: 'cycle-count', code: 'CC-20240607', name: 'Cycle Count 07-Jun', description: 'Zone Fast · 98% accuracy', status: 'Active', created_date: '2024-06-07' },
    { module: 'bin-audit', code: 'BA-A-01-03', name: 'Audit A-01-03', description: 'Matched', status: 'Active', created_date: '2024-06-07' },
    { module: 'bulk-lottables', code: 'BL-EXPIRY', name: 'Bulk Expiry Update', description: '120 lots updated', status: 'Active', created_date: '2024-06-08' },
    // ---- WMS: Miscellaneous ----
    { module: 'putaway-enquiry', code: 'PA-20240605', name: 'Putaway 05-Jun', description: '500 units putaway', status: 'Active', created_date: '2024-06-05' },
    { module: 'dispatch-checkpoint', code: 'DC-GATE2', name: 'Gate 2 Checkpoint', description: 'Outbound scan', status: 'Active', created_date: '2024-06-08' },
    { module: 'sku-grading', code: 'GR-A', name: 'Grade A Stock', description: 'Sellable', status: 'Active', created_date: '2024-06-08' },
    { module: 'discrepancy-enquiry', code: 'DISC-1001', name: 'Short 2 units', description: 'PO20003011 discrepancy', status: 'Inactive', created_date: '2024-06-06' },
    { module: 'bulk-upload', code: 'BU-INV', name: 'Inventory Bulk Upload', description: 'CSV template', status: 'Active', created_date: '2024-06-01' },
    { module: 'mr-inventory-log', code: 'MR-20240607', name: 'MR Log 07-Jun', description: 'Material request log', status: 'Active', created_date: '2024-06-07' },
    // ---- Returns & Transfers ----
    { module: 'rtv-enquiry', code: 'RTV-2001', name: 'RTV to Apex', description: '12 defective units', status: 'Active', created_date: '2024-06-09' },
    { module: 'vendor-return', code: 'VR-NEW', name: 'New Vendor Return', description: 'Return to vendor', status: 'Active', created_date: '2024-06-09' },
    { module: 'return-otc', code: 'OTC-FK-01', name: 'Flipkart OTC Return', description: 'Over-the-counter', status: 'Active', created_date: '2024-06-09' },
    { module: 'return-otc-new', code: 'OTC-FK-NEW', name: 'Flipkart OTC (New)', description: 'New OTC flow', status: 'Active', created_date: '2024-06-09' },
    { module: 'return-wo-order', code: 'RWO-01', name: 'Return without Order', description: 'Goodwill return', status: 'Active', created_date: '2024-06-09' },
    // ---- Admin: User Management ----
    { module: 'user-enquiry', code: 'demo-admin', name: 'Demo Store Admin', description: 'Full access', status: 'Active', created_date: '2024-01-01' },
    { module: 'user-enquiry', code: 'ramesh_k', name: 'Ramesh K (Picker)', description: 'WMS picker role', status: 'Active', created_date: '2024-02-01' },
    { module: 'user-create-edit', code: 'new_user', name: 'Create New User', description: 'User onboarding', status: 'Active', created_date: '2024-06-01' },
    { module: 'role-create-edit', code: 'ROLE-ADMIN', name: 'Administrator', description: 'All permissions', status: 'Active', created_date: '2024-01-01' },
    { module: 'role-create-edit', code: 'ROLE-PICKER', name: 'Warehouse Picker', description: 'WMS ops only', status: 'Active', created_date: '2024-01-01' },
    // ---- Admin: Imports ----
    { module: 'order-import', code: 'IMP-ORD-01', name: 'Amazon Order Import', description: 'Channel order pull', status: 'Active', created_date: '2024-06-01' },
    { module: 'common-import', code: 'IMP-SKU-01', name: 'SKU Master Import', description: 'Bulk SKU upload', status: 'Active', created_date: '2024-06-01' },
    // ---- Admin: Miscellaneous ----
    { module: 'exports', code: 'EXP-SALES', name: 'Sales Export', description: 'Daily sales CSV', status: 'Active', created_date: '2024-06-01' },
    { module: 'force-order-pull', code: 'FP-AMAZON', name: 'Force Pull Amazon', description: 'Manual channel sync', status: 'Active', created_date: '2024-06-09' },
    { module: 'settings', code: 'SET-GENERAL', name: 'General Settings', description: 'System configuration', status: 'Active', created_date: '2024-01-01' },
    { module: 'manage-api', code: 'API-KEY-01', name: 'Primary API Key', description: 'Integration key', status: 'Active', created_date: '2024-01-01' },
    { module: 'api-dashboard', code: 'API-DASH', name: 'API Usage Dashboard', description: '12,400 calls today', status: 'Active', created_date: '2024-06-09' },
    // ---- Admin: Logs ----
    { module: 'user-audit-logs', code: 'AUD-20240609', name: 'Login audit 09-Jun', description: 'Demo admin login', status: 'Active', created_date: '2024-06-09' },
    { module: 'accounting-log', code: 'ACC-20240609', name: 'Accounting sync', description: 'Tally push OK', status: 'Active', created_date: '2024-06-09' },
    { module: 'tax-integration-log', code: 'TAX-20240609', name: 'GST e-invoice', description: 'IRN generated', status: 'Active', created_date: '2024-06-09' },
    { module: 'device-tracking-log', code: 'DEV-HH01', name: 'Handheld HH01', description: 'Last seen Dock 1', status: 'Active', created_date: '2024-06-09' },
    { module: 'external-apps-logs', code: 'EXT-SHOPIFY', name: 'Shopify Sync', description: 'Inventory push OK', status: 'Active', created_date: '2024-06-09' },
    { module: 'pos-integration-log', code: 'POS-STORE1', name: 'Store 1 POS', description: 'Sales synced', status: 'Active', created_date: '2024-06-09' },
    { module: 'repush-log', code: 'RP-20240609', name: 'Repush failed orders', description: '3 orders repushed', status: 'Inactive', created_date: '2024-06-09' },
  ],
  downloads: [],
  // Dedicated Admin module persistence. These records are intentionally
  // separate from generic master records because their workflows have their
  // own validation, audit trail and nested permission data.
  admin_records: [
    ...[
      ['09curefit', 'Pritesh', 'Jain', 'InActive', 'pritesh@curefit.com'],
      ['09dbz', 'Nitin', 'Anand', 'InActive', 'sa@demo.com'],
      ['09de ezeno'.replace(' ', ''), 'Tanima', 'Dey', 'InActive', 'tanima@deezeno.com'],
      ['09habbana', 'Aakash', 'Batra', 'Active', 'akash@habbana.com'],
      ['09Himanshu', 'Himanshu', 'Joshi', 'InActive', 'himanshu.j@efr.com'],
      ['09hora', 'Nilesh', 'Yadav', 'Active', 'nilesh.yadav@pbltd.in'],
      ['09horra', 'Suyogya', 'Mehta', 'Active', 'suyogya@horra.com'],
      ['09label', 'Dinesh', 'Advane', 'InActive', 'dinesh@thelabellife.com'],
      ['09rach', 'Sachin', 'More', 'Active', '123@abc.com'],
      ['09shashi', 'shashi', 'uttamchandani', 'InActive', 'shashi@sochstudio.com'],
      ['11111', 'abs', 'Singh', 'Active', 'cvb@gmail.com'],
      ['27ave.demo', 'Waqas', 'Nakhwa', 'InActive', 'waqas@27avenue.com'],
      ['a', 'ss', 'aa', 'InActive', 'sinvin@gmail.com'],
      ['aa', 'dd', 'dd', 'Active', 'rahulvin@gmail.com'],
      ['aaron', 'Aaron', 'Vituzote', 'Active', 'aaron@vituzote.com'],
      ['ab', 'Abhishek', 'Bose', 'Active', 'ab@example.com'],
      ['admin', 'System', 'Administrator', 'Active', 'admin@vinculumgroup.com'],
      ['agent002', 'API', 'Agent', 'Active', 'agent002@vinculumgroup.com'],
      ['demo-admin', 'Demo', 'Admin', 'Active', 'demo-admin@example.invalid'],
    ].map(([username, firstName, lastName, status, email]) => ({ type: 'user', username, firstName, lastName, status, email, userType: 'Normal', createdAt: '2018-08-30T12:00:00.000Z', version: 1 })),
    ...[
      ['28/06/2018 12:44 PM', 'Vendor Maintenance', 'USPL', 'KV001', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 12:44 PM', 'Vendor Maintenance', 'KV001', 'USPL', '', 'UPDATE', 'sa', 'status', 'Created', 'Confirmed'],
      ['28/06/2018 12:48 PM', 'SKU Maintenance', 'K001', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 12:51 PM', 'SKU Maintenance', 'K002', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 01:12 PM', 'Vendor Maintenance', 'USPL', '2517', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 01:14 PM', 'SKU Maintenance', 'ZARA25', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 01:16 PM', 'SKU Maintenance', 'ZARA17', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 01:30 PM', 'SKU Maintenance', 'ZARA26', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 01:37 PM', 'SKU Maintenance', 'ZARA18', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 02:27 PM', 'SKU Maintenance', 'KANIKA101', '', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 04:12 PM', 'Vendor Maintenance', 'USPL', 'VC001', '', 'INSERT', 'sa', '', '', ''],
      ['28/06/2018 04:13 PM', 'Vendor Maintenance', 'VC001', 'USPL', '', 'UPDATE', 'sa', 'status', 'Created', 'Confirmed'],
      ['28/06/2018 06:19 PM', 'SKU Maintenance', 'K003', '', '', 'INSERT', 'sa', '', '', ''],
      ['29/06/2018 11:57 AM', 'SKU Maintenance', 'K004', '', '', 'INSERT', 'sa', '', '', ''],
      ['29/06/2018 11:58 AM', 'SKU Maintenance', 'K005', '', '', 'INSERT', 'sa', '', '', ''],
    ].map(([date, processGroup, keyValue1, keyValue2, keyValue3, action, user, attribute, oldValue, newValue]) => ({ type: 'audit', date, processGroup, keyValue1, keyValue2, keyValue3, action, user, attribute, oldValue, newValue })),
    ...[
      ['286a4e1785904984ac06d1419bffd33d9c4a4338bf0c402dbfd32cf', 'agent002', '30/08/2018 05:40 PM', '25/09/2028 03:22 PM', 'Active'],
      ['cb0a133c69ad4e588c6e1b74b639b63e3051ca2c40194b7ba89ce3c', 'sa', '28/08/2018 03:02 PM', '28/08/2028 03:02 PM', 'Inactive'],
      ['1a7f3e56ffc34682bca362707229e124bd69d7e21753495ba2f543a', 'srs', '28/08/2018 12:33 PM', '28/08/2028 12:33 PM', 'Inactive'],
      ['8a11fe44e38d4e65a8213e69f7fa49aef58339e217e943debc1d4cc', 'sa', '28/08/2018 12:25 PM', '17/09/2028 06:20 PM', 'Active'],
      ['beac5877f977409592f73190baedfc75d53e38a1989b4a6aad7be48', 'agent002', '10/08/2018 12:36 PM', '29/08/2028 01:52 PM', 'Inactive'],
      ['9b5a2986b45441289a13ab8f03df56d9a800fafb37484240b8e5616', 'sa', '10/08/2018 08:28 AM', '15/08/2028 05:03 AM', 'Inactive'],
    ].map(([apiKey, owner, createdAt, expiryDate, status], index) => ({ type: 'api-key', apiKey, owner, createdAt, expiryDate, status, version: 1, permissions: ['Amazon Login Broken API', 'Amazon Login Fixed API', 'Bulk Order Create', 'Create ASN', 'Create Return', 'Customer Detail', 'Fetch Inventory', 'Fetch Inventory'].map((name, permissionIndex) => ({ name, access: index === 0 && (permissionIndex === 0 || permissionIndex === 7), locations: permissionIndex === 7 ? ['1mg'] : [] })) })),
  ],
  tax_application: [
    { tax_category: '28% GST', tax_type: 'Sales', tax_group_code: 'COVID', goods_direction: 'IN', tax_zone: 'Odisha (formerly Orrisa)', start_date: '2023-05-18', is_active: 'Active', from_mrp: 3009.00, to_mrp: 0 },
    { tax_category: '28% GST', tax_type: 'Sales', tax_group_code: 'G12.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '28% GST', tax_type: 'Purchase', tax_group_code: 'G12.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '998877', tax_type: 'Sales', tax_group_code: 'G12.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '998877', tax_type: 'Purchase', tax_group_code: 'G12.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '98989898', tax_type: 'Sales', tax_group_code: 'COVID19', goods_direction: 'ALL', tax_zone: 'Delhi', start_date: '2022-07-20', is_active: 'Active', from_mrp: 999.00, to_mrp: 0 },
    { tax_category: '98989898', tax_type: 'Sales', tax_group_code: 'HNF', goods_direction: 'ALL', tax_zone: 'Himachal Pradesh', start_date: '2021-01-18', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '98989898', tax_type: 'Sales', tax_group_code: 'G12.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 500.00, to_mrp: 1500.00 },
    { tax_category: '98989898', tax_type: 'Sales', tax_group_code: 'G5.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 0, to_mrp: 500.00 },
    { tax_category: '98989898', tax_type: 'Purchase', tax_group_code: 'G12.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 1000.00, to_mrp: 999999.00 },
    { tax_category: '98989898', tax_type: 'Purchase', tax_group_code: 'G5.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2017-07-01', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '98761234', tax_type: 'Sales', tax_group_code: 'G18.0S', goods_direction: 'ALL', tax_zone: 'Uttar Pradesh', start_date: '2023-01-04', is_active: 'Active', from_mrp: 1.00, to_mrp: 0 },
    { tax_category: '96100000', tax_type: 'Purchase', tax_group_code: 'G0.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2026-05-08', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '96100000', tax_type: 'Sales', tax_group_code: 'G0.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2026-05-08', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: 'CGST', tax_type: 'Sales', tax_group_code: 'G18.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2021-01-07', is_active: 'Active', from_mrp: 0, to_mrp: 100000.00 },
    { tax_category: 'CGST', tax_type: 'Purchase', tax_group_code: 'G18.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2021-01-07', is_active: 'Active', from_mrp: 0, to_mrp: 100000.00 },
    { tax_category: 'GST12', tax_type: 'Sales', tax_group_code: 'GST12', goods_direction: 'ALL', tax_zone: 'Uttar Pradesh', start_date: '2022-12-22', is_active: 'Active', from_mrp: 1.00, to_mrp: 1000.00 },
    { tax_category: '91021100', tax_type: 'Purchase', tax_group_code: 'G18.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2022-06-08', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '91021100', tax_type: 'Sales', tax_group_code: 'G18.0S', goods_direction: 'ALL', tax_zone: '', start_date: '2022-06-08', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
    { tax_category: '9102090', tax_type: 'Purchase', tax_group_code: 'G5.0P', goods_direction: 'ALL', tax_zone: '', start_date: '2025-04-10', is_active: 'Active', from_mrp: 0, to_mrp: 0 },
  ],
  sku_barcode: [
    { sku_code: 'TSHIRT-BLK-M', sku_name: 'Cotton Crew Neck T-Shirt - Black', sku_barcode: '8901234567890', uom: 'Each', barcode_type: 'EAN-13', is_active: 'Active', is_default: 'Yes', modified_date: '2026-07-05', case_size: 1, sale_price: 1299, is_saleable: 'Yes' },
    { sku_code: 'JEANS-BLU-32', sku_name: 'Slim Fit Denim Jeans - Blue', sku_barcode: '8901234567906', uom: 'Each', barcode_type: 'EAN-13', is_active: 'Active', is_default: 'Yes', modified_date: '2026-07-06', case_size: 1, sale_price: 2499, is_saleable: 'Yes' },
    { sku_code: 'SNEAK-WHT-9', sku_name: 'Running Sneakers - White', sku_barcode: '8901234567913', uom: 'Pair', barcode_type: 'EAN-13', is_active: 'Active', is_default: 'Yes', modified_date: '2026-07-07', case_size: 1, sale_price: 3499, is_saleable: 'Yes' },
    { sku_code: 'WATCH-SS-BLK', sku_name: 'Analog Steel Watch - Black', sku_barcode: '8901234567920', uom: 'Each', barcode_type: 'CODE-128', is_active: 'Active', is_default: 'Yes', modified_date: '2026-07-08', case_size: 1, sale_price: 5999, is_saleable: 'Yes' },
    { sku_code: 'EARBUD-TWS-01', sku_name: 'Wireless Earbuds TWS', sku_barcode: '8901234567937', uom: 'Each', barcode_type: 'EAN-13', is_active: 'Active', is_default: 'No', modified_date: '2026-07-09', case_size: 4, sale_price: 2999, is_saleable: 'Yes' },
    { sku_code: 'SERUM-VITC-30', sku_name: 'Vitamin C Face Serum 30ml', sku_barcode: '8901234567944', uom: 'Each', barcode_type: 'EAN-13', is_active: 'Active', is_default: 'Yes', modified_date: '2026-07-09', case_size: 12, sale_price: 899, is_saleable: 'Yes' },
    { sku_code: 'BACKPACK-GRY', sku_name: 'Laptop Backpack 25L - Grey', sku_barcode: '8901234567951', uom: 'Each', barcode_type: 'UPC-A', is_active: 'Inactive', is_default: 'No', modified_date: '2026-07-04', case_size: 1, sale_price: 1899, is_saleable: 'No' },
  ],
  vendors: [
    { vendor_code: 'VEN001', vendor_name: 'Apex Apparel Mfg Pvt Ltd', vendor_type: 'Domestic', credit_days: 30, country: 'India', state: 'Tamil Nadu', city: 'Tirupur', gstin: '33ABCDE1234F1Z5', contact: 'Suresh Nair', phone: '9820011223', email: 'sales@apexapparel.in', status: 'Active' },
    { vendor_code: 'VEN002', vendor_name: 'NovaTech Electronics', vendor_type: 'Domestic', credit_days: 45, country: 'India', state: 'Karnataka', city: 'Bengaluru', gstin: '29NOVAT5678K1Z2', contact: 'Priya Menon', phone: '9900122334', email: 'orders@novatech.in', status: 'Active' },
    { vendor_code: 'VEN003', vendor_name: 'StrideFoot Industries', vendor_type: 'Domestic', credit_days: 30, country: 'India', state: 'Uttar Pradesh', city: 'Agra', gstin: '09STRID9012L1Z8', contact: 'Amit Deshmukh', phone: '9711223344', email: 'supply@stridefoot.in', status: 'Active' },
    { vendor_code: 'VEN004', vendor_name: 'GlowLab Cosmetics', vendor_type: 'Domestic', credit_days: 60, country: 'India', state: 'Maharashtra', city: 'Mumbai', gstin: '27GLOWL3456M1Z1', contact: 'Neha Kapoor', phone: '9833445566', email: 'b2b@glowlab.in', status: 'Active' },
    { vendor_code: 'VEN005', vendor_name: 'Shenzhen Imports Co', vendor_type: 'Import', credit_days: 90, country: 'China', state: 'Guangdong', city: 'Shenzhen', gstin: '', contact: 'Li Wei', phone: '8613800138000', email: 'export@shenzhenimports.cn', status: 'Active' },
    { vendor_code: 'VEN006', vendor_name: 'Rajasthan Handloom', vendor_type: 'Domestic', credit_days: 15, country: 'India', state: 'Rajasthan', city: 'Jaipur', gstin: '08RAJHL6677P1Z9', contact: 'Mohan Lal', phone: '9414012345', email: 'info@rajhandloom.in', status: 'Inactive' },
  ],
  tax_group_codes: [],
  tax_zone_states: [],
  tax_codes: [
    { tax_code: 'VINSCNA', tax_code_type: 'CESS', start_date: '2021-10-13', percentage: 0, description: 'State Non-Advol Cess for SKU', is_active: 'Active' },
    { tax_code: 'VINCCNA', tax_code_type: 'CESS', start_date: '2021-10-13', percentage: 0, description: 'Central Non-Advol Cess for SKU', is_active: 'Active' },
    { tax_code: 'VIN2022', tax_code_type: 'GST', start_date: '2022-03-11', percentage: 10, description: 'Iphone 13', is_active: 'Active' },
    { tax_code: 'TEXTMANSI', tax_code_type: 'GST', start_date: '2019-01-01', percentage: 1, description: '', is_active: 'Active' },
    { tax_code: 'TESTCODE', tax_code_type: 'GST', start_date: '2019-08-08', percentage: 3, description: 'testcode', is_active: 'Active' },
    { tax_code: 'TEST101', tax_code_type: 'CESS', start_date: '2020-07-08', percentage: 5, description: 'TEST', is_active: 'Active' },
    { tax_code: 'TEST', tax_code_type: 'GST', start_date: '2021-10-18', percentage: 18, description: '', is_active: 'Active' },
    { tax_code: '85', tax_code_type: 'GST', start_date: '2022-07-01', percentage: 18, description: 'Rk_apparels', is_active: 'Active' },
    { tax_code: '9999', tax_code_type: 'GST', start_date: '2022-06-01', percentage: 18, description: 'Test', is_active: 'Active' },
    { tax_code: 'T1', tax_code_type: 'GST', start_date: '2022-04-18', percentage: 12, description: '', is_active: 'Active' },
    { tax_code: 'gst2', tax_code_type: 'GST', start_date: '2026-07-07', percentage: 0.02, description: '', is_active: 'Active' },
    { tax_code: 'CessTest', tax_code_type: 'CESS', start_date: '2026-07-09', percentage: 10, description: '', is_active: 'Active' },
    { tax_code: 'JeetGST', tax_code_type: 'GST', start_date: '2026-07-01', percentage: 12, description: 'Custom GST Percentage', is_active: 'Active' },
    { tax_code: 'FGR', tax_code_type: 'GST', start_date: '2026-06-03', percentage: 10, description: '', is_active: 'Active' },
    { tax_code: 'SRIJANA', tax_code_type: 'GST', start_date: '2026-05-08', percentage: 18, description: 'SRIJANA', is_active: 'Active' },
    { tax_code: 'TG7', tax_code_type: 'GST', start_date: '2025-09-09', percentage: 12, description: 'TG7', is_active: 'Active' },
    { tax_code: 'ajittc', tax_code_type: 'GST', start_date: '2022-03-29', percentage: 10, description: 'zxcv', is_active: 'Active' },
    { tax_code: 'GST40', tax_code_type: 'GST', start_date: '2025-09-15', percentage: 40, description: '', is_active: 'Active' },
    { tax_code: '101010126', tax_code_type: 'GST', start_date: '2025-03-26', percentage: 10, description: '', is_active: 'Active' },
    { tax_code: 'ciri', tax_code_type: 'GST', start_date: '2025-03-10', percentage: 18, description: '', is_active: 'Active' },
  ],
  coupons_master: [
    { coupon_key: 'CPN-WELCOME', description: 'Welcome 10% Off', coupon_type: 'Percentage', status: 'Active', coupon_code: 'WELCOME10', start_date: '2024-05-01', end_date: '2024-12-31', active_date: '2024-05-01', created_by: 'demo-admin', discount_value: 10, min_order: 999, usage_limit: 500 },
    { coupon_key: 'CPN-FEST500', description: 'Festive Rs.500 Off', coupon_type: 'Flat Amount', status: 'Inactive', coupon_code: 'FEST500', start_date: '2024-10-01', end_date: '2024-11-15', active_date: '2024-10-01', created_by: 'demo-admin', discount_value: 500, min_order: 2999, usage_limit: 1000 },
    { coupon_key: 'CPN-FLAT15', description: 'Flat 15% App Only', coupon_type: 'Percentage', status: 'Active', coupon_code: 'APP15', start_date: '2024-06-01', end_date: '2025-06-01', active_date: '2024-06-01', created_by: 'demo-admin', discount_value: 15, min_order: 1499, usage_limit: 2000 },
    { coupon_key: 'CPN-FREESHIP', description: 'Free Shipping', coupon_type: 'Flat Amount', status: 'Active', coupon_code: 'FREESHIP', start_date: '2024-01-01', end_date: '2025-12-31', active_date: '2024-01-01', created_by: 'demo-admin', discount_value: 99, min_order: 499, usage_limit: 9999 },
  ],
  channels: [
    { channel_code: 'M13', channel_name: 'Endless Aisle A', brand: 'flipkart', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'FK', registration_date: '2016-06-23T15:06:00', channel_configured: 'Yes' },
    { channel_code: 'AB5', channel_name: 'SUBCONTRACT', brand: 'custom', channel_type: 'Custom Channel', fulfilment_status: 'Online', status: 'Active', location: 'View Location(s)', brand_code: 'CU', registration_date: '2024-07-09T10:18:00', channel_configured: 'No' },
    { channel_code: 'AB8', channel_name: 'FBA', brand: 'amazon', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'AMZ', registration_date: '2024-09-20T14:51:00', channel_configured: 'Yes' },
    { channel_code: 'ABA', channel_name: 'BergneriMP', brand: 'custom', channel_type: 'Custom Channel', fulfilment_status: 'Online', status: 'Active', location: 'View Location(s)', brand_code: 'CU', registration_date: '2024-10-14T11:54:00', channel_configured: 'No' },
    { channel_code: 'ABB', channel_name: 'TSS', brand: 'myntra', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'MYN', registration_date: '2024-10-23T18:34:00', channel_configured: 'No' },
    { channel_code: 'ABE', channel_name: 'QA11', brand: 'custom', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'CHE-CHE', brand_code: 'CU', registration_date: '2024-11-19T21:56:00', channel_configured: 'Yes' },
    { channel_code: 'ABF', channel_name: 'QA12', brand: 'custom', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'CHE-CHE', brand_code: 'CU', registration_date: '2024-11-19T21:56:00', channel_configured: 'Yes' },
    { channel_code: 'ABG', channel_name: 'QA11', brand: 'custom', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'CHE-CHE', brand_code: 'CU', registration_date: '2024-11-19T21:57:00', channel_configured: 'Yes' },
    { channel_code: 'ABH', channel_name: 'QA12', brand: 'custom', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'CHE-CHE', brand_code: 'CU', registration_date: '2024-11-19T21:57:00', channel_configured: 'Yes' },
    { channel_code: 'ABI', channel_name: 'QA11', brand: 'custom', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'View Location(s)', brand_code: 'CU', registration_date: '2024-11-19T21:57:00', channel_configured: 'Yes' },
    { channel_code: 'ABK', channel_name: 'QA11', brand: 'amazon', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'A01-Delhi WH', brand_code: 'AMZ', registration_date: '2024-11-19T21:58:00', channel_configured: 'Yes' },
    { channel_code: 'ABM', channel_name: 'Terratwo', brand: 'shopify', channel_type: 'Webstore', fulfilment_status: 'Online', status: 'Active', location: 'View Location(s)', brand_code: 'SHOP', registration_date: '2024-12-08T10:29:00', channel_configured: 'Yes' },
    { channel_code: 'ABN', channel_name: 'mnbaxckjasb', brand: 'amazon', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'AMZ', registration_date: '2024-12-19T16:06:00', channel_configured: 'Yes' },
    { channel_code: 'ABP', channel_name: 'Trendyol UAT', brand: 'trendyol', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'TRE', registration_date: '2024-12-20T14:42:00', channel_configured: 'Yes' },
    { channel_code: 'ABQ', channel_name: 'Nykaa Fashion', brand: 'nykaa', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'NYK', registration_date: '2025-01-05T11:20:00', channel_configured: 'Yes' },
    { channel_code: 'ABR', channel_name: 'Ajio Seller', brand: 'ajio', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'A01-Delhi WH', brand_code: 'AJI', registration_date: '2025-01-12T09:15:00', channel_configured: 'Yes' },
    { channel_code: 'AMF', channel_name: 'Amazon India MFN', brand: 'amazon', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'Delhi NCR', brand_code: 'AMZ', registration_date: '2026-08-08T10:36:00', channel_configured: 'Yes' },
    { channel_code: 'ABS', channel_name: 'Meesho Store', brand: 'meesho', channel_type: 'Marketplace', fulfilment_status: 'Online', status: 'Active', location: 'UWH-JX Karawaci', brand_code: 'MEE', registration_date: '2025-01-20T16:40:00', channel_configured: 'No' },
    { channel_code: 'ABT', channel_name: 'Own Webstore', brand: 'custom', channel_type: 'Webstore', fulfilment_status: 'Offline', status: 'Inactive', location: 'CHE-CHE', brand_code: 'CU', registration_date: '2025-02-01T12:00:00', channel_configured: 'No' },
  ],
  sku_channel_links: [],
  back_orders: [],
  purchase_charge_masters: [],
};
