import { find, findOne, insert, update, remove, cors } from './mongo.js';
const MODULE='tax-zone';
async function listZones(){const[zones,maps]=await Promise.all([find('generic_records',{module:MODULE},{sort:{id:-1}}),find('tax_zone_states',{})]);return zones.map(zone=>({...zone,states:maps.filter(map=>map.zone_id===zone.id).sort((a,b)=>a.sequence-b.sequence).map(map=>map.state),no_of_states:maps.filter(map=>map.zone_id===zone.id).length}));}
function valid(body){if(!/^\d+$/.test(String(body.code||'')))return'Please Enter Only Numerics in Tax Zone Code!';if(!String(body.name||'').trim())return'Please Enter Tax Zone Name';if(!String(body.country||'').trim())return'Please Select Country';if(!Array.isArray(body.states)||!body.states.length)return'Please Select State';if(!['Active','Inactive'].includes(body.status))return'Invalid status';return null;}
export default async function handler(req,res){if(cors(req,res))return;try{
 if(req.method==='GET'){const{code,name,status}=req.query;return res.status(200).json((await listZones()).filter(row=>(!code||row.code.includes(String(code)))&&(!name||row.name.toLowerCase().includes(String(name).toLowerCase()))&&(!status||row.status===status)));}
 if(req.method==='POST'||req.method==='PUT'){
  const body={...req.body};const zones=await find('generic_records',{module:MODULE});if(req.method==='POST'&&(!String(body.code||'').trim()||String(body.code)==='0'))body.code=String(Math.max(0,...zones.map(zone=>Number(zone.code)||0))+1);
  const error=valid(body);if(error)return res.status(400).json({error});const states=body.states.map(String).map(x=>x.trim()).filter(Boolean);if(new Set(states.map(x=>x.toLowerCase())).size!==states.length)return res.status(400).json({error:'A State can only be added once.'});
  if(req.method==='POST'){if(zones.some(zone=>zone.code===body.code))return res.status(409).json({error:'Tax Zone Code already exists.'});if(zones.some(zone=>zone.name?.toLowerCase()===body.name.trim().toLowerCase()))return res.status(409).json({error:'Tax Zone Name already exists.'});const zone=await insert('generic_records',{module:MODULE,code:body.code,name:body.name.trim(),description:body.description||'',country:body.country.trim(),status:body.status,udf1:body.udf1||'',udf2:body.udf2||'',udf3:body.udf3||'',created_date:new Date().toISOString().slice(0,10)});await Promise.all(states.map((state,index)=>insert('tax_zone_states',{zone_id:zone.id,state,sequence:index+1})));return res.status(201).json((await listZones()).find(row=>row.id===zone.id));}
  const zone=await findOne('generic_records',{id:Number(body.id)});if(!zone||zone.module!==MODULE)return res.status(404).json({error:'Tax Zone not found'});await update('generic_records',zone.id,{code:body.code,name:body.name.trim(),description:body.description||'',country:body.country.trim(),status:body.status,udf1:body.udf1||'',udf2:body.udf2||'',udf3:body.udf3||'',updated_date:new Date().toISOString().slice(0,10)});for(const map of await find('tax_zone_states',{zone_id:zone.id}))await remove('tax_zone_states',map.id);await Promise.all(states.map((state,index)=>insert('tax_zone_states',{zone_id:zone.id,state,sequence:index+1})));return res.status(200).json((await listZones()).find(row=>row.id===zone.id));
 }
 if(req.method==='DELETE')return res.status(409).json({error:'Tax Zones are maintained by status; deletion is not available.'});return res.status(405).json({error:'Method not allowed'});
}catch(error){console.error('tax zones error:',error);return res.status(500).json({error:error.message});}}
