import { cors, find, findOne, insert, update } from './mongo.js';

const titles = [['-1','--- Select ---'],['4','Dr.'],['1','Mr.'],['2','Mrs.'],['3','Ms.']];
const statuses = [['-1','--- Select ---'],['1','Active'],['0','InActive'],['9','Locked']];
const userTypes = [['-1','--- Select ---'],['1001','Admin',true],['3','Distributor'],['1','Normal'],['2','Seller',true],['1002','SellerAdmin'],['4','Store']];
const companies = [['-1','--- Select ---'],['0001','Bustify'],['001','Singh Enterprises'],['001S','ABC Traders'],['008','Tony_Stack'],['020D','NameI'],['0327','Amity'],['0786','lcpl'],['10098','Mayank Enterprises'],['100D','NaIn'],['111','Mobile Accessory'],['1111','Cases & Covers'],['12266','deepanshu'],['12321','Fizz'],['1234','shoes'],['21','LG'],['23','clothes'],['34234','Testing'],['3672','Zepto'],['4443','Zyppp'],['5309','Singh trading'],['54545','bata'],['56745','Indonesia1'],['5748','Homeneed'],['9639','Best Life'],['9922','Pratibha Textile'],['ABC01','ABC-Retail'],['ASHCO','ac'],['COM1','Company123'],['D001','Delami'],['DEALS','DealShare'],['EROIU','eo4ihtig'],['ERTG','rgtert'],['H000','hn'],['HYD','hyd'],['JSQ1','JSQ Retail'],['K01','K_eomm'],['KHA','Khazenly'],['LCPL','LCPL'],['M001','Mrinal'],['MAL12','Malaysia warehouse'],['MNRCH','Monarch'],['MYCMP','mc'],['MYS01','Aazaro'],['NEWCO','NEW COMPANY HOLISTIQUE'],['P99','Psing199'],['PALK','PALAK'],['PELE','Pele'],['PRA','Prashant'],['PRA-1','NameI'],['RCOMP','RK'],['SAAAP','TEST SAP'],['SAMVI','Samvigya Enterprise'],['SHAQ','shaquib'],['SJSJ','SagarJain'],['TEST','test'],['TEST7','test'],['TYUHG','sports apparel pvt Ltd.'],['USPL','Vinculum Solutions Pvt Ltd.'],['VIN','support'],['VIN99','Shellby Traders'],['XCER','Chinaorg'],['XDER','IndonesiaOrg'],['XWAB','Thailandorg'],['XYNB','SingaporeOrg'],['XYZ','XYZ Private Ltd'],['XYZM','Malaysiaorg'],['ZEPTO','food items']];
const roles = [['-1','--- Select ---'],['1','1-Customer Info Masking'],['1002','1002-All Company Level Rights**************************'],['9999','9999-sellermask'],['10049','10049-withright'],['10050','10050-withoutrights'],['10055','10055-All Company Level Rights'],['10062','10062-POTest-Save'],['10063','10063-POTest-Confirm'],['10064','10064-POTest-Release'],['10065','10065-POTest-Reopen'],['10066','10066-InboundConfirm'],['10069','10069-Orders'],['10072','10072-Cyclecount'],['10075','10075-shortpack'],['00001','00001-CRM -Admin'],['00004','00004-All Company Level Rights'],['00007','00007-Cmp Finance'],['00009','00009-Cmp Buyer'],['00010','00010-Cmp Asst Buyer'],['00012','00012-Cmp WMS Inbound QC'],['00013','00013-WMS Level 2'],['00014','00014-WMS Level 3'],['00015','00015-WMS Level 4'],['00016','00016-WMS Level 5'],['00017','00017-WMS Level 6'],['00018','00018-WMS Level 7'],['00021','00021-Cmp Logistics Level 1'],['00022','00022-Cmp Logistic Level 2'],['00023','00023-CRM - Manager'],['00024','00024-CRM_ Department User'],['00025','00025-CRM - Agents'],['00028','00028-Buyer Ops Reports'],['00031','00031-Temp Role-Dont Use'],['00043','00043-Warehouse Manager'],['00045','00045-Distributor Rights'],['00104','00104-PO Checker'],['00105','00105-Read Only']];
const countries = [['-1','--- Select ---'],['107','INDIA'],['108','INDONESIA'],['140','MALAYSIA'],['205','SINGAPORE'],['228','THAILAND'],['242','UNITED KINGDOM'],['243','UNITED STATES']];
const indiaStates = [['-1','--- Select ---'],['DL','Delhi'],['HR','Haryana'],['KA','Karnataka'],['MH','Maharashtra'],['UP','Uttar Pradesh']];
const statusName = id => statuses.find(x=>x[0]===String(id))?.[1] || 'Active';
const typeName = id => userTypes.find(x=>x[0]===String(id))?.[1] || 'Normal';
const mandatory = b => !b.userId || b.title==='-1' || !b.firstName || !b.lastName || b.userType==='-1' || !b.address1 || !b.country || b.country==='-1' || !b.state || b.state==='-1' || !b.city || !b.phone1 || !b.emailId1;

export default async function handler(req,res){
  if(cors(req,res))return;
  try{
    if(req.method==='GET'){
      const userId=String(req.query.userId||'');
      if(userId){const row=(await find('admin_records',{type:'user'})).find(x=>String(x.username).toLowerCase()===userId.toLowerCase());if(!row)return res.status(404).json({error:'User not found'});return res.json({row});}
      return res.json({titles,statuses,userTypes,companies,roles,countries,states:indiaStates,udfCount:5,roleColumns:['Company','Location','Role Desc','Role Id'],defaults:{title:'-1',status:'1',userType:'1'},endpoints:{save:'saveUserDetailBS',roles:'jsonRoleAdd',roleSearch:'jsonSearchRoles',countryState:'jsonCountryStateData',resetMfa:'resetMfa',passwordPolicy:'fetchPasswordPolicy',changePassword:'changePassword'}});
    }
    if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
    const b=req.body||{};
    if(b.action==='catalog'){return res.json(b.kind==='states'?{states:b.country==='107'?indiaStates:[['-1','--- Select ---']]}:{roles,locations:b.company==='USPL'?[['-1','--- Select ---'],['UWH','JX Karawaci']]:[['-1','--- Select ---']]});}
    if(b.action==='role-add'){if(b.company==='-1'||!b.company)return res.status(400).json({error:'Please Select Company'});if(b.company!=='**'&&b.location==='-1')return res.status(400).json({error:'Please Select Location'});if(!b.roleIds?.length||b.roleIds.includes('-1'))return res.status(400).json({error:'Please Select Role'});const company=companies.find(x=>x[0]===b.company)?.[1]||b.company;return res.json({roles:b.roleIds.map(id=>({company,location:b.locationName||'',role:roles.find(x=>x[0]===id)?.[1]?.replace(/^\w+-/,'')||id,roleIdGrid:id,orgId:company}))});}
    if(b.action==='reset-mfa'){if(!b.userId)return res.status(400).json({error:'User Name is mandatory'});return res.json({jsonMessage:'MFA reset successfully.'});}
    if(b.action==='password-policy')return res.json({passwordPolicyMap:{pwdLength:8,characterRegex:1,numericRegex:1,upperCaseRegex:1,specialCaseRegex:'[^a-zA-Z0-9]'}});
    if(b.action==='change-password'){if(!b.userId)return res.status(400).json({error:'User Name is mandatory'});if(!b.password)return res.status(400).json({error:'Please enter password.'});if(b.password.toLowerCase().includes(String(b.userId).toLowerCase()))return res.status(400).json({error:'Password must not contain your username.'});if(/(?:012|123|234|345|456|567|678|789)/.test(b.password))return res.status(400).json({error:'Password cannot include numeric sequences.'});if(b.password.length<8)return res.status(400).json({error:'Password must be 8 character long.'});if(!/[a-zA-Z]/.test(b.password))return res.status(400).json({error:'Password must contain alphabets.'});if(!/[0-9]/.test(b.password))return res.status(400).json({error:'Password must contain numeric digit.'});if(!/[A-Z]/.test(b.password))return res.status(400).json({error:'Password must contain uppercase letter.'});if(!/[^a-zA-Z0-9]/.test(b.password))return res.status(400).json({error:'Password must contain special character.'});const row=(await find('admin_records',{type:'user'})).find(x=>String(x.username).toLowerCase()===String(b.userId).toLowerCase());if(row)await update('admin_records',row.id,{passwordResetAt:new Date().toISOString(),forceChangePwdOnNextLogin:'Y'});return res.json({userId:b.userId,reLogin:false});}
    if(b.action!=='save')return res.status(400).json({error:'Unsupported User action'});
    if(mandatory(b))return res.status(400).json({error:'Please fill all mandatory fields'});
    if(String(b.userId).includes(' '))return res.status(400).json({error:'White Spaces are not allowed'});
    if(!/^[a-zA-Z0-9._]+$/.test(b.userId))return res.status(400).json({error:'Please enter AlphaNumerics only'});
    if(b.userType==='3'&&!b.pincode)return res.status(400).json({error:'Please Enter Shipping Pincode'});
    if(!/^[\w.-]+@([\w-]+\.)+[\w-]{2,4}$/.test(b.emailId1))return res.status(400).json({error:'Please enter valid Email Address'});
    const all=await find('admin_records',{type:'user'}),existing=all.find(x=>String(x.username).toLowerCase()===String(b.userId).toLowerCase());
    const payload={type:'user',username:b.userId,firstName:b.firstName,middleName:b.middleName||'',lastName:b.lastName,designation:b.designation||'',title:b.title,dobStr:b.dobStr||'',status:statusName(b.status),statusId:b.status,userType:typeName(b.userType),userTypeId:b.userType,purchaseOrderLimit:b.purchaseOrderLimit||'',isMFA:!!b.isMFA,address1:b.address1,address2:b.address2||'',address3:b.address3||'',country:b.country,state:b.state,city:b.city,pincode:b.pincode||'',phone1:b.phone1,phone2:b.phone2||'',email:b.emailId1,emailId1:b.emailId1,emailId2:b.emailId2||'',udf:b.udf||Array(5).fill(''),roles:b.roles||[],updatedAt:new Date().toISOString(),version:(existing?.version||0)+1};
    if(existing){const [row]=await update('admin_records',existing.id,payload);return res.json({row,message:'User updated successfully'});}const row=await insert('admin_records',{...payload,createdAt:new Date().toISOString()});return res.status(201).json({row,message:'User saved successfully'});
  }catch(error){console.error('user editor error:',error);return res.status(500).json({error:error.message});}
}
